Repository algorand/go-algorand, pull requests merged in 2019-06, with the labels that each got.

#2 fix flaky agreement test: make sortition deterministic
  agreement/service_test.go
  crypto/rand.go
Labels: test

#6 fix ledger ErrNoEntry issue due to sqlite
  util/db/dbutil.go
  util/db/dbutil_test.go
Labels: bug

#3 make ledger.ErrNoEntry more informative
  daemon/algod/api/server/v1/handlers/handlers.go
  ledger/blockdb.go
  ledger/blockqueue.go
  ledger/error.go
  node/node.go
  rpcs/ledgerService.go
Labels: api

#4 cleanup Gopkg.toml based on suggestions from "dep ensure"
  Gopkg.toml
Labels: operations

#5 websocket: terminate flushThread on Close() without writeTimeout
  Gopkg.lock
  vendor/github.com/algorand/websocket/.travis.yml
  vendor/github.com/algorand/websocket/conn.go
Labels: bug

#26 [GOAL2-743] Check and return error in AlgorandFullNode::BroadcastSignedTxn
  node/node.go
Labels: bug

#33 Support streaming in the coroner debug tool.
  agreement/actor.go
  agreement/autopsy.go
  agreement/trace.go
  debug/coroner/main.go
Labels: enhancement

#36 [GOAL2-513] [GOAL2-775] GOAL account export. Clarify info messages for seed import/export.
  cmd/goal/account.go
  cmd/goal/messages.go
  cmd/goal/wallet.go
Labels: enhancement, goal (CLI)

#30 Enhance NodeExporterPath JSON option to pass additional node_exporter arguments
  util/metrics/reporter.go
  util/metrics/reporter_test.go
Labels: enhancement

#25 [GOAL2-685] sendReceive_tests move more money.
  test/e2e-go/features/transactions/sendReceive_test.go
Labels: enhancement, test

#55 [GOAL2-796] re-enable firstvalid and lastvalid for goal clerk
  cmd/goal/clerk.go
  libgoal/libgoal.go
  libgoal/unencryptedWallet.go
  test/e2e-go/cli/perf/payment_test.go
  test/e2e-go/features/multisig/multisig_test.go
  test/e2e-go/features/participation/onlineOfflineParticipation_test.go
  test/e2e-go/features/transactions/close_account_test.go
  test/e2e-go/restAPI/restClient_test.go
  test/e2e-go/stress/transactions/createManyAndGoOnline_test.go
  test/framework/fixtures/restClientFixture.go
Labels: 1, goal (CLI)

#7 Add metrics to heartbeat event.
  cmd/algod/main.go
  logging/telemetryspec/event.go
  network/wsNetwork.go
  util/metrics/counter.go
  util/metrics/gauge.go
  util/metrics/registry.go
  util/metrics/registryCommon.go
  util/metrics/registry_test.go
  util/metrics/stringGauge.go
  util/metrics/stringGaugeCommon.go
  util/metrics/stringGauge_test.go
Labels: enhancement

#62 fix filter for next round period 0 votes
  agreement/voteAggregator.go
  agreement/voteAggregator_test.go
Labels: bug, protocol
