Repository algorand/go-algorand, pull requests merged in 2019-09, with the labels that each got.

#266 Fix acctupdates refcount concurrency bug.
  ledger/acctupdates.go
Labels: bug

#331 Serialize concurrent access to data in the auction tracker.
  auction/tracker.go
  auction/tracker_test.go
Labels: bug

#261 Add the ability to mark an account as Non-Participating.
  cmd/goal/account.go
  config/config.go
  data/pools/transactionPool.go
  data/transactions/keyreg.go
  data/transactions/keyreg_test.go
  data/transactions/transaction.go
  data/transactions/transaction_test.go
  data/txHandler.go
  libgoal/transactions.go
  protocol/hash.go
  rpcs/txService.go
  test/e2e-go/features/transactions/onlineStatusChange_test.go
  test/testdata/nettemplates/TwoNodesPartlyOfflineVFuture.json
Labels: enhancement, protocol, test, user-facing

#349 Allow transactions to explicitly specify mutual exclusion.
  config/config.go
  data/transactions/transaction.go
  data/txHandler.go
  ledger/cow.go
  ledger/cow_test.go
  ledger/eval.go
  ledger/ledger.go
  ledger/ledger_test.go
  ledger/txtail.go
Labels: enhancement, protocol

#348 Revisit s3_release_bucket usage in build scripts
  cmd/updater/sendCmd.go
  docker/build/Dockerfile-deploy
  scripts/deploy_version.sh
  scripts/upload_config.sh
  scripts/upload_version.sh
Labels: 1

#358 Better error handling for auctionStart.sh
  test/scripts/auctionStart.sh
Labels: 1

#355 Decouple the AccountManager.DeleteOldKeys disk persistence execution
  data/account/participation.go
  data/accountManager.go
  gen/generate.go
  gen/walletData.go
  libgoal/participation.go
  netdeploy/networkTemplate.go
Labels: 1

#359 Support re-run of ARM64 builds on travis
  scripts/buildhost/s3streamup.sh
  scripts/travis/external_build.sh
Labels: 1

#353 Validate "go get" output
  scripts/configure_dev-deps.sh
Labels: 1

#360 Move Command&Control to test
  test/commandandcontrol/README.md
  test/commandandcontrol/cc_agent/component/agent.go
  test/commandandcontrol/cc_agent/component/agent_test.go
  test/commandandcontrol/cc_agent/component/pingPongComponent.go
  test/commandandcontrol/cc_agent/main.go
  test/commandandcontrol/cc_client/main.go
  test/commandandcontrol/cc_service/main.go
  test/commandandcontrol/example/cc_example.sh
  test/commandandcontrol/example/cc_example_client.sh
  test/commandandcontrol/example/pingpong1.json
  test/commandandcontrol/example/pingpong2.json
  test/commandandcontrol/lib/ccCommon.go
Labels: 1

#354 Add ansi colors to travis_wait.sh
  scripts/travis/travis_wait.sh
Labels: 1
