Repository algorand/go-algorand, pull requests merged in 2020-01, with the labels that each got.

#673 Prepare beta release build 9
  buildnumber.dat
  cmd/algod/main.go
  cmd/goal/account.go
  cmd/goal/asset.go
  cmd/goal/clerk.go
  cmd/goal/messages.go
  cmd/goal/multisig.go
  config/config.go
  config/local_defaults.go
  daemon/kmd/wallet/driver/ledger.go
  daemon/kmd/wallet/driver/ledger_hid.go
  daemon/kmd/wallet/driver/sqlite.go
  daemon/kmd/wallet/driver/sqlite_errors.go
  data/transactions/logic/assembler.go
  data/transactions/logic/assembler_test.go
  installer/config.json.example
  logging/log.go
  logging/telemetryhook.go
  logging/telemetryspec/event.go
  network/wsNetwork.go
  scripts/travis/configure_dev.sh
  test/e2e-go/cli/goal/expect/goalExpectCommon.exp
  test/e2e-go/cli/goal/expect/listExpiredParticipationKeyTest.exp
  test/testdata/configs/config-v5.json
  tools/network/bootstrap.go
  tools/network/telemetryURIUpdateService.go
  tools/network/telemetryURIUpdateService_test.go
Labels: 1

#677 Improve teal shell scripting output
  test/scripts/e2e_subs/dynamic-fee-teal-test.sh
  test/scripts/e2e_subs/e2e_teal.sh
  test/scripts/e2e_subs/htlc-teal-test.sh
  test/scripts/e2e_subs/keyreg-teal-test.sh
  test/scripts/e2e_subs/limit-swap-test.sh
  test/scripts/e2e_subs/periodic-teal-test.sh
  test/scripts/e2e_subs/teal-split-test.sh
Labels: 1

#679 Make gracefull exit of a node that is waiting for WaitForBlock call
  daemon/algod/api/server/lib/common.go
  daemon/algod/api/server/router.go
  daemon/algod/api/server/v1/handlers/errors.go
  daemon/algod/api/server/v1/handlers/handlers.go
  daemon/algod/server.go
Labels: 1

#682 Remove tput where not supported by terminal
  docker/releases/build_releases.sh
  scripts/check_deps.sh
  scripts/check_license.sh
  test/packages/test_release.sh
  test/platform/test_linux_amd64_compatibility.sh
Labels: 1

#681 Avoid waiting for block that won't be reached due to unsupported protocol upgrade
  daemon/algod/api/server/v1/handlers/errors.go
  daemon/algod/api/server/v1/handlers/handlers.go
Labels: 1

#684 Fix - Indexer now shows received transactions
  data/transactions/transaction.go
  node/indexer/db.go
  node/indexer/indexer_test.go
Labels: 2

#685 Catchup service stop on unsupported and e2e test
  catchup/service.go
  catchup/service_test.go
  config/config.go
  protocol/consensus.go
  test/e2e-go/features/catchup/basicCatchup_test.go
  test/testdata/nettemplates/TwoNodes100SecondTestUnupgradedProtocol.json
Labels: 1

#694 Make ARM64 build mandatory
  .travis.yml
Labels: 1

#686 Updates to the goal node status
  cmd/goal/messages.go
  cmd/goal/node.go
  daemon/algod/api/server/v1/handlers/handlers.go
  daemon/algod/api/spec/v1/model.go
  node/node.go
  test/e2e-go/cli/goal/expect/goalExpectCommon.exp
  test/e2e-go/features/catchup/basicCatchup_test.go
Labels: 2

#696 relax StartNetwork regex
  test/e2e-go/cli/goal/expect/goalExpectCommon.exp
Labels: 1

#709 Shutdown kmd when test fixture is going down
  test/framework/fixtures/libgoalFixture.go
Labels: 1

#711 Fix failing unit test TestFetchBlockTimeout
  rpcs/fetcher_test.go
Labels: 1

#701 Execute e2e tests one at a time
  netdeploy/network.go
  nodecontrol/kmdControl.go
  scripts/travis/integration_test.sh
  test/e2e-go/cli/goal/common_test.go
  test/e2e-go/cli/goal/expect/goalExpectCommon.exp
  test/e2e-go/restAPI/restClient_test.go
  test/framework/fixtures/goalFixture.go
  test/framework/fixtures/kmdFixture.go
  test/framework/fixtures/restClientFixture.go
  test/scripts/e2e_go_tests.sh
Labels: 1

#713 Update the makefile to skip the static linking when compiling on centos
  Makefile
Labels: 1

#699 Fail e2e-go tests when node panics
  cmd/goal/network.go
  netdeploy/network.go
  nodecontrol/NodeController.go
  nodecontrol/algodControl.go
  test/e2e-go/features/participation/onlineOfflineParticipation_test.go
  test/e2e-go/features/participation/participationRewards_test.go
  test/e2e-go/features/partitionRecovery/partitionRecovery_test.go
  test/framework/fixtures/libgoalFixture.go
Labels: 3

#714 Minor: Use service-wide logger instead of logging.Base() in agreement
  agreement/actions.go
  agreement/actor.go
  agreement/agreementtest/simulate.go
  agreement/fuzzer/fuzzer_test.go
  agreement/gossip/network.go
  agreement/gossip/networkFull_test.go
  agreement/gossip/network_test.go
  node/node.go
Labels: 1

#719 Mark some of the slow e2e tests as such
  scripts/travis/run_tests.sh
  test/e2e-go/features/auction/auctionErrors_test.go
  test/e2e-go/features/auction/basicAuction_test.go
  test/e2e-go/features/participation/participationRewards_test.go
  test/e2e-go/features/transactions/sendReceive_test.go
  test/scripts/e2e_go_tests.sh
Labels: 1

#718 Make network unit test TestSlowHandlers less restrictive
  network/wsNetwork_test.go
Labels: 1

#721 Move slow test to get executed on nightly builds
  scripts/travis/run_tests.sh
  test/e2e-go/features/auction/auctionCancel_test.go
  test/e2e-go/features/auction/auctionErrors_test.go
  test/e2e-go/features/auction/basicAuction_test.go
  test/e2e-go/features/transactions/asset_test.go
Labels: 1

#722 Faster upgrade e2e tests
  test/e2e-go/upgrades/send_receive_upgrade_test.go
Labels: 1

#731 Goal docs tweaks
  cmd/goal/account.go
  cmd/goal/asset.go
  cmd/goal/clerk.go
  cmd/goal/commands.go
  cmd/goal/completion.go
  cmd/goal/kmd.go
  cmd/goal/ledger.go
  cmd/goal/logging.go
  cmd/goal/multisig.go
  cmd/goal/network.go
  cmd/goal/node.go
  cmd/goal/wallet.go
Labels: documentation

#736 Faster stringer implementation for Address
  data/basics/address.go
  data/basics/address_test.go
Labels: 1

#742 Interconnect relays on a locally deployed network
  netdeploy/network.go
Labels: 1

#735 Format numbers using number specifier
  agreement/actions.go
  agreement/agreementtest/simulate.go
  agreement/agreementtest/simulate_test.go
  agreement/common_test.go
  agreement/demux.go
  agreement/fuzzer/ledger_test.go
  agreement/fuzzer/tests_test.go
  agreement/fuzzer/validator_test.go
  agreement/fuzzer/voteFilter_test.go
  agreement/proposal.go
  agreement/proposalManager.go
  agreement/proposalStore_test.go
  agreement/proposalTracker.go
  agreement/proposal_test.go
  agreement/pseudonode.go
  agreement/selector.go
  agreement/vote.go
  agreement/voteAggregator.go
  agreement/voteTracker.go
  agreement/voteTrackerContract.go
Labels: 1
