Repository algorand/go-algorand, pull requests merged in 2020-12, with the labels that each got.

#1732 Fix a race in arm test in algoh startup and algod.* files creation
  test/e2e-go/cli/algoh/expect/algohExpectCommon.exp
  test/e2e-go/cli/algoh/expect/algohTimeoutTest.exp
Labels: Infrastructure

#1737 Fix goalAsset expect test
  test/e2e-go/cli/goal/expect/goalAssetTest.exp
Labels: Infrastructure

#1733 Improve error logging of elastic search telemetry module
  logging/telemetryhook.go
Labels: Infrastructure

#1736 Use OS and fallback DNS servers in DNSSEC resolver
  cmd/catchupsrv/download.go
  network/dialer.go
  network/wsNetwork.go
  tools/network/bootstrap.go
  tools/network/dnssec/anchor.go
  tools/network/dnssec/anchor_test.go
  tools/network/dnssec/client.go
  tools/network/dnssec/client_test.go
  tools/network/dnssec/config.go
  tools/network/dnssec/config_test.go
  tools/network/dnssec/dialer.go
  tools/network/dnssec/dns.go
  tools/network/dnssec/dnssec_test.go
  tools/network/dnssec/relay-check/main.go
  tools/network/dnssec/resolver.go
  tools/network/dnssec/sort_test.go
  tools/network/dnssec/testHarness.go
  tools/network/dnssec/trustchain.go
  tools/network/dnssec/trustedchain_test.go
  tools/network/dnssec/trustedzone.go
  tools/network/dnssec/trustedzone_test.go
  tools/network/dnssec/util_test.go
  tools/network/resolveController.go
  tools/network/resolveController_test.go
  tools/network/resolver.go
  tools/network/resolver_test.go
Labels: Infrastructure

#1741 Add payset benchmarks
  data/transactions/payset.go
  data/transactions/payset_test.go
Labels: Infrastructure

#1713 Add transaction evaluation distribution metrics
  agreement/pseudonode.go
  config/config.go
  data/pools/transactionPool.go
  logging/telemetryspec/metric.go
  logging/telemetryspec/metric_test.go
Labels: Infrastructure

#1742 Fix random limit order test
  test/e2e-go/cli/goal/expect/basicExpectTest.exp
  test/e2e-go/cli/goal/expect/basicGoalTest.exp
  test/e2e-go/cli/goal/expect/catchpointCatchupTest.exp
  test/e2e-go/cli/goal/expect/corsTest.exp
  test/e2e-go/cli/goal/expect/createWalletTest.exp
  test/e2e-go/cli/goal/expect/doubleSpendingTest.exp
  test/e2e-go/cli/goal/expect/goalExpectCommon.exp
  test/e2e-go/cli/goal/expect/goalNodeStatusTest.exp
  test/e2e-go/cli/goal/expect/ledgerTest.exp
  test/e2e-go/cli/goal/expect/multisigCreationDeletionTest.exp
Labels: Infrastructure

#1740 Fix releases-page task
  package-deploy.yaml
  scripts/release/mule/Makefile.mule
  scripts/release/mule/deploy/README.md
  scripts/release/mule/deploy/releases_page/generate_releases_page.py
  scripts/release/mule/deploy/releases_page/generate_releases_page.sh
  scripts/release/mule/deploy/releases_page/reverse_hex_timestamp
Labels: Dev Ops

#1745 Fix various bugs in expect tests
  scripts/release/test/deb/testDebian.exp
  test/e2e-go/cli/goal/expect/basicGoalTest.exp
  test/e2e-go/cli/goal/expect/doubleSpendingTest.exp
  test/e2e-go/cli/goal/expect/goalExpectCommon.exp
Labels: Infrastructure

#1739 Small transaction pool rebuild & assembly optimizations
  data/pools/transactionPool.go
  ledger/eval.go
  logging/telemetryspec/metric.go
Labels: Infrastructure

#1750 Improve catchpoint catchup expect test
  test/e2e-go/cli/goal/expect/catchpointCatchupTest.exp
  test/e2e-go/cli/goal/expect/goalExpectCommon.exp
Labels: Infrastructure

#1749 Remove code quality checking on integration tests builds
  Makefile
  scripts/travis/before_build.sh
  scripts/travis/build.sh
  scripts/travis/build_test.sh
Labels: Infrastructure

#1754 Fix bug revealed by TestFullCatchpointWriter
  ledger/catchupaccessor.go
Labels: Infrastructure

#1755 Fix download location when signing build assets
  package-sign.yaml
  scripts/release/mule/common/running_in_docker.sh
  scripts/release/mule/sign/sign.sh
Labels: Dev Ops, Unplanned

#1702 Use go tooling to get go version string in go.mod
  scripts/check_golang_version.sh
  scripts/configure_dev-deps.sh
  scripts/configure_dev.sh
  scripts/deploy_linux_version.sh
  scripts/get_golang_version.sh
  scripts/release/build/build_algod_docker.sh
  scripts/release/build/rpm/build.sh
  scripts/release/common/setup.sh
  scripts/travis/build.sh
  scripts/travis/deploy_packages.sh
  scripts/travis/test.sh
Labels: Dev Ops, Unplanned

#1758 Minimal bug fixes for latest package deployment
  package-deploy.yaml
  scripts/release/mule/deploy/rpm/deploy.sh
Labels: Dev Ops, Unplanned

#1762 Generate error on `goal clerk group` on signed transaction
  cmd/goal/clerk.go
  crypto/curve25519.go
  test/e2e-go/cli/goal/expect/basicGoalTest.exp
  test/e2e-go/cli/goal/expect/createWalletTest.exp
  test/e2e-go/cli/goal/expect/doubleSpendingTest.exp
  test/e2e-go/cli/goal/expect/goalAccountTest.exp
  test/e2e-go/cli/goal/expect/goalAppAccountAddressTest.exp
  test/e2e-go/cli/goal/expect/goalClerkGroupTest.exp
  test/e2e-go/cli/goal/expect/goalExpectCommon.exp
  test/e2e-go/cli/goal/expect/limitOrderTest.exp
  test/e2e-go/cli/goal/expect/statefulTealCreateAppTest.exp
  test/e2e-go/cli/goal/expect/tealAndStatefulTealTest.exp
Labels: Infrastructure

#1751 Parallelize proposal transactions signature verification
  data/pools/transactionPool.go
  data/transactions/verify/txn.go
  data/transactions/verify/txn_test.go
  ledger/eval.go
  ledger/ledger_perf_test.go
  ledger/ledger_test.go
Labels: Infrastructure

#1764 Fix catchup concurrently from a single host
  catchup/service.go
  network/rateLimitingTransport.go
  network/wsNetwork.go
Labels: Infrastructure

#1767 Wait for EOF on StartNetwork/StopNetwork and test status correctly
  test/e2e-go/cli/goal/expect/goalExpectCommon.exp
Labels: Infrastructure

#1770 Check minimal go version 1.14 prior the build
  Makefile
  scripts/check_golang_version.sh
  scripts/travis/build.sh
  scripts/travis/test.sh
Labels: Infrastructure

#1772 Compact accounts deltas before persisting to disk
  ledger/acctupdates.go
  ledger/acctupdates_test.go
Labels: Infrastructure

#1774 Refactor account updates consistency checking
  ledger/accountdb.go
  ledger/accountdb_test.go
  ledger/acctupdates.go
  ledger/acctupdates_test.go
Labels: Infrastructure

#1777 Convert the catchpointWriting from a channel to an atomic variable
  ledger/acctupdates.go
  ledger/acctupdates_test.go
Labels: Infrastructure

#1780 Allow catchpointdump downloading a single catchpoint from a specified relay
  cmd/catchpointdump/net.go
Labels: Infrastructure

#1794 bugfix: Network peers list memory leak
  network/peersheap.go
Labels: Infrastructure

#1793 Update catchpointdump utility to have progress bars
  catchup/ledgerFetcher.go
  cmd/catchpointdump/database.go
  cmd/catchpointdump/file.go
  cmd/catchpointdump/net.go
  util/watchdogStreamReader.go
Labels: Infrastructure

#1792 bugfix: incorrect block download retry accounting during fast catchup
  catchup/catchpointService.go
Labels: Infrastructure

#1782 Pass transaction groups correctly to logicsig evaluator
  cmd/goal/clerk.go
Labels: Infrastructure

#1795 Add explicit error for stale network message writes
  network/wsPeer.go
Labels: Infrastructure

#1797 Run gofmt against source code.
  agreement/bundle_test.go
  agreement/demux_test.go
  agreement/fuzzer/tests_test.go
  agreement/vote_test.go
  crypto/merkletrie/node.go
  daemon/algod/api/server/v1/handlers/handlers_test.go
  data/basics/userBalance_test.go
  data/bookkeeping/encoding_test.go
  data/ledger.go
  data/pools/transactionPool_test.go
  data/transactions/logic/evalStateful_test.go
  data/txHandler.go
  ledger/eval.go
  ledger/eval_test.go
  ledger/ledger_perf_test.go
  ledger/totals_test.go
  network/multiplexer_test.go
  network/netprio.go
  network/ping.go
  network/wsNetwork_test.go
  test/netperf-go/puppeteer/puppeteer_test.go
  util/metrics/reporter_test.go
Labels: Infrastructure
