Repository algorand/go-algorand, pull requests merged in 2020-11, with the labels that each got.

#1684 Clarify which algod endpoints require developer API
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/routes.go
Labels: FDE

#1682 Mount .docker dir to allow container to push to docker hub
  package-deploy.yaml
Labels: Dev Ops

#1680 Added package test to verify gpg signature
  scripts/release/mule/test/tests/pre/verify_signature.sh
Labels: Dev Ops

#1688 Add e2e test for LegderForLogic
  test/scripts/e2e_subs/e2e-app-cross-round.sh
  test/scripts/e2e_subs/tealprogs/cross-round.teal
Labels: Infrastructure

#1687 Better 'goal asset' help documentation.
  cmd/goal/asset.go
Labels: FDE

#1693 Dynamically adjust catchpoint file serving timeouts based on file size
  ledger/acctupdates.go
  ledger/acctupdates_test.go
  ledger/ledger.go
  rpcs/ledgerService.go
Labels: Infrastructure

#1685 Re-merge master
  .gitignore
  cmd/goal/asset.go
  config/version.go
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/routes.go
  docker/build/releases-page.Dockerfile
  ledger/acctupdates.go
  ledger/acctupdates_test.go
  ledger/ledger.go
  package-deploy.yaml
  package-sign.yaml
  package-upload.yaml
  package.yaml
  rpcs/ledgerService.go
  scripts/build_package.sh
  scripts/compute_branch_network.sh
  scripts/release/common/cpu_name.sh
  scripts/release/mule/Makefile.mule
  scripts/release/mule/README.md
  scripts/release/mule/deploy/README.md
  scripts/release/mule/deploy/deb/.aptly.conf
  scripts/release/mule/deploy/deb/Dockerfile
  scripts/release/mule/deploy/deb/create_and_push
  scripts/release/mule/deploy/deb/reverse_hex_timestamp
  scripts/release/mule/deploy/docker/docker.sh
  scripts/release/mule/deploy/releases_page/generate_releases_page.py
  scripts/release/mule/deploy/releases_page/generate_releases_page.sh
  scripts/release/mule/deploy/releases_page/html.tpl
  scripts/release/mule/deploy/releases_page/releases_page.css
  scripts/release/mule/deploy/rpm/deploy.sh
  scripts/release/mule/deploy/sync_from_staging.sh
  scripts/release/mule/deploy/update_releases_page.sh
  scripts/release/mule/gpg_preset_passphrase.sh
  scripts/release/mule/package/deb/package.sh
  scripts/release/mule/package/rpm/package.sh
  scripts/release/mule/sign/sign.sh
  scripts/release/mule/test/test.sh
  scripts/release/mule/test/tests/post/verify_package_binaries.sh
  scripts/release/mule/test/tests/pre/verify_control_files.sh
  scripts/release/mule/test/tests/pre/verify_signature.sh
  test/muleCI/mule.yaml
  test/scripts/e2e_subs/e2e-app-cross-round.sh
  test/scripts/e2e_subs/tealprogs/cross-round.teal
Labels: Dev Ops

#1689 Improved task that updates deb repo
  .aptly.conf
  docker/build/aptly.Dockerfile
  package-deploy.yaml
  scripts/release/mule/Makefile.mule
  scripts/release/mule/README.md
  scripts/release/mule/deploy/deb/Dockerfile
  scripts/release/mule/deploy/deb/create_and_push
  scripts/release/mule/deploy/deb/deploy.sh
Labels: Dev Ops

#1697 Ordered account insertion into merkle trie (I)
  ledger/accountdb.go
  ledger/acctupdates.go
  ledger/acctupdates_test.go
  ledger/catchpointwriter_test.go
Labels: Infrastructure

#1700 Add app state read-write into pingpong
  cmd/pingpong/runCmd.go
  shared/pingpong/accounts.go
  shared/pingpong/config.go
  shared/pingpong/pingpong.go
  test/commandandcontrol/cc_agent/component/pingPongComponent.go
Labels: Infrastructure

#1618 optional network propagation tracing
  Makefile
  agreement/gossip/network.go
  config/config.go
  config/local_defaults.go
  go.mod
  go.sum
  installer/config.json.example
  network/messagetracer/graphtrace.go
  network/messagetracer/interface.go
  node/node.go
  test/testdata/configs/config-v13.json
Labels: Infrastructure

#1712 Write the catchpoint file in parallel of reading from the database
  ledger/acctupdates_test.go
  ledger/catchpointwriter.go
  ledger/catchpointwriter_test.go
Labels: Infrastructure

#1715 Add applications to min balance requirements calculation
  shared/pingpong/accounts.go
  shared/pingpong/pingpong.go
Labels: Infrastructure

#1706 Fix intermittent failure of algohTimeoutTest.exp
  test/e2e-go/cli/algoh/expect/algohTimeoutTest.exp
Labels: Dev Ops

#1709 Derive the swagger version from the go.mod file
  go.mod
  go.sum
  logging/telemetryCommon.go
  logging/telemetryConfig.go
  scripts/configure_dev-deps.sh
Labels: Infrastructure

#1717 Optimize fast catchup
  catchup/catchpointService.go
  cmd/goal/messages.go
  cmd/goal/node.go
  components/mocks/mockCatchpointCatchupAccessor.go
  daemon/algod/api/Makefile
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/private/routes.go
  daemon/algod/api/server/v2/generated/private/types.go
  daemon/algod/api/server/v2/generated/routes.go
  daemon/algod/api/server/v2/generated/types.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_test.go
  daemon/algod/api/server/v2/test/helpers.go
  ledger/accountdb.go
  ledger/accountdb_test.go
  ledger/acctupdates.go
  ledger/catchpointwriter.go
  ledger/catchupaccessor.go
  node/node.go
Labels: Infrastructure

#1721 Implement opt-in in dryrun
  daemon/algod/api/server/v2/dryrun.go
  test/e2e-go/cli/goal/expect/goalDryrunRestTest.exp
  test/scripts/e2e_subs/tealprogs/app_optin_put.teal
Labels: Infrastructure

#1719 TEAL: fix return type check in assembler
  cmd/opdoc/opdoc.go
  data/transactions/logic/README.md
  data/transactions/logic/README_in.md
  data/transactions/logic/TEAL_opcodes.md
  data/transactions/logic/assembler.go
  data/transactions/logic/assembler_test.go
  data/transactions/logic/opcodes.go
Labels: Infrastructure

#1724 Fix opt-ins and timeouts in pingpong assets testing
  shared/pingpong/accounts.go
  shared/pingpong/pingpong.go
Labels: Infrastructure

#1726 Create configuration file using config.Local data structure
  netdeploy/networkTemplate.go
Labels: Infrastructure

#1636 Fixes to algoh timeout e2e test
  daemon/algod/server.go
  test/e2e-go/cli/algoh/expect/algohExpectCommon.exp
  test/e2e-go/cli/algoh/expect/algohTimeoutTest.exp
  test/e2e-go/cli/goal/expect/catchpointCatchupTest.exp
Labels: Infrastructure
