Repository algorand/go-algorand, pull requests merged in 2020-08, with the labels that each got.

#1324 Add e2e upgrade test for application over REST & Gossip
  test/e2e-go/features/catchup/basicCatchup_test.go
  test/e2e-go/upgrades/application_support_test.go
  test/e2e-go/upgrades/send_receive_upgrade_test.go
  test/testdata/nettemplates/TwoNodes100SecondTestUnupgradedProtocol.json
Labels: Infrastructure

#1333 Fix merge issue with TestApplicationsUpgradeOver e2e test
  test/e2e-go/upgrades/application_support_test.go
Labels: 0.5, Infrastructure

#1330 Added documentation for test env vars for running the expect tests
  test/e2e-go/cli/goal/expect/README.md
Labels: Dev Ops, Unplanned

#1336 Remove deprecated sudo key from travis
  .travis.yml
Labels: 0.5, Infrastructure

#1335 Refactor expect runners by creating a unified expect fixture
  test/e2e-go/cli/algod/expect/algod_expect_test.go
  test/e2e-go/cli/algoh/expect/algoh_expect_test.go
  test/e2e-go/cli/goal/expect/goal_expect_test.go
  test/framework/fixtures/expectFixture.go
Labels: 0.5, Infrastructure

#1340 Testing script for Gossip and TxSync
  test/release-testing/gossip-txsync-upgrade/README.md
  test/release-testing/gossip-txsync-upgrade/assert.sh
  test/release-testing/gossip-txsync-upgrade/functional-test.sh
  test/release-testing/gossip-txsync-upgrade/network-config/three-nodes.json
  test/release-testing/gossip-txsync-upgrade/network-config/two-nodes.json
  test/release-testing/gossip-txsync-upgrade/patch/rel/nightly-1.1.304/consensus-version-next-proto.diff
  test/release-testing/gossip-txsync-upgrade/patch/rel/nightly-1.1.304/enable-asset-create.diff
  test/release-testing/gossip-txsync-upgrade/patch/rel/nightly-1.1.304/fast-upgrade-to-next-proto.diff
  test/release-testing/gossip-txsync-upgrade/patch/rel/nightly-1.1.304/node-no-tx-broadcast.diff
  test/release-testing/gossip-txsync-upgrade/patch/rel/nightly-1.1.304/txpool-remember.diff
  test/release-testing/gossip-txsync-upgrade/patch/rel/nightly-1.1.304/upgrade-path-to-next-proto.diff
  test/release-testing/gossip-txsync-upgrade/patch/rel/nightly-2.0.323/consensus-version-next-proto.diff
  test/release-testing/gossip-txsync-upgrade/patch/rel/nightly-2.0.323/fast-upgrade-to-next-proto
  test/release-testing/gossip-txsync-upgrade/patch/rel/nightly-2.0.323/node-no-tx-broadcast.diff
  test/release-testing/gossip-txsync-upgrade/patch/rel/nightly-2.0.323/txpool-remember.diff
  test/release-testing/gossip-txsync-upgrade/patch/rel/nightly-2.0.323/upgrade-path-to-next-proto.diff
  test/release-testing/gossip-txsync-upgrade/patch/rel/nightly-2.0.574/consensus-version-next-proto.diff
  test/release-testing/gossip-txsync-upgrade/patch/rel/nightly-2.0.574/fast-upgrade-to-next-proto.diff
  test/release-testing/gossip-txsync-upgrade/patch/rel/nightly-2.0.574/node-no-tx-broadcast.diff
  test/release-testing/gossip-txsync-upgrade/patch/rel/nightly-2.0.574/txpool-remember.diff
  test/release-testing/gossip-txsync-upgrade/patch/rel/nightly-2.0.574/upgrade-path-to-next-proto.diff
  test/release-testing/gossip-txsync-upgrade/patch/rel/stable-1.0.29/node-no-tx-broadcast.diff
  test/release-testing/gossip-txsync-upgrade/patch/rel/stable-1.0.29/txpool-remember.diff
  test/release-testing/gossip-txsync-upgrade/patch/v2.0.6-stable/node-no-tx-broadcast.diff
  test/release-testing/gossip-txsync-upgrade/patch/v2.0.6-stable/txpool-remember.diff
Labels: Infrastructure

#1346 TEAL: allow empty string literals
  data/transactions/logic/assembler.go
  data/transactions/logic/assembler_test.go
  data/transactions/logic/eval_test.go
Labels: 0.5, Infrastructure

#1329 Update upgrade path to v24
  cmd/tealdbg/debugger_test.go
  config/consensus.go
  data/basics/teal_test.go
  data/transactions/logic/backwardCompat_test.go
  protocol/consensus.go
  test/e2e-go/upgrades/send_receive_upgrade_test.go
  test/testdata/nettemplates/TwoNodes50EachV23Upgrade.json
Labels: 0.5, Infrastructure

#1348 Fix merketrie prioritization cache
  crypto/merkletrie/cache.go
  crypto/merkletrie/cache_test.go
  crypto/merkletrie/trie_test.go
Labels: Infrastructure

#1344 Create a utility to generate the consensus.json file
  debug/genconsensusconfig/main.go
Labels: 0.5, Infrastructure

#1343 REST API: Add messagepack to produces list for endpoints which can produce messagepack
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/routes.go
Labels: FDE

#1345 Add unit test TestConsensusUpgradeWindow
  config/consensus_test.go
Labels: 0.5, Infrastructure

#1350 Add a fuzzer to the merkletrie cache testing
  crypto/merkletrie/cache.go
  crypto/merkletrie/cache_test.go
Labels: 1, Infrastructure

#1354 Unit test for accountsNewRound creatables parameter
  ledger/accountdb_test.go
Labels: Infrastructure

#1352 Fix Makefile to work with ubuntu 20.04
  Makefile
Labels: FDE

#1369 e2e test: create+delete create+clear in 1 tx
  test/scripts/e2e_subs/e2e-app-bootloader.sh
  test/scripts/e2e_subs/e2e-app-delete-clear.sh
  test/scripts/e2e_subs/e2e-app-real-assets-round.sh
  test/scripts/e2e_subs/e2e-app-simple.sh
  test/scripts/e2e_subs/e2e-app-stateful-global.sh
  test/scripts/e2e_subs/e2e-app-stateful-local.sh
  test/scripts/e2e_subs/e2e-app-x-app-reads.sh
Labels: Infrastructure

#1378 Add some minimal documentation for the test directory.
  README.md
  test/README.md
Labels: FDE

#1372 Eliminate nil map entries on Merkle trie cache
  crypto/merkletrie/cache.go
  crypto/merkletrie/cache_test.go
Labels: Infrastructure

#1380 listCreatablesStmt is selecting 3 columns instead of 2
  ledger/accountdb.go
Labels: Infrastructure

#1382 Avoid using encodedAccountsRange and replace with a single query
  ledger/accountdb.go
  ledger/acctupdates.go
  ledger/catchpointwriter.go
  ledger/catchpointwriter_test.go
Labels: Infrastructure

#1393 Add vacuumming to the database upgrade process
  ledger/accountdb.go
  ledger/acctupdates.go
Labels: Infrastructure

#1392 Improve client-side catchpoint catchup performance
  ledger/catchupaccessor.go
Labels: Infrastructure

#1394 Avoid redundent info message for replacing block 0
  ledger/blockdb.go
Labels: Infrastructure

#1390 Extend ledger request timeout
  agreement/gossip/network_test.go
  components/mocks/mockNetwork.go
  network/requestTracker.go
  network/requestTracker_test.go
  network/wsNetwork.go
  rpcs/ledgerService.go
Labels: Infrastructure

#1383 Added TestListCreatables to test ListAssets and ListApplications
  ledger/accountdb_test.go
  ledger/acctupdates_test.go
Labels: Infrastructure

#1407 Disable deadlock detection on master
  scripts/compute_branch_deadlock_default.sh
  scripts/travis/build_test.sh
  scripts/travis/integration_test.sh
  scripts/travis/test_release.sh
Labels: Infrastructure

#1406 Fix fast catchup processed/total account values swapped.
  cmd/goal/node.go
Labels: FDE

#1409 Slow down catchup while catchpoint file is being written
  catchup/service.go
  catchup/service_test.go
  ledger/acctupdates.go
  ledger/ledger.go
Labels: Infrastructure

#1415 Update CatchpointInterval config comment
  config/config.go
Labels: Infrastructure

#1370 Add Rekeying to pingpong
  cmd/pingpong/runCmd.go
  shared/pingpong/config.go
  shared/pingpong/pingpong.go
Labels: Infrastructure

#1436 Add a test for goal app --app-account flag.
  test/e2e-go/cli/goal/expect/README.md
  test/e2e-go/cli/goal/expect/goalAppAccountAddressTest.exp
  test/e2e-go/cli/goal/expect/goalExpectCommon.exp
  test/scripts/e2e_subs/tealprogs/appAccountParams.teal
Labels: Infrastructure

#1435 add an API for using MsgOfInterest messages
  network/msgOfInterest.go
  network/wsNetwork.go
  protocol/tags.go
Labels: Infrastructure

#1446 Fix accounting bug in page loading
  crypto/merkletrie/cache.go
  crypto/merkletrie/cache_test.go
Labels: Infrastructure

#1442 Fix - avoid "ran out of time for round"
  data/pools/transactionPool.go
  node/node.go
Labels: Infrastructure
