Repository algorand/go-algorand, pull requests merged in 2020-06, with the labels that each got.

#970 Fast Catchup
  catchup/watchdogStreamReader.go
  cmd/goal/node.go
  ledger/acctupdates.go
  ledger/acctupdates_test.go
  ledger/catchpointwriter.go
  ledger/catchpointwriter_test.go
  logging/telemetryspec/event.go
Labels: Infrastructure

#1147 FastCatchup - add unit testing for ledgerFetcher
  catchup/catchpointService.go
  catchup/ledgerFetcher.go
  catchup/ledgerFetcher_test.go
  components/mocks/mockCatchpointCatchupAccessor.go
  ledger/catchupaccessor.go
Labels: Infrastructure

#1129 Eric/fix pingpong asset
  shared/pingpong/accounts.go
  shared/pingpong/pingpong.go
Labels: Dev Ops

#1173 Fix content of hashes file(s)
  scripts/release/mule/sign/sign.sh
Labels: Dev Ops

#1153 Regenerate routes to allow 'pretty' parameter.
  daemon/algod/api/Makefile
  daemon/algod/api/server/v2/generated/private/routes.go
  daemon/algod/api/server/v2/generated/routes.go
  go.mod
  go.sum
Labels: FDE

#1174 Fix deb package name
  scripts/release/mule/package/deb/package.sh
Labels: Dev Ops

#1072 Eric/use mule in jenkins
  Makefile
  docker/build/Dockerfile
  docker/build/Dockerfile-deploy
  docker/build/cicd.alpine.Dockerfile
  docker/build/cicd.centos.Dockerfile
  mule.yaml
  network/ping_test.go
  scripts/build_package.sh
  scripts/build_packages.sh
  scripts/configure_dev.sh
  scripts/release/mule/Makefile.mule
  scripts/upload_version.sh
  test/e2e-go/cli/goal/expect/goalExpectCommon.exp
  test/e2e-go/cli/goal/expect/goalTxValidityTest.exp
  test/e2e-go/upgrades/send_receive_upgrade_test.go
  test/muleCI/Jenkinsfile
  test/muleCI/mule.yaml
  test/scripts/e2e.sh
  test/scripts/e2e_basic_start_stop.sh
  test/scripts/e2e_client_runner.py
  test/scripts/e2e_subs/limit-swap-test.sh
  test/scripts/goal_subcommand_sanity.sh
  test/scripts/testrunid.py
Labels: Dev Ops

#1187 Remove all code for generating the releases page
  package-deploy.yaml
  scripts/release/mule/deploy/generate_releases_page/deploy.sh
  scripts/release/mule/deploy/generate_releases_page/generate_releases_page.py
  scripts/release/mule/deploy/generate_releases_page/html.tpl
  scripts/release/mule/deploy/generate_releases_page/releases_page.css
  scripts/release/prod/Jenkinsfile
  scripts/release/prod/generate_releases_page/generate_releases_page
  scripts/release/prod/generate_releases_page/html.tpl
  scripts/release/prod/generate_releases_page/releases_page.css
  scripts/release/prod/stage/generate_releases_page/run.sh
Labels: Dev Ops

#1181 Only add the latest version to the rpm repo
  scripts/release/mule/deploy/rpm/deploy.sh
Labels: Dev Ops

#1191 Add EnableDeveloperAPI configuration flag
  config/config.go
  config/local_defaults.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_test.go
  daemon/algod/api/server/v2/test/helpers.go
  installer/config.json.example
Labels: review

#1182 Fix deploy location for latest rpm package
  package-deploy.yaml
Labels: Dev Ops

#1115 Improve network connectionPerformanceMonitor performance
  network/connPerfMon.go
  network/connPerfMon_test.go
  network/messageFilter_test.go
Labels: Infrastructure

#1208 Fix random catchpoint catchup expect test case
  test/e2e-go/cli/goal/expect/catchpointCatchupTest.exp
Labels: Infrastructure

#1209 Fix random fails in TestCatchupOverGossip
  test/e2e-go/features/catchup/basicCatchup_test.go
Labels: Infrastructure

#1210 Add e2e teal/compile test
  daemon/algod/api/client/restClient.go
  libgoal/teal.go
  test/e2e-go/features/teal/compile_test.go
  test/testdata/nettemplates/OneNodeFuture.json
Labels: Infrastructure

#1207 Fix cicd perf test
  Makefile
  docker/build/Dockerfile
  docker/build/Dockerfile-deploy
  docker/build/cicd.centos.Dockerfile
  docker/build/cicd.ubuntu.Dockerfile
  docker/build/mule.go.centos.Dockerfile
  scripts/deploy_linux_version.sh
  scripts/deploy_private_version.sh
  scripts/deploy_version.sh
  scripts/envDevnet.sh
  scripts/envTestnet.sh
  scripts/release/common/setup.sh
  scripts/release/mule/Makefile.mule
Labels: Dev Ops
