Repository algorand/go-algorand, pull requests merged in 2020-09, with the labels that each got.

#1439 No need to return an error when requesting the same catchpoint multiple times
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/client/restClient.go
  daemon/algod/api/server/v2/generated/private/routes.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_test.go
  daemon/algod/api/server/v2/test/helpers.go
  node/error.go
  node/node.go
Labels: FDE

#1405 Simplify dryrunning and debugging group txn
  cmd/goal/clerk.go
  cmd/tealdbg/main.go
  daemon/algod/api/server/v2/dryrun.go
  libgoal/libgoal.go
  test/e2e-go/cli/goal/expect/goalDryrunRestTest.exp
Labels: Infrastructure

#1480 Add support for algorelay deleting unused SRV and DNS entries
  cmd/algorelay/relayCmd.go
  tools/network/cloudflare/cloudflare.go
Labels: Infrastructure

#1485 Add a benchmark to test restoring from catchpoint performance
  ledger/catchupaccessor_test.go
  ledger/ledger_test.go
Labels: Infrastructure

#1481 Optimize Merkle trie memory consumption
  crypto/merkletrie/bitset.go
  crypto/merkletrie/bitset_test.go
  crypto/merkletrie/cache.go
  crypto/merkletrie/cache_test.go
  crypto/merkletrie/committer_test.go
  crypto/merkletrie/node.go
  crypto/merkletrie/node_test.go
  crypto/merkletrie/trie.go
  crypto/merkletrie/trie_test.go
Labels: Infrastructure

#1486 Add unit tests for equal functions in teal.go
  data/basics/teal_test.go
Labels: Infrastructure

#1491 Add a benchmark for writeCatchpointStagingBalances
  ledger/accountdb_test.go
Labels: Infrastructure

#1493 Removing close from eof pattern match
  test/e2e-go/cli/goal/expect/goalAppAccountAddressTest.exp
Labels: Infrastructure

#1494 Improve db insertion benchmark - add ordered insertions
  ledger/accountdb_test.go
Labels: Infrastructure

#1495 Adding ledger tests
  ledger/ledger_test.go
Labels: Infrastructure

#1497 Add txn.Accounts and txn.ApplicationArgs support to tealdbg
  cmd/tealdbg/cdtState.go
  data/transactions/logic/eval.go
  data/transactions/logic/eval_test.go
Labels: Infrastructure

#1499 Improve RestoringFromCatchpointFile benchmark precision
  ledger/catchupaccessor_test.go
Labels: Infrastructure

#1509 Calculate normalized balance using genesis proto
  ledger/acctupdates.go
Labels: Infrastructure

#1511 Exit algod with a non-zero in case of a startup error
  cmd/algod/main.go
Labels: Infrastructure

#1502 Test for process return in expect tests
  test/e2e-go/cli/goal/expect/goalAppAccountAddressTest.exp
  test/e2e-go/cli/goal/expect/goalExpectCommon.exp
  test/e2e-go/cli/goal/expect/testInfraTest.exp
Labels: Infrastructure

#1469 Remove commas from mule yaml files
  package-deploy.yaml
  package-sign.yaml
  package-test.yaml
Labels: Dev Ops

#1521 Remove the Lookup from the ledgerForEvaluator interface
  ledger/acctupdates.go
  ledger/eval.go
Labels: Infrastructure

#1508 Vote validation error refactor
  agreement/abstractions.go
  agreement/asyncVoteVerifier.go
  agreement/common_test.go
  agreement/selector.go
  agreement/vote.go
  agreement/voteAggregator_test.go
  ledger/acctupdates.go
  node/impls.go
Labels: Infrastructure

#1520 Filter Timeout Change Refactor
  agreement/types.go
  config/consensus.go
  node/node_test.go
  test/e2e-go/features/transactions/accountv2_test.go
  test/e2e-go/perf/basic_test.go
  test/e2e-go/upgrades/send_receive_upgrade_test.go
  test/testdata/consensus/catchpointtestingprotocol.json
Labels: Infrastructure

#1518 Cache the most recent Seed/Circulation calls to reduce pressure on ledger
  data/ledger.go
  data/ledger_test.go
Labels: Infrastructure

#1536 Deprecate algolambdamsec environment variable
  config/consensus.go
  test/e2e-go/cli/goal/expect/catchpointCatchupTest.exp
  test/e2e-go/features/catchup/catchpointCatchup_test.go
  test/e2e-go/features/transactions/accountv2_test.go
  test/e2e-go/upgrades/application_support_test.go
  test/e2e-go/upgrades/rekey_support_test.go
  test/e2e-go/upgrades/send_receive_upgrade_test.go
Labels: Infrastructure

#1528 Fix heuristicFormatStr logic
  cmd/goal/application.go
  cmd/goal/interact.go
  data/basics/address.go
Labels: Infrastructure

#1539 Correctly account for bloom filter binary marshaling size
  rpcs/txService.go
  util/bloom/bloom.go
Labels: 1, Infrastructure

#1532 Add concurrent read and write test from database table
  util/db/dbutil_test.go
Labels: 1, Infrastructure

#1542 Add detailed error logging in case of failed blocks download
  catchup/catchpointService.go
  catchup/httpFetcher.go
Labels: Infrastructure

#1513 Improve goal node start error reporting in case of algod errored
  nodecontrol/algodControl.go
  nodecontrol/nodeControlErrors.go
  test/e2e-go/cli/goal/expect/goalNodeTest.exp
Labels: 1, Infrastructure

#1549 remove expected ReadError events
  network/requestLogger_test.go
  network/wsNetwork_test.go
  network/wsPeer.go
Labels: Infrastructure

#1556 Add a unit test to confirm BinaryMarshalLength correctness
  util/bloom/bloom_test.go
Labels: Infrastructure

#1564 Fix typos in ledger package
  ledger/accountdb.go
  ledger/acctupdates.go
  ledger/bulletin.go
  ledger/catchpointwriter.go
  ledger/catchupaccessor.go
  ledger/ledger.go
  ledger/notifier.go
Labels: Infrastructure

#1561 bugfix: limit txpool size by transaction count rather then transaction groups count
  data/pools/transactionPool.go
  data/pools/transactionPool_test.go
  node/node.go
  rpcs/httpTxSync.go
  rpcs/txService.go
  rpcs/txSyncer.go
  rpcs/txSyncer_test.go
Labels: Infrastructure

#1574 Fix random failure in goalNodeTest.exp
  test/e2e-go/cli/goal/expect/goalNodeTest.exp
Labels: Infrastructure
