Repository algorand/go-algorand, pull requests merged in 2020-10, with the labels that each got.

#1579 bugfix: fix random failure in goalAppAccountAddressTest.exp
  test/e2e-go/cli/goal/expect/goalAppAccountAddressTest.exp
Labels: Infrastructure

#1476 Update rpm packaging
  docker/build/docker.ubuntu.Dockerfile
  package-deploy.yaml
  scripts/release/mule/deploy/rpm/deploy.sh
Labels: Dev Ops

#1477 Update deploy scripts to reflect current deploy strategy
  package-deploy.yaml
  scripts/release/mule/Makefile.mule
  scripts/release/mule/deploy/deb/deploy.sh
  scripts/release/mule/deploy/docker/docker.sh
  scripts/release/mule/deploy/sync_from_staging.sh
  scripts/release/mule/deploy/update_releases_page.sh
Labels: Dev Ops

#1581 Coverage tests for ledger/acctupdates
  ledger/acctupdates_test.go
Labels: Infrastructure

#1584 bugfix: correct accounting of transactions in checkPendingQueueSize
  data/pools/transactionPool.go
  data/pools/transactionPool_test.go
Labels: Infrastructure

#1512 Improve network template validation
  netdeploy/networkTemplate.go
  netdeploy/networkTemplates_test.go
  test/testdata/nettemplates/TwoNodesOneRelay1000Accounts.json
Labels: 1, Infrastructure

#1527 Decouple database round and acctupdate round
  ledger/accountdb.go
  ledger/accountdb_test.go
  ledger/acctupdates.go
Labels: 3, Infrastructure

#1585 avoid printing control characters from goal
  cmd/goal/application.go
  cmd/goal/commands.go
  cmd/goal/formatting.go
  cmd/goal/formatting_test.go
  cmd/goal/interact.go
  cmd/goal/messages.go
  test/e2e-go/cli/goal/expect/goalFormattingTest.exp
Labels: Infrastructure

#1599 Optimize listCreatables implementation
  ledger/acctupdates.go
Labels: Infrastructure

#1608 Add support for Windows compilation on travis
  .travis.yml
  Makefile
  scripts/configure_dev.sh
  scripts/ostype.sh
  scripts/travis/before_build.sh
  scripts/travis/build.sh
  scripts/travis/configure_dev.sh
  scripts/travis/test.sh
Labels: Infrastructure

#1611 Refactor AssembleBlock error
  data/pools/transactionPool.go
  data/pools/transactionPool_test.go
  data/txHandler_test.go
  node/assemble_test.go
  node/node.go
Labels: Infrastructure

#1612 Repack merkle trie pages before flush
  crypto/merkletrie/cache.go
  crypto/merkletrie/cache_test.go
  crypto/merkletrie/committer.go
  crypto/merkletrie/committer_test.go
  crypto/merkletrie/node.go
  crypto/merkletrie/node_test.go
  crypto/merkletrie/trie.go
  crypto/merkletrie/trie_test.go
  ledger/accountdb.go
  ledger/acctupdates.go
  ledger/catchupaccessor.go
  ledger/catchupaccessor_test.go
Labels: Infrastructure

#1619 Change telemetryConfig from global variable to a member of the logger
  cmd/algod/main.go
  cmd/algoh/main.go
  logging/log.go
  logging/telemetry.go
  logging/telemetryCommon.go
  logging/telemetryConfig.go
  logging/telemetry_test.go
Labels: Infrastructure

#1595 add ascii filtering for remote requests logged data
  network/wsNetwork.go
  network/wsNetwork_test.go
  network/wsPeer.go
Labels: Infrastructure

#1622 fix unreliable network unit test TestSlowPeerDisconnection
  network/wsNetwork_test.go
Labels: Infrastructure

#1609 Implement e2e test for tealdbg
  cmd/tealdbg/cdt/proto.go
  cmd/tealdbg/cdtSession.go
  cmd/tealdbg/cdtState.go
  cmd/tealdbg/cdtdbg.go
  cmd/tealdbg/localLedger.go
  cmd/tealdbg/local_test.go
  cmd/tealdbg/server.go
  test/e2e-go/cli/tealdbg/cdtmock/main.go
  test/e2e-go/cli/tealdbg/expect/tealdbgTest.exp
  test/e2e-go/cli/tealdbg/expect/tealdbg_expect_test.go
Labels: Infrastructure

#1621 Set content type header for health endpoint
  daemon/algod/api/server/common/handlers.go
Labels: FDE

#1613 tealdbg unit tests
  cmd/tealdbg/cdtSession.go
  cmd/tealdbg/cdtSession_test.go
  cmd/tealdbg/cdtState.go
  cmd/tealdbg/cdtdbg.go
  cmd/tealdbg/cdtdbg_test.go
  cmd/tealdbg/debugger.go
  cmd/tealdbg/debugger_test.go
  cmd/tealdbg/local.go
  cmd/tealdbg/localLedger.go
  cmd/tealdbg/main.go
  cmd/tealdbg/remote_test.go
  cmd/tealdbg/server.go
  cmd/tealdbg/server_test.go
  cmd/tealdbg/util_test.go
  cmd/tealdbg/webdbg.go
  cmd/tealdbg/webdbg_test.go
  data/transactions/logic/debugger.go
  test/e2e-go/cli/tealdbg/expect/tealdbg_expect_test.go
Labels: Infrastructure

#1627 Output error when 'goal node stop' is run on invalid directory
  nodecontrol/NodeController.go
  nodecontrol/algodControl.go
  nodecontrol/algodControl_test.go
  test/e2e-go/cli/algod/expect/algodTelemetryLocationTest.exp
  test/e2e-go/cli/goal/expect/goalNodeTest.exp
  test/e2e-go/features/transactions/transactionPool_test.go
Labels: Infrastructure

#1639 Netgoal general templates
  cmd/netgoal/network.go
  netdeploy/remote/buildConfig.go
  netdeploy/remote/deployedNetwork.go
Labels: Infrastructure

#1634 tealdbg: listen for upcoming spinoff connections
  cmd/tealdbg/cdtdbg.go
  cmd/tealdbg/debugger.go
  cmd/tealdbg/debugger_test.go
  cmd/tealdbg/main.go
  cmd/tealdbg/server.go
  cmd/tealdbg/server_test.go
  cmd/tealdbg/webdbg.go
  test/e2e-go/cli/tealdbg/expect/tealdbgSpinoffTest.exp
Labels: Infrastructure

#1642 Tweak the mainnet-model recipe
  test/testdata/deployednettemplates/hosttemplates/hosttemplates.json
  test/testdata/deployednettemplates/recipes/mainnet-model/Makefile
  test/testdata/deployednettemplates/recipes/mainnet-model/generate_network_rules.js
  test/testdata/deployednettemplates/recipes/mainnet-model/generated/net.json
  test/testdata/deployednettemplates/recipes/mainnet-model/generated/topology.json
  test/testdata/deployednettemplates/recipes/mainnet-model/network-tpl.json
  test/testdata/deployednettemplates/recipes/mainnet-model/network_performance_rules
Labels: Infrastructure

#1646 Ensure syncStartNS is managed correctly across catchpoint file writing
  catchup/pref_test.go
  catchup/service.go
  catchup/service_test.go
Labels: Infrastructure

#1644 Refactor parseIntcblock
  data/transactions/logic/assembler.go
  data/transactions/logic/assembler_test.go
Labels: Infrastructure

#1660 Avoid printing control characters for displaying assets
  cmd/goal/account.go
  cmd/goal/accountsList.go
  cmd/goal/asset.go
  test/e2e-go/cli/goal/expect/goalAssetTest.exp
Labels: Infrastructure

#1669 Update mainnet-model for scale and distribution
  test/testdata/deployednettemplates/recipes/mainnet-model/Makefile
  test/testdata/deployednettemplates/recipes/mainnet-model/generated/net.json
  test/testdata/deployednettemplates/recipes/mainnet-model/generated/topology.json
  test/testdata/deployednettemplates/recipes/mainnet-model/network-tpl.json
Labels: Infrastructure

#1658 Separate the error message for duplicate txn id and lease
  ledger/acctupdates.go
  ledger/cow.go
  ledger/cow_test.go
  ledger/error.go
  ledger/eval.go
  ledger/ledger.go
  ledger/txtail.go
  ledger/txtail_test.go
  test/scripts/e2e_subs/keyreg-teal-test.sh
Labels: Infrastructure

#1678 Update goal error message for unauthorized access
  cmd/goal/messages.go
  daemon/algod/api/client/restClient.go
  test/e2e-go/cli/algoh/expect/algohTimeoutTest.exp
  test/e2e-go/cli/goal/expect/goalNodeConnectionTest.exp
Labels: Infrastructure
