Repository algorand/go-algorand, pull requests merged in 2021-12, with the labels that each got.

#3269 testing: fix a data race in app tests
  ledger/applications_test.go
Labels: Team Carbon-11

#3266 testing: fix e2e.sh mixed indent characters
  test/scripts/e2e.sh
Labels: unplanned, Team Carbon-11

#3264 Fix ParticipationKeyResponse type.
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/private/routes.go
  daemon/algod/api/server/v2/generated/private/types.go
  daemon/algod/api/server/v2/generated/routes.go
  daemon/algod/api/server/v2/generated/types.go
Labels: Team Carbon-11

#3245 Updating Readme.md with circleci status badges
  README.md
Labels: Team Hyper Flow

#3234 apply.balances part2: cow to acct update changes
  cmd/catchpointdump/file.go
  data/basics/userBalance.go
  ledger/accountdb.go
  ledger/accountdb_test.go
  ledger/acctupdates.go
  ledger/acctupdates_test.go
  ledger/apply/application.go
  ledger/apply/application_test.go
  ledger/apply/apply.go
  ledger/apply/asset.go
  ledger/apply/keyreg_test.go
  ledger/apply/mockBalances_test.go
  ledger/apply/payment.go
  ledger/apptxn_test.go
  ledger/catchpointtracker_test.go
  ledger/catchpointwriter.go
  ledger/catchupaccessor_test.go
  ledger/evalindexer_test.go
  ledger/internal/appcow.go
  ledger/internal/appcow_test.go
  ledger/internal/applications.go
  ledger/internal/applications_test.go
  ledger/internal/compactcert_test.go
  ledger/internal/cow.go
  ledger/internal/cow_creatables.go
  ledger/internal/cow_test.go
  ledger/internal/eval.go
  ledger/internal/eval_blackbox_test.go
  ledger/internal/eval_test.go
  ledger/ledger.go
  ledger/ledger_perf_test.go
  ledger/ledger_test.go
  ledger/ledgercore/accountdata.go
  ledger/ledgercore/statedelta.go
  ledger/ledgercore/statedelta_test.go
  ledger/ledgercore/totals.go
  ledger/lruaccts.go
  ledger/onlinetopheap.go
  ledger/testing/accountsTotals.go
  ledger/testing/randomAccounts.go
  ledger/tracker.go
  ledger/voters.go
Labels: Team Carbon-11

#3278 Add Custom Scenario for Performance Testing
  scripts/create_and_deploy_recipe.sh
  test/testdata/deployednettemplates/generate-recipe/generate_network.py
  test/testdata/deployednettemplates/recipes/custom/README.md
  test/testdata/deployednettemplates/recipes/custom/configs/node.json
  test/testdata/deployednettemplates/recipes/custom/configs/nonPartNode.json
  test/testdata/deployednettemplates/recipes/custom/configs/relay.json
  test/testdata/deployednettemplates/recipes/custom/example/README.md
  test/testdata/deployednettemplates/recipes/custom/example/config_jsons/config.json
  test/testdata/deployednettemplates/recipes/custom/example/configs/node.json
  test/testdata/deployednettemplates/recipes/custom/example/configs/nonPartNode.json
  test/testdata/deployednettemplates/recipes/custom/example/configs/relay.json
  test/testdata/deployednettemplates/recipes/custom/example/consensus.json
  test/testdata/deployednettemplates/recipes/custom/example/network_templates/c5dmachines.json
  test/testdata/deployednettemplates/recipes/custom/example/network_templates/network-tpl.json
  test/testdata/deployednettemplates/recipes/custom/network_templates/network-tpl.json
Labels: Team Hyper Flow

#3261 ParticipationRegistry - StateProof loading methods
  data/account/participationRegistry.go
  data/account/participationRegistryBench_test.go
  data/account/participationRegistry_test.go
  go.mod
  go.sum
Labels: Team Carbon-11

#3220 Op base64 decode
  .gitignore
  data/transactions/logic/README.md
  data/transactions/logic/TEAL_opcodes.md
  data/transactions/logic/assembler.go
  data/transactions/logic/assembler_test.go
  data/transactions/logic/doc.go
  data/transactions/logic/eval.go
  data/transactions/logic/evalStateful_test.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/fields.go
  data/transactions/logic/fields_string.go
  data/transactions/logic/opcodes.go
Labels: Team Scytale

#3290 go-algorand relstable3.2.1-remerge
  config/version.go
Labels: Team Hyper Flow

#2825 Changing golang version to 1.16.11 in go-algorand
  .circleci/config.yml
  .github/workflows/reviewdog.yml
  Makefile
  go.mod
  go.sum
  scripts/buildtools/go.mod
  scripts/buildtools/install_buildtools.sh
  scripts/get_golang_version.sh
  scripts/travis/before_build.sh
Labels: unplanned, Team Hyper Flow

#3291 Compatibility mode for partkeyinfo.
  cmd/goal/account.go
Labels: unplanned, Team Carbon-11

#3299 Fix: stop the completed catchup service
  catchup/service.go
Labels: unplanned, Team Carbon-11

#3268 Disable flaky test.
  test/e2e-go/features/devmode/devmode_test.go
Labels: unplanned, Team Carbon-11

#3292 ledger refactoring: Ordered resource deltas - part 1
  ledger/applications_test.go
  ledger/ledgercore/statedelta.go
  ledger/ledgercore/totals_test.go
Labels: Team Carbon-11

#3294 ledger refactoring: Remove ToBasicsAccountDataMap - part 2
  ledger/accountdb_test.go
  ledger/acctupdates.go
  ledger/internal/cow_test.go
  ledger/internal/eval_test.go
  ledger/ledgercore/statedelta.go
Labels: Team Carbon-11

#3303 blocks service: avoid serving blocks past service shutdown
  rpcs/blockService.go
  rpcs/blockService_test.go
Labels: Team Carbon-11

#3308 testing: improve new networks spawning performance
  netdeploy/networkTemplate.go
Labels: Team Carbon-11

#3309 Fix algorand specs link
  agreement/README.md
Labels: Team Carbon-11

#3297 testing: reword partitiontest lint message.
  cmd/partitiontest_linter/linter.go
Labels: unplanned, Team Carbon-11

#3315 testing: fix random data race in TestAppAccountDataStorage
  ledger/applications_test.go
Labels: Team Carbon-11

#3311 ledger: perform the catchpoint writing outside the trackers lock.
  ledger/acctupdates.go
  ledger/bulletin.go
  ledger/catchpointtracker.go
  ledger/catchpointtracker_test.go
  ledger/metrics.go
  ledger/notifier.go
  ledger/tracker.go
  ledger/txtail.go
Labels: Team Carbon-11

#3286 Separate Txn and PartKey validity for `goal account renewpartkey`
  cmd/goal/account.go
Labels: external contribution

#3288 Followup to opcode base64_decode
  cmd/opdoc/tmLanguage.go
  data/transactions/logic/README.md
  data/transactions/logic/README_in.md
  data/transactions/logic/TEAL_opcodes.md
  data/transactions/logic/assembler.go
  data/transactions/logic/assembler_test.go
  data/transactions/logic/doc.go
  data/transactions/logic/eval.go
  data/transactions/logic/evalStateful_test.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/fields.go
  data/transactions/logic/fields_string.go
Labels: Team Scytale

#3240 ledger refactoring: resources lookup + merkle trie regeneration
  cmd/tealdbg/localLedger.go
  daemon/algod/api/server/v2/dryrun.go
  daemon/algod/api/server/v2/handlers.go
  ledger/accountdb.go
  ledger/accountdb_test.go
  ledger/acctupdates.go
  ledger/acctupdates_test.go
  ledger/applications_test.go
  ledger/catchpointtracker.go
  ledger/catchpointtracker_test.go
  ledger/evalindexer.go
  ledger/evalindexer_test.go
  ledger/internal/cow_test.go
  ledger/internal/eval.go
  ledger/ledger.go
  ledger/ledger_test.go
  ledger/ledgercore/accountdata.go
  ledger/ledgercore/accountresource.go
  ledger/ledgercore/statedelta.go
  ledger/lruaccts_test.go
  ledger/lruresources.go
  ledger/persistedresources_list.go
Labels: Team Carbon-11

#3313 Add help and fish mode to e2e interactive mode.
  test/scripts/e2e.sh
Labels: Team Carbon-11

#3287 Minimum Account Balance in Algod
  cmd/goal/account.go
  cmd/tealdbg/local_test.go
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/account.go
  daemon/algod/api/server/v2/account_test.go
  daemon/algod/api/server/v2/generated/private/routes.go
  daemon/algod/api/server/v2/generated/private/types.go
  daemon/algod/api/server/v2/generated/routes.go
  daemon/algod/api/server/v2/generated/types.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/helpers.go
  test/e2e-go/cli/goal/expect/README.md
  test/e2e-go/cli/goal/expect/goalAccountInfoTest.exp
  test/scripts/e2e.sh
  test/scripts/e2e_subs/min_balance.py
  test/scripts/e2e_subs/min_balance.sh
Labels: Team Scytale

#3229 ledger refactoring: generate catchpoints
  ledger/accountdb.go
  ledger/accountdb_test.go
  ledger/catchpointtracker.go
  ledger/catchpointwriter.go
  ledger/catchpointwriter_test.go
  ledger/catchupaccessor.go
  ledger/catchupaccessor_test.go
  ledger/msgp_gen.go
  ledger/msgp_gen_test.go
Labels: Team Carbon-11

#3325 ledger refactoring: catchpointdump support of new schema
  cmd/catchpointdump/file.go
  ledger/accountdb.go
Labels: Team Carbon-11

#3331 Ledger refactor: cache missing resources in roundCowBase
  ledger/internal/eval.go
Labels: Team Carbon-11

#3304 Add convertAddress tool.
  README.md
  tools/README.md
  tools/debug/carpenter/main.go
  tools/debug/coroner/main.go
  tools/debug/doberman/logo.go
  tools/debug/doberman/main.go
  tools/debug/genconsensusconfig/main.go
  tools/debug/jslog
  tools/debug/logfilter/example1.in
  tools/debug/logfilter/example1.out.expected
  tools/debug/logfilter/example2.in
  tools/debug/logfilter/example2.out.expected
  tools/debug/logfilter/example3.in
  tools/debug/logfilter/example3.out.expected
  tools/debug/logfilter/example4.in
  tools/debug/logfilter/example4.out.expected
  tools/debug/logfilter/example5.in
  tools/debug/logfilter/example5.out.expected
  tools/debug/logfilter/example6.in
  tools/debug/logfilter/example6.out.expected
  tools/debug/logfilter/example7.in
  tools/debug/logfilter/example7.out.expected
  tools/debug/logfilter/example8.in
  tools/debug/logfilter/example8.out.expected
  tools/debug/logfilter/main.go
  tools/debug/logfilter/main_test.go
  tools/debug/net.py
  tools/debug/showchains.py
  tools/misc/README.md
  tools/misc/convertAddress.go
Labels: unplanned, Team Carbon-11

#3323 ledger refactoring: implement resources writing
  ledger/accountdb.go
  ledger/accountdb_test.go
  ledger/acctupdates.go
  ledger/acctupdates_test.go
  ledger/catchpointtracker_test.go
  ledger/ledgercore/accountdata.go
  ledger/testing/randomAccounts.go
  ledger/tracker.go
  logging/telemetryspec/metric.go
Labels: Team Carbon-11

#3327 ledger refactoring: update merkle trie on resource updates
  ledger/accountdb.go
  ledger/accountdb_test.go
  ledger/acctupdates.go
  ledger/acctupdates_test.go
  ledger/catchpointtracker.go
Labels: Team Carbon-11

#3346 Fix flaky test in randomized ABI encoding test
  data/abi/abi_encode_test.go
Labels: Team Scytale

#3347 ledger refactoring: update compactResourcesDeltas / compactAccountDeltas
  ledger/accountdb.go
  ledger/accountdb_test.go
  ledger/acctupdates.go
  ledger/catchpointtracker.go
Labels: Team Carbon-11

#3351 go-algorand v3.2.3-beta
  buildnumber.dat
  ledger/acctupdates.go
  ledger/bulletin.go
  ledger/catchpointtracker.go
  ledger/catchpointtracker_test.go
  ledger/metrics.go
  ledger/notifier.go
  ledger/tracker.go
  ledger/txtail.go
Labels: Team Hyper Flow

#3352 Update `goal app method` handling of args and return values
  cmd/goal/application.go
  data/abi/abi_encode.go
  data/abi/abi_encode_test.go
  test/scripts/e2e_subs/e2e-app-abi-method.sh
Labels: unplanned, Team Scytale
