Repository algorand/go-algorand, pull requests merged in 2021-10, with the labels that each got.

#3017 testing: Disable the participation key refresh on the TestPartitionHalfOffline test
  test/e2e-go/features/partitionRecovery/partitionRecovery_test.go
Labels: Team Carbon-11

#2984 Move accountdb schema migration to trackerdb.go
  ledger/accountdb.go
  ledger/accountdb_test.go
  ledger/acctupdates.go
  ledger/acctupdates_test.go
  ledger/archival_test.go
  ledger/catchpointwriter_test.go
  ledger/catchupaccessor.go
  ledger/ledger.go
  ledger/tracker.go
  ledger/trackerdb.go
Labels: Team Carbon-11

#3016 Increase machine size to large and use consistent parallelism for circleci nightly testing.
  .circleci/config.yml
Labels: Team Hyper Flow

#3018 Adjust the application of dontReportFailures in syncTest
  test/framework/fixtures/fixture.go
Labels: Team Carbon-11

#3029 ledger: fix regression in transaction pool
  data/pools/transactionPool.go
Labels: Team Carbon-11

#3075 Move deploy from TravisCI to CircleCI
  .circleci/config.yml
  .travis.yml
Labels: Team Hyper Flow

#3079 Fixing CircleCI deploy for Betanet and Stablenet (#3077)
  .circleci/config.yml
Labels: Team Hyper Flow

#3080 Fix missing TX registration
  data/txHandler.go
  network/wsNetwork.go
  test/e2e-go/features/transactions/sendReceive_test.go
Labels: Team Carbon-11

#3090 3.1.1 hotfix
  buildnumber.dat
  data/txHandler.go
  network/wsNetwork.go
  test/e2e-go/features/transactions/sendReceive_test.go
Labels: Team Hyper Flow

#3089 catchup: avoid requesting blocks that aren't needed by the ledger
  catchup/service.go
Labels: Team Carbon-11

#3103 go-algorand v3.1.2-beta
  buildnumber.dat
  data/txHandler.go
  test/e2e-go/features/transactions/sendReceive_test.go
  test/testdata/nettemplates/ThreeNodesOneOnline.json
Labels: Unplanned, Team Hyper Flow

#3051 Add buildpulse
  .circleci/config.yml
Labels: Unplanned, Team Hyper Flow

#3123 Add err to solicitedAsyncTxHandler.loop log message
  data/txHandler.go
Labels: Team Carbon-11

#3124 Enable totals calculation in eval for indexer
  ledger/internal/evalindexer.go
Labels: Team Carbon-11

#3132 ledger: do final validation in `endOfBlock()`
  ledger/internal/eval.go
  ledger/internal/evalindexer.go
Labels: Team Carbon-11

#3168 txnsync: Use dynamic maxEncodedTransactionGroups
  txnsync/encodedgroups_test.go
  txnsync/encodedgroupstypes.go
  txnsync/exchange.go
  txnsync/incoming.go
  txnsync/service.go
  txnsync/txngroups.go
  txnsync/txngroups_test.go
Labels: Team Carbon-11

#3114 Expose `StateProofPK` in TEAL
  data/transactions/logic/README.md
  data/transactions/logic/TEAL_opcodes.md
  data/transactions/logic/assembler_test.go
  data/transactions/logic/doc.go
  data/transactions/logic/eval.go
  data/transactions/logic/evalAppTxn_test.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/fields.go
  data/transactions/logic/fields_string.go
  data/transactions/logictest/ledger.go
Labels: Team Sphinx

#3101 Add unit test to avoid new `string` fields
  data/basics/fields_test.go
Labels: Team Scytale

#3141 Accounts endpoint update
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/account.go
  daemon/algod/api/server/v2/generated/private/routes.go
  daemon/algod/api/server/v2/generated/private/types.go
  daemon/algod/api/server/v2/generated/routes.go
  daemon/algod/api/server/v2/generated/types.go
  test/e2e-go/restAPI/restClient_test.go
Labels: Team Sphinx
