Repository algorand/go-algorand, pull requests merged in 2021-03, with the labels that each got.

#1931 Integrate package signing into CI pipeline
  test/muleCI/mule.yaml
Labels: Dev Ops

#1945 Improve emulator logging & send request on offset change.
  txnsync/emulatorLogger_test.go
  txnsync/emulatorNode_test.go
  txnsync/incoming.go
  txnsync/interfaces.go
  txnsync/mainloop.go
  txnsync/outgoing.go
  txnsync/peer.go
Labels: Infrastructure

#1946 TEAL3 merge branch
  cmd/opdoc/opdoc.go
  cmd/tealdbg/local.go
  cmd/tealdbg/local_test.go
  config/consensus.go
  data/basics/teal.go
  data/basics/userBalance.go
  data/transactions/logic/Makefile
  data/transactions/logic/README.md
  data/transactions/logic/README_in.md
  data/transactions/logic/TEAL_opcodes.md
  data/transactions/logic/assembler.go
  data/transactions/logic/assembler_test.go
  data/transactions/logic/backwardCompat_test.go
  data/transactions/logic/doc.go
  data/transactions/logic/doc_test.go
  data/transactions/logic/eval.go
  data/transactions/logic/evalStateful_test.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/fields.go
  data/transactions/logic/fields_string.go
  data/transactions/logic/opcodes.go
  data/transactions/logic/opcodes_test.go
  ledger/applications.go
  ledger/ledger_test.go
  protocol/consensus.go
  test/README.md
  test/e2e-go/cli/tealdbg/expect/tealdbgTest.exp
  test/scripts/e2e.sh
  test/scripts/e2e_client_runner.py
  test/scripts/e2e_subs/e2e-teal.sh
  test/scripts/e2e_subs/v24/teal-v2-only.sh
  test/testdata/nettemplates/TwoNodes50EachV24.json
Labels: Infrastructure

#1953 Add appeal to kindness to dispenser to help prevent abuse.
  cmd/dispenser/server.go
Labels: Dev Ops

#1938 Net tag stats
  network/wsPeer.go
  util/metrics/tagcounter.go
  util/metrics/tagcounter_test.go
Labels: Infrastructure

#1933 1k+ assets (part 2)
  cmd/tealdbg/localLedger.go
  daemon/algod/api/server/v2/dryrun.go
  ledger/acctupdates.go
  ledger/acctupdates_test.go
  ledger/appcow.go
  ledger/appdbg.go
  ledger/eval.go
  ledger/ledger.go
Labels: Infrastructure

#1955 Fix parameter check in abort procedure
  test/e2e-go/cli/goal/expect/goalExpectCommon.exp
Labels: Infrastructure

#1956 locally allow sync.Mutex
  cmd/algofix/deadlock.go
  cmd/algofix/deadlock_test.go
  test/e2e-go/features/catchup/basicCatchup_test.go
  txnsync/emulatorNode_test.go
Labels: Infrastructure

#1947 Improve txnsync emulator performance and memory profile
  txnsync/emulatorTimer_test.go
  txnsync/incoming.go
  txnsync/outgoing.go
Labels: Infrastructure

#1962 allow struct field to be sync.Mutex if tagged
  cmd/algofix/deadlock.go
  cmd/algofix/deadlock_test.go
Labels: Infrastructure

#1934 1k+ assets (part 3)
  ledger/ledgercore/persistedacctdata.go
  ledger/ledgercore/persistedacctdata_test.go
Labels: Infrastructure

#1959 Txn cache cleanup
  txnsync/peer.go
  txnsync/transactionCache.go
  txnsync/transactionCache_test.go
Labels: Infrastructure

#1940 Reconstruct balances database from blocks
  ledger/acctupdates.go
  ledger/acctupdates_test.go
Labels: Infrastructure

#1965 Improve ConsensusVersion errors
  data/ledger.go
  ledger/README.md
  ledger/blockqueue.go
  ledger/ledger.go
  ledger/ledger_test.go
Labels: Infrastructure

#1972 Fix random e2e test failure in TestAccountInformationV2
  test/e2e-go/features/transactions/accountv2_test.go
Labels: Infrastructure

#1964 Improve ledger running behind the agreement
  agreement/demux.go
Labels: Infrastructure

#1976 TEAL 3 changes for tealdbg
  cmd/tealdbg/cdtState.go
  data/transactions/logic/assembler.go
  data/transactions/logic/assembler_test.go
Labels: FDE

#1935 1k+ assets (part 4)
  ledger/accountdb.go
  ledger/accountdb_test.go
  ledger/acctupdates.go
  ledger/acctupdates_test.go
  scripts/dump_genesis.sh
Labels: Infrastructure

#1981 nil check fix
  util/metrics/tagcounter.go
  util/metrics/tagcounter_test.go
Labels: Infrastructure, Unplanned

#1977 tealdbg: listen on specified address
  cmd/tealdbg/main.go
  cmd/tealdbg/server.go
  cmd/tealdbg/server_test.go
  test/e2e-go/cli/tealdbg/expect/tealdbgTest.exp
Labels: Infrastructure

#1979 skip printing the logs when program is in terminated state.
  test/scripts/e2e_client_runner.py
Labels: Infrastructure

#1923 Universal fetcher for http and ws fetchers
  catchup/catchpointService.go
  catchup/fetcher.go
  catchup/fetcher_test.go
  catchup/httpFetcher.go
  catchup/peerSelector.go
  catchup/pref_test.go
  catchup/service.go
  catchup/service_test.go
  catchup/universalFetcher.go
  catchup/universalFetcher_test.go
  catchup/wsFetcher.go
  rpcs/txSyncer_test.go
Labels: Infrastructure

#1980 Fixes for pending transaction endpoint
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_test.go
  daemon/algod/api/server/v2/test/helpers.go
Labels: FDE, bug

#1975 Optimize bloom filter memory allocations
  util/bloom/bloom.go
  util/bloom/bloom_test.go
Labels: Infrastructure

#1984 Rebase transaction sync with master
  agreement/demux.go
  catchup/catchpointService.go
  catchup/fetcher.go
  catchup/fetcher_test.go
  catchup/httpFetcher.go
  catchup/peerSelector.go
  catchup/pref_test.go
  catchup/service.go
  catchup/service_test.go
  catchup/universalFetcher.go
  catchup/universalFetcher_test.go
  catchup/wsFetcher.go
  cmd/tealdbg/cdtState.go
  cmd/tealdbg/main.go
  cmd/tealdbg/server.go
  cmd/tealdbg/server_test.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_test.go
  daemon/algod/api/server/v2/test/helpers.go
  data/transactions/logic/assembler.go
  data/transactions/logic/assembler_test.go
  rpcs/txSyncer_test.go
  test/e2e-go/cli/tealdbg/expect/tealdbgTest.exp
  test/scripts/e2e_client_runner.py
  util/bloom/bloom.go
  util/bloom/bloom_test.go
  util/metrics/tagcounter.go
  util/metrics/tagcounter_test.go
Labels: Infrastructure

#1982 Report algod panic in algoh
  cmd/algoh/main.go
Labels: Infrastructure, Unplanned

#1990 copy GetPeerData()/SetPeerData() from txnsync branch
  network/wsNetwork.go
  network/wsNetwork_test.go
  network/wsPeer.go
Labels: Infrastructure

#1995 make deadlockLogger thread-safe
  daemon/algod/deadlockLogger.go
  daemon/algod/deadlock_test.go
Labels: Infrastructure

#1991 Avoid compact cert validation on non-validate/non-generate path
  ledger/acctupdates_test.go
  ledger/appcow_test.go
  ledger/cow.go
  ledger/eval.go
  ledger/ledgercore/statedelta.go
  ledger/ledgercore/statedelta_test.go
  ledger/txtail_test.go
  test/e2e-go/features/compactcert/compactcert_test.go
Labels: Infrastructure

#2003 Add comments to releases page script.
  scripts/release/mule/deploy/releases_page/generate_releases_page.py
Labels: Dev Ops, Unplanned

#2000 Fix swagger specification mismatches
  daemon/algod/api/server/v1/handlers/responses.go
  daemon/kmd/lib/kmdapi/requests.go
  daemon/kmd/lib/kmdapi/responses.go
Labels: Infrastructure

#2006 Improve memory allocations in cloneAssetHoldings and cloneAssetParams
  ledger/apply/asset.go
  ledger/apply/asset_test.go
  network/limited_reader_slurper.go
Labels: Infrastructure, Unplanned

#2014 Upgrade the websocket library to use version 1.4.2
  go.mod
  go.sum
Labels: Infrastructure, Unplanned

#2019 Adjust the network outgoing buffer sizes
  network/wsNetwork.go
Labels: Infrastructure, Unplanned

#2016 Precise calculation of paysetHint for block eval
  data/pools/transactionPool.go
  ledger/appcow.go
  ledger/appcow_test.go
  ledger/cow.go
  ledger/cow_test.go
  ledger/eval.go
  ledger/ledgercore/statedelta.go
Labels: Infrastructure, Unplanned

#2002 BlockService redirects when does not have the round
  catchup/catchpointService.go
  catchup/pref_test.go
  catchup/service.go
  catchup/service_test.go
  catchup/universalFetcher.go
  catchup/universalFetcher_test.go
  config/config.go
  config/local_defaults.go
  installer/config.json.example
  network/wsNetwork.go
  node/node.go
  rpcs/blockService.go
  rpcs/blockService_test.go
  rpcs/txService_test.go
  test/testdata/configs/config-v16.json
Labels: Infrastructure

#2012 Cache docker images in Travis and re-load them
  .travis.yml
Labels: Dev Ops

#2020 go-algorand 2.5.3-beta
  buildnumber.dat
  data/pools/transactionPool.go
  go.mod
  go.sum
  ledger/appcow.go
  ledger/appcow_test.go
  ledger/apply/asset.go
  ledger/apply/asset_test.go
  ledger/cow.go
  ledger/cow_test.go
  ledger/eval.go
  ledger/ledgercore/statedelta.go
  ledger/ledgercore/statedelta_test.go
  network/limited_reader_slurper.go
  network/wsNetwork.go
Labels: Dev Ops

#2021 Fix few typos in comments
  agreement/demux.go
  network/connPerfMon.go
  network/wsNetwork_test.go
  test/commandandcontrol/cc_agent/component/agent.go
  test/commandandcontrol/cc_service/main.go
  util/metrics/counter_test.go
  util/metrics/gauge_test.go
  util/metrics/segment_test.go
Labels: Infrastructure, Unplanned

#2025 Improve TestCompactCerts error testing
  test/e2e-go/features/compactcert/compactcert_test.go
Labels: Infrastructure

#2026 clear unused test code
  catchup/fetcher_test.go
  catchup/service_test.go
Labels: Infrastructure

#2035 testing: fix node shutdown on error
  test/e2e-go/cli/goal/expect/goalExpectCommon.exp
Labels: Infrastructure

#2032 node controller: delete pid file on process killing
  nodecontrol/NodeController.go
  nodecontrol/algodControl.go
  nodecontrol/kmdControl.go
Labels: Infrastructure

#1957 Fix for wrong channel when packaging.
  scripts/release/mule/package/deb/package.sh
Labels: Dev Ops
