Repository algorand/go-algorand, pull requests merged in 2021-01, with the labels that each got.

#1806 Add f.Close() return code testing in SystemConfig()
  tools/network/dnssec/config_unix.go
Labels: Infrastructure

#1799 Improve agreement cadaver & crash database error handling
  agreement/cadaver.go
  agreement/persistence.go
Labels: Infrastructure

#1800 Improve node error code checking
  node/node.go
  node/node_test.go
Labels: Infrastructure

#1805 Add the ability to disable catchup in config file
  catchup/service.go
  catchup/service_test.go
  config/config.go
Labels: Infrastructure

#1801 Fix return code testing & fix data directroy cloning
  nodecontrol/algodControl.go
  nodecontrol/kmdControl.go
Labels: Infrastructure

#1804 bugfix: clear roundDigest when fast catchup is switching off
  ledger/acctupdates.go
  ledger/acctupdates_test.go
  ledger/catchpointwriter_test.go
  ledger/txtail_test.go
Labels: Infrastructure

#1811 Add BenchmarkWritingRandomBalancesDisk
  ledger/accountdb_test.go
Labels: Infrastructure

#1812 Indexer state test for keys creation/deletion
  test/scripts/e2e_subs/dex.sh
  test/scripts/e2e_subs/tealprogs/dex.teal
Labels: Infrastructure

#1798 Add BenchmarkVariableTransactionMessageBlockSizes
  network/wsNetwork.go
  network/wsNetwork_test.go
Labels: Infrastructure

#1819 Fix deprication warning on sortition compilation
  data/committee/sortition/sortition.go
Labels: Infrastructure

#1796 Move peer.PrepareURL to net.SubstituteGenesisID
  catchup/fetcher_test.go
  catchup/httpFetcher.go
  catchup/ledgerFetcher.go
  components/mocks/mockNetwork.go
  network/wsNetwork.go
  network/wsPeer.go
  rpcs/httpTxSync.go
  rpcs/txService_test.go
  rpcs/txSyncer_test.go
Labels: Infrastructure

#1765 App refactoring
  cmd/tealdbg/cdtSession.go
  cmd/tealdbg/cdtdbg_test.go
  cmd/tealdbg/debugger.go
  cmd/tealdbg/local.go
  cmd/tealdbg/localLedger.go
  cmd/tealdbg/localLedger_test.go
  cmd/tealdbg/local_test.go
  config/consensus.go
  daemon/algod/api/client/restClient.go
  daemon/algod/api/server/v2/dryrun.go
  daemon/algod/api/server/v2/dryrun_test.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_test.go
  data/basics/msgp_gen.go
  data/basics/teal.go
  data/basics/teal_test.go
  data/basics/userBalance.go
  data/basics/userBalance_test.go
  data/transactions/application.go
  data/transactions/logic/debugger.go
  data/transactions/logic/eval.go
  data/transactions/logic/evalStateful_test.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/kvcow.go
  data/transactions/logic/kvcow_test.go
  ledger/accountdb.go
  ledger/accountdb_test.go
  ledger/acctupdates.go
  ledger/acctupdates_test.go
  ledger/appcow.go
  ledger/appcow_test.go
  ledger/applications.go
  ledger/applications_test.go
  ledger/apply/application.go
  ledger/apply/application_test.go
  ledger/apply/apply.go
  ledger/apply/asset.go
  ledger/apply/keyreg.go
  ledger/apply/keyreg_test.go
  ledger/apply/payment.go
  ledger/apply/payment_test.go
  ledger/catchpointwriter.go
  ledger/catchpointwriter_test.go
  ledger/cow.go
  ledger/cow_test.go
  ledger/eval.go
  ledger/eval_test.go
  ledger/ledger.go
  ledger/ledger_test.go
  ledger/msgp_gen.go
  libgoal/libgoal.go
  scripts/dump_genesis.sh
  test/e2e-go/cli/goal/expect/goalAppAccountAddressTest.exp
  test/e2e-go/features/transactions/accountv2_test.go
  test/scripts/e2e_subs/assets-app.sh
  test/scripts/e2e_subs/e2e-app-delete-clear.sh
Labels: Infrastructure

#1818 Implement base round account caching
  ledger/accountdb.go
  ledger/accountdb_test.go
  ledger/acctupdates.go
  ledger/acctupdates_test.go
  ledger/lruaccts.go
  ledger/lruaccts_test.go
Labels: Infrastructure

#1824 Improve network package error handling
  network/requestTracker.go
  network/wsNetwork.go
  network/wsPeer.go
Labels: Infrastructure

#1822 Move ledger.dbPair to db.Pair
  ledger/accountdb_test.go
  ledger/acctupdates.go
  ledger/acctupdates_test.go
  ledger/archival_test.go
  ledger/blockdb_test.go
  ledger/blockqueue.go
  ledger/catchpointwriter_test.go
  ledger/catchupaccessor.go
  ledger/ledger.go
  ledger/tracker.go
  util/db/dbpair.go
Labels: Infrastructure

#1826 Replace accountDelta by basics.AccountData in ledger
  ledger/accountdb.go
  ledger/accountdb_test.go
  ledger/acctupdates.go
  ledger/acctupdates_test.go
  ledger/applications_test.go
  ledger/cow.go
  ledger/cow_test.go
  ledger/eval.go
  ledger/eval_test.go
  ledger/txtail_test.go
Labels: Infrastructure

#1829 Improve TestAccountsCanSendMoney e2e test
  test/e2e-go/features/transactions/sendReceive_test.go
Labels: Infrastructure

#1830 Increase pending proposals queue
  agreement/gossip/network.go
Labels: Infrastructure

#1825 Restructure ledger package: ledger/ledgercore
  Makefile
  catchup/catchpointService.go
  catchup/service.go
  cmd/catchpointdump/file.go
  cmd/goal/node.go
  daemon/algod/api/server/v1/handlers/handlers.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/helpers.go
  data/ledger.go
  data/pools/transactionPool.go
  data/pools/transactionPool_test.go
  ledger/accountdb.go
  ledger/accountdb_test.go
  ledger/acctupdates.go
  ledger/acctupdates_test.go
  ledger/appcow_test.go
  ledger/applications.go
  ledger/applications_test.go
  ledger/archival_test.go
  ledger/blockdb.go
  ledger/blockqueue.go
  ledger/bulletin.go
  ledger/catchpointwriter.go
  ledger/catchupaccessor.go
  ledger/catchupaccessor_test.go
  ledger/cow.go
  ledger/cow_test.go
  ledger/eval.go
  ledger/eval_test.go
  ledger/ledger.go
  ledger/ledger_test.go
  ledger/ledgercore/catchpointlabel.go
  ledger/ledgercore/catchpointlabel_test.go
  ledger/ledgercore/error.go
  ledger/ledgercore/msgp_gen.go
  ledger/ledgercore/msgp_gen_test.go
  ledger/ledgercore/statedelta.go
  ledger/ledgercore/totals.go
  ledger/ledgercore/totals_test.go
  ledger/metrics.go
  ledger/msgp_gen.go
  ledger/msgp_gen_test.go
  ledger/notifier.go
  ledger/time.go
  ledger/tracker.go
  ledger/txtail.go
  ledger/txtail_test.go
  ledger/voters.go
  node/node.go
  node/topAccountListener.go
  rpcs/blockService.go
  rpcs/ledgerService.go
Labels: Infrastructure

#1831 Support large integers in tealdbg
  cmd/tealdbg/cdtState.go
  cmd/tealdbg/home.html
  cmd/tealdbg/homepage.go
Labels: FDE

#1832 Remove all cow.mods usages outside of cow type
  ledger/appcow.go
  ledger/appcow_test.go
  ledger/applications.go
  ledger/applications_test.go
  ledger/cow.go
Labels: Infrastructure

#1841 Fix insufficient fee error message formatting
  data/transactions/transaction.go
  data/transactions/transaction_test.go
Labels: Infrastructure

#1840 implement a transaction load generator
  cmd/loadgenerator/config.go
  cmd/loadgenerator/loadgenerator.config.example
  cmd/loadgenerator/main.go
  daemon/algod/api/client/restClient.go
Labels: Infrastructure

#1845 Fix regression to loadTelemetryConfig introduced in 2.3.0
  logging/telemetryConfig.go
  logging/telemetryConfig_test.go
  test/testdata/configs/logging/logging.config.test1
Labels: Infrastructure

#1827 Remove check_golang_version check when deploying in travis
  scripts/travis/deploy_packages.sh
Labels: Dev Ops, Unplanned

#1846 testing: fix regression in BenchmarkReadingAllBalancesRAM and BenchmarkReadingAllBalancesDisk
  ledger/accountdb_test.go
Labels: Infrastructure

#1844 diagcfg : Read from global logging config if data dir not provided
  cmd/diagcfg/telemetry.go
  logging/telemetry.go
  logging/telemetry_test.go
Labels: Dev Ops

#1849 non-utf8 app value keys for test
  test/scripts/e2e_subs/tealprogs/globcheck.teal
  test/scripts/e2e_subs/tealprogs/globwrite.teal
  test/scripts/e2e_subs/tealprogs/xappreads.teal
Labels: Infrastructure

#1848 testing: make e2e_client_runner more robust
  test/scripts/e2e_client_runner.py
Labels: Infrastructure

#1507 Top-level compact certificate support
  Makefile
  agreement/msgp_gen.go
  compactcert/builder.go
  compactcert/db.go
  compactcert/msgp_gen.go
  compactcert/msgp_gen_test.go
  compactcert/signer.go
  compactcert/worker.go
  config/config.go
  config/consensus.go
  daemon/algod/api/server/v1/handlers/handlers.go
  daemon/algod/api/spec/v1/model.go
  data/accountManager.go
  data/basics/units.go
  data/basics/units_test.go
  data/bookkeeping/block.go
  data/bookkeeping/msgp_gen.go
  ledger/acctupdates.go
  ledger/appcow_test.go
  ledger/compactcert.go
  ledger/cow.go
  ledger/cow_test.go
  ledger/eval.go
  ledger/ledger_test.go
  ledger/ledgercore/statedelta.go
  ledger/voters.go
  network/wsNetwork.go
  node/node.go
  protocol/tags.go
  test/e2e-go/features/compactcert/compactcert_test.go
  test/testdata/nettemplates/CompactCert.json
Labels: Infrastructure

#1842 Improvements/bugfixes for tealdbg
  cmd/tealdbg/cdtState.go
  cmd/tealdbg/home.html
  cmd/tealdbg/homepage.go
  cmd/tealdbg/webdbg.go
Labels: FDE

#1838 Switch from map of modified accounts to an array
  ledger/accountdb.go
  ledger/accountdb_test.go
  ledger/acctupdates.go
  ledger/acctupdates_test.go
  ledger/appcow.go
  ledger/appcow_test.go
  ledger/cow.go
  ledger/cow_test.go
  ledger/eval.go
  ledger/eval_test.go
  ledger/ledgercore/statedelta.go
  ledger/ledgercore/statedelta_test.go
  ledger/txtail_test.go
Labels: Infrastructure

#1854 Adjust timeouts in assets-app.sh/sectok-app.sh tests
  test/scripts/e2e_subs/assets-app.sh
  test/scripts/e2e_subs/sectok-app.sh
Labels: Infrastructure, Unplanned

#1857 update go.mod/sum to use msgp 46
  go.mod
  go.sum
Labels: Infrastructure

#1853 add a non-utf8 Note
  test/scripts/e2e_subs/rekey.sh
Labels: Infrastructure

#1859 Add core networking support for archivers
  catchup/fetcher.go
  catchup/ledgerFetcher.go
  network/phonebook.go
  network/phonebook_test.go
  network/ping_test.go
  network/requestLogger_test.go
  network/requestTracker_test.go
  network/wsNetwork.go
  network/wsNetwork_test.go
  rpcs/httpTxSync.go
Labels: Infrastructure

#1864 close after rekey
  test/scripts/e2e_subs/rekey.sh
Labels: Infrastructure

#1816 Eval prefetch
  ledger/appcow.go
  ledger/catchpointwriter.go
  ledger/eval.go
  ledger/eval_test.go
  ledger/ledger.go
  ledger/ledger_perf_test.go
Labels: Infrastructure

#1873 fix few minor log string formatting
  auction/tracker.go
  network/wsNetwork.go
  node/node.go
Labels: Infrastructure

#1872 Fix tealdbg Accounts array
  cmd/tealdbg/cdtState.go
Labels: FDE
