Repository algorand/go-algorand, pull requests merged in 2021-07, with the labels that each got.

#2420 catchup: fix potential nil dereferencing
  catchup/catchpointService.go
  catchup/service.go
Labels: Team Carbon-11

#2343 txsync: adjust proposed block size to network bandwidth
  data/pools/transactionPool.go
  data/pools/transactionPool_test.go
  ledger/README.md
  ledger/eval.go
  ledger/eval_test.go
  ledger/ledger_perf_test.go
  node/txnSyncConn.go
  txnsync/emulatorNode_test.go
  txnsync/incoming.go
  txnsync/interfaces.go
  txnsync/mainloop.go
Labels: Team Carbon-11

#2421 txsync: merge master into feature/txnsync branch
  .circleci/config.yml
  catchup/catchpointService.go
  catchup/service.go
  data/bookkeeping/genesis.go
  data/bookkeeping/msgp_gen.go
  data/pools/transactionPool.go
  data/transactions/logic/fields.go
  data/transactions/logic/fields_test.go
  gen/generate.go
  gen/walletData.go
  netdeploy/network.go
  node/node.go
  test/e2e-go/features/transactions/sendReceive_test.go
  test/testdata/nettemplates/DevModeNetwork.json
  util/timers/frozen.go
Labels: Team Carbon-11

#2422 testing: ensure deploy_linux_version generates a linux/amd64 binaries for algonet usage
  docker/build/Dockerfile-deploy
Labels: Team Carbon-11

#2418 Specs and unit test to avoid forgetting in the future
  data/transactions/logic/TEAL_opcodes.md
  data/transactions/logic/doc.go
  data/transactions/logic/doc_test.go
  scripts/travis/codegen_verification.sh
Labels: Team Scytale

#2238 Fix and enable TestNewAccountCanGoOnlineAndParticipate
  test/e2e-go/features/multisig/multisig_test.go
  test/e2e-go/features/participation/onlineOfflineParticipation_test.go
  test/e2e-go/features/participation/participationRewards_test.go
  test/framework/fixtures/restClientFixture.go
  test/testdata/nettemplates/OneNode.json
Labels: Team Carbon-11, Unplanned

#2448 Initialize past side effects with correct length during dryrun requests
  daemon/algod/api/server/v2/dryrun.go
  daemon/algod/api/server/v2/dryrun_test.go
Labels: Team Scytale, Unplanned

#2413 optimize txtail memory consumption
  ledger/cow.go
  ledger/ledger.go
  ledger/txtail.go
  ledger/txtail_test.go
Labels: Team Carbon-11

#2429 enable TestPartkeyOnlyRewards on macos
  test/e2e-go/features/participation/participationRewards_test.go
Labels: SkippedTests, Team Carbon-11

#2494 Fix 10 minute timeout in travis. (Revert parts of #2324)
  scripts/travis/build_test.sh
  scripts/travis/run_tests.sh
Labels: Team Carbon-11, Unplanned

#2493 txsync : merge master into feature/txnsync
  config/version.go
  daemon/algod/api/server/v2/dryrun.go
  daemon/algod/api/server/v2/dryrun_test.go
  data/transactions/logic/README.md
  data/transactions/logic/TEAL_opcodes.md
  data/transactions/logic/doc.go
  data/transactions/logic/doc_test.go
  docker/build/Dockerfile-deploy
  docker/releases/build_releases.sh
  ledger/cow.go
  ledger/ledger.go
  ledger/txtail.go
  ledger/txtail_test.go
  scripts/release/mule/deploy/docker/docker.sh
  scripts/travis/codegen_verification.sh
  test/e2e-go/features/multisig/multisig_test.go
  test/e2e-go/features/participation/onlineOfflineParticipation_test.go
  test/e2e-go/features/participation/participationRewards_test.go
  test/framework/fixtures/restClientFixture.go
  test/testdata/nettemplates/OneNode.json
Labels: Team Carbon-11

#2430 allow to parse ipv6 localhost "[::]:4601"
  network/wsNetwork.go
  network/wsNetwork_test.go
Labels: Team Carbon-11, Unplanned

#2503 testing: avoid running TestAgreementSynchronous10 on nightly build
  agreement/service_test.go
Labels: Team Carbon-11, Unplanned

#2502 testing: avoid division by zero during TestBasicCatchpointWriter
  ledger/accountdb_test.go
Labels: Team Carbon-11, Unplanned

#2358 selector pseudo-op in support of ABI
  data/transactions/logic/assembler.go
  data/transactions/logic/eval_test.go
Labels: Team Scytale

#2505 fix regex for matching charset of valid DNS hosts, add test
  network/wsNetwork.go
  network/wsNetwork_test.go
Labels: Team Carbon-11

#2509 testing: Fix random failure in TestWebsocketNetworkPrioLimit
  network/netprio.go
  network/wsNetwork_test.go
Labels: Team Carbon-11, Unplanned

#2001 Xor filter bloom alternative
  go.mod
  go.sum
  network/wsNetwork_test.go
  txnsync/bitmask.go
  txnsync/bloomFilter.go
  txnsync/bloomFilter_test.go
  txnsync/mainloop.go
  txnsync/outgoing.go
  txnsync/peer.go
  txnsync/service.go
  util/bloom/bloom.go
  util/bloom/bloom_test.go
  util/bloom/generic.go
  util/bloom/xor.go
  util/bloom/xor_test.go
Labels: Team Carbon-11

#2510 txsync: merge changes from master into feature/txnsync branch
  agreement/service_test.go
  cmd/opdoc/opdoc.go
  config/consensus.go
  data/transactions/logic/README.md
  data/transactions/logic/README_in.md
  data/transactions/logic/TEAL_opcodes.md
  data/transactions/logic/assembler.go
  data/transactions/logic/assembler_test.go
  data/transactions/logic/doc.go
  data/transactions/logic/doc_test.go
  data/transactions/logic/eval.go
  data/transactions/logic/evalStateful_test.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/fields.go
  data/transactions/logic/fields_string.go
  data/transactions/logic/opcodes.go
  ledger/accountdb_test.go
  ledger/applications.go
  ledger/applications_test.go
  network/netprio.go
  network/wsNetwork.go
  network/wsNetwork_test.go
  scripts/travis/build_test.sh
  scripts/travis/run_tests.sh
  test/scripts/e2e_subs/teal-app-params.sh
  test/scripts/e2e_subs/tealprogs/app-params.teal
Labels: Team Carbon-11

#2516 testing: make TestPeersDownloadFailed and TestHistoricData predictable
  catchup/peerSelector_test.go
Labels: Team Carbon-11

#2515 testing: improve testing of alloc bounded slices
  protocol/codec_tester.go
Labels: Team Carbon-11

#2415 Save Logging Information in Data Directory If Provided
  logging/telemetry.go
  logging/telemetryConfig.go
  logging/telemetryConfig_test.go
  test/testdata/configs/logging/logging.config.test2
Labels: Team Carbon-11

#2522 txnsync: merge changes from master into feature/txnsync branch
  catchup/peerSelector_test.go
  protocol/codec_tester.go
Labels: Team Carbon-11

#2524 txnsync: add metrics to txnsync
  txnsync/bloomFilter.go
  txnsync/incoming.go
  txnsync/metrics.go
  txnsync/outgoing.go
  txnsync/peer.go
Labels: Team Carbon-11

#2527 testing: improve msgp codec testing
  protocol/codec_tester.go
Labels: Team Carbon-11

#2535 testing: Fix random failures in TestPeriodicSync
  catchup/service_test.go
Labels: Team Carbon-11

#2539 use periodicSyncLogger for cleaner test runs
  catchup/service_test.go
Labels: Team Carbon-11

#2544 build: fix travis nightly build failure
  scripts/travis/build_test.sh
Labels: Team Carbon-11

#2537 test conditional slack alert
  .travis.yml
Labels: Team Hyper Flow

#2504 Added unit tests to profiler
  txnsync/profiler_test.go
Labels: Team Carbon-11

#2536 Added Txnsync Service Unit Tests
  node/node.go
  txnsync/emulatorCore_test.go
  txnsync/service.go
  txnsync/service_test.go
Labels: Team Carbon-11

#2547 Replace yum-cron with dnf-automatic to support centos 8
  installer/rpm/algorand/0dnf-algorand-hourly.cron
  installer/rpm/algorand/0yum-algorand-hourly.cron
  installer/rpm/algorand/algorand.spec
  installer/rpm/algorand/dnf-cron-algorand.conf
  scripts/build_packages.sh
  scripts/compute_package_name.sh
  scripts/release/mule/Makefile.mule
  scripts/release/mule/package/rpm/package.sh
  scripts/release/mule/test/test.sh
  scripts/release/test/util/test_package.sh
  test/muleCI/mule.yaml
Labels: Team Hyper Flow

#2543 txnsync: merge master into feature/txnsync #2530
  .golangci.yml
  ledger/lruaccts.go
  ledger/lruaccts_test.go
  ledger/persistedaccts_list.go
  ledger/persistedaccts_list_test.go
  ledger/txtail.go
  logging/telemetry.go
  logging/telemetryConfig.go
  logging/telemetryConfig_test.go
  node/node.go
  nodecontrol/nodeControlErrors.go
  protocol/codec_tester.go
  test/testdata/configs/logging/logging.config.test2
Labels: Team Carbon-11

#2542 bloomFilter unit tests
  txnsync/bloomFilter.go
  txnsync/bloomFilter_test.go
  txnsync/peer.go
Labels: Team Carbon-11

#2557 testing: remove deprecated transaction pool e2e tests
  test/e2e-go/features/transactions/transactionPool_test.go
  test/e2e-go/restAPI/restClient_test.go
Labels: Team Carbon-11

#2513 txnsync: use signed transaction group hash
  data/pools/transactionPool.go
  data/pools/transactionPool_test.go
  data/transactions/application.go
  data/transactions/msgp_gen.go
  data/transactions/msgp_gen_test.go
  data/transactions/transaction.go
  txnsync/bloomFilter.go
  txnsync/bloomFilter_test.go
  txnsync/emulatorCore_test.go
  txnsync/emulatorNode_test.go
  txnsync/encodedgroupstypes.go
  txnsync/msgp_gen.go
  txnsync/msgp_gen_test.go
  txnsync/peer.go
  txnsync/txngroups_test.go
Labels: Team Carbon-11

#2563 Avoid requesting unsupported blocks by the ensure digest catchup path
  catchup/service.go
Labels: Team Carbon-11

#2562 testing: lookup in no-GOPATH locations for packages in gocodec testing
  protocol/codec_tester.go
Labels: Team Carbon-11

#2555 add handling for non-utf 8 asset names
  cmd/goal/account.go
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v1/handlers/handlers.go
  daemon/algod/api/server/v2/account.go
  daemon/algod/api/server/v2/generated/private/routes.go
  daemon/algod/api/server/v2/generated/private/types.go
  daemon/algod/api/server/v2/generated/routes.go
  daemon/algod/api/server/v2/generated/types.go
  daemon/algod/api/server/v2/utils.go
  libgoal/libgoal.go
  test/e2e-go/features/transactions/asset_test.go
Labels: Team Carbon-11

#2564 txsync: merge master into txnsync feature branch
  .github/ISSUE_TEMPLATE/algorand-engineering-team-issue-template.md
  .travis.yml
  catchup/service.go
  catchup/service_test.go
  cmd/opdoc/tmLanguage.go
  data/transactions/logic/README.md
  data/transactions/logic/TEAL_opcodes.md
  data/transactions/logic/assembler_test.go
  data/transactions/logic/doc.go
  data/transactions/logic/eval.go
  data/transactions/logic/evalStateful_test.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/opcodes.go
  installer/rpm/algorand/0dnf-algorand-hourly.cron
  installer/rpm/algorand/0yum-algorand-hourly.cron
  installer/rpm/algorand/algorand.spec
  installer/rpm/algorand/dnf-cron-algorand.conf
  protocol/codec_tester.go
  scripts/build_packages.sh
  scripts/compute_package_name.sh
  scripts/release/mule/Makefile.mule
  scripts/release/mule/package/rpm/package.sh
  scripts/release/mule/test/test.sh
  scripts/release/test/util/test_package.sh
  scripts/travis/build_test.sh
  test/e2e-go/features/transactions/transactionPool_test.go
  test/e2e-go/restAPI/restClient_test.go
  test/muleCI/mule.yaml
Labels: Team Carbon-11

#2570 txnsync: fix auto-gen document
  data/transactions/logic/README.md
Labels: Team Carbon-11

#2569 Use dashes in v2 API.
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/private/routes.go
  daemon/algod/api/server/v2/generated/private/types.go
  daemon/algod/api/server/v2/generated/routes.go
  daemon/algod/api/server/v2/generated/types.go
Labels: Team Carbon-11

#2566 txnsync: update default bloom filter to use xor32
  txnsync/bloomFilter.go
  txnsync/bloomFilter_test.go
Labels: Team Carbon-11

#2565 txnsync: reduce the amount of logging
  config/config.go
  config/local_defaults.go
  installer/config.json.example
  test/testdata/configs/config-v17.json
  txnsync/incoming.go
  txnsync/logger.go
  txnsync/outgoing.go
  txnsync/service.go
  txnsync/service_test.go
  txnsync/txngroups.go
Labels: Team Carbon-11

#2571 txnsync: typos fix
  data/transactions/transaction.go
  data/txHandler.go
  network/wsNetwork.go
  network/wsPeer.go
  node/txnSyncConn.go
  txnsync/bitmask.go
  txnsync/bloomFilter.go
  txnsync/encodedgroupstypes.go
  txnsync/encodedgroupsunmarshalers.go
  txnsync/exchange.go
  txnsync/incoming.go
  txnsync/msgbuffers.go
  txnsync/peer.go
  txnsync/transactionCache.go
  txnsync/txngroups.go
  txnsync/txngroups_test.go
Labels: Team Carbon-11

#2573 Use byte format for asset b64 fields
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/account.go
  daemon/algod/api/server/v2/generated/private/routes.go
  daemon/algod/api/server/v2/generated/private/types.go
  daemon/algod/api/server/v2/generated/routes.go
  daemon/algod/api/server/v2/generated/types.go
  libgoal/libgoal.go
  test/scripts/e2e_subs/rest-assets-endpoint.sh
  test/scripts/e2e_subs/rest.sh
Labels: Team Carbon-11

#2572 txnsync: Add fields to txnsync msgs for proposal sending
  txnsync/exchange.go
  txnsync/incoming.go
  txnsync/msgp_gen.go
  txnsync/msgp_gen_test.go
Labels: Team Carbon-11

#2582 txnsync: avoid pseudonode execution goroutine hang
  agreement/asyncVoteVerifier.go
  agreement/cryptoVerifier.go
  agreement/pseudonode.go
  agreement/pseudonode_test.go
Labels: Team Carbon-11

#2603 txnsync: avoid deadlock when disconnecting from network peer
  network/wsPeer.go
  node/txnSyncConn.go
Labels: Team Carbon-11

#2601 bug: disable networking on devmode
  node/node.go
Labels: Team Carbon-11, Unplanned

#2590 txsync: incoming unit tests
  txnsync/incoming.go
  txnsync/incoming_test.go
  txnsync/msgorderingheap.go
  txnsync/service_test.go
Labels: Team Carbon-11

#2610 txnsync: avoid reallocating pending transaction ids slice
  txnsync/peer.go
  txnsync/transactionCache.go
Labels: Team Carbon-11

#2615 Remove msgp 1.1.47 from go.mod/go.sum files
  go.sum
  scripts/buildtools/go.mod
  scripts/buildtools/go.sum
Labels: Team Hyper Flow

#2613 txnsync: avoid large allocation tie-ups
  data/txHandler.go
  node/txnSyncConn.go
  txnsync/emulatorNode_test.go
  txnsync/incoming.go
  txnsync/incoming_test.go
  txnsync/interfaces.go
  txnsync/mainloop.go
Labels: Team Carbon-11

#2611 Use strict json encoder in REST API v2 endpoints
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_test.go
  daemon/algod/api/server/v2/test/helpers.go
  daemon/algod/api/server/v2/utils.go
  protocol/codec_test.go
  test/scripts/e2e_subs/serial/rest-proof-endpoint.sh
Labels: Team Scytale, Unplanned

#2600 Peer Unit Test
  txnsync/peer_test.go
Labels: Team Carbon-11

#2640 report on txn pool fullness
  test/heapwatch/metrics_delta.py
Labels: Team Carbon-11

#2541 Stack manipulation opcodes - uncover and cover
  data/transactions/logic/README.md
  data/transactions/logic/TEAL_opcodes.md
  data/transactions/logic/assembler.go
  data/transactions/logic/assembler_test.go
  data/transactions/logic/doc.go
  data/transactions/logic/eval.go
  data/transactions/logic/evalStateful_test.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/opcodes.go
Labels: Team Scytale

#2508 metrics Gauge cleanup
  util/metrics/gauge.go
  util/metrics/gaugeCommon.go
Labels: Team Carbon-11, Unplanned

#2626 Added msgorderingheap tests
  txnsync/msgorderingheap_test.go
Labels: Team Carbon-11

#2618 CircleCI: parameterizing no_output_timeout and -short
  .circleci/config.yml
Labels: Team Hyper Flow

#2650 go-algorand relstable2.8.0-remerge
  config/version.go
  scripts/release/mule/package/rpm/package.sh
Labels: Team Hyper Flow

#2662 Add a public `Eval()` function for indexer
  ledger/eval.go
Labels: Team Carbon-11

#2638 Replace `Balances.PutWithCreatable()`
  ledger/appcow.go
  ledger/appcow_test.go
  ledger/apply/application.go
  ledger/apply/application_test.go
  ledger/apply/apply.go
  ledger/apply/asset.go
  ledger/apply/keyreg_test.go
  ledger/apply/mockBalances_test.go
  ledger/assetcow.go
  ledger/cow.go
  ledger/cow_test.go
  ledger/eval.go
Labels: Team Carbon-11

#2664 txnsync: fix compression
  txnsync/txngroups.go
Labels: Team Carbon-11

#2673 txnsync: fix beta updation condition
  txnsync/mainloop.go
  txnsync/mainloop_test.go
Labels: Team Carbon-11
