Repository algorand/go-algorand, pull requests merged in 2021-05, with the labels that each got.

#2122 add support for a single node private network
  catchup/service.go
  config/config.go
  config/local_defaults.go
  installer/config.json.example
  netdeploy/network.go
  netdeploy/networkTemplate.go
  network/wsNetwork.go
  node/node.go
  test/e2e-go/cli/goal/expect/goalExpectCommon.exp
  test/e2e-go/cli/goal/expect/singleNodeNetworkTest.exp
  test/testdata/configs/config-v17.json
  test/testdata/nettemplates/SingleNodeNetwork.json
  tools/network/telemetryURIUpdateService.go
Labels: Team Carbon-11

#2129 Add ParticipationKeysRefreshInterval to the node config
  agreement/fuzzer/fuzzer_test.go
  config/config.go
  config/local_defaults.go
  data/account/participation.go
  installer/config.json.example
  libgoal/transactions.go
  netdeploy/network.go
  node/node.go
  test/testdata/configs/config-v17.json
Labels: Team Carbon-11

#2134 bugfix: netgoal errors when bootstrap files was missing
  cmd/netgoal/network.go
Labels: Team Carbon-11, Unplanned

#2135 logfilter: provide proper handling for panicing unit tests
  debug/logfilter/example8.in
  debug/logfilter/example8.out.expected
  debug/logfilter/main.go
Labels: Team Carbon-11, Unplanned

#2128 Add tests for ledger/compactcert.go
  compactcert/builder.go
  ledger/compactcert.go
  ledger/compactcert_test.go
Labels: Team Carbon-11

#2138 merge master into feature/txnsync
  agreement/abstractions.go
  agreement/agreementtest/keyManager.go
  agreement/cryptoVerifier_test.go
  agreement/fuzzer/fuzzer_test.go
  agreement/fuzzer/keyManager_test.go
  agreement/pseudonode.go
  agreement/pseudonode_test.go
  agreement/service_test.go
  catchup/service.go
  cmd/goal/clerk.go
  cmd/netgoal/network.go
  compactcert/abstractions.go
  compactcert/signer.go
  compactcert/worker_test.go
  config/config.go
  config/local_defaults.go
  data/account/account.go
  data/account/participation.go
  data/accountManager.go
  debug/logfilter/example8.in
  debug/logfilter/example8.out.expected
  debug/logfilter/main.go
  docker/build/Dockerfile
  docker/build/Dockerfile-deploy
  docker/build/cicd.alpine.Dockerfile
  docker/build/cicd.centos.Dockerfile
  docker/build/cicd.ubuntu.Dockerfile
  installer/config.json.example
  ledger/acctupdates.go
  libgoal/transactions.go
  logging/telemetryspec/metric.go
  netdeploy/network.go
  netdeploy/networkTemplate.go
  network/wsNetwork.go
  node/netprio.go
  node/node.go
  test/e2e-go/cli/goal/expect/goalExpectCommon.exp
  test/e2e-go/cli/goal/expect/singleNodeNetworkTest.exp
  test/e2e-go/features/participation/overlappingParticipationKeys_test.go
  test/testdata/configs/config-v17.json
  test/testdata/deployednettemplates/recipes/bootstrappedScenario/genesis.json
  test/testdata/deployednettemplates/recipes/bootstrappedScenario/net.json
  test/testdata/deployednettemplates/recipes/bootstrappedScenario/node.json
  test/testdata/deployednettemplates/recipes/bootstrappedScenario/relay.json
  test/testdata/deployednettemplates/recipes/scenario1/node.json
  test/testdata/deployednettemplates/recipes/scenario1/relay.json
  test/testdata/deployednettemplates/recipes/scenario2/node.json
  test/testdata/deployednettemplates/recipes/scenario2/relay.json
  test/testdata/deployednettemplates/recipes/scenario3/node.json
  test/testdata/deployednettemplates/recipes/scenario3/relay.json
  test/testdata/nettemplates/ShortParticipationKeys.json
  test/testdata/nettemplates/SingleNodeNetwork.json
  tools/network/telemetryURIUpdateService.go
Labels: Team Carbon-11

#2140 rollback config v17 into v16
  config/config.go
  config/local_defaults.go
  installer/config.json.example
  test/testdata/configs/config-v16.json
  test/testdata/configs/config-v17.json
Labels: Team Carbon-11, Unplanned

#1936 1k+ assets (part 5)
  ledger/accountdb.go
  ledger/accountdb_test.go
  ledger/acctupdates.go
  ledger/acctupdates_test.go
  ledger/appcow.go
  ledger/appcow_test.go
  ledger/appdbg.go
  ledger/apply/application.go
  ledger/apply/application_test.go
  ledger/apply/apply.go
  ledger/apply/asset.go
  ledger/apply/keyreg_test.go
  ledger/apply/mockBalances_test.go
  ledger/cow.go
  ledger/cow_test.go
  ledger/creatablecow.go
  ledger/eval.go
  ledger/ledger.go
  ledger/ledgercore/persistedacctdata.go
  ledger/ledgercore/persistedacctdata_test.go
  ledger/ledgercore/statedelta.go
  ledger/ledgercore/statedelta_test.go
Labels: Team Scytale

#2143 txsync: transaction sync profiler
  logging/telemetryspec/metric.go
  txnsync/mainloop.go
  txnsync/outgoing.go
  txnsync/profiler.go
Labels: Team Carbon-11

#2146 txsync: add synced incoming message handler
  txnsync/incoming.go
  txnsync/mainloop.go
Labels: Team Carbon-11

#2150 txnsync: improve outgoing message error handling
  node/txnSyncConn.go
  txnsync/emulatorNode_test.go
  txnsync/interfaces.go
  txnsync/outgoing.go
Labels: Team Carbon-11

#2155 txpool: Fix incorrect datatype checking in recomputeBlockEvaluator
  data/pools/transactionPool.go
Labels: Team Carbon-11

#2126 Dynamic teal
  cmd/goal/clerk.go
  config/consensus.go
  daemon/algod/api/server/v2/dryrun_test.go
  data/transactions/logic/.gitignore
  data/transactions/logic/README.md
  data/transactions/logic/README_in.md
  data/transactions/logic/TEAL_opcodes.md
  data/transactions/logic/assembler.go
  data/transactions/logic/assembler_test.go
  data/transactions/logic/backwardCompat_test.go
  data/transactions/logic/doc.go
  data/transactions/logic/doc_test.go
  data/transactions/logic/eval.go
  data/transactions/logic/evalStateful_test.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/opcodes.go
  data/transactions/verify/txn.go
  ledger/apply/application.go
  ledger/apply/application_test.go
  test/e2e-go/cli/goal/expect/tealConsensusTest.exp
  test/scripts/e2e_subs/v26/teal-v3-only.sh
  test/testdata/nettemplates/TwoNodes50EachV26.json
Labels: Team Scytale

#2156 txnsync: merge master into feature/txnsync branch
  README.md
  compactcert/builder.go
  config/config.go
  config/local_defaults.go
  data/pools/transactionPool.go
  data/transactions/signedtxn.go
  installer/config.json.example
  ledger/compactcert.go
  ledger/compactcert_test.go
  ledger/cow_test.go
  ledger/eval_test.go
  ledger/perf_test.go
  node/txnSyncConn.go
  scripts/configure_dev.sh
  scripts/install_linux_deps.sh
  test/testdata/configs/config-v16.json
  test/testdata/configs/config-v17.json
  test/testdata/deployednettemplates/recipes/bootstrappedScenario/genesis.json
Labels: Team Carbon-11

#2153 txsync: avoid reevaluating old transactions during transaction selection
  data/pools/transactionPool.go
  data/pools/transactionPool_test.go
  data/transactions/transaction.go
  network/wsPeer.go
  txnsync/emulatorNode_test.go
  txnsync/emulator_test.go
  txnsync/peer.go
  txnsync/peerscheduler.go
Labels: Team Carbon-11

#2137 add support for more strict key registration transaction verification
  config/consensus.go
  data/transactions/transaction.go
  data/transactions/transaction_test.go
  ledger/apply/keyreg.go
  ledger/apply/keyreg_test.go
  ledger/eval.go
  ledger/ledger_test.go
Labels: Team Carbon-11

#2152 Return an empty string instead of null when making a proof for transaction with no siblings.
  daemon/algod/api/server/v2/handlers.go
  test/README.md
  test/scripts/e2e.sh
  test/scripts/e2e_subs/rest-applications-endpoint.sh
  test/scripts/e2e_subs/rest-assets-endpoint.sh
  test/scripts/e2e_subs/rest-genesis-endpoint.sh
  test/scripts/e2e_subs/rest-pprof.sh
  test/scripts/e2e_subs/rest.sh
  test/scripts/e2e_subs/serial/rest-proof-endpoint.sh
Labels: Team Carbon-11

#2149 ledger: disable minimum balance check when not validating or generating
  ledger/eval.go
Labels: Team Carbon-11

#2144 Fix Update Script
  cmd/updater/systemd-setup.sh
  cmd/updater/update.sh
Labels: Team Hyper Flow

#2165 fix the systemctl conditional so it restarts with systemd
  cmd/updater/update.sh
Labels: Team Hyper Flow

#2169 bugfix: ensure stopping a node always stops kmd
  nodecontrol/NodeController.go
  test/e2e-go/cli/goal/expect/goalNodeTest.exp
Labels: Team Carbon-11

#2170 Fix go vet error for string(int) conversion in TestWebsocketNetworkCancel
  network/wsNetwork_test.go
Labels: Team Scytale

#2108 Refactor code generation verification
  .gitignore
  .travis.yml
  Makefile
  auction/README.md
  catchup/service_test.go
  daemon/algod/api/server/lib/bundle_swagger_json.sh
  daemon/algod/api/server/lib/bundledSpecInject.go
  daemon/algod/api/swagger.json
  daemon/algod/api/swagger.json.validated
  daemon/kmd/api/swagger.json
  daemon/kmd/api/swagger.json.validated
  daemon/kmd/lib/kmdapi/bundle_swagger_json.sh
  daemon/kmd/lib/kmdapi/bundledSpecInject.go
  daemon/kmd/lib/kmdapi/requests.go
  go.mod
  go.sum
  scripts/buildtools/go.mod
  scripts/buildtools/go.sum
  scripts/buildtools/install_buildtools.sh
  scripts/check_deps.sh
  scripts/configure_dev-deps.sh
  scripts/configure_dev.sh
  scripts/release/mule/Makefile.mule
  scripts/travis/after_build.sh
  scripts/travis/before_build.sh
  scripts/travis/build.sh
  scripts/travis/build_test.sh
  scripts/travis/codegen_verification.sh
  scripts/travis/integration_test.sh
  scripts/travis/test.sh
  test/e2e-go/cli/algod/expect/algodExpectCommon.exp
  test/e2e-go/cli/goal/expect/createWalletTest.exp
  test/e2e-go/cli/goal/expect/doubleSpendingTest.exp
  test/e2e-go/cli/goal/expect/goalAccountTest.exp
  test/e2e-go/cli/goal/expect/goalAppAccountAddressTest.exp
  test/e2e-go/cli/goal/expect/goalAssetTest.exp
  test/e2e-go/cli/goal/expect/goalDryrunRestTest.exp
  test/e2e-go/cli/goal/expect/ledgerTest.exp
  test/e2e-go/cli/goal/expect/listExpiredParticipationKeyTest.exp
  test/e2e-go/cli/goal/expect/multisigCreationDeletionTest.exp
  test/e2e-go/cli/goal/expect/pingpongTest.exp
  test/e2e-go/cli/goal/expect/reportTest.exp
  test/e2e-go/cli/goal/expect/statefulTealAppInfoTest.exp
  test/e2e-go/cli/goal/expect/statefulTealAppReadTest.exp
  test/e2e-go/cli/goal/expect/statefulTealCreateAppTest.exp
  test/muleCI/mule.yaml
  test/scripts/e2e.sh
Labels: Team Carbon-11

#2176 testing: improve e2e protocol upgrade tests
  test/e2e-go/upgrades/send_receive_upgrade_test.go
Labels: Team Carbon-11

#2178 tests: fix rekey upgrade test
  test/e2e-go/upgrades/rekey_support_test.go
Labels: Team Carbon-11

#2177 network: start network only after handlers registration is complete
  node/node.go
Labels: Team Carbon-11

#2187 tests: disable goal expect tests
  test/e2e-go/cli/goal/expect/goal_expect_test.go
Labels: Team Carbon-11, Unplanned

#2139 Teal4 math
  cmd/opdoc/opdoc.go
  cmd/opdoc/tmLanguage.go
  data/transactions/logic/Makefile
  data/transactions/logic/README.md
  data/transactions/logic/README_in.md
  data/transactions/logic/TEAL_opcodes.md
  data/transactions/logic/assembler_test.go
  data/transactions/logic/doc.go
  data/transactions/logic/doc_test.go
  data/transactions/logic/eval.go
  data/transactions/logic/evalStateful_test.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/opcodes.go
Labels: Team Scytale

#2188 testing: fix TestRekeyUpgrade when round=0
  test/e2e-go/upgrades/rekey_support_test.go
Labels: Team Carbon-11, Unplanned

#2185 Improve fresh node startup time
  cmd/algod/main.go
  cmd/algod/main_test.go
  ledger/accountdb.go
  ledger/accountdb_test.go
  ledger/acctupdates.go
  ledger/acctupdates_test.go
  ledger/blockdb.go
  ledger/blockdb_test.go
  ledger/ledger.go
  ledger/ledger_test.go
Labels: Team Carbon-11, Unplanned

#2175 Adding missing test for universalFetcher.go
  catchup/fetcher_test.go
  catchup/universalFetcher.go
  catchup/universalFetcher_test.go
Labels: Team Carbon-11

#2181 testing: fix data race accessing messagesOfInterest during network shutdown
  network/requestTracker.go
  network/wsNetwork.go
Labels: Team Carbon-11, Unplanned

#2195 Add mention of install_buildtools.sh to README
  README.md
Labels: Team Scytale

#1939 1k+ assets benchmarks and groups merging
  ledger/accountdb.go
  ledger/accountdb_test.go
  ledger/creatablecow.go
  ledger/ledgercore/msgp_gen.go
  ledger/ledgercore/persistedacctdata.go
  ledger/ledgercore/persistedacctdata_test.go
  ledger/ledgercore/statedelta.go
Labels: Team Scytale

#2197 sectok e2e faster
  test/scripts/e2e_subs/sectok-app.sh
Labels: Team Carbon-11

#2198 testing: e2e sub assets-app speedup
  test/scripts/e2e_subs/assets-app-b.sh
  test/scripts/e2e_subs/assets-app.sh
Labels: Team Carbon-11

#2183 Clean up `goal wallet new` output
  cmd/goal/messages.go
  cmd/goal/messages_common.go
  cmd/goal/messages_windows.go
  debug/logfilter/example3.in
  debug/logfilter/example3.out.expected
  debug/logfilter/example6.in
  debug/logfilter/example6.out.expected
  test/e2e-go/cli/goal/expect/goalExpectCommon.exp
  test/e2e-go/cli/goal/expect/goalFormattingTest.exp
Labels: Team Scytale, Unplanned

#2196 testing: fix bug in TestApplicationsUpgradeOverREST
  test/e2e-go/upgrades/application_support_test.go
Labels: Team Carbon-11

#2199 go-algorand relstable2.6.0-remerge
  config/version.go
Labels: Team Hyper Flow

#2207 debug tools: improve carpenter by adding timestamp
  debug/carpenter/main.go
Labels: Team Carbon-11

#2211 testing: ensure we test rather then log
  txnsync/txngroups_test.go
Labels: Team Carbon-11

#2206 testing: improve TestRewardUnitThreshold predicate
  test/e2e-go/features/participation/participationRewards_test.go
Labels: Team Carbon-11

#2212 Re-enable gofmt check during travis build
  catchup/fetcher_test.go
  catchup/peerSelector.go
  catchup/service_test.go
  catchup/universalFetcher.go
  catchup/universalFetcher_test.go
  data/transactions/logic/eval_test.go
  network/requestTracker.go
  scripts/travis/codegen_verification.sh
  util/process_windows.go
Labels: Team Scytale, Unplanned

#2157 "Rent" larger program size
  cmd/goal/application.go
  cmd/goal/clerk.go
  cmd/goal/interact.go
  config/consensus.go
  data/basics/msgp_gen.go
  data/basics/userBalance.go
  data/basics/userBalance_test.go
  data/transactions/application.go
  data/transactions/application_test.go
  data/transactions/logic/assembler_test.go
  data/transactions/logic/eval.go
  data/transactions/logic/evalStateful_test.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/fields.go
  data/transactions/logic/fields_string.go
  data/transactions/msgp_gen.go
  data/transactions/transaction.go
  data/transactions/transaction_test.go
  ledger/apply/application.go
  ledger/apply/application_test.go
  libgoal/transactions.go
  shared/pingpong/accounts.go
  test/e2e-go/cli/goal/expect/goalExpectCommon.exp
  test/e2e-go/cli/goal/expect/statefulTealCreateAppTest.exp
  test/e2e-go/cli/goal/expect/statefulTealCreateLargeAppTest.exp
  test/e2e-go/cli/goal/expect/tealConsensusTest.exp
  test/e2e-go/features/transactions/accountv2_test.go
  test/e2e-go/upgrades/application_support_test.go
Labels: Team Scytale

#2158 Access values from a previous app call's scratch space
  cmd/tealdbg/local.go
  cmd/tealdbg/localLedger_test.go
  cmd/tealdbg/server.go
  daemon/algod/api/server/v2/dryrun.go
  data/transactions/logic/README.md
  data/transactions/logic/TEAL_opcodes.md
  data/transactions/logic/assembler_test.go
  data/transactions/logic/doc.go
  data/transactions/logic/eval.go
  data/transactions/logic/evalStateful_test.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/opcodes.go
  ledger/eval.go
  ledger/eval_test.go
  test/scripts/e2e_subs/access-previous-scratch.sh
  test/scripts/e2e_subs/tealprogs/approve-all.teal
  test/scripts/e2e_subs/tealprogs/scratch-rw.teal
Labels: Team Scytale

#2217 txnsync: fix few non-fetching clients bugs
  network/wsNetwork.go
  txnsync/mainloop.go
  txnsync/peer.go
Labels: Team Carbon-11

#2203 testing: fix random TestAccountInformationV2 test failures
  test/e2e-go/features/transactions/accountv2_test.go
Labels: Team Carbon-11

#2079 Fix proposal propagation
  agreement/player.go
  agreement/player_permutation_test.go
  agreement/player_test.go
  agreement/state_machine_test.go
Labels: Team Carbon-11

#2218 Bugfix/cicdnightly
  scripts/deploy_private_version.sh
Labels: Team Hyper Flow
