Repository algorand/go-algorand, pull requests merged in 2021-11, with the labels that each got.

#3130 Removed Register handler
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/private/routes.go
  daemon/algod/api/server/v2/generated/private/types.go
  daemon/algod/api/server/v2/generated/routes.go
  daemon/algod/api/server/v2/handlers.go
Labels: Team Carbon-11

#3182 Partkey Interface: Rename CompactCertificate to StateProof.
  daemon/algod/api/server/v2/handlers.go
  data/account/participationRegistry.go
  data/account/participationRegistry_test.go
Labels: Team Carbon-11

#3173 `roundCowBase`: use `lookup()` instead of going to ledger directly
  ledger/internal/eval.go
Labels: Team Carbon-11

#3085 ledger: create catchpoint tracker
  data/pools/transactionPool.go
  ledger/acctupdates.go
  ledger/acctupdates_test.go
  ledger/applications_test.go
  ledger/archival_test.go
  ledger/bulletin.go
  ledger/catchpointtracker.go
  ledger/catchpointtracker_test.go
  ledger/evalbench_test.go
  ledger/ledger.go
  ledger/ledger_test.go
  ledger/metrics.go
  ledger/notifier.go
  ledger/tracker.go
  ledger/txtail.go
  ledger/voters.go
  test/e2e-go/cli/goal/expect/catchpointCatchupTest.exp
  test/e2e-go/cli/goal/expect/goalExpectCommon.exp
Labels: Team Carbon-11

#3195 ledger refactoring: Initial support for EnableAccountDataResourceSeparation
  config/consensus.go
  ledger/acctupdates.go
  ledger/bulletin.go
  ledger/catchpointtracker.go
  ledger/metrics.go
  ledger/notifier.go
  ledger/tracker.go
  ledger/txtail.go
  test/testdata/consensus/catchpointtestingprotocol.json
Labels: Team Carbon-11

#3191 PKI PR Feedback.
  agreement/abstractions.go
  agreement/agreementtest/keyManager.go
  agreement/keyManager_test.go
  agreement/pseudonode.go
  agreement/pseudonode_test.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/helpers.go
  data/account/participationRegistry.go
  data/account/participationRegistry_test.go
  data/accountManager.go
  node/node.go
  node/node_test.go
  test/scripts/e2e_subs/rest-participation-key.sh
Labels: Team Carbon-11

#3207 Add compatibility mode for listpartkeys goal command.
  cmd/goal/account.go
Labels: unplanned, Team Carbon-11

#3214 ledger refactoring: fix catchpoint tracker
  ledger/catchpointtracker.go
  ledger/catchpointtracker_test.go
Labels: Team Carbon-11

#2741 agreement: handle pseudonode enqueueing failures
  agreement/asyncVoteVerifier.go
  agreement/asyncVoteVerifier_test.go
  agreement/cryptoVerifier.go
  agreement/cryptoVerifier_test.go
  agreement/pseudonode.go
  agreement/pseudonode_test.go
Labels: Team Carbon-11

#3200 ledger refactoring: perform database schema migration
  ledger/accountdb.go
  ledger/acctupdates_test.go
  ledger/catchpointtracker.go
  ledger/catchpointtracker_test.go
  ledger/catchpointwriter_test.go
  ledger/msgp_gen.go
  ledger/msgp_gen_test.go
  ledger/trackerdb.go
  scripts/dump_genesis.sh
Labels: Team Carbon-11

#3204 goal abi method outfile checking
  cmd/goal/application.go
Labels: unplanned, Team Scytale

#2948 Adding clean target to ci-build target
  scripts/release/mule/Makefile.mule
Labels: Team Hyper Flow

#3228 Fix OnCompletion flag for `goal app method`
  cmd/goal/application.go
  test/scripts/e2e_subs/e2e-app-abi-add.sh
  test/scripts/e2e_subs/tealprogs/app-abi-add-example.teal
Labels: unplanned, Team Scytale

#3235 Revert "Reverse the network protocols ordering to de-prioritize the t…
  network/wsNetwork.go
Labels: Team Carbon-11

#3241 ledger refactoring: refactor NormalizedOnlineBalance
  data/basics/userBalance.go
Labels: Team Carbon-11

#3238 testing: fixes to rest-participation-key e2e test
  test/scripts/e2e_subs/rest-participation-key.sh
Labels: Team Sphinx

#3227 interactive mode for e2e testing
  test/README.md
  test/scripts/e2e.sh
Labels: Team Carbon-11

#3252 Make dev-mode tests less flaky.
  test/e2e-go/features/devmode/devmode_test.go
  test/e2e-go/features/participation/accountParticipationTransitions_test.go
Labels: unplanned, Team Carbon-11

#3258 Fix error shadowing in Eval
  ledger/internal/eval.go
Labels: Team Carbon-11

#3256 Disable flaky test.
  test/e2e-go/features/participation/accountParticipationTransitions_test.go
Labels: unplanned, Team Carbon-11
