Repository algorand/go-algorand, pull requests merged in 2021-06, with the labels that each got.

#2219 txnsync: add message acknowledge
  data/txHandler.go
  data/txHandler_test.go
  node/txnSyncConn.go
  txnsync/emulatorNode_test.go
  txnsync/exchange.go
  txnsync/incoming.go
  txnsync/interfaces.go
  txnsync/msgp_gen.go
  txnsync/outgoing.go
  txnsync/peer.go
  txnsync/transactionCache.go
  txnsync/transactionCache_test.go
Labels: Team Carbon-11

#2226 txnsync: recalibrate the MsgDigestSkip threshold
  network/wsNetwork.go
  network/wsNetwork_test.go
  network/wsPeer.go
Labels: Team Carbon-11

#2220 Fixing a bug in eval and TestOnSwitchToUnSupportedProtocol
  catchup/service_test.go
  ledger/eval.go
Labels: Team Carbon-11

#2159 bandwidth stats for cluster tests
  cmd/netgoal/generate.go
  test/heapwatch/heapWatch.py
  test/heapwatch/metrics_delta.py
  test/testdata/deployednettemplates/recipes/scenario1/net.json
  test/testdata/deployednettemplates/recipes/scenario1/node.json
Labels: Team Carbon-11

#2236 Check setbyte length properly.
  data/transactions/logic/eval.go
  data/transactions/logic/eval_test.go
Labels: Team Scytale

#2232 Use minimal travis container since we install go ourselves.
  .travis.yml
  scripts/travis/codegen_verification.sh
Labels: Team Carbon-11

#2237 Modify build_release to match build_pr and remove ARM Deploy.
  .travis.yml
Labels: Team Hyper Flow, Unplanned

#2241 fix docker builds: skip the `make deps`
  docker/build/Dockerfile
  docker/build/Dockerfile-deploy
Labels: Team Carbon-11

#2161 Use gotestsum instead of logfilter for test formatting.
  Makefile
  scripts/buildtools/go.mod
  scripts/buildtools/go.sum
  scripts/buildtools/install_buildtools.sh
  scripts/configure_dev-deps.sh
  scripts/travis/build.sh
  scripts/travis/integration_test.sh
  scripts/travis/run_tests.sh
  scripts/travis/test.sh
  test/scripts/e2e.sh
  test/scripts/e2e_go_tests.sh
Labels: Team Carbon-11

#2229 Use gzip to compress txnsync msgs
  txnsync/exchange.go
  txnsync/incoming.go
  txnsync/msgp_gen.go
  txnsync/outgoing.go
  txnsync/txngroups.go
  txnsync/txngroups_test.go
Labels: Team Carbon-11

#2244 txnsync: refresh message update rate
  txnsync/mainloop.go
Labels: Team Carbon-11

#2248 catchup: speedup initial node DNS bootstrap time
  catchup/service.go
Labels: Team Carbon-11, Unplanned

#2225 Combine Clear and Approval Program size limits
  config/consensus.go
  data/transactions/logic/README_in.md
  data/transactions/transaction.go
  data/transactions/transaction_test.go
  test/scripts/e2e_client_runner.py
Labels: Team Scytale

#2247 Remove ci-deps and update GOPROXY in Dockerfiles
  docker/build/Dockerfile
  docker/build/Dockerfile-deploy
  docker/build/cicd.alpine.Dockerfile
  docker/build/cicd.centos.Dockerfile
  docker/build/cicd.ubuntu.Dockerfile
  scripts/release/mule/Makefile.mule
Labels: Team Hyper Flow, Unplanned

#2228 codecov integration
  .gitignore
  .travis.yml
  Makefile
  scripts/travis/codecov
  scripts/travis/upload_coverage.sh
Labels: Team Carbon-11

#2254 Disable compact certs and auction tests
  test/e2e-go/features/auction/auctionCancel_test.go
  test/e2e-go/features/auction/auctionErrors_test.go
  test/e2e-go/features/auction/basicAuction_test.go
  test/e2e-go/features/compactcert/compactcert_test.go
Labels: Team Hyper Flow, Unplanned

#2252 If the branch is rel/nightly set channel to nightly
  scripts/release/mule/common/get_channel.sh
Labels: Team Hyper Flow, Unplanned, bug

#2215 Optimize constant assembly
  data/transactions/logic/assembler.go
  data/transactions/logic/assembler_test.go
  data/transactions/logic/evalStateful_test.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/opcodes.go
Labels: Team Scytale

#2253 Use cgo deflate compression for txnsync msgs
  txnsync/exchange.go
  txnsync/incoming.go
  txnsync/msgp_gen.go
  txnsync/outgoing.go
  txnsync/txngroups.go
  txnsync/txngroups_test.go
Labels: Team Carbon-11

#2260 txnsync: fix building on windows
  util/compress/deflate.go
Labels: Team Carbon-11, Unplanned, bug

#2235 Catchupaccessor coverage
  ledger/blockdb.go
  ledger/catchupaccessor.go
  ledger/catchupaccessor_test.go
Labels: Team Carbon-11

#2243 Expose creatable IDs to TEAL code within the same group
  data/transactions/logic/README.md
  data/transactions/logic/TEAL_opcodes.md
  data/transactions/logic/assembler_test.go
  data/transactions/logic/doc.go
  data/transactions/logic/eval.go
  data/transactions/logic/evalStateful_test.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/fields.go
  data/transactions/logic/fields_string.go
  data/transactions/logic/opcodes.go
  ledger/applications.go
  ledger/applications_test.go
  ledger/cow.go
  ledger/eval.go
  test/scripts/e2e_subs/teal-creatable-id.sh
  test/scripts/e2e_subs/tealprogs/check_creatable_id.teal
Labels: Team Scytale

#2180 1k assets: consensus parameter and feature switch
  cmd/goal/messages_windows.go
  config/consensus.go
  daemon/algod/api/server/v1/handlers/handlers.go
  daemon/algod/api/server/v2/handlers.go
  ledger/accountdb.go
  ledger/accountdb_test.go
  ledger/acctupdates.go
  ledger/acctupdates_test.go
  ledger/appcow_test.go
  ledger/appdbg.go
  ledger/apply/application_test.go
  ledger/apply/apply.go
  ledger/apply/asset.go
  ledger/apply/keyreg_test.go
  ledger/apply/mockBalances_test.go
  ledger/cow.go
  ledger/cow_test.go
  ledger/creatablecow.go
  ledger/eval.go
  ledger/ledger.go
  ledger/ledgercore/msgp_gen.go
  ledger/ledgercore/msgp_gen_test.go
  ledger/ledgercore/persistedacctdata.go
  ledger/ledgercore/persistedacctdata_test.go
  ledger/ledgercore/statedelta.go
  ledger/ledgercore/statedelta_test.go
  test/e2e-go/features/transactions/asset_test.go
  test/testdata/nettemplates/TwoNodes50EachV27.json
Labels: Team Carbon-11, Team Scytale

#2263 Allow AVM code to access a max number of foreign refs.
  config/consensus.go
  data/transactions/transaction.go
  data/transactions/transaction_test.go
Labels: Team Scytale

#2261 deprecate auction code
  Makefile
  README.md
  auction/OPERATIONS.md
  auction/README.md
  auction/client/auctionBankRestClient.go
  auction/client/auctionConsoleRestClient.go
  auction/logic.go
  auction/logic_test.go
  auction/messages.go
  auction/msgp_gen.go
  auction/msgp_gen_test.go
  auction/serializedLogic.go
  auction/sigcheck.go
  auction/tracker.go
  auction/tracker_test.go
  cmd/auctionbank/main.go
  cmd/auctionbank/txhandle.go
  cmd/auctionconsole/main.go
  cmd/auctionmaster/main.go
  cmd/auctionmaster/util.go
  cmd/auctionminion/main.go
  scripts/build_package.sh
  test/e2e-go/features/auction/auctionCancel_test.go
  test/e2e-go/features/auction/auctionErrors_test.go
  test/e2e-go/features/auction/basicAuction_test.go
  test/framework/fixtures/auctionFixture.go
  test/scripts/auctionCancel.sh
  test/scripts/auctionEnd.sh
  test/scripts/auctionStart.sh
  test/testdata/auctions/AuctionParams_1.json
  test/testdata/auctions/TenBlocksTenPriceSteps.json
Labels: Team Carbon-11, Unplanned

#2266 Temporarily disabled TestBasicCatchpointCatchup test
  test/e2e-go/features/catchup/catchpointCatchup_test.go
Labels: Team Hyper Flow, Unplanned

#2275 Fix incorrect `gaid` and `gaids` docs
  data/transactions/logic/README.md
  data/transactions/logic/TEAL_opcodes.md
  data/transactions/logic/doc.go
Labels: Team Scytale

#2264 Regularize access to "foreign" references.
  data/transactions/application.go
  data/transactions/logic/README.md
  data/transactions/logic/README_in.md
  data/transactions/logic/TEAL_opcodes.md
  data/transactions/logic/assembler_test.go
  data/transactions/logic/doc.go
  data/transactions/logic/eval.go
  data/transactions/logic/evalStateful_test.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/opcodes.go
  ledger/appcow_test.go
  ledger/apply/application_test.go
  test/scripts/e2e_subs/e2e-app-x-app-reads.sh
Labels: Team Scytale

#2274 txnsync: add support for transaction pool saturation
  node/node.go
  node/txnSyncConn.go
  txnsync/emulatorCore_test.go
  txnsync/incoming.go
  txnsync/mainloop.go
  txnsync/peer.go
  txnsync/service.go
Labels: Team Carbon-11

#2280 testing: fix random failure in TestConsensusVersion
  data/ledger_test.go
Labels: Team Carbon-11

#2276 Make account endpoint produce deterministic JSON
  daemon/algod/api/server/v2/account.go
  daemon/algod/api/server/v2/account_test.go
Labels: Team Scytale, Unplanned

#2287 report substring missing immediates properly
  data/transactions/logic/assembler.go
  data/transactions/logic/eval_test.go
Labels: Team Scytale, Unplanned

#2279 txnsync: optimize message encoding & decoding queue
  logging/telemetryspec/metric.go
  node/node.go
  txnsync/bloomFilter.go
  txnsync/bloomFilter_test.go
  txnsync/emulatorCore_test.go
  txnsync/emulatorNode_test.go
  txnsync/emulator_test.go
  txnsync/incoming.go
  txnsync/mainloop.go
  txnsync/msgbuffers.go
  txnsync/msgorderingheap.go
  txnsync/outgoing.go
  txnsync/peer.go
  txnsync/profiler.go
  txnsync/service.go
  txnsync/txngroups.go
Labels: Team Carbon-11

#2255 Introduce V28 consensus version
  config/consensus.go
  data/transactions/transaction_test.go
  ledger/apply/keyreg_test.go
  ledger/apply/payment_test.go
  node/node.go
  protocol/consensus.go
  test/e2e-go/features/participation/overlappingParticipationKeys_test.go
  test/testdata/nettemplates/ShortParticipationKeys.json
Labels: Team Scytale

#2295 Allow fee to be below minfee, if given explicitly.
  cmd/goal/application.go
  cmd/goal/asset.go
  cmd/goal/interact.go
Labels: Team Scytale, Unplanned

#2294 Expose extra program pages to API
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/account.go
  daemon/algod/api/server/v2/account_test.go
  daemon/algod/api/server/v2/generated/private/routes.go
  daemon/algod/api/server/v2/generated/private/types.go
  daemon/algod/api/server/v2/generated/routes.go
  daemon/algod/api/server/v2/generated/types.go
  daemon/algod/api/server/v2/test/helpers.go
Labels: Team Scytale, Unplanned

#2302 testing: fix random failure in TestAppEmptyAccountsLocal
  ledger/applications_test.go
  ledger/ledger_test.go
Labels: Team Carbon-11

#2284 Add ledger coverage for onlineacct roundlru txtail
  ledger/onlineacct.go
  ledger/onlineacct_test.go
  ledger/roundlru.go
  ledger/roundlru_test.go
  ledger/txtail_test.go
Labels: Team Carbon-11

#2290 Fix darwin-arm64 builds
  crypto/curve25519.go
  installer/external/node_exporter-stable-darwin-arm64.tar.gz
  scripts/archtype.sh
Labels: Team Carbon-11

#2265 testing: add unit tests for ledger BlockQueue
  ledger/blockqueue_test.go
Labels: Team Carbon-11

#2291 testing: enable unit tests on travis mac build
  scripts/travis/after_build.sh
  scripts/travis/run_tests.sh
Labels: Team Carbon-11, Unplanned

#2306 testing: move extra page test to e2e_subs
  test/e2e-go/cli/goal/expect/statefulTealCreateLargeAppTest.exp
  test/scripts/e2e_subs/e2e-app-extra-pages.sh
Labels: Team Scytale, Unplanned

#2300 txnsync: optimize selectPendingTransactions loop
  txnsync/bloomFilter.go
  txnsync/msgp_gen.go
  txnsync/peer.go
Labels: Team Carbon-11

#2285 Fixes to peer selector and TestBasicCatchpointCatchup
  catchup/catchpointService.go
  catchup/peerSelector.go
  catchup/peerSelector_test.go
  catchup/service.go
  test/e2e-go/features/catchup/catchpointCatchup_test.go
Labels: Team Carbon-11

#2308 Specify truncated division is used in TEAL
  data/transactions/logic/README.md
  data/transactions/logic/TEAL_opcodes.md
  data/transactions/logic/doc.go
Labels: Team Scytale

#2313 REST API: make extra-program-pages and apps-total-extra-pages optional
  daemon/algod/api/server/v2/account.go
  daemon/algod/api/server/v2/account_test.go
  daemon/algod/api/server/v2/test/helpers.go
Labels: Team Scytale

#2267 txnsync: fix compression warning msgs
  txnsync/exchange.go
  txnsync/txngroups.go
  txnsync/txngroups_test.go
Labels: Team Carbon-11

#2314 go-algorand 2.7.1-beta
  buildnumber.dat
  daemon/algod/api/server/v2/account.go
  daemon/algod/api/server/v2/account_test.go
  daemon/algod/api/server/v2/test/helpers.go
Labels: Team Hyper Flow, Unplanned

#2319 network: reduce unneeded contention around checking the peers connectivity
  network/wsNetwork.go
Labels: Team Carbon-11

#2322 Improve TestMetricSegment test reliability
  util/metrics/segment_test.go
Labels: Team Carbon-11

#2317 txnsync: merge master into feature/txnsync
  README.md
  agreement/player_permutation_test.go
  catchup/catchpointService.go
  catchup/peerSelector.go
  catchup/peerSelector_test.go
  catchup/service.go
  cmd/goal/application.go
  cmd/goal/asset.go
  cmd/goal/interact.go
  config/consensus.go
  crypto/curve25519.go
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/account.go
  daemon/algod/api/server/v2/account_test.go
  daemon/algod/api/server/v2/generated/private/routes.go
  daemon/algod/api/server/v2/generated/private/types.go
  daemon/algod/api/server/v2/generated/routes.go
  daemon/algod/api/server/v2/generated/types.go
  data/transactions/logic/README.md
  data/transactions/logic/README_in.md
  data/transactions/logic/TEAL_opcodes.md
  data/transactions/logic/assembler.go
  data/transactions/logic/doc.go
  data/transactions/logic/eval_test.go
  data/transactions/transaction_test.go
  installer/external/node_exporter-stable-darwin-arm64.tar.gz
  ledger/applications_test.go
  ledger/apply/keyreg_test.go
  ledger/apply/payment_test.go
  ledger/blockqueue_test.go
  ledger/ledger_test.go
  ledger/lruaccts_test.go
  ledger/onlineacct.go
  ledger/onlineacct_test.go
  ledger/roundlru.go
  ledger/roundlru_test.go
  ledger/txtail_test.go
  node/node.go
  protocol/consensus.go
  scripts/archtype.sh
  scripts/travis/after_build.sh
  scripts/travis/run_tests.sh
  test/e2e-go/cli/goal/expect/statefulTealCreateLargeAppTest.exp
  test/e2e-go/features/catchup/catchpointCatchup_test.go
  test/e2e-go/features/participation/overlappingParticipationKeys_test.go
  test/scripts/e2e_subs/e2e-app-extra-pages.sh
  test/testdata/nettemplates/ShortParticipationKeys.json
Labels: Team Carbon-11

#2326 testing: enable previously disabled TestConfigMigrate unit test
  config/config_test.go
  test/testdata/nettemplates/TwoNodesOneOnline.json
Labels: SkippedTests, Team Carbon-11

#2328 testing: fix gotestsum install
  scripts/buildtools/install_buildtools.sh
  scripts/travis/test.sh
Labels: Team Carbon-11, Unplanned

#2324 testing: move travis_retry to skip rebuilding
  .travis.yml
  scripts/travis/build_test.sh
  scripts/travis/run_tests.sh
  scripts/travis/travis_retry.sh
  scripts/travis/travis_wait.sh
Labels: Team Carbon-11

#2321 testing: fix telemetry unit tests
  logging/telemetryhook.go
  logging/telemetryhook_test.go
Labels: Team Carbon-11

#2331 Add Fedora support into install_linux_deps.sh
  scripts/install_linux_deps.sh
Labels: Team Scytale, external contribution

#2336 Add missing txna allowed args to doc and langspec
  data/transactions/logic/fields.go
  data/transactions/logic/fields_test.go
Labels: Team Scytale, Unplanned

#2334 Add initial devMode support
  data/bookkeeping/genesis.go
  data/bookkeeping/msgp_gen.go
  data/pools/transactionPool.go
  gen/generate.go
  gen/walletData.go
  netdeploy/network.go
  node/node.go
  test/e2e-go/features/transactions/sendReceive_test.go
  test/testdata/nettemplates/DevModeNetwork.json
  util/timers/frozen.go
Labels: Team Carbon-11
