Repository algorand/go-algorand, pull requests merged in 2021-09, with the labels that each got.

#2823 expose nonparticipation txn field in teal
  data/transactions/logic/README.md
  data/transactions/logic/TEAL_opcodes.md
  data/transactions/logic/assembler_test.go
  data/transactions/logic/doc.go
  data/transactions/logic/eval.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/fields.go
  data/transactions/logic/fields_string.go
Labels: Team Scytale

#2750 Increase max app opt ins to 50
  config/consensus.go
  data/basics/userBalance.go
  ledger/accountdb_test.go
  ledger/apply/application_test.go
  ledger/eval_test.go
  ledger/perf_test.go
Labels: Team Scytale

#2833 Add pooldata package
  Makefile
  data/basics/msgp_gen.go
  data/pooldata/msgp_gen.go
  data/pooldata/msgp_gen_test.go
  data/pooldata/signedTxGroup.go
  data/pools/transactionPool.go
  data/pools/transactionPool_test.go
  data/transactions/msgp_gen.go
  data/transactions/msgp_gen_test.go
  data/transactions/transaction.go
  data/transactions/verify/verifiedTxnCache.go
  data/txHandler.go
  data/txHandler_test.go
  node/assemble_test.go
  node/node.go
  node/txnSyncConn.go
  rpcs/txSyncer.go
  rpcs/txSyncer_test.go
  txnsync/bloomFilter.go
  txnsync/bloomFilter_test.go
  txnsync/emulatorCore_test.go
  txnsync/emulatorNode_test.go
  txnsync/encodedgroups_test.go
  txnsync/encodedgroupstypes.go
  txnsync/encodedgroupsunmarshalers.go
  txnsync/incoming.go
  txnsync/incoming_test.go
  txnsync/interfaces.go
  txnsync/msgorderingheap_test.go
  txnsync/msgp_gen.go
  txnsync/outgoing.go
  txnsync/outgoing_test.go
  txnsync/peer.go
  txnsync/peer_test.go
  txnsync/service_test.go
  txnsync/txngroups.go
  txnsync/txngroups_test.go
Labels: Team Carbon-11

#2820 Fix partition recovery tests
  test/e2e-go/features/partitionRecovery/partitionRecovery_test.go
Labels: Team Carbon-11

#2834 txnsync: bloom filter refactoring
  txnsync/bloomFilter.go
  txnsync/bloomFilter_test.go
  txnsync/exchange.go
  txnsync/incoming.go
  txnsync/incoming_test.go
  txnsync/msgorderingheap_test.go
  txnsync/msgp_gen.go
  txnsync/outgoing.go
  txnsync/peer.go
  txnsync/peer_test.go
  txnsync/txngroups_test.go
Labels: Team Carbon-11

#2836 Display app address in `goal app info` & show logs are binary in REST API
  cmd/goal/application.go
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/dryrun.go
  daemon/algod/api/server/v2/dryrun_test.go
  daemon/algod/api/server/v2/generated/private/routes.go
  daemon/algod/api/server/v2/generated/private/types.go
  daemon/algod/api/server/v2/generated/routes.go
  daemon/algod/api/server/v2/generated/types.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_test.go
  daemon/algod/api/server/v2/utils.go
  test/e2e-go/restAPI/restClient_test.go
Labels: Unplanned, Team Scytale

#2851 txnsync: Add linked list based short term lru cache
  txnsync/transactionCache.go
  txnsync/transactionCache_test.go
Labels: Team Carbon-11

#2749 Checking CircleCI tests run once and only once
  .circleci/config.yml
  agreement/agreementtest/simulate_test.go
  agreement/fuzzer/tests_test.go
  cmd/algofix/deadlock_test.go
  cmd/algofix/main_test.go
  cmd/algoh/blockWatcher_test.go
  cmd/algoh/blockstats_test.go
  cmd/catchupsrv/download_test.go
  cmd/goal/commands_test.go
  cmd/goal/formatting_test.go
  cmd/goal/inspect_test.go
  cmd/tealdbg/cdtSession_test.go
  cmd/tealdbg/cdtdbg_test.go
  cmd/tealdbg/debugger_test.go
  cmd/tealdbg/localLedger_test.go
  cmd/tealdbg/local_test.go
  cmd/tealdbg/remote_test.go
  cmd/tealdbg/server_test.go
  cmd/tealdbg/util_test.go
  cmd/tealdbg/webdbg_test.go
  cmd/updater/version_test.go
  crypto/curve25519_test.go
  crypto/encoding_test.go
  crypto/onetimesig_test.go
  crypto/util_test.go
  crypto/vrf_test.go
  daemon/algod/api/server/lib/middlewares/auth_test.go
  daemon/algod/api/server/router_test.go
  daemon/algod/api/server/v1/handlers/handlers_test.go
  daemon/algod/api/server/v2/account_test.go
  daemon/algod/api/server/v2/dryrun_test.go
  daemon/algod/api/server/v2/test/handlers_test.go
  data/committee/sortition/sortition_test.go
  data/transactions/logic/assembler_test.go
  data/transactions/logic/doc_test.go
  data/transactions/logic/evalStateful_test.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/fields_test.go
  data/transactions/logic/opcodes_test.go
  debug/logfilter/main_test.go
  gen/generate_test.go
  ledger/persistedaccts_list_test.go
  ledger/txtail_test.go
  libgoal/libgoal_test.go
  logging/cyclicWriter_test.go
  logging/logBuffer_test.go
  logging/log_test.go
  logging/telemetryConfig_test.go
  logging/telemetry_test.go
  logging/telemetryhook_test.go
  logging/telemetryspec/metric_test.go
  network/wsNetwork_test.go
  scripts/buildtools/check_tests.py
  test/e2e-go/cli/algod/expect/algod_expect_test.go
  test/e2e-go/cli/algoh/expect/algoh_expect_test.go
  test/e2e-go/cli/goal/expect/goal_expect_test.go
  test/e2e-go/cli/tealdbg/expect/tealdbg_expect_test.go
  test/scripts/e2e_go_tests.sh
  util/condvar/timedwait_test.go
Labels: Team Hyper Flow

#2853 loads and stores opcodes that take scratch slot from stack
  cmd/goal/clerk.go
  cmd/tealdbg/local.go
  cmd/tealdbg/local_test.go
  daemon/algod/api/server/v2/dryrun.go
  data/transactions/logic/README.md
  data/transactions/logic/TEAL_opcodes.md
  data/transactions/logic/assembler.go
  data/transactions/logic/assembler_test.go
  data/transactions/logic/debugger.go
  data/transactions/logic/doc.go
  data/transactions/logic/eval.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/opcodes.go
  data/transactions/verify/txn.go
  ledger/eval.go
  ledger/eval_test.go
Labels: Team Scytale

#2865 txnsync: merge from master
  cmd/goal/clerk.go
  cmd/tealdbg/local.go
  cmd/tealdbg/local_test.go
  daemon/algod/api/server/v2/dryrun.go
  data/transactions/logic/README.md
  data/transactions/logic/TEAL_opcodes.md
  data/transactions/logic/assembler.go
  data/transactions/logic/assembler_test.go
  data/transactions/logic/debugger.go
  data/transactions/logic/doc.go
  data/transactions/logic/eval.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/opcodes.go
  data/transactions/verify/txn.go
  ledger/eval.go
  ledger/eval_test.go
  test/scripts/e2e_go_tests.sh
Labels: Team Carbon-11

#2844 Data race in tests: TestApplicationsUpgradeOverREST race
  test/e2e-go/cli/algod/cleanup_test.go
  test/e2e-go/cli/algod/expect/algod_expect_test.go
  test/e2e-go/cli/algod/stdstreams_test.go
  test/e2e-go/cli/algoh/expect/algoh_expect_test.go
  test/e2e-go/cli/goal/account_test.go
  test/e2e-go/cli/goal/clerk_test.go
  test/e2e-go/cli/goal/expect/goal_expect_test.go
  test/e2e-go/cli/goal/node_cleanup_test.go
  test/e2e-go/cli/tealdbg/expect/tealdbg_expect_test.go
  test/e2e-go/features/catchup/basicCatchup_test.go
  test/e2e-go/features/catchup/catchpointCatchup_test.go
  test/e2e-go/features/compactcert/compactcert_test.go
  test/e2e-go/features/multisig/multisig_test.go
  test/e2e-go/features/participation/onlineOfflineParticipation_test.go
  test/e2e-go/features/participation/overlappingParticipationKeys_test.go
  test/e2e-go/features/participation/participationRewards_test.go
  test/e2e-go/features/partitionRecovery/partitionRecovery_test.go
  test/e2e-go/features/teal/compile_test.go
  test/e2e-go/features/transactions/accountv2_test.go
  test/e2e-go/features/transactions/app_pages_test.go
  test/e2e-go/features/transactions/application_test.go
  test/e2e-go/features/transactions/asset_test.go
  test/e2e-go/features/transactions/close_account_test.go
  test/e2e-go/features/transactions/group_test.go
  test/e2e-go/features/transactions/lease_test.go
  test/e2e-go/features/transactions/onlineStatusChange_test.go
  test/e2e-go/features/transactions/proof_test.go
  test/e2e-go/features/transactions/sendReceive_test.go
  test/e2e-go/kmd/e2e_kmd_server_client_test.go
  test/e2e-go/kmd/e2e_kmd_sqlite_test.go
  test/e2e-go/kmd/e2e_kmd_wallet_keyops_test.go
  test/e2e-go/kmd/e2e_kmd_wallet_multisig_test.go
  test/e2e-go/kmd/e2e_kmd_wallet_test.go
  test/e2e-go/restAPI/restClient_test.go
  test/e2e-go/stress/transactions/createManyAndGoOnline_test.go
  test/e2e-go/upgrades/application_support_test.go
  test/e2e-go/upgrades/rekey_support_test.go
  test/e2e-go/upgrades/send_receive_upgrade_test.go
  test/framework/fixtures/fixture.go
Labels: Team Carbon-11

#2873 txnsync: improve emulator setup
  txnsync/emulatorCore_test.go
Labels: Team Carbon-11

#2808 Register keys with ParticipationRegistry.
  data/account/participationRegistry.go
  data/account/participationRegistry_test.go
  logging/testingLogger.go
  node/node.go
  node/node_test.go
Labels: Team Carbon-11

#2869 txnsync: remove known txid from bloom filter
  txnsync/bloomFilter.go
  txnsync/bloomFilter_test.go
  txnsync/outgoing.go
  txnsync/outgoing_test.go
  txnsync/peer.go
  txnsync/peer_test.go
Labels: Team Carbon-11

#2872 Add ledger.GetBlockAddresses()
  ledger/eval.go
Labels: Team Carbon-11

#2880 testing: fix auto-gen tests
  data/basics/msgp_gen_test.go
  data/transactions/msgp_gen_test.go
Labels: Team Carbon-11

#2883 Introduce itxn to get inner transaction results
  cmd/opdoc/opdoc.go
  config/consensus.go
  daemon/algod/api/server/v1/handlers/handlers.go
  daemon/algod/api/server/v2/utils.go
  data/pools/transactionPool.go
  data/transactions/logic/README.md
  data/transactions/logic/README_in.md
  data/transactions/logic/TEAL_opcodes.md
  data/transactions/logic/assembler.go
  data/transactions/logic/assembler_test.go
  data/transactions/logic/doc.go
  data/transactions/logic/doc_test.go
  data/transactions/logic/eval.go
  data/transactions/logic/evalAppTxn_test.go
  data/transactions/logic/evalStateful_test.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/fields.go
  data/transactions/logic/fields_string.go
  data/transactions/logic/opcodes.go
  data/transactions/logictest/ledger.go
  data/transactions/msgp_gen.go
  data/transactions/transaction.go
  data/transactions/verify/txn.go
  ledger/applications.go
  ledger/applications_test.go
  ledger/apply/application.go
  ledger/apply/asset.go
  ledger/apptxn_test.go
  ledger/cow.go
  ledger/eval.go
  ledger/eval_test.go
  test/e2e-go/restAPI/restClient_test.go
  test/scripts/e2e_subs/tealprogs/app-escrow.teal
Labels: Unplanned, Team Scytale

#2891 Extract rename
  data/transactions/logic/README.md
  data/transactions/logic/README_in.md
  data/transactions/logic/TEAL_opcodes.md
  data/transactions/logic/assembler_test.go
  data/transactions/logic/doc.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/opcodes.go
Labels: Team Scytale

#2877 Consensus V30 updates
  config/consensus.go
  ledger/applications_test.go
  ledger/eval_test.go
  protocol/consensus.go
Labels: Unplanned, Team Scytale

#2864 use matrix for CircleCI config
  .circleci/config.yml
  scripts/travis/build.sh
Labels: Unplanned, Team Hyper Flow

#2900 Enable debugging itxn programs
  cmd/tealdbg/local.go
  cmd/tealdbg/local_test.go
  daemon/algod/api/server/v2/dryrun.go
  daemon/algod/api/server/v2/dryrun_test.go
  test/e2e-go/cli/tealdbg/expect/tealdbgTest.exp
Labels: Unplanned, Team Scytale

#2882 Improve peerScheduler.peerDuration performance
  txnsync/bloomFilter_test.go
  txnsync/incoming_test.go
  txnsync/mainloop.go
  txnsync/outgoing_test.go
  txnsync/peerscheduler.go
  txnsync/peerscheduler_test.go
  txnsync/service.go
Labels: Team Carbon-11

#2897 Add `indexerLedgerForEval` interface
  ledger/eval.go
  ledger/evalIndexer.go
  ledger/evalIndexer_test.go
  ledger/eval_test.go
Labels: Team Carbon-11

#2905 Rel/beta 3.0.1
  buildnumber.dat
  cmd/tealdbg/local.go
  cmd/tealdbg/localLedger.go
  cmd/tealdbg/local_test.go
  daemon/algod/api/server/v2/account.go
  daemon/algod/api/server/v2/dryrun.go
  daemon/algod/api/server/v2/dryrun_test.go
  test/e2e-go/cli/tealdbg/expect/tealdbgTest.exp
Labels: Team Hyper Flow

#2903 Fix random failures TestWaitAndAddConnectionTimeLongtWindow
  network/phonebook_test.go
Labels: Team Carbon-11

#2926 testing: fix unit test data race
  compactcert/worker_test.go
Labels: Team Carbon-11

#2927 txnsync: merge master into txnsync branch.
  .circleci/config.yml
  cmd/netgoal/generate.go
  cmd/opdoc/opdoc.go
  cmd/tealdbg/local.go
  cmd/tealdbg/localLedger.go
  cmd/tealdbg/local_test.go
  config/consensus.go
  crypto/secp256k1/dummy.go
  daemon/algod/api/server/v1/handlers/handlers.go
  daemon/algod/api/server/v2/account.go
  daemon/algod/api/server/v2/dryrun.go
  daemon/algod/api/server/v2/dryrun_test.go
  daemon/algod/api/server/v2/utils.go
  data/pools/transactionPool.go
  data/transactions/logic/README.md
  data/transactions/logic/README_in.md
  data/transactions/logic/TEAL_opcodes.md
  data/transactions/logic/assembler.go
  data/transactions/logic/assembler_test.go
  data/transactions/logic/doc.go
  data/transactions/logic/doc_test.go
  data/transactions/logic/eval.go
  data/transactions/logic/evalAppTxn_test.go
  data/transactions/logic/evalStateful_test.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/fields.go
  data/transactions/logic/fields_string.go
  data/transactions/logic/opcodes.go
  data/transactions/logictest/ledger.go
  data/transactions/msgp_gen.go
  data/transactions/transaction.go
  data/transactions/verify/txn.go
  ledger/applications.go
  ledger/applications_test.go
  ledger/apply/application.go
  ledger/apply/asset.go
  ledger/apptxn_test.go
  ledger/cow.go
  ledger/eval.go
  ledger/evalIndexer.go
  ledger/evalIndexer_test.go
  ledger/eval_test.go
  network/phonebook_test.go
  protocol/consensus.go
  scripts/travis/build.sh
  test/e2e-go/cli/tealdbg/expect/tealdbgTest.exp
  test/e2e-go/restAPI/restClient_test.go
  test/scripts/e2e_subs/tealprogs/app-escrow.teal
  test/testdata/deployednettemplates/recipes/scenario1/genesis.json
  test/testdata/deployednettemplates/recipes/scenario1/net.json
  test/testdata/deployednettemplates/recipes/scenario2/genesis.json
  test/testdata/deployednettemplates/recipes/scenario2/net.json
  test/testdata/deployednettemplates/recipes/scenario3/genesis.json
  test/testdata/deployednettemplates/recipes/scenario3/net.json
Labels: Team Carbon-11

#2922 ledger: move account totals calculation to StateDelta
  ledger/acctupdates.go
  ledger/acctupdates_test.go
  ledger/appcow.go
  ledger/appcow_test.go
  ledger/catchpointwriter_test.go
  ledger/cow.go
  ledger/cow_test.go
  ledger/eval.go
  ledger/evalIndexer.go
  ledger/eval_test.go
  ledger/ledgercore/statedelta.go
  ledger/txtail_test.go
Labels: Team Carbon-11

#2923 Support arm cross compile
  scripts/archtype.sh
  scripts/ostype.sh
  test/muleCI/Jenkinsfile
  test/muleCI/mule.yaml
Labels: Team Hyper Flow

#2934 Rotate Travis Env Variables and Remove codecov Env variable
  .travis.yml
Labels: Team Hyper Flow

#2928 TestRequestBlockBytesErrors: Various fixes
  catchup/universalFetcher.go
  catchup/universalFetcher_test.go
  rpcs/blockService.go
Labels: Team Carbon-11

#2937 Remove time ledger tracker as not used
  ledger/README.md
  ledger/ledger.go
  ledger/time.go
Labels: Team Scytale

#2938 readme grammar change
  README.md
Labels: Team Hyper Flow

#2941 ledger: update EvalForIndexer to avoid totals computation
  ledger/evalIndexer.go
Labels: Team Carbon-11

#2939 Cache creators in cow base
  ledger/appcow.go
  ledger/eval.go
  ledger/evalIndexer.go
  ledger/eval_test.go
Labels: Team Carbon-11

#2940 testing: fix TestLatestSigsFromThisNode
  compactcert/worker_test.go
Labels: Team Carbon-11

#2950 e2e tests for log
  test/e2e-go/restAPI/restClient_test.go
  test/scripts/e2e_subs/e2e-logs.sh
  test/scripts/e2e_subs/tealprogs/logs.teal
Labels: Unplanned, Team Scytale

#2945 Add application account into a dryrun req created by goal
  cmd/goal/application.go
  cmd/goal/clerk.go
  cmd/goal/commands.go
  cmd/goal/common.go
  libgoal/libgoal.go
Labels: Team Scytale

#2919 GroupCounter based iterative txnsync filters
  txnsync/bloomFilter.go
  txnsync/emulatorLogger_test.go
  txnsync/emulatorNode_test.go
  txnsync/exchange.go
  txnsync/incoming.go
  txnsync/mainloop.go
  txnsync/msgp_gen.go
  txnsync/outgoing.go
  txnsync/peer.go
  txnsync/peer_test.go
  txnsync/sent_filter.go
  txnsync/sent_filter_test.go
Labels: Team Carbon-11

#2947 e2e tests for axfer, acfg, and afrz inner txns
  test/scripts/e2e_subs/app-assets.sh
  test/scripts/e2e_subs/tealprogs/assets-escrow.teal
Labels: Team Scytale

#2954 Enable cost and fee pooling in tealdbg
  cmd/tealdbg/local.go
  cmd/tealdbg/local_test.go
Labels: Team Scytale

#2962 testing: metrics_delta.py fixes
  test/heapwatch/metrics_delta.py
Labels: 1, Team Carbon-11

#2888 added benchmark to participation. refactored fillDB benchmark too.
  data/account/participation_test.go
Labels: Team Sphinx

#2846 ledger: refactor the ledger Totals
  daemon/algod/api/server/v1/handlers/handlers.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_test.go
  data/ledger.go
  data/ledger_test.go
  data/pools/transactionPool.go
  ledger/acctupdates.go
  ledger/eval.go
  ledger/evalIndexer.go
  ledger/evalIndexer_test.go
  ledger/ledger.go
  ledger/ledger_test.go
  ledger/ledgercore/error.go
  node/node.go
Labels: Team Carbon-11

#2946 E2E PR for new stateProof keys
  test/e2e-go/upgrades/send_receive_upgrade_test.go
  test/e2e-go/upgrades/stateproof_test.go
  test/testdata/nettemplates/TwoNodesWithoutStateProofPartkeys.json
  test/testdata/nettemplates/UpgradeIntoCompactCert.json
Labels: Team Sphinx

#2975 Extended logic eval error
  data/transactions/logic/eval.go
  data/transactions/logic/eval_test.go
  ledger/appcow.go
  ledger/ledgercore/error.go
Labels: Unplanned, Team Scytale
