Repository algorand/go-algorand, pull requests merged in 2021-04, with the labels that each got.

#1966 Add networking infrastructure for cancelling sends
  agreement/gossip/networkFull_test.go
  network/ping.go
  network/wsNetwork.go
  network/wsNetwork_test.go
  network/wsPeer.go
Labels: Infrastructure

#2007 Pingpong nft
  cmd/pingpong/runCmd.go
  shared/pingpong/accounts.go
  shared/pingpong/config.go
  shared/pingpong/pingpong.go
  test/commandandcontrol/cc_agent/component/pingPongComponent.go
Labels: Infrastructure, Unplanned

#2011 script to watch algod heap
  test/heapwatch/README.md
  test/heapwatch/heapWatch.py
  test/heapwatch/start.sh
  test/heapwatch/stop.sh
Labels: Infrastructure, Unplanned

#2027 ledger: split committed round range by consensus protocol version
  ledger/accountdb.go
  ledger/accountdb_test.go
  ledger/acctupdates.go
  ledger/acctupdates_test.go
Labels: Infrastructure

#1997 Improve txsync and txpool data exchange
  data/pools/transactionPool.go
  data/pools/transactionPool_test.go
  data/transactions/transaction.go
  data/transactions/verify/verifiedTxnCache.go
  data/txHandler.go
  data/txHandler_test.go
  node/node.go
  node/txnSyncConn.go
  rpcs/txService.go
  rpcs/txSyncer.go
  rpcs/txSyncer_test.go
  txnsync/emulatorCore_test.go
  txnsync/emulatorNode_test.go
  txnsync/emulatorTimer_test.go
  txnsync/emulator_test.go
  txnsync/incoming.go
  txnsync/interfaces.go
  txnsync/outgoing.go
Labels: Infrastructure

#2038 Fix ClearState program applying when it errs
  ledger/appcow.go
  ledger/apply/application.go
  ledger/apply/application_test.go
  ledger/ledgercore/error.go
  test/scripts/e2e_subs/e2e-app-simple.sh
Labels: Infrastructure

#2037 Fix for empty local state key value map assignment
  ledger/appcow.go
  ledger/applications_test.go
Labels: Infrastructure

#2043 Fix node panicing during shutdown
  node/node.go
Labels: Infrastructure, Unplanned

#2049 bugfix: ensure loading of a merkle trie deferred page during commit
  crypto/merkletrie/cache.go
  crypto/merkletrie/cache_test.go
  ledger/accountdb.go
Labels: Infrastructure, Unplanned

#2051 Fix requestNonce alignment on arm32
  network/wsPeer.go
  network/wsPeer_test.go
Labels: Infrastructure, Unplanned

#2028 Filter out automated testing useless verbosed output
  Makefile
  debug/logfilter/example1.in
  debug/logfilter/example1.out.expected
  debug/logfilter/example2.in
  debug/logfilter/example2.out.expected
  debug/logfilter/example3.in
  debug/logfilter/example3.out.expected
  debug/logfilter/example4.in
  debug/logfilter/example4.out.expected
  debug/logfilter/example5.in
  debug/logfilter/example5.out.expected
  debug/logfilter/example6.in
  debug/logfilter/example6.out.expected
  debug/logfilter/main.go
  debug/logfilter/main_test.go
  test/scripts/e2e_go_tests.sh
Labels: Infrastructure, Unplanned

#2050 Extend catchpointdump utility to verify merkle trie
  cmd/catchpointdump/commands.go
  cmd/catchpointdump/database.go
  crypto/merkletrie/cache_test.go
  crypto/merkletrie/committer_test.go
  crypto/merkletrie/node.go
  crypto/merkletrie/trie.go
  crypto/merkletrie/trie_test.go
  ledger/accountdb.go
  ledger/acctupdates.go
  ledger/catchupaccessor.go
Labels: Infrastructure, Unplanned

#2054 make the msgp less verbosed on the success case
  Makefile
Labels: Infrastructure

#2055 txnsync: fix incoming/outgoing messages text.
  txnsync/logger.go
Labels: Infrastructure

#2052 merge master into feature/txnsync
  crypto/merkletrie/cache.go
  crypto/merkletrie/cache_test.go
  ledger/accountdb.go
  ledger/appcow.go
  ledger/applications_test.go
  ledger/apply/application.go
  ledger/apply/application_test.go
  ledger/ledgercore/error.go
  network/wsPeer.go
  network/wsPeer_test.go
  node/node.go
  test/scripts/e2e_subs/e2e-app-simple.sh
Labels: Infrastructure

#2056 ensure the participation key database is being correctly closed after being installed.
  cmd/goal/account.go
  libgoal/participation.go
Labels: Infrastructure, Unplanned

#2053 Use shared encoding buffer for the encoded transaction groups
  txnsync/outgoing.go
  txnsync/txngroups.go
Labels: Infrastructure, Unplanned

#2062 txnsync: Avoid regenerating bloom filters when not needed
  txnsync/bloomFilter.go
  txnsync/mainloop.go
  txnsync/outgoing.go
  txnsync/peer.go
Labels: Infrastructure

#2066 Log error conditions of invalid incoming messages
  txnsync/incoming.go
Labels: Infrastructure

#2070 debug tooling: logfilter bug when running test without -v
  debug/logfilter/example7.in
  debug/logfilter/example7.out.expected
  debug/logfilter/main.go
Labels: Infrastructure

#2063 netgoal: fixup small amounts of float64 roundoff
  cmd/genesis/newgenesis.go
  gen/generate.go
  gen/generate_test.go
  netdeploy/networkTemplate.go
  netdeploy/remote/deployedNetwork.go
Labels: Infrastructure, Unplanned

#2042 Tealdbg don't assume program version
  cmd/tealdbg/local.go
  cmd/tealdbg/local_test.go
  cmd/tealdbg/main.go
  test/e2e-go/cli/tealdbg/expect/tealdbgSpinoffTest.exp
  test/e2e-go/cli/tealdbg/expect/tealdbgTest.exp
Labels: FDE, Unplanned

#2067 goal: improve waitForCommit logic
  cmd/goal/account.go
  cmd/goal/application.go
  cmd/goal/asset.go
  cmd/goal/clerk.go
  cmd/goal/interact.go
  cmd/goal/messages.go
  test/e2e-go/cli/goal/expect/goalAccountTest.exp
  test/e2e-go/cli/goal/expect/goalExpectCommon.exp
Labels: Infrastructure

#2061 Refactor participation keys management
  agreement/agreementtest/simulate_test.go
  agreement/fuzzer/fuzzer_test.go
  agreement/service_test.go
  catchup/pref_test.go
  cmd/algokey/part.go
  cmd/goal/account.go
  compactcert/worker_test.go
  daemon/algod/api/server/v2/test/helpers.go
  data/account/account.go
  data/account/participation.go
  data/account/participation_test.go
  data/accountManager.go
  data/common_test.go
  gen/generate.go
  libgoal/participation.go
  test/framework/fixtures/libgoalFixture.go
  util/db/perf_test.go
Labels: Infrastructure, Unplanned

#2060 Fine tune catchup peer selection logic
  catchup/peerSelector.go
  catchup/peerSelector_test.go
  catchup/service.go
  catchup/universalFetcher.go
  ledger/ledger.go
Labels: Infrastructure

#2046 netgoal: add pre-generated network support
  cmd/netgoal/generate.go
  cmd/netgoal/network.go
  cmd/netgoal/recipe.go
  netdeploy/remote/bootstrappedNetwork.go
  netdeploy/remote/bootstrappedNetwork_test.go
  netdeploy/remote/deployedNetwork.go
  netdeploy/remote/deployedNetwork_test.go
  test/testdata/deployednettemplates/networks/bootstrapped/badSpec.json
  test/testdata/deployednettemplates/networks/bootstrapped/okSpec.json
  test/testdata/deployednettemplates/recipes/bootstrappedScenario/Makefile
  test/testdata/deployednettemplates/recipes/bootstrappedScenario/boostrappedFile.json
  test/testdata/deployednettemplates/recipes/bootstrappedScenario/gen_topology.py
  test/testdata/deployednettemplates/recipes/bootstrappedScenario/genesis.json
  test/testdata/deployednettemplates/recipes/bootstrappedScenario/net.json
  test/testdata/deployednettemplates/recipes/bootstrappedScenario/node.json
  test/testdata/deployednettemplates/recipes/bootstrappedScenario/nonPartNode.json
  test/testdata/deployednettemplates/recipes/bootstrappedScenario/recipe.json
  test/testdata/deployednettemplates/recipes/bootstrappedScenario/relay.json
  test/testdata/deployednettemplates/recipes/bootstrappedScenario/topology.json
Labels: Infrastructure

#2076 goal: refactor waitForCommit
  cmd/goal/account.go
  cmd/goal/application.go
  cmd/goal/asset.go
  cmd/goal/clerk.go
  cmd/goal/interact.go
Labels: Infrastructure

#2075 goal node restart message when node already started
  cmd/goal/messages.go
  cmd/goal/node.go
  test/e2e-go/cli/goal/expect/goalNodeTest.exp
Labels: Infrastructure

#2077 catchup: cross verify genesis.json hash
  catchup/catchpointService.go
Labels: Infrastructure, Unplanned

#2078 agreement: rollback early proposal propagation changes
  agreement/player.go
Labels: Infrastructure

#2081 go-algorand 2.5.5-beta
  agreement/player.go
  buildnumber.dat
Labels: Dev Ops

#2082 go-algorand 2.5.5-stable
  agreement/player.go
  buildnumber.dat
Labels: Dev Ops

#2083 reduce verbosity of logged messages
  catchup/service.go
  node/node.go
  util/db/dbutil.go
Labels: Infrastructure, Unplanned

#2086 ledger: avoid producing empty local delta
  config/consensus.go
  ledger/appcow.go
  ledger/appcow_test.go
  ledger/applications_test.go
  protocol/consensus.go
Labels: Infrastructure

#2091 Prevent storing empty accounts in DB after opting out from an app
  ledger/appcow.go
  ledger/appcow_test.go
  ledger/applications_test.go
Labels: Infrastructure

#2092 Fix initial balances in ledger tests
  cmd/tealdbg/local.go
  ledger/accountdb_test.go
  ledger/applications_test.go
  ledger/catchupaccessor_test.go
  ledger/ledger_test.go
Labels: Infrastructure

#2093 DB data migration for empty accounts
  ledger/accountdb.go
  ledger/acctupdates.go
Labels: Infrastructure

#2096 ledger: fix consensus version flushes incorrectly
  ledger/acctupdates.go
  ledger/acctupdates_test.go
Labels: Infrastructure

#2094 Copy database files to nodes
  cmd/netgoal/network.go
  netdeploy/remote/nodecfg/nodeConfigurator.go
  scripts/create_and_deploy_recipe.sh
Labels: Infrastructure

#2100 logfilter: exit with non-zero when test fails
  debug/logfilter/main.go
  debug/logfilter/main_test.go
Labels: Infrastructure

#2103 ledger: improve error testing on database migration 4
  ledger/accountdb.go
  ledger/acctupdates.go
Labels: Infrastructure, Unplanned

#2102 Fix accessing int64 atomic variables on arm32
  crypto/merklearray/worker.go
Labels: Infrastructure, Unplanned

#2095 ledger: compatibility mode for account index calculation in eval delta
  data/transactions/logic/eval.go
  data/transactions/logic/evalStateful_test.go
  ledger/appcow.go
  ledger/appcow_test.go
  ledger/applications.go
  ledger/applications_test.go
  ledger/cow.go
  ledger/cow_test.go
  ledger/eval.go
Labels: Infrastructure

#2106 catchpoint: truncate output file
  cmd/catchpointdump/database.go
  cmd/catchpointdump/file.go
  cmd/catchpointdump/net.go
Labels: Infrastructure, Unplanned

#2107 fix typos in comments
  ledger/acctupdates.go
  ledger/appcow.go
Labels: Infrastructure, Unplanned

#2098 Fix insufficient account with preloaded db files
  netdeploy/remote/deployedNetwork.go
Labels: Infrastructure, Unplanned

#2113 Fix merge conflict
  cmd/goal/clerk.go
Labels: Infrastructure

#2115 Add performance metrics for account updates
  config/config.go
  config/local_defaults.go
  installer/config.json.example
  ledger/acctupdates.go
  logging/telemetryspec/metric.go
  test/testdata/configs/config-v17.json
  test/testdata/deployednettemplates/recipes/bootstrappedScenario/net.json
  test/testdata/deployednettemplates/recipes/bootstrappedScenario/node.json
  test/testdata/deployednettemplates/recipes/bootstrappedScenario/relay.json
  test/testdata/deployednettemplates/recipes/scenario1/node.json
  test/testdata/deployednettemplates/recipes/scenario1/relay.json
  test/testdata/deployednettemplates/recipes/scenario2/node.json
  test/testdata/deployednettemplates/recipes/scenario2/relay.json
  test/testdata/deployednettemplates/recipes/scenario3/node.json
  test/testdata/deployednettemplates/recipes/scenario3/relay.json
Labels: Infrastructure
