Repository algorand/go-algorand, pull requests merged in 2021-08, with the labels that each got.

#2620 merkle-part-key-integration
  Makefile
  cmd/goal/account.go
  crypto/merklearray/layer.go
  crypto/merklearray/merkle.go
  crypto/merklearray/msgp_gen.go
  crypto/merklearray/msgp_gen_test.go
  crypto/merklearray/partial.go
  crypto/merklekeystore/keystore.go
  crypto/merklekeystore/keystore_test.go
  crypto/merklekeystore/msgp_gen.go
  crypto/merklekeystore/msgp_gen_test.go
  crypto/merklekeystore/posdivs.go
  data/account/account.go
  data/account/participation.go
  data/account/participation_test.go
  data/basics/userBalance.go
  data/transactions/keyreg.go
  data/transactions/transaction.go
  data/transactions/transaction_test.go
  gen/generate.go
  ledger/accountdb_test.go
  ledger/apply/keyreg_test.go
  ledger/ledger_test.go
  libgoal/participation.go
Labels: Team Sphinx

#2682 Create a quine to test `app_params_get AppApprovalProgram`
  test/scripts/e2e_subs/teal-app-params.sh
  test/scripts/e2e_subs/tealprogs/quine.teal
Labels: Team Scytale

#2669 Extend global and txn field tests for all TEAL versions and protocols
  data/transactions/logic/backwardCompat_test.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/fields_test.go
Labels: Team Scytale, Unplanned

#2671 Create New Participation Key Interface REST endpoints
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/private/routes.go
  daemon/algod/api/server/v2/generated/private/types.go
  daemon/algod/api/server/v2/generated/routes.go
  daemon/algod/api/server/v2/generated/types.go
  daemon/algod/api/server/v2/handlers.go
Labels: Team Carbon-11

#2623 Added outgoing unit tests
  txnsync/outgoing.go
  txnsync/outgoing_test.go
Labels: Team Carbon-11

#2680 Record modified local creatable states in state delta.
  ledger/appcow.go
  ledger/apply/asset.go
  ledger/assetcow.go
  ledger/cow.go
  ledger/eval_test.go
  ledger/ledgercore/statedelta.go
Labels: Team Carbon-11

#2668 Fix oapi-codegen installation.
  daemon/algod/api/Makefile
  scripts/buildtools/go.mod
  scripts/buildtools/go.sum
  scripts/buildtools/install_buildtools.sh
  scripts/travis/codegen_verification.sh
Labels: Team Carbon-11, Unplanned

#2686 txnsync: avoid race condition in evaluateIncomingMessage
  txnsync/incoming.go
Labels: Team Carbon-11

#2689 Revert "replace the KMD usage in pingpong with direct signing"
  shared/pingpong/accounts.go
  shared/pingpong/pingpong.go
Labels: Team Carbon-11

#2688 Fix a go lint issue.
  cmd/partitiontest_linter/plugin/plugin.go
Labels: Team Carbon-11

#2648 txnsync: correctness e2e test
  daemon/algod/api/client/restClient.go
  libgoal/libgoal.go
  test/e2e-go/features/transactions/txnsync_test.go
  test/testdata/nettemplates/TwoNodes50EachWithTwoRelays.json
  txnsync/incoming_test.go
  txnsync/logger.go
Labels: Team Carbon-11

#2694 Consensus upgrade for ExtraProgramPages fix
  config/consensus.go
  daemon/algod/api/client/restClient.go
  data/basics/overflow.go
  data/basics/units_test.go
  ledger/apply/application.go
  ledger/apply/application_test.go
  libgoal/libgoal.go
  protocol/consensus.go
  test/e2e-go/features/transactions/app_pages_test.go
Labels: Unplanned, Team Scytale

#2693 txnsync: make configurable data exchange rate
  config/config.go
  config/local_defaults.go
  installer/config.json.example
  test/testdata/configs/config-v17.json
  txnsync/emulatorCore_test.go
  txnsync/incoming.go
  txnsync/mainloop.go
  txnsync/outgoing.go
  txnsync/outgoing_test.go
  txnsync/peer.go
  txnsync/peer_test.go
  txnsync/peerscheduler.go
Labels: Team Carbon-11

#2699 Add individual program length checks into updateApplication
  ledger/apply/application.go
  ledger/apply/application_test.go
Labels: Team Scytale

#2691 testing: replace the KMD usage in pingpong with direct signing
  shared/pingpong/accounts.go
  shared/pingpong/pingpong.go
Labels: Team Carbon-11

#2709 Fix flaky ledger app tests that use commitRound directly
  ledger/acctupdates.go
  ledger/applications_test.go
Labels: Unplanned, Team Scytale

#2720 using the appIdx instead of txn app id
  libgoal/libgoal.go
Labels: Team Scytale

#2621 E2E test: txnsync message rate increases with txn rate
  test/e2e-go/features/transactions/messageRate_test.go
  test/testdata/nettemplates/OneNodeTwoRelays.json
Labels: Team Carbon-11

#2708 Return an error in `EncodeSignedTxn()` and `DecodeSignedTxn()` if consensus protocol is unknown.
  data/bookkeeping/block.go
  data/bookkeeping/block_test.go
  node/indexer/indexer_test.go
  node/topAccountListener_test.go
Labels: Team Carbon-11

#2700 Added More Transaction Cache Unit Tests
  txnsync/transactionCache_test.go
Labels: Team Carbon-11

#2721 testing: update crypto library to use partitiontest
  crypto/batchverifier_test.go
  crypto/cryptoerror.go
  crypto/multisig_test.go
Labels: Team Carbon-11

#2643 CircleCI: Add Slack notifications for rel/nightly failures
  .circleci/config.yml
Labels: Team Hyper Flow

#2678 Dil sigs
  agreement/msgp_gen_test.go
  compactcert/msgp_gen_test.go
  crypto/compactcert/msgp_gen_test.go
  crypto/dillithium.go
  crypto/dillithium_test.go
  crypto/merklekeystore/keystore.go
  crypto/merklekeystore/keystore_test.go
  crypto/merklekeystore/msgp_gen.go
  crypto/msgp_gen.go
  crypto/msgp_gen_test.go
  crypto/placeholder.go
  crypto/sig_abstractions.go
  data/account/participation.go
  data/account/participation_test.go
  data/basics/msgp_gen_test.go
  data/bookkeeping/msgp_gen_test.go
  data/committee/msgp_gen_test.go
  data/hashable/msgp_gen_test.go
  data/transactions/msgp_gen_test.go
  go.mod
  go.sum
  ledger/apply/keyreg_test.go
  ledger/ledger_test.go
  ledger/ledgercore/msgp_gen_test.go
  ledger/msgp_gen_test.go
  node/msgp_gen_test.go
  protocol/test/msgp_gen_test.go
  rpcs/msgp_gen_test.go
Labels: Team Sphinx

#2729 Barbara/circle filter branches
  .circleci/config.yml
Labels: Team Hyper Flow

#2740 go-algorand v2.9.1-stable re-merge
  .travis.yml
  config/version.go
  scripts/travis/run_tests.sh
Labels: Team Hyper Flow

#2705 Consolidate SKIP_E2E_SUBS and E2E_SUBS_ONLY
  .circleci/config.yml
  test/scripts/e2e.sh
Labels: Team Hyper Flow

#2742 Fix TestRekeyUpgrade test
  test/e2e-go/upgrades/rekey_support_test.go
Labels: Team Scytale

#2732 Make config.MaxLogCalls dependant on some consensus param
  config/consensus.go
  data/transactions/logic/backwardCompat_test.go
  data/transactions/logic/eval.go
  data/transactions/logic/eval_test.go
Labels: Team Scytale

#2748 txnsync: merge from master
  .circleci/config.yml
  .travis.yml
  config/config.go
  config/consensus.go
  config/version.go
  data/pools/transactionPool.go
  data/transactions/logic/backwardCompat_test.go
  data/transactions/logic/eval.go
  data/transactions/logic/eval_test.go
  scripts/travis/run_tests.sh
  test/e2e-go/upgrades/rekey_support_test.go
  test/scripts/e2e.sh
Labels: Team Carbon-11

#2753 testing: fixing a typo in e2e.sh for integration tests
  test/scripts/e2e.sh
Labels: Team Hyper Flow

#2747 testing: update pingpong transaction sending logic
  daemon/algod/api/client/restClient.go
  libgoal/libgoal.go
  shared/pingpong/accounts.go
  shared/pingpong/pingpong.go
Labels: Team Carbon-11

#2763 Display extra pages in goal info commands
  cmd/goal/account.go
  cmd/goal/accountsList.go
  cmd/goal/application.go
  test/e2e-go/cli/goal/expect/goalAccountInfoTest.exp
  test/scripts/e2e_subs/e2e-app-extra-pages.sh
Labels: Unplanned, Team Scytale

#2766 Improve error message in update.sh when updater is corrupt.
  cmd/updater/update.sh
Labels: Unplanned, Team Carbon-11

#2768 Remove codegen from travis file
  .travis.yml
Labels: Team Hyper Flow

#2752 testing: added MsgBuffer unit tests
  txnsync/msgbuffers_test.go
Labels: Team Carbon-11

#2771 add account balance range
  cmd/netgoal/generate.go
  netdeploy/remote/bootstrappedNetwork.go
  netdeploy/remote/deployedNetwork.go
  test/testdata/deployednettemplates/recipes/bootstrappedScenario/Makefile
  test/testdata/deployednettemplates/recipes/bootstrappedScenario/boostrappedFile.json
  test/testdata/deployednettemplates/recipes/bootstrappedScenario/genesis.json
Labels: Team Scytale

#2772 Fix ParseHostOrURL and enable expect tests
  network/wsNetwork.go
  network/wsNetwork_test.go
  test/e2e-go/cli/goal/expect/goalCmdFlagsTest.exp
  test/e2e-go/cli/goal/expect/goalExpectCommon.exp
  test/e2e-go/cli/goal/expect/goal_expect_test.go
  test/e2e-go/cli/goal/expect/tealConsensusTest.exp
  test/framework/fixtures/expectFixture.go
Labels: Unplanned, Team Scytale

#2722 txnsync: change iterate
  txnsync/bitmask.go
  txnsync/bitmask_test.go
  txnsync/encodedgroups_test.go
  txnsync/encodedgroupsunmarshalers.go
Labels: Team Carbon-11

#2778 txnsync: merge master into feature/txnsync branch
  .travis.yml
  cmd/goal/account.go
  cmd/goal/accountsList.go
  cmd/goal/application.go
  cmd/netgoal/generate.go
  cmd/updater/update.sh
  netdeploy/remote/bootstrappedNetwork.go
  netdeploy/remote/deployedNetwork.go
  network/wsNetwork.go
  network/wsNetwork_test.go
  protocol/hash.go
  protocol/tags.go
  shared/pingpong/accounts.go
  shared/pingpong/pingpong.go
  test/e2e-go/cli/goal/expect/goalAccountInfoTest.exp
  test/e2e-go/cli/goal/expect/goalCmdFlagsTest.exp
  test/e2e-go/cli/goal/expect/goalExpectCommon.exp
  test/e2e-go/cli/goal/expect/goalNodeTest.exp
  test/e2e-go/cli/goal/expect/goal_expect_test.go
  test/e2e-go/cli/goal/expect/tealConsensusTest.exp
  test/framework/fixtures/expectFixture.go
  test/scripts/e2e.sh
  test/scripts/e2e_subs/e2e-app-extra-pages.sh
  test/testdata/deployednettemplates/recipes/bootstrappedScenario/Makefile
  test/testdata/deployednettemplates/recipes/bootstrappedScenario/boostrappedFile.json
  test/testdata/deployednettemplates/recipes/bootstrappedScenario/genesis.json
Labels: Team Carbon-11

#2775 Limit the number of buckets in `verifiedTransactionCache` to 3
  data/transactions/verify/verifiedTxnCache.go
  data/transactions/verify/verifiedTxnCache_test.go
Labels: Team Carbon-11

#2785 testing: disable deadlock for netgoal
  cmd/netgoal/commands.go
Labels: Team Carbon-11

#2781 Fix goalNodeTest.exp
  test/e2e-go/cli/goal/expect/goalAccountTest.exp
  test/e2e-go/cli/goal/expect/goalClerkGroupTest.exp
  test/e2e-go/cli/goal/expect/goalNodeTest.exp
  test/framework/fixtures/expectFixture.go
Labels: Team Scytale

#2757 testing: fix TestStartAndStop
  rpcs/txSyncer_test.go
Labels: Team Carbon-11

#2782 Peer Scheduler Unit Tests
  txnsync/peerscheduler_test.go
  txnsync/service_test.go
Labels: Team Carbon-11

#2783 per-client RAM measurement scripts
  cmd/goal/account.go
  cmd/goal/commands.go
  test/heapwatch/client_ram_report.py
  test/heapwatch/heapWatch.py
  test/heapwatch/metrics_delta.py
  test/heapwatch/nodeHostTarget.py
  test/heapwatch/runNodeHost.py
Labels: Team Carbon-11

#2800 go-algorand 2.10.1-beta
  buildnumber.dat
  data/transactions/logic/assembler.go
  data/transactions/logic/assembler_test.go
  data/transactions/logic/debugger.go
  data/transactions/logic/eval.go
  data/transactions/logic/evalStateful_test.go
  data/transactions/logic/fields.go
  data/transactions/logic/fields_test.go
Labels: Team Hyper Flow

#2764 Fix and enable TestSlowOutboundPeer
  network/wsNetwork_test.go
Labels: Team Carbon-11

#2811 Fix overriding consensus parameters in evaluator.
  ledger/appcow.go
  ledger/appcow_test.go
  ledger/cow.go
  ledger/cow_test.go
  ledger/eval.go
  ledger/eval_test.go
Labels: Team Carbon-11

#2818 Fix bugs / refactor txnsync message encoding / decoding
  data/basics/userBalance.go
  txnsync/bitmask.go
  txnsync/encodedgroups_test.go
  txnsync/encodedgroupsmarshalers.go
  txnsync/encodedgroupsunmarshalers.go
  txnsync/txngroups.go
  txnsync/txngroups_test.go
Labels: Team Carbon-11
