Repository algorand/go-algorand, pull requests merged in 2022-11, with the labels that each got.

#4716 test: fix after boxes and prefetcher remerge
  ledger/internal/eval.go
  test/e2e-go/features/transactions/accountv2_test.go
Labels: Team Carbon-11, Bug-Fix

#4720 Bug-Fix: Blank Import Needs Commenting for Indexer's Lint
  daemon/algod/api/swagger.go
Labels: Bug-Fix

#4719 AVM: fix early eval exits for Debugger
  daemon/algod/api/server/v2/dryrun_test.go
  data/transactions/logic/README.md
  data/transactions/logic/README_in.md
  data/transactions/logic/TEAL_opcodes.md
  data/transactions/logic/doc.go
  data/transactions/logic/eval.go
  data/transactions/logic/langspec.json
Labels: Bug-Fix

#4703 catchpoint: actualize limit constants and fix txtail table init
  catchup/ledgerFetcher.go
  data/basics/userBalance.go
  data/basics/userBalance_test.go
  ledger/accountdb.go
  ledger/accountdb_test.go
  ledger/catchpointtracker.go
  ledger/catchpointwriter.go
  ledger/catchpointwriter_test.go
  ledger/msgp_gen.go
Labels: Team Carbon-11, Bug-Fix

#4643 tools: Allow specification of Reward Pool Account Balance in Genesis
  gen/generate.go
  gen/generate_test.go
  gen/resources/genesis-balance.json
  gen/resources/genesis-base.json
  gen/walletData.go
Labels: Enhancement, dev tools

#4722 Consensus: v36 upgrade
  config/consensus.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/frames_test.go
  data/transactions/logic/langspec.json
  data/transactions/logic/opcodes.go
  ledger/apply/application_test.go
  ledger/boxtxn_test.go
  ledger/testing/consensusRange.go
  ledger/testing/consensusRange_test.go
  protocol/consensus.go
Labels: Enhancement

#4713 dispenser: add input validation
  cmd/dispenser/index.html.tpl
  cmd/dispenser/server.go
Labels: Bug-Fix

#4726 mergeback: feature/alphanet
  installer/genesis/alphanet/genesis.json
  test/testdata/deployednettemplates/recipes/alphanet/gen_topology.py
  test/testdata/deployednettemplates/recipes/alphanet/genesis.json
  test/testdata/deployednettemplates/recipes/alphanet/topology.json
Labels: unplanned, Team Hyper Flow, Skip-Release-Notes

#4724 db: add AtomicContext
  ledger/catchpointtracker.go
  util/db/dbutil.go
Labels: Team Carbon-11, Skip-Release-Notes

#4743 Catchpoint Dump Utility: catchpointdump now supports tar.gz
  cmd/catchpointdump/file.go
Labels: New Feature

#4715 performance: Don't preallocate rarely used maps in MakeStateDelta
  ledger/internal/appcow.go
  ledger/internal/appcow_test.go
  ledger/internal/applications.go
  ledger/internal/assetcow.go
  ledger/internal/cow.go
  ledger/ledgercore/statedelta.go
  ledger/ledgercore/statedelta_test.go
  ledger/txtail_test.go
Labels: Enhancement, Team Carbon-11

#4750 Tech Debt: Reduce number of dependencies.
  go.mod
  go.sum
  tools/debug/doberman/logo.go
  tools/debug/doberman/main.go
Labels: Enhancement, Team Lamprey

#4684 algod: Migrate internal uses of v1 algod API to v2
  cmd/algoh/blockWatcher.go
  cmd/algoh/blockWatcher_test.go
  cmd/algoh/blockstats.go
  cmd/algoh/blockstats_test.go
  cmd/algoh/client.go
  cmd/algoh/deadman.go
  cmd/algoh/mockClient.go
  cmd/goal/account.go
  cmd/goal/application.go
  cmd/goal/asset.go
  cmd/goal/clerk.go
  cmd/goal/interact.go
  cmd/goal/ledger.go
  cmd/goal/node.go
  cmd/loadgenerator/main.go
  daemon/algod/api/client/restClient.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/utils.go
  libgoal/libgoal.go
  libgoal/transactions.go
  shared/pingpong/accounts.go
  shared/pingpong/pingpong.go
  test/e2e-go/cli/goal/clerk_test.go
  test/e2e-go/features/accountPerf/sixMillion_test.go
  test/e2e-go/features/devmode/devmode_test.go
  test/e2e-go/features/participation/onlineOfflineParticipation_test.go
  test/e2e-go/features/participation/overlappingParticipationKeys_test.go
  test/e2e-go/features/participation/participationExpiration_test.go
  test/e2e-go/features/participation/participationRewards_test.go
  test/e2e-go/features/stateproofs/stateproofs_test.go
  test/e2e-go/features/transactions/accountv2_test.go
  test/e2e-go/features/transactions/asset_test.go
  test/e2e-go/features/transactions/onlineStatusChange_test.go
  test/e2e-go/features/transactions/proof_test.go
  test/e2e-go/features/transactions/sendReceive_test.go
  test/e2e-go/perf/basic_test.go
  test/e2e-go/restAPI/restClient_test.go
  test/e2e-go/stress/transactions/createManyAndGoOnline_test.go
  test/e2e-go/upgrades/application_support_test.go
  test/e2e-go/upgrades/stateproof_participation_test.go
  test/framework/fixtures/libgoalFixture.go
  test/framework/fixtures/restClientFixture.go
  test/scripts/e2e_subs/e2e-app-simple.sh
Labels: Enhancement

#4741 Tests: Add test defending against regression in testnet genesis generation
  gen/generate_test.go
Labels: Skip-Release-Notes

#4751 tests: Fix account tests for calling pending txn endpoint and box tests
  cmd/goal/box.go
  test/e2e-go/features/transactions/accountv2_test.go
Labels: Skip-Release-Notes

#4731 goal: Add URL to goal asset info.
  cmd/goal/asset.go
  test/scripts/e2e_subs/app-assets.sh
Labels: Enhancement, Team Lamprey

#4617 performance: turn cache misses during assembly into cache hits during eval
  ledger/acctupdates.go
  ledger/evalindexer.go
  ledger/internal/eval.go
  ledger/internal/eval_test.go
  ledger/internal/prefetcher/prefetcher_alignment_test.go
  ledger/ledger.go
  ledger/lruaccts.go
  ledger/lruresources.go
  shared/pingpong/config.go
  shared/pingpong/pingpong.go
Labels: Enhancement, Team Carbon-11

#4746 Testing: Lint for unparallelized tests without explicit reason
  .golangci.yml
  data/transactions/logic/assembler_test.go
  data/transactions/logic/evalAppTxn_test.go
Labels: Enhancement

#4755 daemon: pool error messages and old txn expiration
  daemon/algod/api/server/v2/handlers.go
Labels: Team Carbon-11, Bug-Fix

#4754 Tests: Fix types in assertions and change to using libgoal client when getting `PendingTransaction` information
  test/e2e-go/features/participation/participationExpiration_test.go
  test/framework/fixtures/restClientFixture.go
Labels: Bug-Fix

#4733 StateProofs: Use stateproof tracker
  cmd/tealdbg/localLedger.go
  config/consensus.go
  daemon/algod/api/server/v2/dryrun.go
  ledger/acctupdates.go
  ledger/apply/apply.go
  ledger/apply/stateproof.go
  ledger/evalindexer.go
  ledger/internal/appcow_test.go
  ledger/internal/cow.go
  ledger/internal/cow_test.go
  ledger/internal/eval.go
  ledger/internal/eval_test.go
  ledger/internal/prefetcher/prefetcher_alignment_test.go
  ledger/ledger_test.go
  ledger/ledgercore/msgp_gen.go
  ledger/ledgercore/stateproofverification.go
  ledger/stateproofverificationtracker.go
  stateproof/verify/stateproof.go
  stateproof/verify/stateproof_test.go
  test/e2e-go/features/stateproofs/stateproofs_test.go
Labels: Team Sphinx

#4758 goal: Change asset commands to use AccountAssetInformation
  cmd/goal/asset.go
  libgoal/libgoal.go
  libgoal/transactions.go
  test/scripts/e2e_subs/asset-misc.sh
Labels: Bug-Fix

#4736 DevOps: Update minor version number from 3.11 to 3.12
  buildnumber.dat
Labels: Enhancement

#4707 API: Update oapi-codegen version to v1.12.0 of our fork
  cmd/goal/account.go
  daemon/algod/api/Makefile
  daemon/algod/api/generated_server.yml
  daemon/algod/api/generated_types.yml
  daemon/algod/api/private_server.yml
  daemon/algod/api/private_types.yml
  daemon/algod/api/server/v2/account.go
  daemon/algod/api/server/v2/generated/private/routes.go
  daemon/algod/api/server/v2/generated/private/types.go
  daemon/algod/api/server/v2/generated/routes.go
  daemon/algod/api/server/v2/generated/types.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_resources_test.go
  daemon/algod/api/server/v2/test/handlers_test.go
  daemon/algod/api/server/v2/utils.go
  go.mod
  go.sum
  scripts/buildtools/versions
  shared/pingpong/accounts.go
  test/e2e-go/features/accountPerf/sixMillion_test.go
  test/e2e-go/features/transactions/asset_test.go
  test/framework/fixtures/libgoalFixture.go
  test/scripts/e2e_subs/rest-applications-endpoint.sh
  test/scripts/e2e_subs/rest-assets-endpoint.sh
Labels: Enhancement, tech debt

#4771 Tests: Move box test artifacts to a temp directory
  test/scripts/e2e_subs/box-search.sh
Labels: Enhancement

#4767 algod: Delete v1 usage from client and remove `V2` prefix from APIs
  cmd/goal/account.go
  cmd/goal/application.go
  cmd/goal/asset.go
  cmd/goal/clerk.go
  cmd/loadgenerator/main.go
  daemon/algod/api/client/restClient.go
  libgoal/libgoal.go
  libgoal/transactions.go
  shared/pingpong/accounts.go
  shared/pingpong/pingpong.go
  test/e2e-go/features/accountPerf/sixMillion_test.go
  test/e2e-go/features/participation/onlineOfflineParticipation_test.go
  test/e2e-go/features/participation/overlappingParticipationKeys_test.go
  test/e2e-go/features/participation/participationExpiration_test.go
  test/e2e-go/features/participation/participationRewards_test.go
  test/e2e-go/features/stateproofs/stateproofs_test.go
  test/e2e-go/features/transactions/accountv2_test.go
  test/e2e-go/features/transactions/app_pages_test.go
  test/e2e-go/features/transactions/asset_test.go
  test/e2e-go/features/transactions/onlineStatusChange_test.go
  test/e2e-go/features/transactions/sendReceive_test.go
  test/e2e-go/restAPI/restClient_test.go
  test/e2e-go/stress/transactions/createManyAndGoOnline_test.go
  test/framework/fixtures/restClientFixture.go
Labels: Enhancement

#4780 StateProofs: Sp verification-tracker last lookup cache
  ledger/stateproofverificationtracker.go
  ledger/stateproofverificationtracker_test.go
Labels: Team Sphinx

#4779 netgoal: start with at least 20GB RootStorage
  netdeploy/remote/deployedNetwork.go
Labels: Enhancement, unplanned, Team Hyper Flow

#4782 Docs: Update SECURITY.md
  SECURITY.md
Labels: documentation, Enhancement

#4784 tests: Fix resolver test endpoint
  tools/network/resolver_test.go
Labels: Bug-Fix

#4714 algod: Consolidate models
  cmd/algoh/client.go
  cmd/algoh/mockClient.go
  cmd/goal/account.go
  cmd/goal/accountsList.go
  cmd/goal/clerk.go
  cmd/goal/node.go
  cmd/loadgenerator/main.go
  cmd/tealdbg/dryrunRequest.go
  cmd/tealdbg/localLedger.go
  daemon/algod/api/Makefile
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/client/restClient.go
  daemon/algod/api/server/router.go
  daemon/algod/api/server/v2/account.go
  daemon/algod/api/server/v2/account_test.go
  daemon/algod/api/server/v2/dryrun.go
  daemon/algod/api/server/v2/dryrun_test.go
  daemon/algod/api/server/v2/generated/model/model_types.yml
  daemon/algod/api/server/v2/generated/model/types.go
  daemon/algod/api/server/v2/generated/nonparticipating/private/private_routes.yml
  daemon/algod/api/server/v2/generated/nonparticipating/private/routes.go
  daemon/algod/api/server/v2/generated/nonparticipating/public/public_routes.yml
  daemon/algod/api/server/v2/generated/nonparticipating/public/routes.go
  daemon/algod/api/server/v2/generated/participating/private/private_routes.yml
  daemon/algod/api/server/v2/generated/participating/private/routes.go
  daemon/algod/api/server/v2/generated/participating/public/public_routes.yml
  daemon/algod/api/server/v2/generated/participating/public/routes.go
  daemon/algod/api/server/v2/generated/private/routes.go
  daemon/algod/api/server/v2/generated/private/types.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_resources_test.go
  daemon/algod/api/server/v2/test/handlers_test.go
  daemon/algod/api/server/v2/test/helpers.go
  daemon/algod/api/server/v2/utils.go
  libgoal/libgoal.go
  libgoal/participation.go
  libgoal/transactions.go
  netdeploy/network.go
  shared/pingpong/accounts.go
  shared/pingpong/pingpong.go
  test/e2e-go/features/accountPerf/sixMillion_test.go
  test/e2e-go/features/catchup/catchpointCatchup_test.go
  test/e2e-go/features/participation/accountParticipationTransitions_test.go
  test/e2e-go/features/stateproofs/stateproofs_test.go
  test/e2e-go/features/transactions/asset_test.go
  test/e2e-go/features/transactions/sendReceive_test.go
  test/e2e-go/perf/basic_test.go
  test/e2e-go/restAPI/restClient_test.go
  test/framework/fixtures/libgoalFixture.go
  test/framework/fixtures/restClientFixture.go
Labels: Enhancement

#4770 StateProofs: Limit builders memory usage and reduce StateProofs signatures spam
  data/basics/units.go
  stateproof/builder.go
  stateproof/db.go
  stateproof/db_test.go
  stateproof/signer.go
  stateproof/worker.go
  stateproof/worker_test.go
Labels: Team Sphinx

#4791 CI: Notify when GHA workflow fails on master
  .github/workflows/benchmarks.yml
  .github/workflows/build.yml
  .github/workflows/codegen_verification.yml
  .github/workflows/reviewdog.yml
Labels: Enhancement

#4789 CI: Notify when CircleCI build failures for master and rel branches only
  .circleci/config.yml
Labels: Enhancement

#4792 Tests: Fix txid-string comparison
  test/e2e-go/features/transactions/accountv2_test.go
  test/e2e-go/upgrades/application_support_test.go
Labels: Enhancement

#4811 mergeback: Relstable3.11.3 remerge
  network/topics.go
Labels: Team Hyper Flow, Skip-Release-Notes

#4745 telemetry: add TCP RTT info collection
  logging/telemetryspec/event.go
  network/limitlistener/rejectingLimitListener.go
  network/requestTracker.go
  network/wsNetwork.go
  network/wsNetwork_test.go
  network/wsPeer.go
  util/tcpinfo.go
  util/tcpinfo_darwin.go
  util/tcpinfo_linux.go
  util/tcpinfo_noop.go
Labels: Enhancement

#4786 txHandler: add more metric
  data/transactions/verify/txn.go
  data/txHandler.go
  data/txHandler_test.go
  logging/telemetryspec/event.go
  network/wsNetwork.go
  network/wsNetwork_test.go
  network/wsPeer.go
  util/metrics/metrics.go
Labels: Enhancement, Team Carbon-11

#4795 metrics: split out /Transaction/AssembleBlock metrics
  data/pools/transactionPool.go
  ledger/ledgercore/error.go
  logging/telemetryspec/metric.go
Labels: Enhancement, Team Carbon-11

#4772 test: large generated accountdb cluster test
  cmd/netgoal/network.go
  netdeploy/remote/deployedNetwork.go
  netdeploy/remote/deployedNetwork_test.go
  test/heapwatch/block_history_plot.py
  test/heapwatch/heapWatch.py
  test/testdata/deployednettemplates/recipes/bootstrappedScenario/Makefile
  test/testdata/deployednettemplates/recipes/bootstrappedScenario/boostrappedFile.json
  test/testdata/deployednettemplates/recipes/bootstrappedScenario/gen_topology.py
  test/testdata/deployednettemplates/recipes/bootstrappedScenario/genesis.json
  test/testdata/deployednettemplates/recipes/bootstrappedScenario/net.json
  test/testdata/deployednettemplates/recipes/bootstrappedScenario/node.json
  test/testdata/deployednettemplates/recipes/bootstrappedScenario/nonPartNode.json
  test/testdata/deployednettemplates/recipes/bootstrappedScenario/topology.json
  test/testdata/deployednettemplates/recipes/scenario1s/Makefile
  test/testdata/deployednettemplates/recipes/scenario1s/gen_topology.py
  test/testdata/deployednettemplates/recipes/scenario1s/genesis.json
  test/testdata/deployednettemplates/recipes/scenario1s/net.json
  test/testdata/deployednettemplates/recipes/scenario1s/node.json
  test/testdata/deployednettemplates/recipes/scenario1s/relay.json
  test/testdata/deployednettemplates/recipes/scenario1s/topology.json
Labels: Enhancement, Team Carbon-11

#4804 cow: always process KvMods to add OldData to mods when building StateDeltas
  ledger/accountdb.go
  ledger/acctupdates_test.go
  ledger/boxtxn_test.go
  ledger/catchpointtracker.go
  ledger/internal/cow.go
Labels: Team Scytale, Bug-Fix

#4812 Catchpoints: Add the kv hashes into the trie
  ledger/catchpointtracker.go
Labels: Bug-Fix

#4768 txSyncer: service does not start after node catching up
  catchup/service.go
  rpcs/txService_test.go
  rpcs/txSyncer.go
  rpcs/txSyncer_test.go
  test/e2e-go/features/catchup/catchpointCatchup_test.go
Labels: Team Carbon-11, Bug-Fix

#4810 CI: Fix GHA failure notification trigger condition
  .github/workflows/benchmarks.yml
  .github/workflows/build.yml
  .github/workflows/codegen_verification.yml
  .github/workflows/reviewdog.yml
Labels: Bug-Fix

#4808 Catchpoints: Enrich catchpoint generation and status with KV metadata
  catchup/catchpointService.go
  cmd/catchpointdump/file.go
  cmd/goal/messages.go
  cmd/goal/node.go
  components/mocks/mockCatchpointCatchupAccessor.go
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/model/types.go
  daemon/algod/api/server/v2/generated/nonparticipating/private/routes.go
  daemon/algod/api/server/v2/generated/nonparticipating/public/routes.go
  daemon/algod/api/server/v2/generated/participating/private/routes.go
  daemon/algod/api/server/v2/generated/participating/public/routes.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_test.go
  daemon/algod/api/server/v2/test/helpers.go
  ledger/accountdb.go
  ledger/catchpointfileheader.go
  ledger/catchpointtracker.go
  ledger/catchpointtracker_test.go
  ledger/catchpointwriter.go
  ledger/catchupaccessor.go
  ledger/catchupaccessor_test.go
  ledger/hashkind_string.go
  ledger/msgp_gen.go
  logging/telemetryspec/event.go
  node/node.go
Labels: Enhancement

#4814 Tests: Squelch macOS accept incoming network connections notifications
  catchup/fetcher_test.go
  rpcs/txService_test.go
  util/metrics/counter_test.go
  util/metrics/gauge_test.go
Labels: Enhancement

#4822 accountdb: add migration 8 for resetting accounthashes on betanet
  ledger/accountdb.go
  ledger/catchupaccessor.go
  ledger/ledger_test.go
  ledger/trackerdb.go
Labels: Enhancement

#4776 refactor: start moving pieces of `accountdb.go` into a storage package
  Makefile
  ledger/accountdb.go
  ledger/accountdb_test.go
  ledger/acctonline.go
  ledger/acctonline_test.go
  ledger/acctupdates.go
  ledger/acctupdates_test.go
  ledger/applications_test.go
  ledger/blockdb_test.go
  ledger/catchpointtracker.go
  ledger/catchpointtracker_test.go
  ledger/catchupaccessor_test.go
  ledger/lruaccts.go
  ledger/lruaccts_test.go
  ledger/lrukv.go
  ledger/lrukv_test.go
  ledger/lruonlineaccts.go
  ledger/lruonlineaccts_test.go
  ledger/lruresources.go
  ledger/lruresources_test.go
  ledger/msgp_gen.go
  ledger/msgp_gen_test.go
  ledger/onlineaccountscache.go
  ledger/onlineaccountscache_test.go
  ledger/persistedaccts_list.go
  ledger/persistedaccts_list_test.go
  ledger/persistedonlineaccts_list.go
  ledger/persistedonlineaccts_list_test.go
  ledger/store/data.go
  ledger/store/data_test.go
  ledger/store/interface.go
  ledger/store/msgp_gen.go
  ledger/store/msgp_gen_test.go
  ledger/store/sql.go
  ledger/store/sql_test.go
  ledger/store/testing/helpers.go
  ledger/tracker.go
Labels: quality, Team Carbon-11, Skip-Release-Notes

#4828 go-algorand v3.12.2-beta
  buildnumber.dat
  network/wsNetwork_test.go
Labels: Team Hyper Flow

#4813 ledger: move catchpoint sql code into storage package
  ledger/accountdb.go
  ledger/accountdb_test.go
  ledger/catchpointtracker.go
  ledger/catchpointtracker_test.go
  ledger/catchupaccessor.go
  ledger/msgp_gen.go
  ledger/store/catchpoint.go
  ledger/store/interface.go
  ledger/trackerdb.go
Labels: Team Carbon-11, Skip-Release-Notes

#4821 Catchpoint: Add context to block mismatch error in VerifyCatchpoint
  ledger/catchupaccessor.go
Labels: Enhancement

#4766 performance: Implement sync.Pool for cow.child()
  ledger/internal/appcow.go
  ledger/internal/cow.go
  ledger/internal/cow_test.go
  ledger/internal/eval.go
  ledger/ledgercore/statedelta.go
  ledger/ledgercore/statedelta_test.go
Labels: Enhancement

#4830 ledger: move non-lookup methods into a storage package
  ledger/accountdb.go
  ledger/accountdb_test.go
  ledger/acctonline.go
  ledger/acctonline_test.go
  ledger/acctupdates.go
  ledger/acctupdates_test.go
  ledger/catchpointtracker.go
  ledger/catchpointwriter.go
  ledger/catchpointwriter_test.go
  ledger/catchupaccessor.go
  ledger/msgp_gen.go
  ledger/msgp_gen_test.go
  ledger/store/accountsV2.go
  ledger/store/accountsV2_test.go
  ledger/store/data.go
  ledger/store/msgp_gen.go
  ledger/store/msgp_gen_test.go
  ledger/tracker.go
  ledger/trackerdb.go
  ledger/txtail.go
  ledger/txtail_test.go
  util/db/interfaces.go
Labels: Team Carbon-11, Skip-Release-Notes

#4833 metrics: count large txn groups and msigs
  crypto/batchverifier.go
  data/transactions/verify/txn.go
  data/txHandler.go
  util/metrics/metrics.go
Labels: Team Carbon-11, Skip-Release-Notes

#4824 node: Fix disabled node tests
  node/node_test.go
Labels: Enhancement

#4835 refactor: `accountdb.go` into a `store` package (4 of N)
  cmd/catchpointdump/database.go
  cmd/catchpointdump/file.go
  ledger/accountdb.go
  ledger/accountdb_test.go
  ledger/acctonline.go
  ledger/acctonline_test.go
  ledger/acctupdates_test.go
  ledger/catchpointtracker.go
  ledger/catchpointtracker_test.go
  ledger/catchpointwriter_test.go
  ledger/catchupaccessor.go
  ledger/msgp_gen.go
  ledger/msgp_gen_test.go
  ledger/store/accountsV2.go
  ledger/store/catchpoint.go
  ledger/store/interface.go
  ledger/store/merkle_commiter.go
  ledger/store/msgp_gen.go
  ledger/store/msgp_gen_test.go
  ledger/trackerdb.go
Labels: Team Carbon-11, Skip-Release-Notes

#4838 Bug-Fix: upgrade avm-abi
  go.mod
  go.sum
Labels: Bug-Fix, dependencies

#4818 Tests: Extend TestCatchpointAfterTxns to catch catchpoint write corruption
  ledger/accountdb.go
  ledger/catchpointwriter_test.go
Labels: Enhancement

#4840 Catchpoint: Fix broken merge between #4818 and #4835
  ledger/catchpointwriter_test.go
Labels: Bug-Fix

#4843 CICD: go-algorand relstable3.12.2-remerge mergeback
  config/version.go
Labels: Team Hyper Flow, Skip-Release-Notes
