Repository algorand/go-algorand, pull requests merged in 2022-10, with the labels that each got.

#4613 tools: fix lagging cinfo.AppParams data structure in PingPong
  shared/pingpong/accounts.go
Labels: Bug-Fix

#4625 CICD: reduce mmnet LastPartKeyRound to 50k
  test/testdata/deployednettemplates/recipes/mmnet/genesis.json
Labels: Enhancement

#4623 testing: extend transactions signature verification testing
  data/transactions/verify/txn_test.go
Labels: Enhancement, Team Carbon-11

#4606 metrics: Remove labels from gauge metrics
  ledger/metrics.go
  network/wsNetwork.go
  node/node.go
  util/metrics/gauge.go
  util/metrics/gauge_test.go
Labels: Enhancement

#4614 Batch-verify: Return failed sig indexes
  crypto/batchverifier.go
  crypto/batchverifier_test.go
  crypto/onetimesig.go
Labels: Enhancement, Team Carbon-11

#4511 tests: extend pingpong to generate box workload
  cmd/pingpong/README.md
  cmd/pingpong/runCmd.go
  shared/pingpong/accounts.go
  shared/pingpong/config.go
  shared/pingpong/pingpong.go
Labels: Enhancement

#4588 DEVOPS: Update betanet model recipe, move NPN hosts to regions not shared by hosts for relays and nodes
  test/testdata/deployednettemplates/hosttemplates/hosttemplates.json
  test/testdata/deployednettemplates/recipes/betanet-model-2/Makefile
  test/testdata/deployednettemplates/recipes/betanet-model-2/gen_extra_npn_nodes.py
  test/testdata/deployednettemplates/recipes/betanet-model-2/gen_topology.py
  test/testdata/deployednettemplates/recipes/betanet-model-2/genesis.json
  test/testdata/deployednettemplates/recipes/betanet-model-2/net-extension.json
  test/testdata/deployednettemplates/recipes/betanet-model-2/net.json
  test/testdata/deployednettemplates/recipes/betanet-model-2/topology.json
Labels: Enhancement, Team Hyper Flow

#4589 network: proposal payload compression
  go.mod
  go.sum
  network/msgCompressor.go
  network/msgCompressor_test.go
  network/wsNetwork.go
  network/wsNetwork_test.go
  network/wsPeer.go
  network/wsPeer_test.go
Labels: Enhancement, Team Carbon-11

#4650 network: compression followup fixes
  network/msgCompressor.go
  network/wsNetwork.go
Labels: Team Carbon-11, Skip-Release-Notes

#4651 go-algorand 3.11.0-beta Release PR
  cmd/goal/application.go
  config/version.go
  crypto/batchverifier.go
  crypto/batchverifier_test.go
  crypto/onetimesig.go
  daemon/kmd/README.md
  data/transactions/verify/txn_test.go
  go.mod
  go.sum
  ledger/metrics.go
  network/msgCompressor.go
  network/msgCompressor_test.go
  network/wsNetwork.go
  network/wsNetwork_test.go
  network/wsPeer.go
  network/wsPeer_test.go
  node/node.go
  shared/pingpong/accounts.go
  test/testdata/deployednettemplates/hosttemplates/hosttemplates.json
  test/testdata/deployednettemplates/recipes/betanet-model-2/Makefile
  test/testdata/deployednettemplates/recipes/betanet-model-2/gen_extra_npn_nodes.py
  test/testdata/deployednettemplates/recipes/betanet-model-2/gen_topology.py
  test/testdata/deployednettemplates/recipes/betanet-model-2/genesis.json
  test/testdata/deployednettemplates/recipes/betanet-model-2/net-extension.json
  test/testdata/deployednettemplates/recipes/betanet-model-2/net.json
  test/testdata/deployednettemplates/recipes/betanet-model-2/topology.json
  test/testdata/deployednettemplates/recipes/mmnet/genesis.json
  util/metrics/gauge.go
  util/metrics/gauge_test.go
Labels: Skip-Release-Notes

#4662 pingpong: fix config check for GeneratedAccountsMnemonics
  cmd/pingpong/runCmd.go
Labels: Bug-Fix

#4668 catchpoints: don't make duplicate account hashes in prepareNormalizedBalances
  ledger/accountdb.go
  ledger/catchpointwriter_test.go
  ledger/catchupaccessor.go
  ledger/catchupaccessor_test.go
Labels: Bug-Fix

#4672 batchverifier: preserve the memory until the end
  crypto/batchverifier.go
  crypto/batchverifier_test.go
Labels: Bug-Fix

#4553 Persist StateProof builders on disk
  crypto/stateproof/builder.go
  crypto/stateproof/builder_test.go
  crypto/stateproof/msgp_gen.go
  crypto/stateproof/msgp_gen_test.go
  node/node.go
  stateproof/builder.go
  stateproof/db.go
  stateproof/db_test.go
  stateproof/msgp_gen.go
  stateproof/msgp_gen_test.go
  stateproof/signer.go
  stateproof/worker.go
  stateproof/worker_test.go
Labels: Enhancement, New Feature

#4570 State Proof Recoverability: state proof verification tracking
  ledger/accountdb.go
  ledger/ledger.go
  ledger/ledger_test.go
  ledger/ledgercore/msgp_gen.go
  ledger/ledgercore/msgp_gen_test.go
  ledger/ledgercore/stateproofverification.go
  ledger/stateproofverificationtracker.go
  ledger/stateproofverificationtracker_test.go
  ledger/tracker.go
  ledger/trackerdb.go
  scripts/dump_genesis.sh
Labels: Team Sphinx, New Feature

#4633 API: bump max size of teal source and dryrun
  daemon/algod/api/server/v2/handlers.go
Labels: Enhancement

#4652 Perf test: Transaction group handle/verify
  data/txHandler.go
  data/txHandler_test.go
Labels: test, Team Carbon-11, New Feature

#4656 Netgoal: Update netgoal generate flags and variables
  cmd/netgoal/README.md
  cmd/netgoal/generate.go
  test/testdata/deployednettemplates/generate-recipe/generate_network.py
  test/testdata/deployednettemplates/recipes/README.md
  test/testdata/deployednettemplates/recipes/alphanet-extension/Makefile
  test/testdata/deployednettemplates/recipes/alphanet/Makefile
  test/testdata/deployednettemplates/recipes/betanet-model-2/Makefile
  test/testdata/deployednettemplates/recipes/bootstrappedScenario/Makefile
  test/testdata/deployednettemplates/recipes/custom/README.md
  test/testdata/deployednettemplates/recipes/custom/example/network_templates/c5dmachines.json
  test/testdata/deployednettemplates/recipes/custom/example/network_templates/network-tpl.json
  test/testdata/deployednettemplates/recipes/custom/network_templates/network-tpl.json
  test/testdata/deployednettemplates/recipes/mainnet-model/network-tpl.json
  test/testdata/deployednettemplates/recipes/mmnet/Makefile
  test/testdata/deployednettemplates/recipes/network-partition/Makefile
  test/testdata/deployednettemplates/recipes/scenario1/Makefile
  test/testdata/deployednettemplates/recipes/scenario1s/Makefile
  test/testdata/deployednettemplates/recipes/scenario2/Makefile
  test/testdata/deployednettemplates/recipes/scenario3/Makefile
  test/testdata/deployednettemplates/recipes/scenario3s/Makefile
  test/testdata/deployednettemplates/recipes/txnsync/Makefile
Labels: Enhancement

#4601 Algod: state-proof key deletion safety
  data/account/participationRegistry.go
  data/accountManager.go
  data/accountManager_test.go
  stateproof/abstractions.go
  stateproof/builder.go
  stateproof/signer.go
  stateproof/stateproofMessageGenerator_test.go
  stateproof/worker.go
  stateproof/worker_test.go
Labels: Team Sphinx, Bug-Fix

#4639 test: 20221012 improvements
  config/localTemplate.go
  config/local_defaults.go
  installer/config.json.example
  logging/usage.go
  node/node.go
  test/heapwatch/block_history.py
  test/heapwatch/block_history_plot.py
  test/heapwatch/metrics_delta.py
  test/testdata/configs/config-v24.json
Labels: Enhancement, Team Carbon-11

#4645 AVM: match, pushints, and pushbytess opcodes
  data/transactions/logic/README.md
  data/transactions/logic/TEAL_opcodes.md
  data/transactions/logic/assembler.go
  data/transactions/logic/assembler_test.go
  data/transactions/logic/doc.go
  data/transactions/logic/eval.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/frames.go
  data/transactions/logic/langspec.json
  data/transactions/logic/opcodes.go
  data/transactions/logic/teal.tmLanguage.json
Labels: New Feature

#4702 network: align duplicateFilterCount to prevent panic on 32-bit platforms
  logging/telemetryspec/event.go
  network/wsPeer.go
  network/wsPeer_test.go
Labels: Bug-Fix

#4697 Bug-fix: return v2 spec from swagger endpoint
  daemon/algod/api/server/common/handlers.go
  daemon/algod/api/swagger.go
Labels: Bug-Fix

#4704 telemetry: add CatchpointRootUpdateEvent
  ledger/catchpointtracker.go
  logging/telemetryspec/event.go
Labels: Enhancement

#4706 performance: don't create child cow in TestTransactionGroup
  ledger/internal/eval.go
Labels: Enhancement

#4712 Util: Print dbutil.go error in stderr
  util/db/dbutil.go
Labels: Skip-Release-Notes

#4644 performance: Agreement state serialization using msgp
  agreement/actions.go
  agreement/actiontype_string.go
  agreement/asyncVoteVerifier.go
  agreement/bundle.go
  agreement/cryptoVerifier.go
  agreement/cryptoVerifier_test.go
  agreement/demux.go
  agreement/errors.go
  agreement/events.go
  agreement/events_test.go
  agreement/eventtype_string.go
  agreement/message.go
  agreement/message_test.go
  agreement/msgp_gen.go
  agreement/msgp_gen_test.go
  agreement/persistence.go
  agreement/persistence_test.go
  agreement/player.go
  agreement/player_permutation_test.go
  agreement/player_test.go
  agreement/proposalManager.go
  agreement/proposalStore.go
  agreement/proposalTable.go
  agreement/proposalTable_test.go
  agreement/proposalTracker.go
  agreement/proposalTrackerContract.go
  agreement/pseudonode.go
  agreement/router.go
  agreement/service.go
  agreement/sort.go
  agreement/sort_test.go
  agreement/voteAggregator.go
  agreement/voteAggregator_test.go
  agreement/voteAuxiliary.go
  agreement/voteTracker.go
  agreement/voteTrackerContract.go
  go.mod
  go.sum
  protocol/codec_tester.go
  scripts/buildtools/versions
Labels: Enhancement, Team Carbon-11

#4352 prefetcher: enable prefetcher for assets and apps
  ledger/internal/eval.go
  ledger/internal/prefetcher/prefetcher.go
  ledger/internal/prefetcher/prefetcher_alignment_test.go
  ledger/internal/prefetcher/prefetcher_test.go
  test/e2e-go/features/transactions/accountv2_test.go
Labels: Enhancement, Team Carbon-11
