Repository algorand/go-algorand, pull requests merged in 2022-03, with the labels that each got.

#3702 unlimited assets : fix bug in AccountApplicationInformation handler
  daemon/algod/api/server/v2/handlers.go
Labels: Team Carbon-11

#3704 Enhancement: Document instructions for updating Indexer E2E test input
  test/README.md
Labels: Enhancement, Team Scytale

#3706 go-algorand relstable3.4.2-remerge
  config/version.go
  scripts/release/mule/Makefile.mule
Labels: Team Hyper Flow

#3647 Algod: refactor registry operations
  data/account/participationRegistry.go
  data/account/participationRegistry_test.go
  data/account/registeryDbOps.go
Labels: Enhancement, Team Sphinx

#3707 REST API: fix check for record.AppParams in AccountApplicationInformation
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_resources_test.go
Labels: Team Carbon-11, Bug-Fix

#3622 Add forward secrecy to State Proofs (WIP: SP key deletion)
  compactcert/abstractions.go
  compactcert/builder.go
  compactcert/signer.go
  compactcert/worker_test.go
  crypto/compactcert/builder.go
  crypto/compactcert/builder_test.go
  data/account/participationRegistry.go
  data/account/participationRegistry_test.go
  data/account/registeryDbOps.go
  data/accountManager.go
  node/node.go
Labels: Enhancement, Team Sphinx

#3703 agreement: Add validatedAt to proposal type and BlockAcceptedEventDetails message
  agreement/actions.go
  agreement/agreementtest/simulate.go
  agreement/demux.go
  agreement/demux_test.go
  agreement/events.go
  agreement/msgp_gen.go
  agreement/proposal.go
  agreement/service_test.go
  logging/telemetryspec/event.go
  util/timers/frozen.go
  util/timers/interface.go
  util/timers/monotonic.go
Labels: Enhancement, Team Carbon-11

#3711 fast catchup: retry peers fetching
  catchup/catchpointService.go
Labels: Team Carbon-11, Bug-Fix

#3710 testing: fix TestAssetConfig test to support unlimited assets
  test/e2e-go/features/transactions/asset_test.go
Labels: Team Carbon-11, Bug-Fix

#3712 agreement: add messagesHandled/Dropped TagCounters
  agreement/gossip/network.go
Labels: Enhancement

#3708 ledger: replace Ledger.LookupResource with Lookup{Application,Asset}
  cmd/tealdbg/localLedger.go
  daemon/algod/api/server/v1/handlers/handlers.go
  daemon/algod/api/server/v2/dryrun.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_resources_test.go
  daemon/algod/api/spec/v2/model.go
  ledger/acctupdates.go
  ledger/applications_test.go
  ledger/evalindexer.go
  ledger/evalindexer_test.go
  ledger/internal/appcow_test.go
  ledger/internal/eval.go
  ledger/internal/eval_test.go
  ledger/internal/evalprefetcher.go
  ledger/internal/evalprefetcher_test.go
  ledger/ledger.go
  ledger/ledger_test.go
  ledger/ledgercore/accountresource.go
Labels: Enhancement, Team Carbon-11

#3716 agreement: fix fuzzer test NetworkFacade Clock implementation
  agreement/fuzzer/networkFacade_test.go
Labels: Team Carbon-11, Bug-Fix

#3718 telemetry: Fix version configuration
  logging/telemetry.go
  logging/telemetryhook_test.go
Labels: Bug-Fix

#3729 prefetcher: add Eval vs prefetcher alignment tests
  ledger/internal/eval.go
  ledger/internal/evalprefetcher.go
  ledger/internal/evalprefetcher_alignment_test.go
  ledger/internal/evalprefetcher_test.go
Labels: Enhancement, Team Carbon-11

#3735 ledger: move prefetcher to a new package
  ledger/internal/eval.go
  ledger/internal/prefetcher/prefetcher.go
  ledger/internal/prefetcher/prefetcher_alignment_test.go
  ledger/internal/prefetcher/prefetcher_test.go
  ledger/internal/prefetcher/prefetcher_whitebox_test.go
Labels: Enhancement, Team Carbon-11

#3737 REST API: use ErrorResponse instead of AccountsErrorResponse
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/private/routes.go
  daemon/algod/api/server/v2/generated/private/types.go
  daemon/algod/api/server/v2/generated/routes.go
  daemon/algod/api/server/v2/generated/types.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_resources_test.go
Labels: Enhancement

#3740 prefetcher: ensure the groupTask.incompleteCount is allocated on a 64-bit aligned address
  ledger/internal/prefetcher/prefetcher.go
  ledger/internal/prefetcher/prefetcher_whitebox_test.go
Labels: Team Carbon-11, Bug-Fix

#3514 AVM: FIDO2 OpCodes
  config/consensus.go
  data/transactions/logic/README.md
  data/transactions/logic/TEAL_opcodes.md
  data/transactions/logic/assembler.go
  data/transactions/logic/assembler_test.go
  data/transactions/logic/doc.go
  data/transactions/logic/eval.go
  data/transactions/logic/evalCrypto_test.go
  data/transactions/logic/evalStateful_test.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/fields.go
  data/transactions/logic/fields_string.go
  data/transactions/logic/jsonspec.md
  data/transactions/logic/jsonspec_test.go
  data/transactions/logic/opcodes.go
  go.mod
Labels: Team Scytale, New Feature

#3739 ledger refactoring: test 6M assets/apps per account
  node/node.go
  test/e2e-go/features/accountPerf/sixMillion_test.go
Labels: New Feature

#3749 testing: improve 6M asset testing performance
  test/e2e-go/features/accountPerf/sixMillion_test.go
Labels: Enhancement, Team Carbon-11

#3741 REST API: Fix typo in OpenAPI json and yml files
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/routes.go
Labels: Bug-Fix

#3750 testing: update Test5MAssetsScenario e2e test
  test/e2e-go/features/accountPerf/sixMillion_test.go
Labels: Enhancement, Team Carbon-11

#3759 crypto: call batchVerificationImpl from OneTimeSignatureVerifier.Verify
  crypto/onetimesig.go
  crypto/onetimesig_test.go
Labels: Enhancement

#3736 REST API: dryrun scratch slot type fix
  daemon/algod/api/server/v2/dryrun.go
  daemon/algod/api/server/v2/dryrun_test.go
Labels: Bug-Fix

#3742 Algod: Compcert msg into struct
  Makefile
  compactcert/builder.go
  compactcert/signer.go
  compactcert/worker.go
  compactcert/worker_test.go
  crypto/compactcert/builder.go
  crypto/compactcert/builder_test.go
  crypto/compactcert/common.go
  crypto/compactcert/common_test.go
  crypto/compactcert/msgp_gen.go
  crypto/compactcert/msgp_gen_test.go
  crypto/compactcert/structs.go
  crypto/compactcert/verifier.go
  daemon/algod/api/server/lib/bundledSpecInject.go
  daemon/algod/api/server/v1/handlers/handlers.go
  daemon/algod/api/spec/v1/model.go
  daemon/algod/api/swagger.json
  data/stateproof/message.go
  data/stateproof/msgp_gen.go
  data/stateproof/msgp_gen_test.go
  data/transactions/compactcert.go
  data/transactions/msgp_gen.go
  data/txntest/txn.go
  ledger/internal/compactcert.go
  ledger/internal/compactcert_test.go
  ledger/internal/eval.go
  ledger/internal/eval_test.go
  ledger/ledger.go
  protocol/hash.go
  test/e2e-go/features/compactcert/compactcert_test.go
Labels: Enhancement, Team Sphinx

#3762 AVM: Sha3-256
  THANKS.md
  data/transactions/logic/README.md
  data/transactions/logic/TEAL_opcodes.md
  data/transactions/logic/assembler_test.go
  data/transactions/logic/doc.go
  data/transactions/logic/eval.go
  data/transactions/logic/evalCrypto_test.go
  data/transactions/logic/evalStateful_test.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/opcodes.go
Labels: Enhancement

#3730 Agreement: Add warning when decoding proposal of an unsupported consensus version
  agreement/demux.go
Labels: Team Carbon-11, Bug-Fix

#3218 AVM: opcode for ed25519 verify of arbitrary messages.
  data/transactions/logic/README.md
  data/transactions/logic/TEAL_opcodes.md
  data/transactions/logic/assembler_test.go
  data/transactions/logic/doc.go
  data/transactions/logic/eval.go
  data/transactions/logic/evalCrypto_test.go
  data/transactions/logic/evalStateful_test.go
  data/transactions/logic/opcodes.go
Labels: Enhancement, Team Scytale

#3768 participation key registry : complete cleanup
  components/mocks/mockParticipationRegistry.go
  data/account/participationRegistry.go
  data/account/participationRegistry_test.go
  data/account/participation_test.go
  data/accountManager.go
  data/accountManager_test.go
  node/node.go
  util/db/dbpair.go
  util/db/dbutil.go
Labels: Enhancement, Team Carbon-11

#3771 testing: avoid generating large output on TestDeadlockLogging
  daemon/algod/deadlockLogger.go
Labels: Team Carbon-11, Bug-Fix

#3772 AVM: getbyte and setbyte description to say index must be within length of array
  data/transactions/logic/README.md
  data/transactions/logic/TEAL_opcodes.md
  data/transactions/logic/doc.go
Labels: documentation, Bug-Fix

#3612 AVM: Improve error handling and execution time
  data/transactions/logic/assembler.go
  data/transactions/logic/debugger.go
  data/transactions/logic/eval.go
  data/transactions/logic/evalStateful_test.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/fields.go
  data/transactions/logic/ledger_test.go
  data/transactions/logic/opcodes.go
  ledger/internal/eval_blackbox_test.go
  ledger/internal/txnbench_test.go
Labels: Enhancement, Team Scytale

#3614 Goal: Warn on invalid method signature assembly
  cmd/goal/account.go
  cmd/goal/application.go
  cmd/goal/clerk.go
  cmd/goal/commands.go
  cmd/goal/logging.go
  data/abi/abi_encode.go
  data/abi/abi_type.go
  data/transactions/logic/assembler.go
  data/transactions/logic/assembler_test.go
Labels: Enhancement, Team Scytale

#3773 Goal: Add check for signer passed in the case of logic sig rekeyed account
  cmd/goal/clerk.go
Labels: bug, Bug-Fix

#3784 DevMode: create a block for external txns only
  compactcert/abstractions.go
  compactcert/builder.go
  compactcert/worker_test.go
  node/node.go
Labels: Enhancement, Team Carbon-11

#3770 Ledger: Refactor online totals
  ledger/acctupdates.go
  ledger/acctupdates_test.go
  ledger/catchpointtracker_test.go
  ledger/ledger.go
Labels: Enhancement, Team Carbon-11

#3800 320 rounds: make a separate online accounts tracker
  data/basics/userBalance.go
  ledger/accountdb.go
  ledger/accountdb_test.go
  ledger/acctonline.go
  ledger/acctupdates.go
  ledger/acctupdates_test.go
  ledger/catchpointtracker_test.go
  ledger/ledger.go
  ledger/ledgercore/accountdata.go
  ledger/tracker.go
  ledger/tracker_test.go
  ledger/trackerdb.go
  ledger/voters.go
  scripts/dump_genesis.sh
  test/framework/fixtures/expectFixture.go
Labels: Enhancement, Team Carbon-11

#3804 tests: fix TestAcctUpdateslookupLatestCacheRetry
  ledger/acctupdates_test.go
Labels: Bug-Fix

#3765 Algod: Add a new caching mechanism for the ledger - latest 512 block headers
  ledger/blockHeaderCache.go
  ledger/blockHeaderCache_test.go
  ledger/ledger.go
  ledger/ledger_test.go
Labels: Enhancement, Team Sphinx

#3803 build: compile with golang 1.16
  .circleci/config.yml
  .github/workflows/build.yml
  .github/workflows/reviewdog.yml
  Makefile
  go.mod
  network/dialer.go
  network/rateLimitingTransport.go
  network/wsNetwork.go
  scripts/buildtools/go.mod
  scripts/buildtools/install_buildtools.sh
  scripts/get_golang_version.sh
  scripts/travis/before_build.sh
  shared/pingpong/accounts.go
  shared/pingpong/pingpong.go
  test/e2e-go/features/participation/participationRewards_test.go
  test/scripts/e2e_go_tests.sh
  util/condvar/timedwait.go
  util/sleep.go
  util/sleep_linux.go
Labels: Enhancement, Team Carbon-11

#3805 tealdbg: Replace LocalRunner.Run with LocalRunner.RunAll
  cmd/tealdbg/local.go
  cmd/tealdbg/local_test.go
  go.mod
  go.sum
Labels: Enhancement, Team Scytale

#3816 build: update build dependencies to use go 1.16
  go.mod
  go.sum
  scripts/buildtools/go.mod
  scripts/buildtools/go.sum
Labels: Enhancement, Team Carbon-11

#3826 Bug-Fix: ABI inferToSlice nil testcases
  data/abi/abi_encode_test.go
Labels: Bug-Fix

#3819 KMD: use updated karalabe lib
  daemon/kmd/wallet/driver/ledger.go
  daemon/kmd/wallet/driver/ledger_hid.go
  go.mod
  go.sum
Labels: Enhancement, Team Sphinx

#3728 REST client: always set Exclude value in accountInformationParams
  daemon/algod/api/client/restClient.go
  libgoal/libgoal.go
Labels: Enhancement

#3831 ledger: test OnlineAccountData
  data/ledger_test.go
  ledger/ledger_test.go
  ledger/ledgercore/accountdata.go
Labels: Enhancement, Team Carbon-11

#3834 merge master into feature/320-rounds
  .circleci/config.yml
  .github/workflows/build.yml
  .github/workflows/reviewdog.yml
  Makefile
  cmd/tealdbg/local.go
  cmd/tealdbg/local_test.go
  daemon/algod/api/client/restClient.go
  daemon/kmd/wallet/driver/ledger.go
  daemon/kmd/wallet/driver/ledger_hid.go
  data/abi/abi_encode.go
  data/abi/abi_encode_test.go
  data/ledger_test.go
  go.mod
  go.sum
  ledger/acctupdates.go
  ledger/acctupdates_test.go
  ledger/catchpointtracker_test.go
  ledger/ledger.go
  ledger/ledger_test.go
  ledger/ledgercore/accountdata.go
  libgoal/libgoal.go
  network/dialer.go
  network/rateLimitingTransport.go
  network/wsNetwork.go
  scripts/buildtools/go.mod
  scripts/buildtools/go.sum
  scripts/buildtools/install_buildtools.sh
  scripts/get_golang_version.sh
  scripts/install_linux_deps.sh
  scripts/travis/before_build.sh
  shared/pingpong/accounts.go
  shared/pingpong/pingpong.go
  test/e2e-go/features/participation/participationRewards_test.go
  test/scripts/e2e_go_tests.sh
  util/condvar/timedwait.go
  util/sleep.go
  util/sleep_linux.go
Labels: Enhancement, Team Carbon-11

#3815 prefetcher: improve error codes
  ledger/internal/prefetcher/error.go
  ledger/internal/prefetcher/prefetcher.go
  ledger/internal/prefetcher/prefetcher_alignment_test.go
  ledger/internal/prefetcher/prefetcher_test.go
Labels: Enhancement, Team Carbon-11
