Repository algorand/go-algorand, pull requests merged in 2022-05, with the labels that each got.

#3939 ledger: fix lookupLatest usage of the resources cache
  ledger/acctupdates.go
  ledger/acctupdates_test.go
  ledger/ledgercore/accountresource.go
Labels: Team Carbon-11, Bug-Fix

#3942 Merge master into feature/320-rounds
  ledger/acctupdates.go
  ledger/acctupdates_test.go
  ledger/ledgercore/accountresource.go
Labels: Enhancement, Team Carbon-11

#3888 algod:Stateproof server api
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/private/routes.go
  daemon/algod/api/server/v2/generated/private/types.go
  daemon/algod/api/server/v2/generated/routes.go
  daemon/algod/api/server/v2/generated/types.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_test.go
  daemon/algod/api/server/v2/test/helpers.go
Labels: Team Sphinx

#3940 ABI: Fix typo in abi_type.go
  data/abi/abi_type.go
Labels: Enhancement

#3946 Devops: Fix git safe directory handling
  docker/build/cicd.ubuntu.Dockerfile
Labels: bug, unplanned, Team Hyper Flow

#3944 race condition: Add lock around catchpointsMu to avoid race condition
  ledger/catchpointtracker.go
Labels: Team Lamprey, Bug-Fix

#3921 build: Add install_buildtools.sh to check_deps.sh error message
  scripts/check_deps.sh
Labels: Enhancement

#3948 e2e tests: Fixes for e2e test runs
  test/scripts/e2e.sh
  test/scripts/e2e_client_runner.py
Labels: Bug-Fix

#3949 Tests: Support e2e-go tests when repo is not installed in GOPATH.
  test/framework/fixtures/baseFixture.go
  test/framework/fixtures/expectFixture.go
Labels: Enhancement, Team Lamprey

#3951 320 rounds: more precise online accounts test
  ledger/acctonline_test.go
Labels: Enhancement, Team Carbon-11

#3954 tests: Fix flaky "goal-partkey-commands.sh" integration test.
  test/scripts/e2e_subs/goal-partkey-commands.sh
Labels: Team Lamprey, Bug-Fix

#3927 AVM: Unify inner transaction ID calculation
  config/consensus.go
  data/transactions/logic/eval.go
  data/transactions/logic/evalAppTxn_test.go
  data/transactions/logic/eval_test.go
Labels: Enhancement

#3885 320 rounds: restore voting data in accountbase
  ledger/accountdb.go
  ledger/accountdb_test.go
  ledger/acctupdates.go
  ledger/acctupdates_test.go
  ledger/applications_test.go
  ledger/catchpointwriter_test.go
  ledger/ledger.go
  ledger/msgp_gen.go
  ledger/msgp_gen_test.go
Labels: Enhancement, Team Carbon-11

#3935 320 rounds: expose block header from txtail
  config/consensus.go
  ledger/accountdb.go
  ledger/accountdb_test.go
  ledger/ledger.go
  ledger/ledger_test.go
  ledger/msgp_gen.go
  ledger/tracker.go
  ledger/trackerdb.go
  ledger/txtail.go
  ledger/txtail_test.go
Labels: Enhancement, Team Carbon-11

#3919 build: Bump golang to 1.17.9/Mac M1 Support
  .circleci/config.yml
  .github/workflows/build.yml
  .github/workflows/reviewdog.yml
  Makefile
  agreement/msgp_gen_test.go
  cmd/partitiontest_linter/go.mod
  compactcert/msgp_gen_test.go
  crypto/compactcert/msgp_gen_test.go
  crypto/merklearray/msgp_gen_test.go
  crypto/merklesignature/msgp_gen_test.go
  crypto/msgp_gen_test.go
  crypto/secp256k1/dummy.go
  crypto/secp256k1/libsecp256k1/contrib/dummy.go
  crypto/secp256k1/libsecp256k1/dummy.go
  crypto/secp256k1/libsecp256k1/include/dummy.go
  crypto/secp256k1/libsecp256k1/src/dummy.go
  crypto/secp256k1/libsecp256k1/src/modules/dummy.go
  crypto/secp256k1/libsecp256k1/src/modules/ecdh/dummy.go
  crypto/secp256k1/libsecp256k1/src/modules/recovery/dummy.go
  crypto/secp256k1/panic_cb.go
  crypto/secp256k1/scalar_mult_cgo.go
  crypto/secp256k1/scalar_mult_nocgo.go
  crypto/secp256k1/secp256.go
  daemon/algod/api/spec/v2/msgp_gen_test.go
  data/account/msgp_gen_test.go
  data/basics/msgp_gen_test.go
  data/bookkeeping/msgp_gen_test.go
  data/committee/msgp_gen_test.go
  data/hashable/msgp_gen_test.go
  data/transactions/msgp_gen_test.go
  go.mod
  go.sum
  ledger/ledgercore/msgp_gen_test.go
  ledger/msgp_gen_test.go
  libgoal/lockedFileLinux.go
  libgoal/lockedFileUnix.go
  libgoal/lockedFileWindows.go
  network/messagetracer/graphtrace.go
  node/msgp_gen_test.go
  node/node.go
  nodecontrol/kmdControl_common.go
  protocol/msgp_gen_test.go
  protocol/test/msgp_gen_test.go
  rpcs/msgp_gen_test.go
  scripts/buildtools/go.mod
  scripts/get_golang_version.sh
  tools/network/dnssec/config_unix.go
  tools/network/dnssec/config_unix_test.go
  tools/network/dnssec/config_windows.go
  util/process_common.go
  util/process_windows.go
  util/util.go
Labels: New Feature

#3895 Make stateproof verifier snark friendly
  compactcert/builder.go
  compactcert/worker_test.go
  config/consensus.go
  crypto/compactcert/bigfloat.go
  crypto/compactcert/bigfloat_test.go
  crypto/compactcert/builder.go
  crypto/compactcert/builder_test.go
  crypto/compactcert/coinGenerator.go
  crypto/compactcert/coinGenerator_test.go
  crypto/compactcert/committableSignatureSlot.go
  crypto/compactcert/committableSignatureSlot_test.go
  crypto/compactcert/common.go
  crypto/compactcert/common_test.go
  crypto/compactcert/const.go
  crypto/compactcert/msgp_gen.go
  crypto/compactcert/msgp_gen_test.go
  crypto/compactcert/structs.go
  crypto/compactcert/verifier.go
  crypto/compactcert/verifier_test.go
  crypto/compactcert/weights.go
  crypto/compactcert/weights_test.go
  crypto/falconWrapper.go
  crypto/falconWrapper_test.go
  crypto/merklesignature/kats_test.go
  crypto/merklesignature/merkleSignatureScheme.go
  data/stateproof/message.go
  data/stateproof/msgp_gen.go
  go.mod
  go.sum
  ledger/internal/compactcert.go
  ledger/internal/compactcert_test.go
  ledger/ledger.go
  test/e2e-go/features/compactcert/compactcert_test.go
Labels: Enhancement, Team Sphinx

#3829 StateProofs: New block header field - SHA256 merkle root of the transactions
  agreement/msgp_gen.go
  catchup/fetcher_test.go
  config/consensus.go
  crypto/compactcert/structs.go
  crypto/hashes.go
  crypto/hashes_test.go
  crypto/merklearray/merkle_test.go
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/client/restClient.go
  daemon/algod/api/server/lib/bundledSpecInject.go
  daemon/algod/api/server/v1/handlers/handlers.go
  daemon/algod/api/server/v2/errors.go
  daemon/algod/api/server/v2/generated/private/routes.go
  daemon/algod/api/server/v2/generated/private/types.go
  daemon/algod/api/server/v2/generated/routes.go
  daemon/algod/api/server/v2/generated/types.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_test.go
  daemon/algod/api/spec/v1/model.go
  daemon/algod/api/swagger.json
  data/bookkeeping/block.go
  data/bookkeeping/block_test.go
  data/bookkeeping/genesis.go
  data/bookkeeping/msgp_gen.go
  data/bookkeeping/msgp_gen_test.go
  data/bookkeeping/txn_merkle.go
  data/bookkeeping/txn_merkle_test.go
  data/ledger_test.go
  data/pools/transactionPool_test.go
  data/transactions/signedtxn.go
  data/transactions/transaction.go
  ledger/applications_test.go
  ledger/internal/eval.go
  ledger/ledger_test.go
  ledger/perf_test.go
  ledger/testing/initState.go
  libgoal/libgoal.go
  netdeploy/remote/deployedNetwork.go
  rpcs/blockService_test.go
  test/e2e-go/features/transactions/proof_test.go
  test/testdata/nettemplates/TwoNodes50EachV32.json
Labels: Enhancement

#3968 320 rounds: Fix flaky test
  ledger/acctonline_test.go
Labels: Team Carbon-11, Bug-Fix

#3974 320 rounds: Ledger keyreg test
  ledger/ledger_test.go
  ledger/testing/initState.go
Labels: Team Carbon-11

#3938 algod: Add a sourcemap flag for compile endpoint
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/errors.go
  daemon/algod/api/server/v2/generated/private/routes.go
  daemon/algod/api/server/v2/generated/private/types.go
  daemon/algod/api/server/v2/generated/routes.go
  daemon/algod/api/server/v2/generated/types.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_test.go
Labels: Enhancement, Team Scytale

#3929 Dryrun: Return EvalDeltas for failed executions in Dryrun
  daemon/algod/api/server/v2/dryrun.go
  daemon/algod/api/server/v2/dryrun_test.go
Labels: Enhancement

#3982 algod API: Remove errant base64 docs reference
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/routes.go
Labels: Enhancement

#3882 transaction sync: Transition test
  test/scripts/transition_mix_test.py
  test/testdata/nettemplates/TransitionSix.json
Labels: Enhancement, Team Carbon-11

#3958 cleanup: replace crypto.HashObj(Transaction) with Transaction.ID()
  cmd/goal/clerk.go
  data/transactions/transaction.go
  data/transactions/transaction_test.go
  data/txntest/txn.go
  ledger/internal/eval.go
  libgoal/transactions.go
Labels: Enhancement, tech debt, Team Carbon-11

#3988 TxTail reload test
  ledger/ledger_test.go
  ledger/testing/randomAccounts.go
  ledger/txtail.go
Labels: Team Carbon-11

#3978 CI: ensure msgp generator has been run and is clean
  agreement/msgp_gen.go
  agreement/msgp_gen_test.go
  compactcert/msgp_gen_test.go
  crypto/compactcert/msgp_gen_test.go
  crypto/merklearray/msgp_gen.go
  crypto/merklearray/msgp_gen_test.go
  crypto/merklesignature/msgp_gen.go
  crypto/merklesignature/msgp_gen_test.go
  crypto/msgp_gen_test.go
  daemon/algod/api/spec/v2/msgp_gen.go
  daemon/algod/api/spec/v2/msgp_gen_test.go
  data/account/msgp_gen.go
  data/account/msgp_gen_test.go
  data/basics/msgp_gen.go
  data/basics/msgp_gen_test.go
  data/bookkeeping/msgp_gen.go
  data/bookkeeping/msgp_gen_test.go
  data/committee/msgp_gen_test.go
  data/hashable/msgp_gen_test.go
  data/transactions/msgp_gen.go
  data/transactions/msgp_gen_test.go
  go.mod
  go.sum
  ledger/ledgercore/msgp_gen_test.go
  ledger/msgp_gen.go
  ledger/msgp_gen_test.go
  node/msgp_gen_test.go
  protocol/test/msgp_gen_test.go
  rpcs/msgp_gen_test.go
  scripts/buildtools/go.mod
  scripts/buildtools/go.sum
  scripts/buildtools/install_buildtools.sh
  scripts/buildtools/versions
  scripts/travis/codegen_verification.sh
Labels: Bug-Fix

#3950 PKI: 3924 handle stateproof in rest api goal
  libgoal/libgoal.go
  node/node.go
  test/e2e-go/features/participation/overlappingParticipationKeys_test.go
Labels: Enhancement

#3997 CI: add simple codecov config
  .codecov.yml
Labels: Enhancement

#4008 Merge master into feature/320 rounds
  .codecov.yml
Labels: Team Carbon-11

#4004 Algokey: Add -v flag to get the version
  cmd/algokey/main.go
Labels: Enhancement

#3998 Tools: Add benchmark warnings for PRs and push graphs for commits into master
  .github/workflows/README.md
  .github/workflows/benchmarks.yml
Labels: Enhancement

#4017 ci: use tag to determine channel if possible
  scripts/compute_branch.sh
Labels: Enhancement, Team Lamprey

#4015 AVM: base64_decode can decode padded or unpadded encodings
  data/transactions/logic/eval.go
  data/transactions/logic/eval_test.go
Labels: Enhancement

#4031 320 rounds: txtail review fixes
  ledger/txtail.go
Labels: Team Carbon-11

#3994 AVM: Allow immutable access to foreign app accounts
  data/transactions/logic/README.md
  data/transactions/logic/README_in.md
  data/transactions/logic/eval.go
  data/transactions/logic/evalAppTxn_test.go
  data/transactions/logic/opcodes.go
  ledger/internal/apptxn_test.go
Labels: Enhancement

#4032 Move online queries into onlineAccountsDbQueries
  ledger/accountdb.go
  ledger/accountdb_test.go
  ledger/acctonline.go
Labels: Team Carbon-11

#4013 AVM: Add bn256 pairing opcodes experimentally
  data/transactions/logic/README.md
  data/transactions/logic/TEAL_opcodes.md
  data/transactions/logic/assembler_test.go
  data/transactions/logic/doc.go
  data/transactions/logic/evalCrypto_test.go
  data/transactions/logic/evalStateful_test.go
  data/transactions/logic/langspec.json
  data/transactions/logic/opcodes.go
  data/transactions/logic/pairing.go
  data/transactions/logic/teal.tmLanguage.json
  go.mod
  go.sum
Labels: New Feature

#4033 320 rounds testing: test fields setters/getters for baseOnlineAccountData
  ledger/accountdb_test.go
Labels: Enhancement, Team Carbon-11

#4020 metrics: make metrics easier to use with prometheus
  agreement/gossip/network.go
  agreement/pseudonode.go
  network/wsPeer.go
  util/metrics/counter.go
  util/metrics/counter_test.go
  util/metrics/gauge_test.go
  util/metrics/registry_test.go
  util/metrics/segment.go
  util/metrics/segment_test.go
  util/metrics/tagcounter.go
  util/metrics/tagcounter_test.go
Labels: Bug-Fix

#3918 network: non-participating nodes request TX gossip only if ForceFetchTransactions: true
  components/mocks/mockParticipationRegistry.go
  data/account/participationRegistry.go
  data/accountManager.go
  network/wsNetwork.go
  network/wsNetwork_test.go
  network/wsPeer.go
  network/wsPeer_test.go
  node/node.go
Labels: Enhancement, Team Carbon-11

#3983 fix: place updater in same directory as update.sh
  cmd/updater/update.sh
Labels: Bug-Fix

#4042 320 rounds: Fix race cond in TestReproducibleCatchpointLabels
  ledger/catchpointtracker_test.go
Labels: Team Carbon-11

#4044 320 rounds: fix more data races in catchpoint tracker tests.
  ledger/catchpointtracker_test.go
Labels: Team Carbon-11

#3985 StateProofs: fix GetProof endpoint response
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_test.go
Labels: Bug-Fix

#4028 agreement: fix typo in bandwidthFilter_test
  agreement/fuzzer/bandwidthFilter_test.go
Labels: external contribution, Bug-Fix

#4045 320 rounds testing: migration and reload test
  ledger/ledger_test.go
Labels: Enhancement, Team Carbon-11

#4039 Devops: Use Cloudflare API token instead of auth key
  cmd/algons/dnsCmd.go
  cmd/algorelay/relayCmd.go
  netdeploy/remote/nodecfg/nodeConfigurator.go
  tools/network/cloudflare/cloudflare.go
  tools/network/cloudflare/createRecord.go
  tools/network/cloudflare/deleteRecord.go
  tools/network/cloudflare/helpers.go
  tools/network/cloudflare/listRecords.go
  tools/network/cloudflare/updateRecord.go
  tools/network/cloudflare/zones.go
Labels: Enhancement

#3893 Developer Tools: Add manjaro support to build script
  scripts/install_linux_deps.sh
Labels: Bug-Fix

#4052 Better reporting for TestLedgerMemoryLeak
  ledger/ledger_test.go
Labels: Team Carbon-11
