Repository algorand/go-algorand, pull requests merged in 2022-09, with the labels that each got.

#4442 AVM: Handle Teal programs with manual constant blocks better
  data/transactions/logic/assembler.go
  data/transactions/logic/assembler_test.go
  data/transactions/logic/eval_test.go
Labels: Bug-Fix

#4487 e2e tests: remove unused e2e artifact
  test/scripts/e2e.sh
Labels: Team Lamprey, Bug-Fix

#4479 enhancement: Return a 404 when a block is not found.
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_test.go
Labels: Enhancement, Team Lamprey

#4461 CI: optimize caches used by CircleCI and GHA
  .circleci/config.yml
  .github/workflows/build.yml
  .github/workflows/codegen_verification.yml
  .github/workflows/reviewdog.yml
Labels: Enhancement

#4510 Testing: fix TestAttestorsChange
  test/e2e-go/features/stateproofs/stateproofs_test.go
Labels: Enhancement, Team Sphinx

#4514 CICD: go-algorand relstable3.9.2-remerge
  config/version.go
Labels: Team Hyper Flow, Skip-Release-Notes

#4513 updater: cleanup key.pub
  cmd/updater/update.sh
Labels: unplanned, Team Hyper Flow, Bug-Fix

#4515 StateProofs: Add timeout to stateproof api
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/routes.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_resources_test.go
  daemon/algod/api/server/v2/test/handlers_test.go
  daemon/algod/api/server/v2/utils.go
Labels: Team Sphinx, Bug-Fix

#4294 tools: pingpong improvements
  cmd/pingpong/runCmd.go
  libgoal/libgoal.go
  libgoal/transactions.go
  shared/pingpong/accounts.go
  shared/pingpong/accounts_test.go
  shared/pingpong/config.go
  shared/pingpong/pingpong.go
  test/commandandcontrol/cc_agent/component/pingPongComponent.go
  test/scripts/tps.py
Labels: Enhancement, Team Carbon-11

#4524 metrics: create filtered TagCounters from init
  network/wsPeer.go
Labels: Bug-Fix

#4526 metrics: network tag filtering test
  network/wsPeer_test.go
Labels: Enhancement, Team Carbon-11

#4525 go-algorand v3.9.4-beta
  buildnumber.dat
  network/wsPeer.go
Labels: Team Hyper Flow

#4529 tests: fix network metrics race condition in tests
  network/wsPeer_test.go
  util/metrics/tagcounter.go
Labels: Team Carbon-11, Bug-Fix

#4530 Tests: Bump py-algorand-sdk to v1.17.0
  test/scripts/e2e.sh
Labels: Enhancement

#4552 performance: Update two transaction verification benchmarks
  data/bookkeeping/txn_merkle_test.go
  data/txHandler_test.go
Labels: Enhancement, Team Carbon-11

#3138 testing: benchmark assemble / transaction pool's uses of recomputeBlockEvaluator
  data/pools/transactionPool_test.go
Labels: Enhancement, Team Carbon-11

#4458 AVM: Switch opcode
  cmd/opdoc/opdoc.go
  data/transactions/logic/README.md
  data/transactions/logic/TEAL_opcodes.md
  data/transactions/logic/assembler.go
  data/transactions/logic/assembler_test.go
  data/transactions/logic/doc.go
  data/transactions/logic/eval.go
  data/transactions/logic/evalStateful_test.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/langspec.json
  data/transactions/logic/opcodes.go
  data/transactions/logic/teal.tmLanguage.json
Labels: New Feature

#4558 tools: pingpong nil fix
  shared/pingpong/accounts.go
Labels: Team Carbon-11, Bug-Fix

#4248 Typo Fix: "Transcation" to "Transaction"
  data/transactions/verify/verifiedTxnCache.go
  data/transactions/verify/verifiedTxnCache_test.go
  ledger/internal/eval.go
Labels: Enhancement

#4561 tests: fix method name after typo correction
  data/txHandler_test.go
Labels: Team Carbon-11, Bug-Fix

#4554 Algod: fix nil deref while fetching stateproof secrets
  data/account/participationRegistry.go
  data/account/participationRegistry_test.go
  data/accountManager.go
  data/accountManager_test.go
Labels: Team Sphinx, Bug-Fix

#4522 performance: block validation benchmark
  ledger/fullblock_perf_test.go
Labels: Enhancement, Team Carbon-11

#4563 telemetry: add StartupEventDetails.Overrides
  cmd/algod/main.go
  config/config_test.go
  config/migrate.go
  logging/telemetryspec/event.go
Labels: Enhancement

#4311 config: Resource Cache Size Reduction
  ledger/acctupdates.go
Labels: Enhancement

#4569 catchup: increase HTTPFetcher fetcherMaxBlockBytes for larger block size
  catchup/universalFetcher.go
Labels: Bug-Fix

#4533 Tests: skip db concurrent Read/Write tests if test.short is set
  util/db/dbutil_test.go
Labels: Enhancement, Team Sphinx

#4579 ledger: fix TestCatchpointReadDatabaseOverflowSingleAccount
  ledger/catchpointwriter_test.go
Labels: Team Carbon-11, Bug-Fix

#4572 Tests: betanet-2 extended recipe
  test/testdata/deployednettemplates/hosttemplates/hosttemplates.json
  test/testdata/deployednettemplates/recipes/betanet-model-2/Makefile
  test/testdata/deployednettemplates/recipes/betanet-model-2/gen_topology.py
  test/testdata/deployednettemplates/recipes/betanet-model-2/genesis.json
  test/testdata/deployednettemplates/recipes/betanet-model-2/net.json
  test/testdata/deployednettemplates/recipes/betanet-model-2/node.json
  test/testdata/deployednettemplates/recipes/betanet-model-2/nonPartNode.json
  test/testdata/deployednettemplates/recipes/betanet-model-2/recipe.json
  test/testdata/deployednettemplates/recipes/betanet-model-2/relay.json
  test/testdata/deployednettemplates/recipes/betanet-model-2/topology.json
Labels: Enhancement

#4583 telemetry: add BlockAcceptedEventDetails.ReceivedAt to complement ValidatedAt
  agreement/actions.go
  agreement/demux.go
  agreement/events.go
  agreement/msgp_gen.go
  agreement/proposal.go
  logging/telemetryspec/event.go
Labels: Enhancement

#4580 REST API: Add GetBlockHash API to algod v2
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/private/routes.go
  daemon/algod/api/server/v2/generated/private/types.go
  daemon/algod/api/server/v2/generated/routes.go
  daemon/algod/api/server/v2/generated/types.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_test.go
Labels: Enhancement

#4564 CICD: Reordering circleci config
  .circleci/config.yml
Labels: Enhancement, Team Hyper Flow

#4319 AVM: frame pointers
  data/transactions/logic/README.md
  data/transactions/logic/TEAL_opcodes.md
  data/transactions/logic/assembler.go
  data/transactions/logic/assembler_test.go
  data/transactions/logic/debugger.go
  data/transactions/logic/debugger_test.go
  data/transactions/logic/doc.go
  data/transactions/logic/doc_test.go
  data/transactions/logic/eval.go
  data/transactions/logic/evalStateful_test.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/frames.go
  data/transactions/logic/frames_test.go
  data/transactions/logic/langspec.json
  data/transactions/logic/opcodes.go
  data/transactions/logic/teal.tmLanguage.json
Labels: New Feature

#4611 ledger: fix accounts cache ordering
  ledger/accountdb.go
  ledger/acctonline_test.go
Labels: Team Carbon-11, Bug-Fix

#4595 testing: tool to dump blocks to directory
  tools/debug/dumpblocks/main.go
Labels: New Feature

#4578 BatchVerifier: Rename and unexport local functions in verify/txn
  crypto/batchverifier.go
  crypto/batchverifier_test.go
  crypto/multisig.go
  crypto/multisig_test.go
  data/transactions/verify/txn.go
  data/transactions/verify/txn_test.go
  test/e2e-go/kmd/e2e_kmd_wallet_multisig_test.go
  test/e2e-go/upgrades/rekey_support_test.go
Labels: Enhancement, tech debt, Team Carbon-11

#4605 telemetry: Count and report the number of duplicate proposals and MsgDigestSkipTag messages received
  agreement/proposalStore.go
  logging/telemetryspec/event.go
  network/wsNetwork.go
  network/wsPeer.go
  util/metrics/metrics.go
Labels: Enhancement
