Repository algorand/go-algorand, pull requests merged in 2022-01, with the labels that each got.

#3356 go-algorand 3.2.3-stable
  buildnumber.dat
  ledger/acctupdates.go
  ledger/bulletin.go
  ledger/catchpointtracker.go
  ledger/catchpointtracker_test.go
  ledger/metrics.go
  ledger/notifier.go
  ledger/tracker.go
  ledger/txtail.go
Labels: Team Hyper Flow

#3367 Add totals checks into acct updates tests
  ledger/acctupdates_test.go
  ledger/catchpointtracker_test.go
Labels: Team Carbon-11

#3280 Falcon key gen time: set LastPartKeyRound 3K
  Makefile
  cmd/genesis/newgenesis.go
  cmd/goal/network.go
  gen/generate.go
  netdeploy/network.go
  scripts/travis/codegen_verification.sh
  test/framework/fixtures/libgoalFixture.go
  test/testdata/deployednettemplates/recipes/scenario1/genesis.json
  test/testdata/deployednettemplates/recipes/scenario2/genesis.json
  test/testdata/deployednettemplates/recipes/scenario3/genesis.json
  test/testdata/nettemplates/CatchpointCatchupTestNetwork.json
  test/testdata/nettemplates/CompactCert.json
  test/testdata/nettemplates/David20.json
  test/testdata/nettemplates/DevModeNetwork.json
  test/testdata/nettemplates/DevModeOneWallet.json
  test/testdata/nettemplates/FourNodes.json
  test/testdata/nettemplates/NegativeStake.json
  test/testdata/nettemplates/OneNode.json
  test/testdata/nettemplates/OneNodeFuture.json
  test/testdata/nettemplates/SingleNodeNetwork.json
  test/testdata/nettemplates/TenThousandAccountsEqual.json
  test/testdata/nettemplates/ThreeNodesEvenDist.json
  test/testdata/nettemplates/ThreeNodesEvenDistOneOffline.json
  test/testdata/nettemplates/TwoNodes100Second.json
  test/testdata/nettemplates/TwoNodes100SecondTestUnupgradedProtocol.json
  test/testdata/nettemplates/TwoNodes50Each.json
  test/testdata/nettemplates/TwoNodes50EachFuture.json
  test/testdata/nettemplates/TwoNodes50EachOneOnline.json
  test/testdata/nettemplates/TwoNodes50EachTestShorterLookback.json
  test/testdata/nettemplates/TwoNodes50EachV15.json
  test/testdata/nettemplates/TwoNodes50EachV15Upgrade.json
  test/testdata/nettemplates/TwoNodes50EachV21Upgrade.json
  test/testdata/nettemplates/TwoNodes50EachV22.json
  test/testdata/nettemplates/TwoNodes50EachV22Upgrade.json
  test/testdata/nettemplates/TwoNodes50EachV23Upgrade.json
  test/testdata/nettemplates/TwoNodes50EachV24.json
  test/testdata/nettemplates/TwoNodes50EachV24Upgrade.json
  test/testdata/nettemplates/TwoNodes50EachV26.json
  test/testdata/nettemplates/TwoNodes50EachWithRelay.json
  test/testdata/nettemplates/TwoNodes50Each_RapidRewardRecalculation.json
  test/testdata/nettemplates/TwoNodesExpiredOfflineV29.json
  test/testdata/nettemplates/TwoNodesExpiredOfflineVFuture.json
  test/testdata/nettemplates/TwoNodesOneRelay1000Accounts.json
  test/testdata/nettemplates/TwoNodesPartialPartkeyOnlyWallets.json
  test/testdata/nettemplates/TwoNodesPartlyOffline.json
  test/testdata/nettemplates/TwoNodesPartlyOfflineVFuture.json
  test/testdata/nettemplates/TwoNodesWithoutStateProofPartkeys.json
  test/testdata/nettemplates/UpgradeIntoCompactCert.json
  test/testdata/nettemplates/perf/FourNodes25Each.json
  test/testdata/nettemplates/perf/OneNodeOneWalletBigBlocks.json
Labels: Team Sphinx

#3348 ledger refactoring: addrid lookup fix
  ledger/accountdb.go
  ledger/acctupdates.go
  ledger/catchpointtracker_test.go
  ledger/evalindexer_test.go
Labels: Team Carbon-11

#3371 ledger refactoring: tealdbg + dryrun tests fixes
  cmd/tealdbg/localLedger.go
  daemon/algod/api/server/v2/dryrun.go
  daemon/algod/api/server/v2/handlers.go
  ledger/accountdb.go
  ledger/acctupdates.go
  ledger/evalindexer.go
  ledger/internal/eval.go
  ledger/internal/eval_test.go
  ledger/ledgercore/accountresource.go
  ledger/ledgercore/statedelta.go
Labels: Team Carbon-11

#3373 ledger refactoring: make TestAcctUpdates faster by ~10s
  ledger/acctupdates_test.go
  ledger/ledgercore/accountdata.go
  ledger/ledgercore/statedelta.go
  ledger/testing/randomAccounts.go
Labels: Team Carbon-11

#3281 PKI State Proof Incremental Key Loading
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/private/routes.go
  daemon/algod/api/server/v2/generated/private/types.go
  daemon/algod/api/server/v2/generated/routes.go
  daemon/algod/api/server/v2/generated/types.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_test.go
  daemon/algod/api/server/v2/test/helpers.go
  data/account/msgp_gen.go
  data/account/msgp_gen_test.go
  data/account/participationRegistry.go
  node/node.go
Labels: Team Carbon-11

#3326 Limit number of simultaneous REST connections
  agreement/gossip/networkFull_test.go
  config/localTemplate.go
  config/local_defaults.go
  daemon/algod/api/server/lib/middlewares/connectionLimiter.go
  daemon/algod/api/server/lib/middlewares/connectionLimiter_test.go
  daemon/algod/api/server/router.go
  daemon/algod/server.go
  installer/config.json.example
  network/limitlistener/helper_stub_test.go
  network/limitlistener/helper_unix_test.go
  network/limitlistener/helper_windows_test.go
  network/limitlistener/rejectingLimitListener.go
  network/limitlistener/rejectingLimitListener_test.go
  network/wsNetwork.go
  network/wsNetwork_common.go
  network/wsNetwork_test.go
  node/node.go
  node/node_test.go
  test/testdata/configs/config-v20.json
  util/util.go
  util/util_windows.go
Labels: Team Carbon-11

#3380 Use rejecting limit listener in `WebsocketNetwork`
  network/wsNetwork.go
Labels: Team Carbon-11

#3379 Delete unused constant
  network/wsNetwork.go
Labels: Team Carbon-11

#3378 ledger refactoring: fix zero addrids in TestCompactDeltasResources
  ledger/acctupdates_test.go
Labels: Team Carbon-11

#3343 txsync: compress msgOrderingHeap
  txnsync/incoming.go
  txnsync/msgorderingheap.go
  txnsync/msgorderingheap_test.go
Labels: Team Carbon-11

#3306 Test for catchup stop on completion
  test/e2e-go/features/catchup/basicCatchup_test.go
Labels: unplanned, Team Carbon-11

#3383 Delete unused `AtomicCommitWriteLock()`
  util/db/dbutil.go
Labels: Team Carbon-11

#2685 testing: fix unit test TestAsyncTelemetryHook_QueueDepth
  logging/telemetryhook_test.go
Labels: Team Carbon-11

#3386 Deprecate `FastPartitionRecovery` from `ConsensusParams`
  agreement/demux.go
  agreement/vote.go
  agreement/voteAggregator.go
  config/consensus.go
  test/testdata/consensus/catchpointtestingprotocol.json
Labels: Team Carbon-11

#3374 ledger refactoring: catchpoint fixes
  cmd/catchpointdump/file.go
  ledger/accountdb.go
Labels: Team Carbon-11

#3330 Ledger refactor: Lookup all resources for address
  daemon/algod/api/server/v1/handlers/handlers.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_test.go
  data/ledger_test.go
  ledger/accountdb.go
  ledger/acctupdates.go
  ledger/acctupdates_test.go
  ledger/applications_test.go
  ledger/apply/asset.go
  ledger/apptxn_test.go
  ledger/catchpointwriter_test.go
  ledger/internal/appcow.go
  ledger/internal/appcow_test.go
  ledger/internal/cow.go
  ledger/internal/cow_creatables.go
  ledger/internal/eval.go
  ledger/internal/eval_blackbox_test.go
  ledger/ledger.go
  ledger/ledger_test.go
  ledger/ledgercore/accountresource.go
  ledger/ledgercore/statedelta.go
  ledger/lruresources.go
Labels: Team Carbon-11

#3405 Make TestAcctUpdates faster
  ledger/accountdb.go
  ledger/accountdb_test.go
  ledger/acctupdates.go
  ledger/acctupdates_test.go
  ledger/ledgercore/statedelta.go
Labels: Team Carbon-11

#3381 [Other] CircleCI pipeline change for binary uploads
  .circleci/config.yml
Labels: Team Hyper Flow

#3410 ledger refactoring: restore fast rounds for catchpoint e2e test
  test/testdata/consensus/catchpointtestingprotocol.json
Labels: Team Carbon-11

#3265 signer.KeyDilution need not depend on config package
  agreement/cryptoVerifier_test.go
  agreement/vote.go
  crypto/onetimesig.go
  node/netprio.go
Labels: Team Carbon-11, Team Sphinx

#3408 ledger refactoring: test for updating holdings and params
  ledger/acctupdates_test.go
Labels: Team Carbon-11

#3375 Removing C/crypto dependencies from `data/abi` package
  data/abi/abi_encode.go
  data/abi/abi_encode_test.go
  data/abi/abi_json.go
  data/abi/abi_json_test.go
  data/abi/abi_type.go
  data/basics/address.go
Labels: Team Scytale

#3393 Feature Networks pipeline related changes
  scripts/build_package.sh
  scripts/release/mule/sign/sign.sh
Labels: Team Hyper Flow

#3411 add context to (most) agreement logged writes
  agreement/demux.go
  agreement/listener.go
  agreement/persistence.go
  agreement/persistence_test.go
  agreement/proposalManager.go
  agreement/proposalStore.go
  agreement/proposalTracker.go
  agreement/pseudonode.go
  agreement/service.go
  agreement/trace.go
  agreement/voteAggregator.go
  agreement/voteAuxiliary.go
  agreement/voteTracker.go
Labels: Team Carbon-11

#3416 network: faster node shutdown
  network/wsNetwork.go
  network/wsPeer.go
Labels: Team Carbon-11

#3425 Fix stateproof in goal
  agreement/agreementtest/keyManager.go
  agreement/keyManager_test.go
  cmd/goal/account.go
  compactcert/abstractions.go
  compactcert/signer.go
  compactcert/worker_test.go
  crypto/invalidsigner.go
  crypto/merklekeystore/msgp_gen.go
  crypto/merklekeystore/msgp_gen_test.go
  crypto/msgp_gen.go
  crypto/sig_abstractions.go
  crypto/sig_abstractions_test.go
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/private/routes.go
  daemon/algod/api/server/v2/generated/private/types.go
  daemon/algod/api/server/v2/generated/routes.go
  daemon/algod/api/server/v2/generated/types.go
  daemon/algod/api/server/v2/handlers.go
  data/account/msgp_gen.go
  data/account/participationRegistry.go
  data/account/participationRegistryBench_test.go
  data/account/participationRegistry_test.go
  data/accountManager.go
  node/node.go
  test/e2e-go/restAPI/restClient_test.go
Labels: Team Sphinx

#3417 txnsync: Use 100 txns/msg maximum for txnsync messages
  go.sum
  txnsync/incoming.go
  txnsync/msgorderingheap_test.go
  txnsync/peer.go
  txnsync/peer_test.go
Labels: Team Carbon-11

#3406 ledger refactoring: track per-resource in NewAccountDeltas
  ledger/accountdb.go
  ledger/accountdb_test.go
  ledger/acctupdates.go
  ledger/acctupdates_test.go
  ledger/apply/application.go
  ledger/apply/application_test.go
  ledger/internal/appcow.go
  ledger/internal/appcow_test.go
  ledger/internal/cow.go
  ledger/internal/cow_creatables.go
  ledger/internal/cow_test.go
  ledger/internal/eval.go
  ledger/internal/eval_blackbox_test.go
  ledger/ledgercore/statedelta.go
  ledger/testing/randomAccounts.go
Labels: Team Carbon-11

#3436 Avoid copying during baseAccountData.IsEmpty
  ledger/accountdb.go
  ledger/accountdb_test.go
  ledger/catchpointtracker.go
  protocol/codec_tester.go
Labels: Team Carbon-11

#3403 ledger: fix `NextRewardsState()`
  config/consensus.go
  daemon/algod/api/server/v2/test/handlers_test.go
  data/bookkeeping/block.go
  data/bookkeeping/block_test.go
  ledger/internal/eval.go
  ledger/ledger_test.go
Labels: Team Carbon-11

#3453 Fix a potential problem of committing non-uniform consensus versions
  ledger/accountdb.go
  ledger/acctupdates_test.go
  ledger/catchpointtracker.go
  ledger/catchpointtracker_test.go
  ledger/tracker.go
  ledger/tracker_test.go
Labels: Team Carbon-11

#3424 avoid generating log error on EnsureValidatedBlock / EnsureBlock
  catchup/service.go
  data/ledger.go
  data/ledger_test.go
  ledger/ledger.go
Labels: Team Carbon-11

#3456 Fix typo Fulll to Full
  netdeploy/network.go
Labels: Team Carbon-11

#3455 Fix warning message on restore crash db
  agreement/persistence.go
Labels: Team Carbon-11

#3438 non archival node catchpoint writing
  ledger/accountdb.go
  ledger/acctupdates.go
  ledger/catchpointtracker.go
  ledger/catchpointwriter_test.go
  ledger/catchupaccessor.go
  ledger/ledger.go
  ledger/tracker.go
Labels: Team Carbon-11

#3452 update arm32 builds from v6 to v7
  test/muleCI/mule.yaml
Labels: unplanned, Team Hyper Flow

#3461 Update reference to arm32 build for 3.3.0 release
  test/muleCI/mule.yaml
Labels: Team Hyper Flow

#3463 Specify GOARCH for golang download in Dockerfile
  docker/build/cicd.ubuntu.Dockerfile
  test/muleCI/mule.yaml
Labels: Team Hyper Flow

#3465 ledger refactoring: various touchups
  ledger/accountdb.go
  ledger/accountdb_test.go
  ledger/apply/application.go
  ledger/apply/application_test.go
  ledger/apply/asset.go
Labels: Team Carbon-11

#3477 ledger refactoring: small improvement for processAllResource
  ledger/accountdb.go
Labels: Team Carbon-11

#3480 ledger refactoring: normalize verified accounts
  catchup/catchpointService.go
  ledger/catchupaccessor.go
Labels: Team Carbon-11

#3479 ledger refactoring: resourceData tests
  ledger/accountdb.go
  ledger/accountdb_test.go
Labels: Team Carbon-11

#3472 ledger refactoring: improve merkle trie regeneration
  ledger/accountdb.go
  ledger/accountdb_test.go
  ledger/catchpointtracker.go
Labels: Team Carbon-11

#3482 ledger refactoring: generalize TestResourcesDataSetData for apps
  ledger/accountdb_test.go
Labels: Team Carbon-11

#3481 ledger refactoring: optimize catchpoint catchup
  ledger/accountdb.go
Labels: Team Carbon-11

#3484 ledger refactoring: fix lookupResources
  ledger/accountdb.go
  ledger/applications_test.go
Labels: Team Carbon-11

#3451 Adding new scenario for feature networks
  test/testdata/deployednettemplates/recipes/feature-networks/genesis.json
  test/testdata/deployednettemplates/recipes/feature-networks/hosttemplates.json
  test/testdata/deployednettemplates/recipes/feature-networks/net.json
  test/testdata/deployednettemplates/recipes/feature-networks/recipe.json
  test/testdata/deployednettemplates/recipes/feature-networks/topology.json
Labels: Team Hyper Flow

#3492 ledger refactoring: set empty addrid for deleted resources in base case
  ledger/accountdb.go
  ledger/accountdb_test.go
  ledger/acctupdates.go
Labels: Team Carbon-11

#3485 ledger refactoring: improve some of the error messages
  ledger/accountdb.go
  ledger/catchpointtracker.go
Labels: Team Carbon-11

#3496 ledger refactoring: fix incorrect schema during catchpoint catchup
  ledger/accountdb.go
Labels: Team Carbon-11

#3497 Fixing telemetry ports for feature networks
  test/testdata/deployednettemplates/recipes/feature-networks/net.json
Labels: Team Hyper Flow

#3498 Revert `fillBytes` method to `bigIntToBytes` for lower golang version
  data/abi/abi_encode.go
  data/abi/abi_encode_test.go
  data/abi/abi_json_test.go
Labels: Team Scytale

#3370 Add vector commitment
  crypto/compactcert/builder_test.go
  crypto/compactcert/commitableSignatureSlot_test.go
  crypto/compactcert/committableSignatureSlot.go
  crypto/digest.go
  crypto/digest_test.go
  crypto/hashes.go
  crypto/merklearray/array.go
  crypto/merklearray/layer.go
  crypto/merklearray/layer_test.go
  crypto/merklearray/merkle.go
  crypto/merklearray/merkle_test.go
  crypto/merklearray/msgp_gen.go
  crypto/merklearray/msgp_gen_test.go
  crypto/merklearray/partial.go
  crypto/merklearray/proof.go
  crypto/merklearray/proof_test.go
  crypto/merklearray/vectorCommitmentArray.go
  crypto/merklearray/vectorCommitmentArray_test.go
  crypto/merklekeystore/committablePublicKeys.go
  crypto/merklekeystore/committablePublicKeys_test.go
  crypto/merklekeystore/keystore.go
  crypto/merklekeystore/keystore_test.go
  crypto/util.go
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/private/routes.go
  daemon/algod/api/server/v2/generated/private/types.go
  daemon/algod/api/server/v2/generated/routes.go
  daemon/algod/api/server/v2/generated/types.go
  daemon/algod/api/server/v2/handlers.go
  data/basics/ccertpart.go
  data/bookkeeping/block.go
  data/bookkeeping/txn_merkle.go
  protocol/hash.go
  test/e2e-go/features/transactions/proof_test.go
Labels: Team Sphinx

#3500 REST API: Remove unused DeleteParticipationIdResponse type
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/private/routes.go
  daemon/algod/api/server/v2/generated/routes.go
Labels: Team Lamprey

#3511 ledger refactoring: use 64-bit total resource counts
  ledger/accountdb.go
  ledger/acctupdates.go
  ledger/apply/application.go
  ledger/apply/asset.go
  ledger/ledgercore/accountdata.go
  ledger/msgp_gen.go
Labels: Team Carbon-11

#3506 Revert "Changing golang version to 1.16.11 in go-algorand"
  .circleci/config.yml
  .github/workflows/reviewdog.yml
  Makefile
  go.mod
  go.sum
  scripts/buildtools/go.mod
  scripts/buildtools/install_buildtools.sh
  scripts/get_golang_version.sh
  scripts/travis/before_build.sh
Labels: Team Hyper Flow

#3487 Add bandwidth testing
  test/heapwatch/metrics_delta.py
  test/testdata/deployednettemplates/recipes/hello-world/genesis.json
  test/testdata/deployednettemplates/recipes/hello-world/net.json
  test/testdata/deployednettemplates/recipes/hello-world/topology.json
Labels: Team Hyper Flow

#3512 Integrate mss and vc
  compactcert/worker_test.go
  crypto/compactcert/builder.go
  crypto/compactcert/builder_test.go
  crypto/compactcert/commitableSignatureSlot_test.go
  crypto/compactcert/verifier.go
  crypto/merklearray/proof.go
  crypto/merklearray/proof_test.go
  crypto/merklekeystore/committablePublicKeys_test.go
  crypto/merklekeystore/keystore.go
  crypto/merklekeystore/keystore_test.go
  ledger/ledgercore/votersForRound.go
  test/e2e-go/features/participation/onlineOfflineParticipation_test.go
Labels: Team Sphinx

#3516 ledger refactoring: delete resources table on accountsReset
  ledger/accountdb.go
Labels: Team Carbon-11

#3518 ledger refactoring: acct new round fix + test
  ledger/accountdb.go
  ledger/accountdb_test.go
Labels: Team Carbon-11

#3519 Add compact deltas permutations into TestAccountUnorderedUpdates
  ledger/accountdb_test.go
Labels: Team Carbon-11

#3507 ledger refactoring: remove index and type from `ledgercore.AccountResource`
  cmd/tealdbg/localLedger.go
  daemon/algod/api/server/v2/dryrun.go
  ledger/accountdb.go
  ledger/accountdb_test.go
  ledger/acctupdates.go
  ledger/acctupdates_test.go
  ledger/evalindexer.go
  ledger/ledgercore/accountresource.go
  ledger/ledgercore/statedelta.go
Labels: Team Carbon-11

#3522 Avoid exceed copying when calling WithUpdatedRewards
  data/basics/userBalance.go
  ledger/ledgercore/accountdata.go
Labels: Team Carbon-11

#3502 ledger refactoring: Indexer related changes
  ledger/evalindexer.go
  ledger/evalindexer_test.go
Labels: Team Carbon-11

#3528 Test empty update entries for deleted accounts in accountsNewRound
  ledger/accountdb_test.go
Labels: Team Carbon-11

#3533 ledger refactoring: get rid of LookupLatest from /v1/assets
  daemon/algod/api/server/v1/handlers/handlers.go
Labels: Team Carbon-11

#3532 ledger refactoring: more tests and dead code removal
  ledger/accountdb_test.go
  ledger/ledgercore/statedelta.go
Labels: Team Carbon-11

#3531 ledger refactoring: measure and log performance during fast catchup
  catchup/catchpointService.go
  catchup/ledgerFetcher.go
  ledger/catchupaccessor.go
Labels: Team Carbon-11

#3031 batch verification: add batch verification implementation
  agreement/vote.go
  config/consensus.go
  crypto/batchverifier.go
  crypto/batchverifier_test.go
  crypto/compactcert/builder.go
  crypto/compactcert/structs.go
  crypto/compactcert/verifier.go
  crypto/crypto_test.go
  crypto/curve25519.go
  crypto/curve25519_test.go
  crypto/libsodium-fork/src/libsodium/Makefile.am
  crypto/libsodium-fork/src/libsodium/crypto_core/ed25519/ref10/ed25519_ref10.c
  crypto/libsodium-fork/src/libsodium/crypto_core/ed25519/ref10/fe_25_5/base_ge25519.h
  crypto/libsodium-fork/src/libsodium/crypto_core/ed25519/ref10/fe_51/base_ge25519.h
  crypto/libsodium-fork/src/libsodium/crypto_sign/crypto_sign.c
  crypto/libsodium-fork/src/libsodium/crypto_sign/ed25519/ref10/batch.c
  crypto/libsodium-fork/src/libsodium/crypto_sign/ed25519/ref10/open_bv_compat.c
  crypto/libsodium-fork/src/libsodium/crypto_sign/ed25519/ref10/sign_ed25519_ref10.h
  crypto/libsodium-fork/src/libsodium/crypto_sign/ed25519/sign_ed25519.c
  crypto/libsodium-fork/src/libsodium/include/sodium/crypto_sign.h
  crypto/libsodium-fork/src/libsodium/include/sodium/crypto_sign_ed25519.h
  crypto/libsodium-fork/src/libsodium/include/sodium/private/ed25519_ref10.h
  crypto/libsodium-fork/src/libsodium/include/sodium/private/ed25519_ref10_sc_25_5.h
  crypto/libsodium-fork/src/libsodium/include/sodium/private/ed25519_ref10_sc_51.h
  crypto/libsodium-fork/test/default/Makefile.am
  crypto/libsodium-fork/test/default/batch.c
  crypto/libsodium-fork/test/default/batch.exp
  crypto/libsodium-fork/test/default/sign_bv_compat.c
  crypto/libsodium-fork/test/default/sign_bv_compat.exp
  crypto/multisig.go
  crypto/multisig_test.go
  crypto/onetimesig.go
  crypto/onetimesig_test.go
  data/transactions/logic/eval.go
  data/transactions/verify/txn.go
  data/transactions/verify/txn_test.go
  ledger/internal/compactcert.go
  node/netprio.go
  test/e2e-go/kmd/e2e_kmd_wallet_keyops_test.go
Labels: Team Sphinx
