Repository algorand/go-algorand, pull requests merged in 2022-07, with the labels that each got.

#4207 Fix exceed mem allocation in state deltas
  ledger/ledgercore/statedelta.go
Labels: Team Carbon-11

#4208 320 rounds: bring back StateDelta.OptimizeAllocatedMemory
  ledger/ledger.go
  ledger/ledgercore/statedelta.go
Labels: Enhancement, Team Carbon-11

#4210 Optimization: Use bits package for Muldiv. 266x speedup
  data/basics/overflow.go
  data/basics/units_test.go
Labels: Enhancement

#4203 Block proof e2e
  crypto/merklearray/merkle.go
  crypto/merklearray/proof.go
  crypto/merklearray/proof_test.go
  daemon/algod/api/client/restClient.go
  daemon/algod/api/server/v2/test/handlers_test.go
  libgoal/libgoal.go
  test/e2e-go/features/stateproofs/stateproofs_test.go
  test/e2e-go/features/transactions/proof_test.go
  test/framework/fixtures/libgoalFixture.go
Labels: Team Sphinx

#4213 Algod: Attestors change test
  test/e2e-go/features/stateproofs/stateproofs_test.go
  test/testdata/nettemplates/RichAccountStateProof.json
Labels: Team Sphinx

#4211 320 rounds PR feedback
  ledger/accountdb.go
  ledger/accountdb_test.go
  ledger/acctupdates.go
  ledger/tracker.go
  ledger/txtail_test.go
Labels: Team Carbon-11

#4167 CICD: add m1 to integration tests
  .circleci/config.yml
Labels: Enhancement

#4209 Re-enable catchpoint expect test
  ledger/accountdb.go
  ledger/catchpointtracker.go
  ledger/tracker.go
  test/e2e-go/cli/goal/expect/catchpointCatchupTest.exp
  test/e2e-go/cli/goal/expect/catchpointCatchupWebProxy/webproxy.go
  test/framework/fixtures/expectFixture.go
  test/testdata/consensus/catchpointtestingprotocol.json
Labels: Team Carbon-11

#4184 320-rounds: Remove stateproofID from offline accounts
  config/consensus.go
  ledger/accountdb.go
  ledger/accountdb_test.go
  ledger/acctupdates.go
  ledger/apply/keyreg.go
  ledger/apply/keyreg_test.go
  ledger/catchpointtracker.go
  ledger/catchpointtracker_test.go
  ledger/msgp_gen.go
  ledger/msgp_gen_test.go
  ledger/trackerdb.go
  test/testdata/consensus/catchpointtestingprotocol.json
Labels: Team Carbon-11, Bug-Fix

#4069 testing: pingpong fixes and heap watch reporting
  cmd/pingpong/runCmd.go
  shared/pingpong/pingpong.go
  test/heapwatch/client_ram_report.py
  test/heapwatch/start.sh
  test/scripts/tps.py
Labels: Enhancement, Team Carbon-11

#4221 320 rounds: PR feedback fixes
  ledger/accountdb.go
  ledger/accountdb_test.go
  ledger/acctonline.go
  ledger/acctupdates.go
  ledger/txtail.go
Labels: Team Carbon-11

#4235 320 rounds: fix linter complains
  ledger/accountdb_test.go
  ledger/acctonline_test.go
  ledger/archival_test.go
  ledger/catchpointtracker_test.go
  ledger/catchupaccessor.go
  ledger/evalbench_test.go
  ledger/onlineaccountscache_test.go
  ledger/voters.go
Labels: Team Carbon-11

#4228 CICD: go-algorand relstable3.8.0-remerge
  config/version.go
Labels: Skip-Release-Notes

#4230 alphanet: define vAlpha2 consensus parameters
  config/consensus.go
  protocol/consensus.go
Labels: Enhancement

#4236 tests: fixes to catchpoint e2e tests
  ledger/catchpointtracker_test.go
  test/e2e-go/features/catchup/catchpointCatchup_test.go
Labels: Enhancement, Team Carbon-11

#4240 DevOps: Updated alphanet algonet recipe genesis files to use alpha2 protocol.
  test/testdata/deployednettemplates/recipes/hello-world/genesis.json
  test/testdata/deployednettemplates/recipes/scenario1/genesis.json
  test/testdata/deployednettemplates/recipes/scenario2/genesis.json
  test/testdata/deployednettemplates/recipes/scenario3/genesis.json
Labels: Enhancement, Team Hyper Flow

#4251 CICD: go-algorand relstable3.8.1-remerge
  ledger/internal/prefetcher/prefetcher.go
  ledger/internal/prefetcher/prefetcher_alignment_test.go
  ledger/internal/prefetcher/prefetcher_test.go
Labels: Team Hyper Flow, Skip-Release-Notes

#4252 CICD: go-algorand v3.8.1-beta
  buildnumber.dat
  ledger/internal/prefetcher/prefetcher.go
Labels: Team Hyper Flow, Skip-Release-Notes

#4239 ledger: restore pointer receivers and args from #4003
  ledger/accountdb.go
  ledger/accountdb_test.go
  ledger/ledgercore/accountdata.go
Labels: Enhancement

#4260 AVM: Document what the field _is_ rather than pointer to table
  data/transactions/logic/README.md
  data/transactions/logic/TEAL_opcodes.md
  data/transactions/logic/fields.go
Labels: Skip-Release-Notes

#4110 Algod: fix issues causing database is locked sqlite error
  cmd/algokey/part.go
  data/account/participationRegistry_test.go
  util/db/dbutil.go
  util/db/dbutil_test.go
Labels: Bug-Fix

#4258 Refactoring and minor fixes
  crypto/merklesignature/merkleSignatureScheme.go
  crypto/merklesignature/merkleSignatureScheme_test.go
  crypto/stateproof/builder.go
  crypto/stateproof/builder_test.go
  crypto/stateproof/verifier.go
  data/bookkeeping/lightBlockHeader.go
  data/pools/transactionPool.go
  data/pools/transactionPool_test.go
  data/transactions/stateproof.go
  ledger/internal/eval.go
  ledger/ledgercore/votersForRound.go
  stateproof/builder.go
  stateproof/stateproofMessageGenerator.go
  stateproof/stateproofMessageGenerator_test.go
  test/e2e-go/upgrades/stateproof_participation_test.go
Labels: Team Sphinx

#4270 StateProof verifier rejects long proofs
  crypto/stateproof/const.go
  crypto/stateproof/verifier.go
  crypto/stateproof/verifier_test.go
  data/bookkeeping/lightBlockHeader.go
  data/bookkeeping/msgp_gen.go
Labels: Team Sphinx

#4030 Enhancement: Detect when valid partkeys represent an offline or closed account
  node/node.go
  node/node_test.go
Labels: Enhancement

#4170 AVM: Refactor Pseudo-ops
  cmd/opdoc/opdoc.go
  data/transactions/logic/README.md
  data/transactions/logic/README_in.md
  data/transactions/logic/TEAL_opcodes.md
  data/transactions/logic/assembler.go
  data/transactions/logic/assembler_test.go
  data/transactions/logic/backwardCompat_test.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/fields.go
  data/transactions/logic/langspec.json
  data/transactions/logic/opcodes.go
  data/transactions/logic/opcodes_test.go
  data/transactions/logic/teal.tmLanguage.json
Labels: New Feature

#4276 Broken build: Fix struct initialization with promoted field
  node/node_test.go
Labels: Skip-Release-Notes

#4257 BugFix VotersTracker loadFromDisk
  ledger/acctonline.go
  ledger/ledger_test.go
  ledger/voters.go
  stateproof/worker_test.go
Labels: Team Sphinx, Bug-Fix

#4277 Test: Fail codegen_verification if dump_genesis.sh is bad
  scripts/dump_genesis.sh
Labels: Enhancement

#4282 AVM: Move elliptic curve math up to v8 so it doesn't get released
  data/transactions/logic/README.md
  data/transactions/logic/TEAL_opcodes.md
  data/transactions/logic/assembler_test.go
  data/transactions/logic/langspec.json
  data/transactions/logic/opcodes.go
Labels: Enhancement

#4284 testing: Support multiple e2e test archives.
  .circleci/config.yml
  test/scripts/e2e.sh
Labels: Enhancement

#4297 Test: Fix typo in ledger_test.go
  data/ledger_test.go
Labels: Enhancement

#4295 Tests: Attempt to make TestBasicCatchpointCatchup more deterministic
  test/e2e-go/features/catchup/catchpointCatchup_test.go
  test/framework/fixtures/restClientFixture.go
Labels: Skip-Release-Notes

#4286 Test: Make e2e subs report individual results better
  test/e2e-go/cli/goal/expect/corsTest.exp
  test/scripts/e2e.sh
  test/scripts/e2e_client_runner.py
Labels: Enhancement

#4305 alphanet: define consensus version vAlpha3
  config/consensus.go
  protocol/consensus.go
Labels: Enhancement

#4229 kvstore table migration during consensus upgrade
  ledger/accountdb.go
  ledger/accountdb_test.go
  ledger/acctupdates.go
  ledger/acctupdates_test.go
  ledger/ledger_test.go
  ledger/trackerdb.go
Labels: Team Scytale

#4315 Ledger: remove txtail from data race test
  ledger/acctupdates_test.go
Labels: Team Carbon-11, Bug-Fix

#4308 Rename StateProof operationId to GetStateProof.
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/routes.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_test.go
Labels: Team Lamprey

#4273 config: update vFuture consensus and configuration for 5MB blocks
  agreement/service_test.go
  config/consensus.go
  config/localTemplate.go
  config/local_defaults.go
  installer/config.json.example
  network/wsPeer.go
  test/testdata/configs/config-v23.json
Labels: Enhancement

#4314 AVM: Allow fido into a release with v7 on
  data/transactions/logic/assembler_test.go
  data/transactions/logic/evalCrypto_test.go
Labels: Skip-Release-Notes

#4243 CICD: create model mainnet (mmnet) recipe based on scenario2
  test/testdata/deployednettemplates/hosttemplates/hosttemplates.json
  test/testdata/deployednettemplates/recipes/mmnet/Makefile
  test/testdata/deployednettemplates/recipes/mmnet/README.md
  test/testdata/deployednettemplates/recipes/mmnet/configs/node.json
  test/testdata/deployednettemplates/recipes/mmnet/configs/nonPartNode.json
  test/testdata/deployednettemplates/recipes/mmnet/configs/relay.json
  test/testdata/deployednettemplates/recipes/mmnet/gen_topology.py
  test/testdata/deployednettemplates/recipes/mmnet/genesis.json
  test/testdata/deployednettemplates/recipes/mmnet/net.json
  test/testdata/deployednettemplates/recipes/mmnet/recipe.json
  test/testdata/deployednettemplates/recipes/mmnet/topology.json
Labels: Enhancement

#4321 loadgenerator: add multiple accounts config option
  cmd/loadgenerator/config.go
  cmd/loadgenerator/main.go
Labels: Enhancement
