Repository algorand/go-algorand, pull requests merged in 2022-06, with the labels that each got.

#3478 pingpong: improve transaction scheduling
  cmd/pingpong/runCmd.go
  shared/pingpong/accounts.go
  shared/pingpong/config.go
  shared/pingpong/pingpong.go
Labels: Enhancement, tech debt, Team Carbon-11

#4055 Stateproofs: get proof on block headers endpoint
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/errors.go
  daemon/algod/api/server/v2/generated/private/routes.go
  daemon/algod/api/server/v2/generated/private/types.go
  daemon/algod/api/server/v2/generated/routes.go
  daemon/algod/api/server/v2/generated/types.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_resources_test.go
  daemon/algod/api/server/v2/test/handlers_test.go
  data/bookkeeping/lightBlockHeader.go
  data/bookkeeping/lightBlockHeader_test.go
  data/bookkeeping/msgp_gen.go
  data/bookkeeping/msgp_gen_test.go
  data/stateproofmsg/message.go
  stateproof/abstractions.go
  stateproof/stateproofMessageGenerator.go
  stateproof/stateproofMessageGenerator_test.go
  stateproof/transactionFinder.go
  stateproof/transactionFinder_test.go
Labels: Team Sphinx

#4068 320 rounds: fix another flakiness in `TestReproducibleCatchpointLabels`
  ledger/accountdb_test.go
  ledger/acctupdates_test.go
  ledger/catchpointtracker_test.go
  ledger/testing/randomAccounts.go
Labels: Team Carbon-11

#4065 320 rounds: Fix migration and reload test
  ledger/ledger_test.go
Labels: Enhancement, Team Carbon-11

#4070 Tools: Fixing calls to pingpong with deprecated flag --rest
  test/e2e-go/cli/goal/expect/pingpongTest.exp
  test/heapwatch/bwstart.sh
  test/heapwatch/start.sh
Labels: unplanned, Team Hyper Flow, Bug-Fix

#4059 320 rounds: feedback for two stage catchpoints
  catchup/ledgerFetcher.go
  ledger/catchpointtracker.go
  ledger/tracker.go
Labels: Team Carbon-11

#4061 320 rounds testing: Catchpoint Label Test
  test/e2e-go/features/catchup/catchpointCatchup_test.go
Labels: Enhancement, Team Carbon-11

#4037 320 rounds: extended online accounts history for voters
  ledger/accountdb.go
  ledger/accountdb_test.go
  ledger/acctonline.go
  ledger/acctonline_test.go
  ledger/onlineaccountscache.go
  ledger/onlineaccountscache_test.go
  ledger/tracker.go
Labels: Team Carbon-11

#4058 320 rounds: memory optimizations
  ledger/accountdb.go
  ledger/acctonline.go
  ledger/acctupdates.go
  ledger/catchpointtracker.go
  ledger/catchpointtracker_test.go
  ledger/catchpointwriter.go
  ledger/catchpointwriter_test.go
  ledger/ledger_test.go
  ledger/msgp_gen.go
  ledger/tracker.go
Labels: Team Carbon-11

#4074 ledger: fix flakiness in `TestReproducibleCatchpointLabels`
  ledger/accountdb_test.go
  ledger/acctupdates_test.go
  ledger/catchpointtracker_test.go
  ledger/testing/randomAccounts.go
Labels: Team Carbon-11, Bug-Fix

#4075 320 rounds: implement catchpoint persistence - enhancements
  ledger/accountdb.go
  ledger/accountdb_test.go
  ledger/acctupdates.go
  ledger/acctupdates_test.go
  ledger/applications_test.go
  ledger/catchpointtracker.go
  ledger/catchpointtracker_test.go
  ledger/catchupaccessor.go
  ledger/trackerdb.go
  scripts/dump_genesis.sh
  util/db/interfaces.go
Labels: Team Carbon-11

#4078 320 rounds: use snappy for stage 1 compression
  go.mod
  go.sum
  ledger/catchpointtracker.go
  ledger/catchpointwriter.go
  ledger/catchpointwriter_test.go
Labels: Enhancement

#4082 ledger: onlineacct tracker preserve blocks as voters requires
  ledger/acctonline.go
  ledger/acctonline_test.go
Labels: Team Carbon-11

#4083 merge master into 320 rounds
  cmd/goal/account.go
  libgoal/libgoal.go
  libgoal/participation.go
  libgoal/transactions.go
  node/node.go
  test/e2e-go/features/participation/accountParticipationTransitions_test.go
  test/e2e-go/features/participation/onlineOfflineParticipation_test.go
  test/e2e-go/features/participation/overlappingParticipationKeys_test.go
  test/e2e-go/features/participation/participationExpiration_test.go
  test/e2e-go/features/transactions/onlineStatusChange_test.go
  test/e2e-go/stress/transactions/createManyAndGoOnline_test.go
  test/scripts/e2e_subs/goal-partkey-commands.sh
  test/scripts/e2e_subs/goal-partkey-information.sh
Labels: Team Carbon-11

#4085 Bug Fix: Adds validity round check for failing tests
  libgoal/transactions.go
  test/e2e-go/features/participation/participationExpiration_test.go
Labels: Bug-Fix

#4086 AVM: Allow app downgrades in old protocol versions
  config/consensus.go
  ledger/internal/apptxn_test.go
Labels: Bug-Fix

#4084 320 rounds: fix restoring from a catchpoint
  ledger/accountdb.go
  ledger/catchupaccessor.go
  ledger/trackerdb.go
Labels: Team Carbon-11

#4066 DevOps: Define recipe for FastNet.
  test/testdata/deployednettemplates/recipes/alphanet/Makefile
  test/testdata/deployednettemplates/recipes/alphanet/gen_topology.py
  test/testdata/deployednettemplates/recipes/alphanet/genesis.json
  test/testdata/deployednettemplates/recipes/alphanet/net.json
  test/testdata/deployednettemplates/recipes/alphanet/node.json
  test/testdata/deployednettemplates/recipes/alphanet/nonPartNode.json
  test/testdata/deployednettemplates/recipes/alphanet/recipe.json
  test/testdata/deployednettemplates/recipes/alphanet/relay.json
  test/testdata/deployednettemplates/recipes/alphanet/topology.json
Labels: Enhancement

#4096 AVM: Set proper costs for json_ref
  data/transactions/logic/TEAL_opcodes.md
  data/transactions/logic/doc.go
  data/transactions/logic/eval.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/jsonspec.md
  data/transactions/logic/jsonspec_test.go
  data/transactions/logic/opcodes.go
Labels: Enhancement

#4098 320 rounds: download `DeeperBlockHeaderHistory` more blocks in fast catchup
  catchup/catchpointService.go
Labels: Team Carbon-11

#4097 Temporary disable empty voting data check
  ledger/accountdb.go
  ledger/accountdb_test.go
Labels: Team Carbon-11

#4102 Use a utility function to delete catchpoint (data) files
  ledger/catchpointtracker.go
Labels: Team Carbon-11

#4100 Discard an unfinished catchpoint after upgrade
  ledger/trackerdb.go
Labels: Team Carbon-11

#4064 AVM: Track Scratch Slot Types
  data/transactions/logic/assembler.go
  data/transactions/logic/assembler_test.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/opcodes.go
Labels: Enhancement

#4089 metrics: specify telemetry hostname and instance name as prometheus labels
  daemon/algod/server.go
  logging/log.go
  logging/telemetryConfig.go
  logging/telemetryhook.go
  logging/telemetryspec/event.go
  network/requestTracker.go
  network/wsNetwork.go
Labels: Enhancement

#4112 Revert a small change related to contexts in catchpoint tracker
  ledger/catchpointtracker.go
Labels: Team Carbon-11

#4111 Misc: Add helper functions to genesis.
  cmd/buildtools/genesis.go
  data/bookkeeping/genesis.go
  data/bookkeeping/genesis_test.go
  netdeploy/remote/deployedNetwork.go
  node/node.go
  test/e2e-go/features/participation/overlappingParticipationKeys_test.go
Labels: Enhancement, Team Lamprey

#4107 network: message-of-interest tiny bugfix
  network/wsNetwork.go
  network/wsNetwork_test.go
Labels: Team Carbon-11, Bug-Fix

#4116 go-algorand v3.7.2-beta
  buildnumber.dat
  network/wsNetwork.go
  network/wsNetwork_test.go
Labels: Team Hyper Flow

#4123 AVM: Make it easier to move experimental opcode groups
  config/consensus.go
  data/transactions/logic/TEAL_opcodes.md
  data/transactions/logic/assembler.go
  data/transactions/logic/assembler_test.go
  data/transactions/logic/langspec.json
  data/transactions/logic/opcodes.go
  data/transactions/logic/pairing_test.go
  ledger/.gitignore
  ledger/internal/eval_blackbox_test.go
Labels: Enhancement

#4124 Catchpoint tracker persistence tests
  ledger/accountdb.go
  ledger/catchpointtracker_test.go
Labels: Team Carbon-11

#4129 AVM: replace opcodes
  data/transactions/logic/README.md
  data/transactions/logic/TEAL_opcodes.md
  data/transactions/logic/assembler_test.go
  data/transactions/logic/doc.go
  data/transactions/logic/eval.go
  data/transactions/logic/evalStateful_test.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/langspec.json
  data/transactions/logic/opcodes.go
  data/transactions/logic/teal.tmLanguage.json
Labels: New Feature

#4143 ledger: fix typo in error.go
  ledger/ledgercore/error.go
Labels: Enhancement

#4133 Remerge: go-algorand relstable3.7.2-remerge
  config/version.go
Labels: Enhancement, Re-Merge

#4144 testing: Is stateproof tx well formed
  data/transactions/transaction.go
  data/transactions/transaction_test.go
  stateproof/stateproofMessageGenerator_test.go
  stateproof/worker_test.go
Labels: Team Sphinx

#4134 Small improvements in catchpoint tracker tests.
  ledger/catchpointtracker_test.go
Labels: Team Carbon-11

#4135 A benchmark for `onlineAccountsCache.read()`
  ledger/onlineaccountscache_test.go
Labels: Team Carbon-11

#4130 catchpointdump: fixes
  cmd/catchpointdump/net.go
Labels: Team Carbon-11, Bug-Fix

#4152 merge master into feature/320 rounds
  .circleci/config.yml
  cmd/buildtools/genesis.go
  cmd/catchpointdump/net.go
  config/consensus.go
  config/version.go
  daemon/algod/server.go
  data/bookkeeping/genesis.go
  data/bookkeeping/genesis_test.go
  data/transactions/logic/README.md
  data/transactions/logic/TEAL_opcodes.md
  data/transactions/logic/assembler.go
  data/transactions/logic/assembler_test.go
  data/transactions/logic/doc.go
  data/transactions/logic/eval.go
  data/transactions/logic/evalStateful_test.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/jsonspec.md
  data/transactions/logic/jsonspec_test.go
  data/transactions/logic/langspec.json
  data/transactions/logic/opcodes.go
  data/transactions/logic/pairing_test.go
  data/transactions/logic/teal.tmLanguage.json
  data/transactions/transaction.go
  ledger/.gitignore
  ledger/internal/apptxn_test.go
  ledger/internal/eval_blackbox_test.go
  ledger/ledgercore/error.go
  libgoal/transactions.go
  logging/log.go
  logging/telemetryConfig.go
  logging/telemetryhook.go
  logging/telemetryspec/event.go
  netdeploy/remote/deployedNetwork.go
  network/requestTracker.go
  network/wsNetwork.go
  network/wsNetwork_test.go
  node/node.go
  scripts/release/mule/sign/sign.sh
  test/e2e-go/features/participation/overlappingParticipationKeys_test.go
  test/e2e-go/features/participation/participationExpiration_test.go
  test/muleCI/mule.yaml
  test/testdata/deployednettemplates/recipes/alphanet/Makefile
  test/testdata/deployednettemplates/recipes/alphanet/gen_topology.py
  test/testdata/deployednettemplates/recipes/alphanet/genesis.json
  test/testdata/deployednettemplates/recipes/alphanet/net.json
  test/testdata/deployednettemplates/recipes/alphanet/node.json
  test/testdata/deployednettemplates/recipes/alphanet/nonPartNode.json
  test/testdata/deployednettemplates/recipes/alphanet/recipe.json
  test/testdata/deployednettemplates/recipes/alphanet/relay.json
  test/testdata/deployednettemplates/recipes/alphanet/topology.json
Labels: Team Carbon-11

#4147 CICD: update build pipeline for darwin-amd64
  test/muleCI/mule.yaml
Labels: Enhancement

#3781 crypto: remove batch verification flag
  agreement/vote.go
  config/consensus.go
  crypto/batchverifier.go
  crypto/batchverifier_test.go
  crypto/crypto_test.go
  crypto/curve25519.go
  crypto/curve25519_test.go
  crypto/multisig.go
  crypto/multisig_test.go
  crypto/onetimesig.go
  crypto/onetimesig_test.go
  data/transactions/logic/eval.go
  data/transactions/verify/txn.go
  data/transactions/verify/txn_test.go
  node/netprio.go
  test/e2e-go/kmd/e2e_kmd_wallet_keyops_test.go
Labels: Enhancement, Team Sphinx

#4056 Node recovery from stalled Stateproof chain
  config/consensus.go
  crypto/stateproof/builder.go
  crypto/stateproof/structs.go
  data/pools/transactionPool_test.go
  ledger/internal/eval.go
  ledger/ledger_test.go
  ledger/voters.go
  ledger/voters_test.go
  stateproof/builder.go
  stateproof/stateproofMessageGenerator_test.go
  stateproof/worker.go
  stateproof/worker_test.go
  test/e2e-go/features/stateproofs/stateproofs_test.go
Labels: Team Sphinx

#4158 logging: Add a way to inject an external logger.
  logging/log.go
Labels: Enhancement

#4159 goal: Make the -n flag (network name) optional. Get it from template file
  cmd/goal/network.go
  netdeploy/network.go
Labels: Enhancement

#4148 AVM: Provide access to large programs in a txn, for read and inner submit
  data/transactions/logic/README.md
  data/transactions/logic/TEAL_opcodes.md
  data/transactions/logic/assembler_test.go
  data/transactions/logic/eval.go
  data/transactions/logic/evalAppTxn_test.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/fields.go
  data/transactions/logic/fields_string.go
  data/transactions/logic/langspec.json
  data/transactions/logic/opcodes.go
  data/transactions/logic/teal.tmLanguage.json
Labels: New Feature

#4174 merge master into feature/320-rounds
  agreement/vote.go
  cmd/algokey/part.go
  cmd/catchpointdump/net.go
  cmd/goal/account.go
  cmd/goal/messages.go
  cmd/goal/network.go
  cmd/goal/node.go
  cmd/goal/node_test.go
  config/consensus.go
  crypto/batchverifier.go
  crypto/batchverifier_test.go
  crypto/crypto_test.go
  crypto/curve25519.go
  crypto/curve25519_test.go
  crypto/multisig.go
  crypto/multisig_test.go
  crypto/onetimesig.go
  crypto/onetimesig_test.go
  data/transactions/logic/README.md
  data/transactions/logic/TEAL_opcodes.md
  data/transactions/logic/assembler_test.go
  data/transactions/logic/eval.go
  data/transactions/logic/evalAppTxn_test.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/fields.go
  data/transactions/logic/fields_string.go
  data/transactions/logic/langspec.json
  data/transactions/logic/opcodes.go
  data/transactions/logic/teal.tmLanguage.json
  data/transactions/verify/txn.go
  data/transactions/verify/txn_test.go
  logging/log.go
  netdeploy/network.go
  node/netprio.go
  test/e2e-go/kmd/e2e_kmd_wallet_keyops_test.go
  test/muleCI/mule.yaml
Labels: Team Carbon-11

#4175 goal: Allow --signer to send txns from rekeyed accounts
  cmd/goal/account.go
  cmd/goal/application.go
  cmd/goal/asset.go
  cmd/goal/clerk.go
  cmd/goal/common.go
  cmd/goal/interact.go
  cmd/goal/messages.go
  test/scripts/e2e_subs/asset-misc.sh
  test/scripts/e2e_subs/assets-app-b.sh
  test/scripts/e2e_subs/assets-app.sh
  test/scripts/e2e_subs/rekey.sh
  test/scripts/e2e_subs/sectok-app.sh
Labels: Enhancement

#4176 Signature handling more checks and tests
  stateproof/builder.go
  stateproof/worker_test.go
Labels: Team Sphinx

#4193 Metrics: Don't allocate when invoking the Inc() fastpath
  crypto/curve25519.go
Labels: Enhancement

#4194 ledger: Update onlineAccounts lookup methods for slightly easier reading
  ledger/accountdb.go
  ledger/acctonline.go
Labels: Enhancement

#4190 DevOps: Update alphanet topology
  installer/genesis/alphanet/genesis.json
  test/testdata/deployednettemplates/recipes/alphanet/Makefile
  test/testdata/deployednettemplates/recipes/alphanet/gen_topology.py
  test/testdata/deployednettemplates/recipes/alphanet/genesis.json
  test/testdata/deployednettemplates/recipes/alphanet/net.json
  test/testdata/deployednettemplates/recipes/alphanet/topology.json
Labels: Enhancement

#4155 CICD: remove unused genesis in stash
  test/muleCI/mule.yaml
Labels: Enhancement

#4188 CICD: upgrade xcode on circleci macos executors
  .circleci/config.yml
  test/e2e-go/cli/goal/expect/testInfraTest.exp
Labels: Enhancement, unplanned, Team Hyper Flow

#4200 320 rounds: PR feedback fixes
  cmd/catchpointdump/file.go
  ledger/accountdb.go
  ledger/acctonline.go
  ledger/acctupdates.go
  ledger/catchpointtracker.go
  ledger/internal/cow.go
  ledger/ledger.go
  ledger/ledgercore/msgp_gen.go
  ledger/ledgercore/statedelta.go
  ledger/ledgercore/totals.go
  ledger/onlineaccountscache.go
  ledger/testing/randomAccounts.go
  ledger/tracker.go
  ledger/trackerdb.go
  ledger/txtail.go
  ledger/txtail_test.go
Labels: Team Carbon-11
