Repository algorand/go-algorand, pull requests merged in 2022-12, with the labels that each got.

#4834 txHandler: Upgraded txHandler benchmark
  data/txHandler_test.go
  util/metrics/counter.go
  util/metrics/counter_test.go
Labels: Enhancement, Team Carbon-11

#4734 updater: use more-recent installer package
  cmd/updater/update.sh
Labels: Enhancement, unplanned, Team Hyper Flow

#4841 refactor: accountdb.go into a store package (6 of N)
  ledger/accountdb.go
  ledger/accountdb_test.go
  ledger/archival_test.go
  ledger/blockdb_test.go
  ledger/blockqueue.go
  ledger/catchpointtracker.go
  ledger/catchpointtracker_test.go
  ledger/catchupaccessor.go
  ledger/ledger.go
  ledger/msgp_gen.go
  ledger/store/blockdb/blockdb.go
  ledger/store/hashing.go
  ledger/store/hashkind_string.go
  ledger/trackerdb.go
Labels: Team Carbon-11, Skip-Release-Notes

#4788 goal: account deletepartkey subcomand
  cmd/goal/account.go
  daemon/algod/api/client/restClient.go
  libgoal/libgoal.go
  test/e2e-go/features/participation/deletePartKeys_test.go
Labels: New Feature

#4846 refactor: accountdb.go into a store package (7 of N)
  cmd/catchpointdump/database.go
  ledger/accountdb.go
  ledger/accountdb_test.go
  ledger/acctupdates_test.go
  ledger/catchpointtracker.go
  ledger/catchpointtracker_test.go
  ledger/catchpointwriter_test.go
  ledger/catchupaccessor.go
  ledger/ledger.go
  ledger/ledger_test.go
  ledger/store/accountsV2.go
  ledger/store/catchpoint.go
  ledger/store/catchpoint_test.go
  ledger/store/data.go
  ledger/store/data_test.go
  ledger/store/interface.go
  ledger/store/schema.go
  ledger/store/schema_test.go
  ledger/store/testing.go
  ledger/store/trackerdbV2.go
  ledger/trackerdb.go
  ledger/txtail_test.go
  util/db/versioning.go
Labels: Team Carbon-11, Skip-Release-Notes

#4847 algod: Sunset v1 handlers
  Makefile
  daemon/algod/api/README.md
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/common/handlers.go
  daemon/algod/api/server/lib/bundle_swagger_json.sh
  daemon/algod/api/server/lib/bundledSpecInject.go
  daemon/algod/api/server/lib/common.go
  daemon/algod/api/server/router.go
  daemon/algod/api/server/router_test.go
  daemon/algod/api/server/v1/handlers/errors.go
  daemon/algod/api/server/v1/handlers/handlers.go
  daemon/algod/api/server/v1/handlers/handlers_test.go
  daemon/algod/api/server/v1/handlers/responses.go
  daemon/algod/api/server/v1/routes/routes.go
  daemon/algod/api/server/v2/generated/data/routes.go
  daemon/algod/api/server/v2/generated/nonparticipating/private/routes.go
  daemon/algod/api/server/v2/generated/nonparticipating/public/routes.go
  daemon/algod/api/server/v2/generated/participating/private/routes.go
  daemon/algod/api/server/v2/generated/participating/public/routes.go
  daemon/algod/api/spec/v1/model.go
  daemon/algod/api/swagger.json
  daemon/algod/api/swagger.json.validated
  scripts/travis/codegen_verification.sh
  test/framework/fixtures/restClientFixture.go
  test/scripts/e2e_client_runner.py
Labels: Enhancement

#4872 Goal: Test ABI reference arguments during creation
  test/scripts/e2e_subs/e2e-app-abi-method.sh
  test/scripts/e2e_subs/tealprogs/app-abi-method-example.teal
Labels: Enhancement

#4864 refactor: accountdb.go into a store package (9 of N)
  ledger/accountdb.go
  ledger/store/accountsV2.go
Labels: Team Carbon-11, Skip-Release-Notes

#4816 docker: General purpose docker container.
  Dockerfile
  docker/README.md
  docker/files/build/install.sh
  docker/files/build/kmd_config.json.example
  docker/files/run/devmode_template.json
  docker/files/run/future_template.json
  docker/files/run/run.sh
  docker/files/run/template.json
Labels: Enhancement, Team Lamprey

#4839 txHandler: metrics for txpool.Remember
  data/pools/errors.go
  data/pools/transactionPool.go
  data/pools/transactionPool_test.go
  data/transactions/error.go
  data/transactions/logic/eval.go
  data/transactions/logic/eval_test.go
  data/transactions/msgp_gen.go
  data/transactions/transaction.go
  data/transactions/verify/txn.go
  data/transactions/verify/txn_test.go
  data/txHandler.go
  data/txHandler_test.go
  ledger/internal/eval.go
  ledger/ledgercore/error.go
Labels: Enhancement, Team Carbon-11

#4877 txHandler: disable canonical hashmap by default
  config/config_test.go
  config/localTemplate.go
  config/local_defaults.go
  data/txHandler_test.go
  installer/config.json.example
  test/testdata/configs/config-v26.json
Labels: Team Carbon-11, Skip-Release-Notes

#4875 algod: Delete deprecated cost field in dyrun response and mapping field in sourcemap
  cmd/goal/clerk.go
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/dryrun.go
  daemon/algod/api/server/v2/generated/data/routes.go
  daemon/algod/api/server/v2/generated/model/types.go
  daemon/algod/api/server/v2/generated/nonparticipating/private/routes.go
  daemon/algod/api/server/v2/generated/nonparticipating/public/routes.go
  daemon/algod/api/server/v2/generated/participating/private/routes.go
  daemon/algod/api/server/v2/generated/participating/public/routes.go
  data/transactions/logic/sourcemap.go
  test/scripts/e2e_subs/tealprogs/quine.map
Labels: Enhancement

#4879 metrics: fix TestGetValue
  util/metrics/counter_test.go
Labels: Team Carbon-11, Skip-Release-Notes

#4881 metrics: add counters for checkAlreadyCommitted, split "InLedger" counters by reason
  data/txHandler.go
  data/txHandler_test.go
  ledger/internal/cow.go
  ledger/internal/eval.go
  ledger/internal/eval_test.go
  ledger/ledgercore/error.go
  ledger/txtail.go
  ledger/txtail_test.go
Labels: Enhancement

#4862 tests: Remove flaky node tests
  node/node_test.go
Labels: tech debt, Skip-Release-Notes

#4880 algod: Remove unused generated code
  daemon/algod/api/server/v2/generated/private/routes.go
  daemon/algod/api/server/v2/generated/private/types.go
Labels: Skip-Release-Notes

#4882 Catchpoint: Promote trie-related log warnings to error
  ledger/catchpointtracker.go
Labels: Enhancement

#4886 testing: defi txn group benchmark
  data/transactions/verify/artifact_test.go
  data/txntest/defi.go
Labels: Team Carbon-11, Team Scytale, Skip-Release-Notes

#4898 metrics: split alive check counter between early/dead
  data/pools/transactionPool.go
  data/transactions/error.go
  data/transactions/transaction.go
  data/txHandler.go
  data/txHandler_test.go
Labels: Enhancement

#4900 API: Make the data endpoints public.
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/data/data_routes.yml
  daemon/algod/api/server/v2/generated/data/routes.go
Labels: Skip-Release-Notes

#4896 Docs: Update API docs, remove unused codegen configs
  daemon/algod/api/README.md
  daemon/algod/api/generated_server.yml
  daemon/algod/api/generated_types.yml
  daemon/algod/api/private_server.yml
  daemon/algod/api/private_types.yml
Labels: Skip-Release-Notes

#4899 metrics: update some new metric names
  data/transactions/verify/txn.go
  data/txHandler.go
  util/metrics/metrics.go
Labels: Team Carbon-11, Skip-Release-Notes

#4903 Enhancement: Add missing ArgEnum fields, tweaks to immediate note
  cmd/opdoc/opdoc.go
  data/transactions/logic/TEAL_opcodes.md
  data/transactions/logic/doc.go
  data/transactions/logic/langspec.json
Labels: documentation, Enhancement

#4905 tests: fix flaky TestTxHandlerRememberReportErrorsWithTxPool
  data/txHandler_test.go
Labels: Team Carbon-11, Skip-Release-Notes

#4909 DevOps: Adding old artifact cleanup for self-hosted runners
  .circleci/config.yml
Labels: Bug-Fix

#4892 refactor: accountdb.go into a store package (11 of N)
  ledger/catchpointtracker.go
  ledger/catchpointwriter.go
  ledger/store/kvsIter.go
Labels: Team Carbon-11, Skip-Release-Notes

#4856 testing: make MakeAccountData as testing only method
  agreement/agreementtest/simulate_test.go
  daemon/algod/api/server/v2/test/helpers.go
  data/basics/testing/userBalance.go
  data/basics/userBalance.go
  data/common_test.go
  data/ledger_test.go
  ledger/acctonline.go
  ledger/archival_test.go
  ledger/fullblock_perf_test.go
  ledger/ledger_perf_test.go
  ledger/testing/initState.go
Labels: tech debt, Team Carbon-11, Skip-Release-Notes

#4910 rest api: update WaitForBlock summary
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/nonparticipating/public/routes.go
Labels: Enhancement, Team Carbon-11

#4908 Benchmark: Benchmark txHandler with Multisig Txns
  data/accountManager_test.go
  data/ledger_test.go
  data/txHandler_test.go
Labels: Enhancement, Team Carbon-11

#4921 tests: fix dependency on global counters
  data/accountManager_test.go
  data/txHandler_test.go
Labels: Enhancement, Team Carbon-11

#4923 bench: fix benchmarking after remerges
  data/txHandler_test.go
Labels: Team Carbon-11, Skip-Release-Notes

#4925 CICD: go-algorand relstable3.13.1-remerge mergeback
  config/version.go
Labels: Team Hyper Flow, Skip-Release-Notes

#4926 benchmark: Use more common multisig sizes in the benchmark
  data/txHandler_test.go
Labels: Team Carbon-11, Skip-Release-Notes

#4928 Bugfix: removed redundant unlock, potentially causing double unlock
  ledger/acctonline.go
Labels: Bug-Fix

#4932 telemetry: don't report let asyncTelemetryHook wrap and log its own errors
  logging/telemetryhook.go
  logging/telemetryhook_test.go
Labels: Enhancement

#4930 log: stderr offending large log messages
  logging/cyclicWriter.go
Labels: Team Carbon-11, Skip-Release-Notes

#4931 Tests: Fix `t.Parallel()` errors in `data/transactions/logic` package
  .golangci.yml
  data/transactions/logic/assembler_test.go
  data/transactions/logic/backwardCompat_test.go
  data/transactions/logic/blackbox_test.go
  data/transactions/logic/box_test.go
  data/transactions/logic/debugger_test.go
  data/transactions/logic/doc_test.go
  data/transactions/logic/evalAppTxn_test.go
  data/transactions/logic/evalCrypto_test.go
  data/transactions/logic/evalStateful_test.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/jsonspec_test.go
  data/transactions/logic/opcodes_test.go
  data/transactions/logic/parsing_test.go
  data/transactions/logic/sourcemap_test.go
Labels: Enhancement

#4936 go-algorand 3.13.2-beta Release PR
  buildnumber.dat
  logging/cyclicWriter.go
  logging/telemetryhook.go
  logging/telemetryhook_test.go
Labels: Team Hyper Flow

#4937 Tests: Enable more parallel tests in data/transactions/logic/evalAppTxn_test.go
  data/transactions/logic/evalAppTxn_test.go
Labels: Enhancement

#4942 Tests: Switch e2e_basic_start_stop from devnet to private network
  test/scripts/e2e.sh
  test/scripts/e2e_basic_start_stop.sh
  tools/network/resolver_test.go
Labels: Enhancement

#4939 e2e_subs: Remove unused Python cryptography package
  test/scripts/e2e.sh
Labels: Enhancement

#4940 telemetry: don't report ES client errors
  logging/telemetryhook.go
Labels: Enhancement

#4887 Fix catchup stateproof race
  catchup/catchpointService.go
  ledger/acctonline.go
  ledger/acctupdates.go
  ledger/acctupdates_test.go
  ledger/ledger.go
  ledger/ledger_test.go
  ledger/ledgercore/votersForRound.go
  ledger/voters.go
  ledger/voters_test.go
  stateproof/abstractions.go
  stateproof/builder.go
  stateproof/db.go
  stateproof/db_test.go
  stateproof/signer.go
  stateproof/stateproofMessageGenerator_test.go
  stateproof/worker_test.go
  test/e2e-go/features/stateproofs/stateproofs_test.go
  test/testdata/nettemplates/StateProof.json
Labels: Team Sphinx

#4949 Apply StateProof transactions on catchup
  daemon/algod/api/server/v2/test/handlers_test.go
  ledger/apply/apply.go
  ledger/apply/stateproof.go
  ledger/internal/cow_test.go
  ledger/internal/eval.go
  ledger/internal/eval_test.go
  ledger/internal/prefetcher/prefetcher_alignment_test.go
  ledger/ledger_test.go
  stateproof/builder.go
  test/e2e-go/features/catchup/catchpointCatchup_test.go
Labels: Team Sphinx

#4621 Batch-verify: Stream transactions to the verifier
  agreement/asyncVoteVerifier_test.go
  cmd/goal/clerk.go
  crypto/batchverifier.go
  crypto/batchverifier_test.go
  data/ledger.go
  data/transactions/verify/artifact_test.go
  data/transactions/verify/txn.go
  data/transactions/verify/txn_test.go
  data/transactions/verify/verifiedTxnCache.go
  data/transactions/verify/verifiedTxnCache_test.go
  data/txDupCache.go
  data/txDupCache_test.go
  data/txHandler.go
  data/txHandler_test.go
  ledger/ledger.go
  ledger/ledgercore/misc.go
  ledger/notifier.go
  ledger/simulation/simulator.go
  logging/log.go
  logging/log_test.go
  node/node.go
  util/execpool/backlog.go
Labels: Team Carbon-11, New Feature, Performance
