Repository algorand/go-algorand, pull requests merged in 2022-02, with the labels that each got.

#3541 Remove sig abstraction
  cmd/algokey/part.go
  crypto/compactcert/builder_test.go
  crypto/compactcert/committableSignatureSlot.go
  crypto/compactcert/committableSignatureSlot_test.go
  crypto/compactcert/const.go
  crypto/compactcert/msgp_gen.go
  crypto/curve25519_wrapper.go
  crypto/curve25519_wrapper_test.go
  crypto/falconWrapper.go
  crypto/falconWrapper_test.go
  crypto/invalidsigner.go
  crypto/merklesignature/committablePublicKeys.go
  crypto/merklesignature/committablePublicKeys_test.go
  crypto/merklesignature/keysBuilder.go
  crypto/merklesignature/keysBuilder_test.go
  crypto/merklesignature/merkleSignatureScheme.go
  crypto/merklesignature/merkleSignatureScheme_test.go
  crypto/merklesignature/msgp_gen.go
  crypto/merklesignature/msgp_gen_test.go
  crypto/merklesignature/persistentMerkleSignatureScheme.go
  crypto/merklesignature/persistentMerkleSignatureScheme_test.go
  crypto/msgp_gen.go
  crypto/msgp_gen_test.go
  crypto/sig_abstractions.go
  crypto/sig_abstractions_test.go
  daemon/algod/api/server/v2/test/handlers_test.go
  data/account/participation.go
  data/account/participationRegistry.go
  data/account/participationRegistry_test.go
Labels: Team Sphinx

#3551 agreement: verify VotingKeys run time
  agreement/pseudonode.go
Labels: Team Carbon-11

#3550 ledger refactoring: merge master onto feature branch
  agreement/vote.go
  config/consensus.go
  crypto/batchverifier.go
  crypto/batchverifier_test.go
  crypto/compactcert/builder.go
  crypto/compactcert/structs.go
  crypto/compactcert/verifier.go
  crypto/crypto_test.go
  crypto/curve25519.go
  crypto/curve25519_test.go
  crypto/libsodium-fork/src/libsodium/Makefile.am
  crypto/libsodium-fork/src/libsodium/crypto_core/ed25519/ref10/ed25519_ref10.c
  crypto/libsodium-fork/src/libsodium/crypto_core/ed25519/ref10/fe_25_5/base_ge25519.h
  crypto/libsodium-fork/src/libsodium/crypto_core/ed25519/ref10/fe_51/base_ge25519.h
  crypto/libsodium-fork/src/libsodium/crypto_sign/crypto_sign.c
  crypto/libsodium-fork/src/libsodium/crypto_sign/ed25519/ref10/batch.c
  crypto/libsodium-fork/src/libsodium/crypto_sign/ed25519/ref10/open_bv_compat.c
  crypto/libsodium-fork/src/libsodium/crypto_sign/ed25519/ref10/sign_ed25519_ref10.h
  crypto/libsodium-fork/src/libsodium/crypto_sign/ed25519/sign_ed25519.c
  crypto/libsodium-fork/src/libsodium/include/sodium/crypto_sign.h
  crypto/libsodium-fork/src/libsodium/include/sodium/crypto_sign_ed25519.h
  crypto/libsodium-fork/src/libsodium/include/sodium/private/ed25519_ref10.h
  crypto/libsodium-fork/src/libsodium/include/sodium/private/ed25519_ref10_sc_25_5.h
  crypto/libsodium-fork/src/libsodium/include/sodium/private/ed25519_ref10_sc_51.h
  crypto/libsodium-fork/test/default/Makefile.am
  crypto/libsodium-fork/test/default/batch.c
  crypto/libsodium-fork/test/default/batch.exp
  crypto/libsodium-fork/test/default/sign_bv_compat.c
  crypto/libsodium-fork/test/default/sign_bv_compat.exp
  crypto/multisig.go
  crypto/multisig_test.go
  crypto/onetimesig.go
  crypto/onetimesig_test.go
  data/transactions/logic/eval.go
  data/transactions/verify/txn.go
  data/transactions/verify/txn_test.go
  ledger/README.md
  ledger/internal/compactcert.go
  node/netprio.go
  test/e2e-go/kmd/e2e_kmd_wallet_keyops_test.go
Labels: Team Carbon-11

#3460 ledger refactoring: remove assets limits
  config/consensus.go
  data/basics/userBalance_test.go
  ledger/apply/application.go
  ledger/apply/application_test.go
  ledger/apply/asset.go
  ledger/catchpointwriter_test.go
  ledger/evalbench_test.go
  ledger/internal/eval_blackbox_test.go
  netdeploy/remote/deployedNetwork.go
  shared/pingpong/accounts.go
  shared/pingpong/pingpong.go
  test/e2e-go/features/transactions/asset_test.go
Labels: Team Carbon-11

#3561 Optimize catchpointdump utility
  cmd/catchpointdump/file.go
  cmd/catchpointdump/net.go
Labels: Team Carbon-11

#3560 Moving to centos stream 8
  scripts/release/README.md
  scripts/release/test/util/test_package.sh
  test/packages/test_release.sh
  test/platform/test_linux_amd64_compatibility.sh
Labels: Team Hyper Flow

#3558 Removed hard-coded constant in `sortition.go`.
  data/committee/sortition/sortition.go
Labels: quality

#3566 catchpointdump: allow print filters
  cmd/catchpointdump/database.go
  cmd/catchpointdump/file.go
  cmd/catchpointdump/net.go
  cmd/goal/common.go
  cmd/tealdbg/main.go
  cmd/util/cmd.go
Labels: Team Carbon-11

#3573 ledger refactoring: merge master into feature branch
  agreement/pseudonode.go
  cmd/catchpointdump/database.go
  cmd/catchpointdump/file.go
  cmd/catchpointdump/net.go
  cmd/goal/common.go
  cmd/tealdbg/main.go
  cmd/util/cmd.go
  data/committee/sortition/sortition.go
  rpcs/txSyncer.go
  scripts/release/README.md
  scripts/release/test/util/test_package.sh
  test/packages/test_release.sh
  test/platform/test_linux_amd64_compatibility.sh
Labels: Team Carbon-11

#3576 Account sorting in catchpointdump printer
  ledger/accountdb.go
  ledger/acctupdates_test.go
Labels: Team Carbon-11

#3593 address keybuilder issues
  crypto/merklesignature/keysBuilder.go
Labels: Team Sphinx

#3595 update THANKS.md file
  THANKS.md
Labels: Team Carbon-11

#3596 catchpointdump: set genesis proto version
  cmd/catchpointdump/commands.go
  cmd/catchpointdump/file.go
  cmd/catchpointdump/net.go
Labels: Team Carbon-11

#3590 Add catchpointdump into tools package
  .dockerignore
  scripts/build_package.sh
  scripts/create_and_deploy_recipe.sh
Labels: Team Carbon-11

#3598 Add filter fields to catchpointdump net command
  cmd/catchpointdump/net.go
Labels: Team Carbon-11

#3599 Use context instead of an atomic variable
  crypto/merklesignature/keysBuilder.go
  crypto/merklesignature/merkleSignatureScheme_test.go
Labels: Team Sphinx

#3601 update import order
  compactcert/worker.go
  crypto/compactcert/builder_test.go
  crypto/compactcert/committableSignatureSlot_test.go
  crypto/merklesignature/committablePublicKeys.go
  crypto/merklesignature/keysBuilder_test.go
  data/basics/ccertpart.go
  ledger/apply/keyreg_test.go
  util/cmdUtils.go
Labels: Team Sphinx

#3602 fix reviewdog linter error
  data/account/participationRegistry.go
Labels: Team Carbon-11

#3603 Few touchups for Secrets.Persist
  crypto/merklesignature/persistentMerkleSignatureScheme.go
Labels: Team Carbon-11

#3608 fix minor regression in txnMerkleToRaw
  data/bookkeeping/txn_merkle.go
  data/bookkeeping/txn_merkle_test.go
  test/e2e-go/features/transactions/proof_test.go
Labels: Team Carbon-11

#3553 V31 consensus upgrade
  config/consensus.go
  data/account/participation.go
  data/account/participation_test.go
  gen/generate.go
  ledger/accountdb_test.go
  ledger/apply/keyreg_test.go
  protocol/consensus.go
  test/e2e-go/features/participation/onlineOfflineParticipation_test.go
  test/e2e-go/features/participation/participationExpiration_test.go
  test/e2e-go/restAPI/restClient_test.go
  test/e2e-go/upgrades/stateproof_test.go
  test/testdata/nettemplates/TwoNodes50EachV30.json
Labels: High Priority, Team Sphinx

#3575 Moving windows build to Github Actions
  .github/workflows/build.yml
  .travis.yml
Labels: Team Hyper Flow

#3611 testing: rollback changes to ParticipationExpirationTest
  test/e2e-go/features/participation/participationExpiration_test.go
Labels: Team Carbon-11

#3615 revert golang1.16 arm32 changes
  docker/build/cicd.ubuntu.Dockerfile
  test/muleCI/mule.yaml
Labels: Team Hyper Flow

#3616 testing: fix bug in TestParticipationAccountsExpirationFuture/TestParticipationAccountsExpirationNonFuture
  test/e2e-go/features/participation/participationExpiration_test.go
Labels: Team Carbon-11

#3619 add a fallback for missing state proof keys in participation file
  crypto/merklesignature/persistentMerkleSignatureScheme.go
  crypto/merklesignature/persistentMerkleSignatureScheme_test.go
  data/account/account.go
  data/account/participation.go
  data/account/participation_test.go
  node/node.go
  test/e2e-go/upgrades/stateproof_test.go
Labels: Team Sphinx

#3624 testing: improve TestAccountInformationV2
  test/e2e-go/features/transactions/accountv2_test.go
Labels: Team Carbon-11

#3618 ledger-refactoring: testing network template
  test/testdata/deployednettemplates/recipes/catchpoint-verification-s1/README.md
  test/testdata/deployednettemplates/recipes/catchpoint-verification-s1/hosttemplates.json
  test/testdata/deployednettemplates/recipes/catchpoint-verification-s1/recipe.json
  test/testdata/deployednettemplates/recipes/catchpoint-verification-s1/topology.json
  test/testdata/deployednettemplates/recipes/catchpoint-verification-small/README.md
  test/testdata/deployednettemplates/recipes/catchpoint-verification-small/genesis.json
  test/testdata/deployednettemplates/recipes/catchpoint-verification-small/hosttemplates.json
  test/testdata/deployednettemplates/recipes/catchpoint-verification-small/net.json
  test/testdata/deployednettemplates/recipes/catchpoint-verification-small/recipe.json
  test/testdata/deployednettemplates/recipes/catchpoint-verification-small/topology.json
Labels: Team Carbon-11

#3628 remove Parallel from txnproofs and fix timeout bug
  test/e2e-go/features/transactions/proof_test.go
  test/e2e-go/restAPI/restClient_test.go
Labels: Team Sphinx

#3631 testing: fix bug in TestAssetGroupCreateSendDestroy
  test/e2e-go/features/transactions/asset_test.go
Labels: Team Carbon-11

#3629 catchpointdump: load only option
  cmd/catchpointdump/file.go
  cmd/catchpointdump/net.go
Labels: Team Carbon-11

#3623 ledger: fix ledger.Eval code comments
  ledger/internal/eval.go
  ledger/internal/eval_blackbox_test.go
  ledger/internal/eval_test.go
Labels: Team Carbon-11

#3638 DevOps: Fix bandwidth testing
  test/testdata/deployednettemplates/recipes/custom/configs/node.json
  test/testdata/deployednettemplates/recipes/custom/configs/nonPartNode.json
  test/testdata/deployednettemplates/recipes/scenario2/node.json
  test/testdata/deployednettemplates/recipes/scenario2/nonPartNode.json
Labels: enhancement

#3643 add StateProofID to AccountData.ClearOnlineState()
  data/basics/userBalance.go
  ledger/internal/eval_test.go
Labels: Team Carbon-11

#3648 Add addrid resolution comments
  ledger/accountdb.go
Labels: Team Carbon-11

#3656 ledger refactoring: fix linter detected issues
  ledger/acctupdates_test.go
  ledger/catchpointtracker.go
  ledger/catchpointtracker_test.go
Labels: Team Carbon-11

#3657 ledger refactoring: cleanup StateDelta
  ledger/internal/appcow.go
  ledger/internal/assetcow.go
  ledger/internal/cow.go
  ledger/internal/eval_blackbox_test.go
  ledger/ledgercore/statedelta.go
Labels: Team Carbon-11

#3651 testing: Fix a typo in agreement test
  agreement/asyncVoteVerifier_test.go
Labels: Team Carbon-11

#3664 dryrun: add gloads test
  daemon/algod/api/server/v2/dryrun_test.go
Labels: Team Carbon-11

#3670 ledger refactoring: few CR fixes
  data/basics/userBalance.go
  ledger/accountdb_test.go
  ledger/apply/application_test.go
  ledger/internal/appcow_test.go
  ledger/ledgercore/statedelta_test.go
Labels: Team Carbon-11

#3663 ledger refactoring: update evaluator benchmarks
  ledger/evalbench_test.go
  ledger/testing/testGenesis.go
Labels: Team Carbon-11

#3645 CICD: Adding PR Type label checker
  .github/workflows/pr-type-category.yml
Labels: unplanned, Team Hyper Flow, New Feature

#3662 Decrease partkey rounds to 3mil for feature networks
  test/testdata/deployednettemplates/recipes/feature-networks/genesis.json
Labels: bug, Team Hyper Flow

#3639 goal node create improvements
  Makefile
  cmd/goal/bundle_genesis_json.sh
  cmd/goal/bundledGenesisInject.go
  cmd/goal/node.go
  config/localTemplate.go
Labels: Team Carbon-11

#3632 API: Fix prove bug on API
  crypto/merklearray/proof.go
  crypto/merklearray/proof_test.go
  daemon/algod/api/server/v2/handlers.go
  test/e2e-go/features/transactions/proof_test.go
Labels: Team Sphinx, Bug-Fix

#3661 algod : deregister metrics tracker on close
  ledger/metrics.go
  ledger/metrics_test.go
  util/metrics/counter.go
  util/metrics/registry.go
  util/metrics/service.go
Labels: Team Carbon-11, Bug-Fix

#3673 ledger refactoring: merge master into ledger refactoring branch
  .github/workflows/pr-type-category.yml
  Makefile
  cmd/goal/bundle_genesis_json.sh
  cmd/goal/bundledGenesisInject.go
  cmd/goal/node.go
  config/localTemplate.go
  crypto/merklearray/proof.go
  crypto/merklearray/proof_test.go
  daemon/algod/api/server/v2/dryrun_test.go
  daemon/algod/api/server/v2/handlers.go
  ledger/metrics.go
  ledger/metrics_test.go
  test/e2e-go/features/transactions/proof_test.go
  test/testdata/deployednettemplates/recipes/feature-networks/genesis.json
  util/metrics/counter.go
  util/metrics/registry.go
  util/metrics/service.go
Labels: Enhancement, Team Carbon-11

#3665 Algod: Compcert signature version
  crypto/compactcert/builder.go
  crypto/compactcert/builder_test.go
  crypto/compactcert/msgp_gen.go
  crypto/compactcert/structs.go
  crypto/compactcert/verifier.go
  crypto/falconWrapper.go
  crypto/falconWrapper_test.go
  crypto/merklesignature/merkleSignatureScheme.go
  crypto/merklesignature/merkleSignatureScheme_test.go
Labels: Enhancement, Team Sphinx

#3675 CICD: Limit PR Type and Category check to master branch
  .github/workflows/pr-type-category.yml
Labels: Team Hyper Flow, Bug-Fix

#3676 REST API: rename new total fields to "total-X-opted-in"
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/account.go
  daemon/algod/api/server/v2/generated/private/routes.go
  daemon/algod/api/server/v2/generated/private/types.go
  daemon/algod/api/server/v2/generated/routes.go
  daemon/algod/api/server/v2/generated/types.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_resources_test.go
Labels: Enhancement

#3677 ledger refactoring: make changes per CR
  ledger/accountdb.go
  ledger/accountdb_test.go
  ledger/acctupdates.go
Labels: Enhancement, Team Carbon-11

#3678 ledger refactoring: update tests
  ledger/internal/eval_blackbox_test.go
Labels: Enhancement, Team Carbon-11

#3654 DevOps: Regen net.json for scenario2 test to include api endpoints for nodes.
  test/testdata/deployednettemplates/recipes/custom/configs/node.json
  test/testdata/deployednettemplates/recipes/custom/configs/nonPartNode.json
  test/testdata/deployednettemplates/recipes/scenario2/net.json
  test/testdata/deployednettemplates/recipes/scenario2/node.json
  test/testdata/deployednettemplates/recipes/scenario2/nonPartNode.json
Labels: Enhancement, unplanned, Team Hyper Flow

#3674 ledger refactoring: make consensus upgrade
  config/consensus.go
  protocol/consensus.go
Labels: Enhancement, Team Carbon-11

#3683 testing: fix randomly failing TestPseudonodeFailedEnqueuedTasks
  agreement/pseudonode_test.go
Labels: Team Carbon-11, Bug-Fix

#3680 txnsync : merge master to feature branch
  .circleci/config.yml
  .github/workflows/pr-type-category.yml
  Makefile
  agreement/asyncVoteVerifier_test.go
  cmd/goal/bundle_genesis_json.sh
  cmd/goal/bundledGenesisInject.go
  cmd/goal/node.go
  cmd/tealdbg/cdtSession.go
  cmd/tealdbg/cdtSession_test.go
  cmd/tealdbg/cdtState.go
  cmd/tealdbg/debugger.go
  cmd/tealdbg/local.go
  config/localTemplate.go
  crypto/merklearray/proof.go
  crypto/merklearray/proof_test.go
  crypto/secp256k1/secp256_test.go
  daemon/algod/api/server/v2/dryrun_test.go
  daemon/algod/api/server/v2/handlers.go
  data/basics/userBalance.go
  data/transactions/logic/debugger.go
  data/transactions/logic/eval.go
  data/transactions/logic/evalAppTxn_test.go
  data/transactions/logic/eval_test.go
  ledger/accountdb_test.go
  ledger/internal/apptxn_test.go
  ledger/internal/eval.go
  ledger/internal/eval_blackbox_test.go
  ledger/internal/eval_test.go
  ledger/metrics.go
  ledger/metrics_test.go
  test/e2e-go/features/transactions/proof_test.go
  test/testdata/deployednettemplates/recipes/custom/configs/node.json
  test/testdata/deployednettemplates/recipes/feature-networks/genesis.json
  test/testdata/deployednettemplates/recipes/scenario2/net.json
  test/testdata/deployednettemplates/recipes/scenario2/node.json
  util/metrics/counter.go
  util/metrics/registry.go
  util/metrics/service.go
Labels: Team Carbon-11

#3666 ledger refactoring: implement account data and resources prefetcher
  ledger/evalbench_test.go
  ledger/internal/eval.go
  ledger/internal/evalprefetcher.go
  ledger/internal/evalprefetcher_test.go
Labels: Enhancement, Team Carbon-11

#3644 Algod: remove batch verification flag from the compact certs struct
  crypto/compactcert/structs.go
  ledger/internal/compactcert.go
Labels: Enhancement, Team Sphinx

#3684 Algod: use updated sumhash lib
  go.mod
  go.sum
Labels: Team Sphinx, Bug-Fix

#3679 REST API: split msgpack API type AccountResourceModel into two
  cmd/goal/application.go
  cmd/goal/interact.go
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/client/restClient.go
  daemon/algod/api/server/v2/generated/private/routes.go
  daemon/algod/api/server/v2/generated/routes.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/spec/v2/model.go
  daemon/algod/api/spec/v2/msgp_gen.go
  daemon/algod/api/spec/v2/msgp_gen_test.go
  ledger/msgp_gen.go
  libgoal/libgoal.go
Labels: Team Carbon-11

#3692 Algod: compcert unit test error check fix
  ledger/internal/compactcert.go
  ledger/internal/compactcert_test.go
Labels: test, Team Sphinx

#3690 Algod: compcert sig struct refactor
  crypto/compactcert/builder.go
  crypto/compactcert/builder_test.go
  crypto/compactcert/committableSignatureSlot.go
  crypto/compactcert/committableSignatureSlot_test.go
  crypto/compactcert/msgp_gen.go
  crypto/compactcert/msgp_gen_test.go
  crypto/compactcert/structs.go
  crypto/compactcert/verifier.go
Labels: Enhancement, Team Sphinx

#3689 Tools: Add 'algokey part keyreg'
  cmd/algokey/keyreg.go
  cmd/algokey/part.go
  test/scripts/e2e_subs/keyreg.sh
Labels: New Feature, New-Feature
