Repository algorand/go-algorand, pull requests merged in 2023-04, with the labels that each got.

#5214 ledger: fix commit tasks enqueueing
  ledger/catchpointtracker_test.go
  ledger/tracker.go
  ledger/txtail_test.go
Labels: Team Carbon-11, Bug-Fix

#5246 algod: Limit request body size to 10MB
  daemon/algod/api/server/router.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_test.go
  test/scripts/e2e_subs/e2e-app-simulate.sh
Labels: Enhancement

#5243 Algod: rename crypto-stateproof-builder to crypto-stateproof-prover
  crypto/stateproof/msgp_gen.go
  crypto/stateproof/msgp_gen_test.go
  crypto/stateproof/prover.go
  crypto/stateproof/prover_test.go
  data/pools/transactionPool_test.go
  stateproof/builder.go
  stateproof/db.go
  stateproof/db_test.go
  stateproof/msgp_gen.go
  stateproof/msgp_gen_test.go
  stateproof/signer.go
  stateproof/verify/stateproof.go
  stateproof/worker.go
  stateproof/worker_test.go
Labels: Skip-Release-Notes

#5252 AVM: Avoid panics in disassembly when branch instructions are short
  data/transactions/logic/assembler.go
  data/transactions/logic/assembler_test.go
Labels: Bug-Fix

#5256 tests: Change truncate to dd for mac amd tests
  test/scripts/e2e_subs/e2e-app-simulate.sh
Labels: Bug-Fix

#5253 Algod: Minor refactoring REST client `submitForm` from go-sdk PR #335
  daemon/algod/api/client/restClient.go
  data/transactions/logic/sourcemap.go
  libgoal/teal.go
  test/e2e-go/features/teal/compile_test.go
Labels: Enhancement

#5262 algocfg(profile): Add file name to config file conflict message.
  cmd/algocfg/profileCommand.go
Labels: Enhancement, Team Lamprey

#5259 goal: Better formatting in `goal clerk simulate`
  cmd/goal/clerk.go
  daemon/algod/api/client/restClient.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/handlers_test.go
  daemon/algod/api/server/v2/utils.go
  libgoal/libgoal.go
  test/e2e-go/restAPI/restClient_test.go
Labels: Bug-Fix

#5263 tests: Change `dd` argument to use a bytes value
  test/scripts/e2e_subs/e2e-app-simulate.sh
Labels: Bug-Fix

#5251 Bugfix: Follower's Initial Sync Round
  ledger/ledger.go
  ledger/tracker.go
  node/follower_node.go
  node/follower_node_test.go
  test/e2e-go/features/followerNode/syncRestart_test.go
  test/testdata/nettemplates/TwoNodesFollower100SecondMaxAccountLookback2.json
Labels: Bug-Fix

#5035 AVM: Share resource arrays across transactions
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/data/routes.go
  daemon/algod/api/server/v2/generated/experimental/routes.go
  daemon/algod/api/server/v2/generated/model/types.go
  daemon/algod/api/server/v2/generated/nonparticipating/private/routes.go
  daemon/algod/api/server/v2/generated/nonparticipating/public/routes.go
  daemon/algod/api/server/v2/generated/participating/private/routes.go
  daemon/algod/api/server/v2/generated/participating/public/routes.go
  daemon/algod/api/server/v2/utils.go
  data/transactions/application.go
  data/transactions/application_test.go
  data/transactions/logic/README.md
  data/transactions/logic/README_in.md
  data/transactions/logic/TEAL_opcodes.md
  data/transactions/logic/assembler_test.go
  data/transactions/logic/box_test.go
  data/transactions/logic/doc.go
  data/transactions/logic/eval.go
  data/transactions/logic/evalAppTxn_test.go
  data/transactions/logic/evalStateful_test.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/export_test.go
  data/transactions/logic/fields_test.go
  data/transactions/logic/langspec.json
  data/transactions/logic/ledger_test.go
  data/transactions/logic/opcodes.go
  data/transactions/logic/resources.go
  data/transactions/logic/resources_test.go
  data/transactions/msgp_gen.go
  data/transactions/teal.go
  ledger/apptxn_test.go
  ledger/boxtxn_test.go
  ledger/eval/cow.go
  ledger/eval/cow_creatables.go
  ledger/eval_simple_test.go
  ledger/simple_test.go
  ledger/testing/consensusRange.go
  test/scripts/e2e_subs/shared-resources.py
Labels: Enhancement

#5271 AVM: Avoid panics while type checking bad immediates
  data/transactions/logic/assembler.go
  data/transactions/logic/assembler_test.go
Labels: Bug-Fix

#5270 docker: disable rewards in devmode template
  docker/files/run/devmode_template.json
Labels: Enhancement

#5294 chore: Focus CONTRIBUTING.md on code contributions.
  CONTRIBUTING.md
  README.md
Labels: Enhancement

#5257 tools: new endpoints for block generator
  tools/block-generator/generator/generate.go
  tools/block-generator/generator/generate_test.go
  tools/block-generator/generator/server.go
  tools/block-generator/generator/server_test.go
  tools/block-generator/generator/utils.go
  tools/block-generator/generator/utils_test.go
  tools/block-generator/runner/run.go
Labels: Enhancement, Team Lamprey

#5301 Fix: broken links (correct md link syntax) in contributing.md
  CONTRIBUTING.md
Labels: Bug-Fix, Skip-Release-Notes

#5300 ledger: Check MaxAcctLookback in tracker.
  ledger/tracker.go
Labels: Enhancement

#5265 chore: Rename ModStateProofNextRound to StateProofNext.
  ledger/apply/stateproof_test.go
  ledger/eval/cow.go
  ledger/ledger_test.go
  ledger/ledgercore/statedelta.go
  ledger/ledgercore/statedelta_test.go
  ledger/spverificationtracker.go
  ledger/spverificationtracker_test.go
Labels: Team Lamprey, Bug-Fix

#5268 network: enforce maximum header size on outgoing ws conns
  go.mod
  go.sum
  network/wsNetwork.go
  network/wsNetwork_test.go
Labels: Enhancement, Team Carbon-11

#5260 scripts: enhance upload_config.sh
  scripts/upload_config.sh
Labels: Enhancement, tech debt, Team Carbon-11

#5266 ledger: fix error shadowing in accountsNewRound
  ledger/acctdeltas.go
  ledger/acctdeltas_test.go
Labels: Team Carbon-11, Bug-Fix

#5292 algod: Modify simulate endpoint request type
  cmd/goal/clerk.go
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/client/restClient.go
  daemon/algod/api/server/v2/generated/data/routes.go
  daemon/algod/api/server/v2/generated/experimental/routes.go
  daemon/algod/api/server/v2/generated/model/types.go
  daemon/algod/api/server/v2/generated/nonparticipating/private/routes.go
  daemon/algod/api/server/v2/generated/nonparticipating/public/routes.go
  daemon/algod/api/server/v2/generated/participating/private/routes.go
  daemon/algod/api/server/v2/generated/participating/public/routes.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/handlers_test.go
  daemon/algod/api/server/v2/test/handlers_test.go
  libgoal/libgoal.go
  test/e2e-go/restAPI/restClient_test.go
  test/scripts/e2e_subs/e2e-app-simulate.sh
Labels: Enhancement

#5276 docker: Updated user and data dir handling.
  Dockerfile
  docker/README.md
  docker/files/run/run.sh
Labels: Enhancement

#5307 docs: remove outdated personal statements
  docs/agreement_service.md
Labels: documentation, external contribution, Skip-Release-Notes

#5317 docs: update agreement README with committableEvent
  agreement/README.md
Labels: external contribution, Skip-Release-Notes

#5296 algod: Allow timestamp offsets in dev mode
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/errors.go
  daemon/algod/api/server/v2/generated/data/routes.go
  daemon/algod/api/server/v2/generated/experimental/routes.go
  daemon/algod/api/server/v2/generated/model/types.go
  daemon/algod/api/server/v2/generated/nonparticipating/private/routes.go
  daemon/algod/api/server/v2/generated/nonparticipating/public/routes.go
  daemon/algod/api/server/v2/generated/participating/private/routes.go
  daemon/algod/api/server/v2/generated/participating/public/routes.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_resources_test.go
  daemon/algod/api/server/v2/test/handlers_test.go
  daemon/algod/api/server/v2/test/helpers.go
  node/follower_node.go
  node/node.go
Labels: Enhancement

#5306 tools: update block-generator to use conduit binary
  tools/block-generator/generator/generate.go
  tools/block-generator/generator/generate_test.go
  tools/block-generator/generator/server_test.go
  tools/block-generator/metrics/metrics.go
  tools/block-generator/run_generator.sh
  tools/block-generator/run_postgres.sh
  tools/block-generator/run_runner.sh
  tools/block-generator/run_tests.sh
  tools/block-generator/runner/metrics_collector.go
  tools/block-generator/runner/run.go
  tools/block-generator/runner/runner.go
  tools/block-generator/runner/template/conduit.yml.tmpl
Labels: Enhancement

#5291 docs: increase heading levels, thus only one h1 is used
  agreement/README.md
Labels: Enhancement, external contribution

#5323 docker: add profile support and improved endpoint access.
  docker/README.md
  docker/files/run/run.sh
Labels: Enhancement

#5325 Algod: Better Box Reference Error Message
  data/transactions/logic/box.go
  data/transactions/logic/box_test.go
  data/transactions/logic/ledger_test.go
  ledger/boxtxn_test.go
  ledger/eval/applications.go
Labels: Enhancement

#5324 algocfg(profile): improve invalid profile error message.
  cmd/algocfg/profileCommand.go
  cmd/algocfg/profileCommand_test.go
Labels: Enhancement

#5247 Algod: Simulation run with increased limits on logs
  cmd/goal/clerk.go
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/data/routes.go
  daemon/algod/api/server/v2/generated/experimental/routes.go
  daemon/algod/api/server/v2/generated/model/types.go
  daemon/algod/api/server/v2/generated/nonparticipating/private/routes.go
  daemon/algod/api/server/v2/generated/nonparticipating/public/routes.go
  daemon/algod/api/server/v2/generated/participating/private/routes.go
  daemon/algod/api/server/v2/generated/participating/public/routes.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/helpers.go
  daemon/algod/api/server/v2/utils.go
  data/transactions/logic/eval.go
  ledger/simulation/simulation_eval_test.go
  ledger/simulation/simulator.go
  ledger/simulation/trace.go
  ledger/simulation/tracer.go
  node/follower_node.go
  node/follower_node_test.go
  node/node.go
  test/e2e-go/restAPI/restClient_test.go
  test/scripts/e2e_subs/e2e-app-simulate.sh
  test/scripts/e2e_subs/tealprogs/logs-a-lot.teal
Labels: New Feature

#5279 docs: add titles of subsystems, minor md fixes
  README.md
Labels: documentation, Enhancement, external contribution

#5333 Test: Improve flaky test from non-deterministic order string
  cmd/algocfg/profileCommand_test.go
Labels: Bug-Fix

#5322 docs: Fix bug label
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: Enhancement

#5334 tests: Fix devmode test
  daemon/algod/api/client/restClient.go
  test/e2e-go/features/devmode/devmode_test.go
Labels: Enhancement

#5336 AVM: Show opcode context for logicsigs (not just apps)
  config/consensus.go
  data/transactions/logic/backwardCompat_test.go
  data/transactions/logic/eval.go
  data/transactions/logic/eval_test.go
  data/transactions/verify/txn.go
  ledger/apply/application.go
  ledger/apply/application_test.go
  ledger/boxtxn_test.go
  ledger/eval/appcow.go
  ledger/eval/cow.go
  ledger/ledgercore/error.go
Labels: Enhancement

#5335 Simulate: Make optional signatures an opt-in feature
  cmd/goal/clerk.go
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/data/routes.go
  daemon/algod/api/server/v2/generated/experimental/routes.go
  daemon/algod/api/server/v2/generated/model/types.go
  daemon/algod/api/server/v2/generated/nonparticipating/private/routes.go
  daemon/algod/api/server/v2/generated/nonparticipating/public/routes.go
  daemon/algod/api/server/v2/generated/participating/private/routes.go
  daemon/algod/api/server/v2/generated/participating/public/routes.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_test.go
  daemon/algod/api/server/v2/utils.go
  data/transactions/verify/txn.go
  data/transactions/verify/txnBatch.go
  ledger/simulation/simulation_eval_test.go
  ledger/simulation/simulator.go
  ledger/simulation/simulator_test.go
  ledger/simulation/trace.go
  ledger/simulation/tracer.go
  test/e2e-go/restAPI/restClient_test.go
  test/scripts/e2e_subs/e2e-app-simulate.sh
Labels: Enhancement

#5297 EvalTracer: Txn group deltas Tracer
  config/localTemplate.go
  config/local_defaults.go
  data/transactions/logic/debugger.go
  data/transactions/logic/eval.go
  data/transactions/logic/mocktracer/tracer.go
  data/transactions/logic/tracer.go
  installer/config.json.example
  ledger/eval/eval.go
  ledger/eval/eval_test.go
  ledger/eval/txntracer.go
  ledger/eval/txntracer_test.go
  ledger/evalbench_test.go
  ledger/fullblock_perf_test.go
  ledger/ledger.go
  ledger/ledger_perf_test.go
  ledger/ledger_test.go
  ledger/simulation/tracer.go
  ledger/simulation/tracer_test.go
Labels: New Feature

#5340 REST: add the round number to algod box endpoint repsonse
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/data/routes.go
  daemon/algod/api/server/v2/generated/experimental/routes.go
  daemon/algod/api/server/v2/generated/model/types.go
  daemon/algod/api/server/v2/generated/nonparticipating/private/routes.go
  daemon/algod/api/server/v2/generated/nonparticipating/public/routes.go
  daemon/algod/api/server/v2/generated/participating/private/routes.go
  daemon/algod/api/server/v2/generated/participating/public/routes.go
  daemon/algod/api/server/v2/handlers.go
  test/e2e-go/restAPI/restClient_test.go
Labels: Enhancement

#5295 Enhancement: Only look back to FirstValid for pending transactions that were found in the pool
  node/node.go
Labels: Enhancement

#5321 tools: search/replace indexer/conduit in block-generator
  tools/block-generator/README.md
  tools/block-generator/generator/generate.go
  tools/block-generator/generator/utils.go
  tools/block-generator/run_tests.sh
  tools/block-generator/runner/run.go
  tools/block-generator/runner/runner.go
Labels: Enhancement
