Repository algorand/go-algorand, pull requests merged in 2023-09, with the labels that each got.

#5706 Feature: Disable EnableBlockServiceFallbackToArchiver by default.
  catchup/universalFetcher_test.go
  config/localTemplate.go
  config/local_defaults.go
  installer/config.json.example
  network/wsNetwork_test.go
  rpcs/blockService_test.go
  test/testdata/configs/config-v31.json
Labels: Enhancement

#5703 merklearray: simplify single-leaf proofs
  crypto/merklearray/proof.go
  crypto/merklearray/proof_test.go
  daemon/algod/api/server/v2/test/handlers_test.go
  test/framework/fixtures/libgoalFixture.go
Labels: Skip-Release-Notes

#5721 p2p: Make p2p listen address configurable via config.NetAddress
  network/p2p/p2p.go
  network/p2p/p2p_test.go
Labels: Enhancement, Team Carbon-11, p2p

#5717 chore: fix misspelled filename
  ledger/store/trackerdb/sqlitedriver/merkle_committer.go
Labels: Skip-Release-Notes

#5672 goal: Add export and import options for genesis files during network creation
  cmd/goal/network.go
  netdeploy/network.go
  netdeploy/networkTemplate.go
  netdeploy/networkTemplates_test.go
  test/e2e-go/features/privatenet/privatenet_test.go
  test/framework/fixtures/goalFixture.go
  test/scripts/test_private_network.sh
Labels: Enhancement

#5686 Simulate: Return application initial states accessed during simulation
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/data/routes.go
  daemon/algod/api/server/v2/generated/experimental/routes.go
  daemon/algod/api/server/v2/generated/model/types.go
  daemon/algod/api/server/v2/generated/nonparticipating/private/routes.go
  daemon/algod/api/server/v2/generated/nonparticipating/public/routes.go
  daemon/algod/api/server/v2/generated/participating/private/routes.go
  daemon/algod/api/server/v2/generated/participating/public/routes.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/utils.go
  data/transactions/logic/assembler.go
  data/transactions/logic/opcodeExplain.go
  data/transactions/logic/opcodes.go
  ledger/simulation/initialStates.go
  ledger/simulation/simulation_eval_test.go
  ledger/simulation/trace.go
  ledger/simulation/tracer.go
  test/e2e-go/restAPI/helpers.go
  test/e2e-go/restAPI/other/appsRestAPI_test.go
  test/e2e-go/restAPI/restClient_test.go
  test/e2e-go/restAPI/simulate/simulateRestAPI_test.go
  test/e2e-go/restAPI/stateproof/stateproofRestAPI_test.go
  util/set.go
Labels: Team Scytale, New Feature

#5731 tests: update TestCatchupOverGossip to be less parallel and use sub-tests
  test/e2e-go/features/catchup/basicCatchup_test.go
Labels: Enhancement

#5733 CICD: go-algorand relstable3.18.0-remerge mergeback
  config/version.go
Labels: Team Hyper Flow, Skip-Release-Notes

#5736 p2p: remove TestP2PThreeNodesEvenDist
  test/e2e-go/features/p2p/p2p_basic_test.go
Labels: test, Skip-Release-Notes, p2p

#5737 tests: fix a rare data race in staling tracker tests
  ledger/acctonline_test.go
  ledger/acctupdates_test.go
  ledger/catchpointtracker_test.go
Labels: Skip-Release-Notes

#5738 tests: fix flaky simulate test
  test/e2e-go/restAPI/simulate/simulateRestAPI_test.go
Labels: Skip-Release-Notes

#5725 chore: Refactor catchpoint tracking logic into config
  config/config.go
  config/config_test.go
  config/localTemplate.go
  ledger/acctupdates.go
  ledger/catchpointtracker.go
Labels: Enhancement

#5742 DevOps: update releases page GPG key mentions
  scripts/release/mule/deploy/releases_page/html.tpl
Labels: Enhancement, Team Hyper Flow

#5714 tools: Block Generator - allow exporting to files
  tools/block-generator/Makefile
  tools/block-generator/README.md
  tools/block-generator/generator/daemon.go
  tools/block-generator/generator/server.go
  tools/block-generator/runner/run.go
  tools/block-generator/runner/runner.go
  tools/block-generator/runner/template/conduit_file_exporter.tmpl
  tools/block-generator/runner/template/conduit_pg_exporter.tmpl
  tools/block-generator/scripts/run_runner.py
Labels: Enhancement

#5735 docker: Support pregenerated keys in docker private networks
  cmd/goal/network.go
  docker/README.md
  docker/files/run/run.sh
Labels: New Feature

#5746 DevOps: fix releases page links
  scripts/release/mule/deploy/releases_page/generate_releases_page.py
  scripts/release/mule/deploy/rpm/deploy.sh
Labels: Team Hyper Flow, Bug-Fix

#5745 windows: Fix GC
  tools/network/dnssec/config_windows.go
Labels: Bug-Fix

#5751 Specs: Change spec generation for Foundation to handle _v*.md
  data/transactions/logic/Makefile
Labels: Bug-Fix

#5753 Docs: No code change
  data/transactions/logic/assembler.go
Labels: Skip-Release-Notes

#5752 api: StartFastCatchup initialize parameter
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/errors.go
  daemon/algod/api/server/v2/generated/model/types.go
  daemon/algod/api/server/v2/generated/nonparticipating/private/routes.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_test.go
Labels: Enhancement

#5729 docs: Update node config comments so that they can be used for doc generation.
  config/localTemplate.go
Labels: Enhancement

#5754 goal: Add initialize option to 'goal node catchup'.
  cmd/goal/node.go
  daemon/algod/api/client/restClient.go
  libgoal/libgoal.go
  test/e2e-go/features/catchup/catchpointCatchup_test.go
  test/e2e-go/features/catchup/stateproofsCatchup_test.go
Labels: Enhancement

#5758 Tests: Address flakiness with TestMergePrimarySecondaryRelayAddressListsPartialOverlap
  network/wsNetwork_test.go
  tools/network/dnssec/config_windows.go
Labels: Enhancement

#5760 perf: upgrade go-deadlock
  go.mod
  go.sum
  tools/block-generator/go.mod
  tools/block-generator/go.sum
Labels: Enhancement, Performance

#5761 tools: better heap data rendering
  test/heapwatch/client_ram_report.py
  test/heapwatch/plot_crr_csv.py
Labels: Bug-Fix

#5749 config: Add MaxBlockHistoryLookback option
  config/localTemplate.go
  config/local_defaults.go
  installer/config.json.example
  ledger/ledger.go
  ledger/ledger_test.go
  test/testdata/configs/config-v31.json
Labels: Enhancement

#5762 docker: Update docker config with node_exporter path.
  docker/files/run/run.sh
Labels: Bug-Fix

#5756 docker: Do not catchup if already initialized.
  cmd/goal/node.go
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/client/restClient.go
  daemon/algod/api/server/v2/generated/model/types.go
  daemon/algod/api/server/v2/generated/nonparticipating/private/routes.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_test.go
  docker/files/run/run.sh
  libgoal/libgoal.go
Labels: Bug-Fix

#5764 ci: fix scripts/create_and_deploy_recipe.sh build
  docker/build/Dockerfile-deploy
  scripts/upload_config.sh
Labels: Bug-Fix
