Repository algorand/go-algorand, pull requests merged in 2023-02, with the labels that each got.

#5009 node: Add follower node for sync mode
  catchup/service.go
  config/localTemplate.go
  config/local_defaults.go
  daemon/algod/api/client/restClient.go
  daemon/algod/api/server/lib/common.go
  daemon/algod/api/server/router.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_test.go
  daemon/algod/server.go
  installer/config.json.example
  libgoal/libgoal.go
  node/error.go
  node/follower_node.go
  node/follower_node_test.go
  node/node.go
  test/e2e-go/features/followerNode/syncDeltas_test.go
Labels: Enhancement

#5017 goal: allow ConfigJSONOverride in local network templates
  netdeploy/networkTemplate.go
  netdeploy/networkTemplates_test.go
  netdeploy/remote/nodeConfig.go
  test/testdata/nettemplates/perf/mkconf.py
Labels: Enhancement, Team Carbon-11

#5070 algod: split SetFdSoftLimit calls for relay and non-relay nodes
  config/config_test.go
  config/localTemplate.go
  daemon/algod/server.go
  network/wsNetwork.go
  util/util.go
  util/util_windows.go
Labels: Enhancement, Team Carbon-11

#4984 container: support kmd
  .github/workflows/container.yml
  Dockerfile
  docker/README.md
  docker/files/run/kmd_config.json.example
  docker/files/run/run.sh
Labels: Enhancement

#4517 network: Ignore invalid tags
  agreement/service_test.go
  logging/telemetryspec/event.go
  network/wsNetwork.go
  network/wsNetwork_test.go
  network/wsPeer.go
  network/wsPeer_test.go
  protocol/hash_test.go
  protocol/tags.go
  protocol/tags_test.go
  rpcs/blockService.go
  tools/debug/algodump/main.go
  util/metrics/metrics.go
Labels: Enhancement, Team Carbon-11

#4891 Goal: goal network create default templates
  cmd/goal/defaultNetworkTemplate.json
  cmd/goal/network.go
  netdeploy/network.go
  netdeploy/networkTemplate.go
  test/framework/fixtures/libgoalFixture.go
  test/scripts/test_private_network.sh
Labels: Enhancement

#5093 ledger: turn deferredCommitContext.newBase into a function
  ledger/acctonline.go
  ledger/acctonline_test.go
  ledger/acctupdates.go
  ledger/acctupdates_test.go
  ledger/catchpointtracker.go
  ledger/tracker.go
  ledger/txtail.go
  ledger/txtail_test.go
Labels: Enhancement

#5095 docs: link to security doc, minor formatting
  CONTRIBUTING.md
Labels: external contribution, Skip-Release-Notes

#5084 API: Incorrect KvDelta in StateDeltaToLedgerDelta
  daemon/algod/api/server/v2/delta.go
  daemon/algod/api/server/v2/delta_test.go
Labels: Team Lamprey, Bug-Fix

#5101 stateproof: e2e flakey-test AttestorsChange
  test/e2e-go/features/stateproofs/stateproofs_test.go
Labels: Team Sphinx

#5100 goal: fix for goal node status crash - no longer getting block
  daemon/algod/api/server/v2/handlers.go
Labels: Team Lamprey, Bug-Fix

#5096 fix(gha): disable update-repo-description
  .github/workflows/container.yml
Labels: Skip-Release-Notes

#5102 go-algorand v3.14.2-beta Release PR
  buildnumber.dat
  config/config_test.go
  config/localTemplate.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/server.go
  network/wsNetwork.go
  util/util.go
  util/util_windows.go
Labels: Team Hyper Flow

#5099 ledger: eternalData trackers concept
  ledger/README.md
  ledger/bulletin.go
  ledger/bulletin_test.go
  ledger/ledger.go
  ledger/ledger_test.go
  ledger/tracker.go
  ledger/voters.go
  stateproof/abstractions.go
  stateproof/builder.go
  stateproof/stateproofMessageGenerator_test.go
  stateproof/worker_test.go
Labels: Skip-Release-Notes

#5103 tests: Fix test by sorting results
  daemon/algod/api/server/v2/delta_test.go
Labels: Bug-Fix

#5118 CICD: go-algorand relstable3.14.2-remerge mergeback
  config/version.go
Labels: Team Hyper Flow, Skip-Release-Notes

#5113 node: Fix time since last block.
  node/follower_node.go
  node/node.go
  test/scripts/e2e_subs/time.sh
Labels: Bug-Fix

#5119 tests: debug flaky expect test
  test/e2e-go/cli/goal/expect/catchpointCatchupTest.exp
  test/e2e-go/cli/goal/expect/goalExpectCommon.exp
Labels: Team Carbon-11, Skip-Release-Notes

#5098 algod: Refactor AccountData conversion
  daemon/algod/api/server/v2/account.go
  daemon/algod/api/server/v2/delta.go
  daemon/algod/api/server/v2/delta_test.go
  daemon/algod/api/server/v2/test/helpers.go
Labels: Bug-Fix

#4737 AVM: Teal macros
  data/transactions/logic/assembler.go
  data/transactions/logic/assembler_test.go
  data/transactions/logic/opcodes.go
Labels: Enhancement

#5039 txHandler : Move streamverifer out of txn go
  data/transactions/verify/streamverifier.go
  data/transactions/verify/streamverifier_test.go
  data/transactions/verify/txn.go
  data/transactions/verify/txn_test.go
Labels: Enhancement, Team Carbon-11

#5123 API: Update state delta type, handler
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/account.go
  daemon/algod/api/server/v2/delta.go
  daemon/algod/api/server/v2/delta_test.go
  daemon/algod/api/server/v2/generated/data/routes.go
  daemon/algod/api/server/v2/generated/experimental/routes.go
  daemon/algod/api/server/v2/generated/model/types.go
  daemon/algod/api/server/v2/generated/nonparticipating/private/routes.go
  daemon/algod/api/server/v2/generated/nonparticipating/public/routes.go
  daemon/algod/api/server/v2/generated/participating/private/routes.go
  daemon/algod/api/server/v2/generated/participating/public/routes.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_resources_test.go
  daemon/algod/api/server/v2/test/handlers_test.go
  daemon/algod/api/server/v2/test/helpers.go
  tools/debug/vbconvert/main.go
Labels: Enhancement

#5135 algorelay: Fix typo in relayCmd.go
  cmd/algorelay/relayCmd.go
Labels: Enhancement

#5091 repo: add an Enhancement issue-template
  .github/ISSUE_TEMPLATE/enhancement.md
Labels: external contribution, Skip-Release-Notes

#5133 tools: Remove vbconvert
  tools/debug/vbconvert/README.md
  tools/debug/vbconvert/main.go
Labels: Enhancement

#5137 CircleCI: Fix cached Results issue in self-hosted runner
  .circleci/config.yml
Labels: Bug-Fix

#5071 Algod: Modify `EvalTracer` design and improve testing for failures
  data/transactions/logic/debugger.go
  data/transactions/logic/debugger_eval_test.go
  data/transactions/logic/debugger_test.go
  data/transactions/logic/eval.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/export_test.go
  data/transactions/logic/ledger_test.go
  data/transactions/logic/mocktracer/scenarios.go
  data/transactions/logic/mocktracer/tracer.go
  data/transactions/logic/tracer.go
  data/transactions/logic/tracer_test.go
  data/transactions/verify/txn_test.go
  ledger/internal/eval.go
  ledger/internal/eval_test.go
Labels: Enhancement, Team Scytale

#5058 Tests: No Cache Testing in ledger
  config/localTemplate.go
  config/local_defaults.go
  installer/config.json.example
  ledger/acctonline.go
  ledger/acctupdates.go
  ledger/acctupdates_test.go
  ledger/apptxn_test.go
  ledger/archival_test.go
  ledger/boxtxn_test.go
  ledger/catchpointtracker_test.go
  ledger/catchpointwriter_test.go
  ledger/double_test.go
  ledger/eval_simple_test.go
  ledger/ledger.go
  ledger/ledger_test.go
  ledger/lruaccts.go
  ledger/lruaccts_test.go
  ledger/lrukv.go
  ledger/lrukv_test.go
  ledger/lruonlineaccts.go
  ledger/lruonlineaccts_test.go
  ledger/lruresources.go
  ledger/lruresources_test.go
  ledger/simple_test.go
  ledger/testing/consensusRange.go
  ledger/testing/consensusRange_test.go
  ledger/testing/withAndWithoutCache.go
  ledger/txnbench_test.go
  test/testdata/configs/config-v27.json
Labels: Enhancement, test

#4695 network: connection deduplication
  .gitignore
  Makefile
  config/localTemplate.go
  network/connPerfMon.go
  network/msgp_gen.go
  network/msgp_gen_test.go
  network/netidentity.go
  network/netidentity_test.go
  network/phonebook.go
  network/requestTracker.go
  network/topics.go
  network/wsNetwork.go
  network/wsNetwork_test.go
  network/wsPeer.go
  protocol/hash.go
  protocol/tags.go
Labels: Team Carbon-11, New Feature, Performance

#5080 refactor: remove sql.Tx from Batch
  ledger/acctdeltas.go
  ledger/acctdeltas_test.go
  ledger/acctonline.go
  ledger/acctonline_test.go
  ledger/acctupdates.go
  ledger/acctupdates_test.go
  ledger/bulletin.go
  ledger/catchpointtracker.go
  ledger/catchpointtracker_test.go
  ledger/catchpointwriter.go
  ledger/catchpointwriter_test.go
  ledger/catchupaccessor.go
  ledger/ledger_test.go
  ledger/metrics.go
  ledger/notifier.go
  ledger/store/accountsV2.go
  ledger/store/encodedAccountsIter.go
  ledger/store/interface.go
  ledger/store/store.go
  ledger/store/testing.go
  ledger/tracker.go
  ledger/tracker_test.go
  ledger/trackerdb.go
  ledger/txtail.go
  ledger/txtail_test.go
  util/db/dbutil.go
Labels: Team Carbon-11, Skip-Release-Notes

#5147 network: add OutgoingMessage disconnectReason field
  network/netidentity.go
  network/wsNetwork.go
  network/wsNetwork_test.go
Labels: Enhancement, Team Carbon-11

#5150 Enhancement: use assert.Eventually to wait for peering to settle
  network/wsNetwork_test.go
Labels: Enhancement, test

#5054 CI: upgrade test_nightly infra to large
  .circleci/config.yml
Labels: Enhancement, Team Hyper Flow

#5152 test: Fix TestStreamVerifierPoolShutdown
  data/transactions/verify/streamverifier_test.go
Labels: Team Carbon-11, Bug-Fix

#5132 perf: Separate the txn specific operations from StreamVerifier
  data/transactions/verify/streamverifier.go
  data/transactions/verify/txn.go
  data/transactions/verify/txnBatch.go
  data/transactions/verify/txnBatch_test.go
  data/txHandler.go
  data/txHandler_test.go
Labels: Team Carbon-11, New Feature, Performance

#5158 tests: fix debug output in expect test harness
  test/e2e-go/cli/goal/expect/goalExpectCommon.exp
Labels: Team Carbon-11, Skip-Release-Notes

#4439 Algod: Additional simulation result information
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/data/routes.go
  daemon/algod/api/server/v2/generated/experimental/routes.go
  daemon/algod/api/server/v2/generated/model/types.go
  daemon/algod/api/server/v2/generated/nonparticipating/private/routes.go
  daemon/algod/api/server/v2/generated/nonparticipating/public/routes.go
  daemon/algod/api/server/v2/generated/participating/private/routes.go
  daemon/algod/api/server/v2/generated/participating/public/routes.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/handlers_test.go
  daemon/algod/api/server/v2/test/handlers_test.go
  daemon/algod/api/server/v2/test/helpers.go
  daemon/algod/api/server/v2/utils.go
  data/transactions/logic/debugger_eval_test.go
  data/transactions/logic/eval.go
  data/transactions/logic/mocktracer/scenarios.go
  data/transactions/verify/txn.go
  ledger/simulation/simulation_eval_test.go
  ledger/simulation/simulator.go
  ledger/simulation/simulator_test.go
  ledger/simulation/testing/utils.go
  ledger/simulation/trace.go
  ledger/simulation/tracer.go
  ledger/simulation/tracer_test.go
  node/follower_node.go
  node/follower_node_test.go
  node/node.go
Labels: New Feature

#5151 Fix: guard addPeer from adding peers who are closing
  network/wsNetwork.go
Labels: Bug-Fix

#5157 devmode: Allow DevMode + FollowMode configurations.
  netdeploy/networkTemplate.go
  netdeploy/networkTemplates_test.go
  node/follower_node.go
  node/follower_node_test.go
  node/node.go
Labels: Enhancement

#5069 algocfg: Add relay profile, algocfg profile cmd
  cmd/algocfg/profileCommand.go
Labels: Enhancement

#5162 fix(follower): update test that defines a follower relay.
  test/testdata/nettemplates/TwoNodesFollower100Second.json
Labels: Bug-Fix

#5169 fix(follower): add experimental tag to deltas endpoint.
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/data/data_routes.yml
  daemon/algod/api/server/v2/generated/data/routes.go
Labels: Team Lamprey, Bug-Fix
