Repository algorand/go-algorand, pull requests merged in 2023-12, with the labels that each got.

#5750 AVM: Add box_splice and box_resize opcodes
  data/transactions/logic/README.md
  data/transactions/logic/README_in.md
  data/transactions/logic/TEAL_opcodes_v10.md
  data/transactions/logic/TEAL_opcodes_v8.md
  data/transactions/logic/TEAL_opcodes_v9.md
  data/transactions/logic/assembler_test.go
  data/transactions/logic/box.go
  data/transactions/logic/box_test.go
  data/transactions/logic/doc.go
  data/transactions/logic/eval.go
  data/transactions/logic/langspec_v10.json
  data/transactions/logic/langspec_v8.json
  data/transactions/logic/langspec_v9.json
  data/transactions/logic/opcodeExplain.go
  data/transactions/logic/opcodes.go
  data/transactions/logic/teal.tmLanguage.json
Labels: Enhancement

#5856 tests: dump logs if e2e test node exited with an error
  test/framework/fixtures/libgoalFixture.go
Labels: Skip-Release-Notes

#5853 Round Times: Set minimum dynamic filter timeout to 2500ms.
  agreement/dynamicFilterTimeoutParams.go
  agreement/router.go
Labels: Enhancement

#5859 CICD: go-algorand relstable3.20.1-remerge mergeback
  config/version.go
Labels: Team Hyper Flow, Skip-Release-Notes

#5850 Round Times: Period 0 deadline timeout
  agreement/actions.go
  agreement/player.go
  agreement/service_test.go
  agreement/types.go
  catchup/service.go
  catchup/service_test.go
  config/consensus.go
  daemon/algod/api/server/common/handlers.go
Labels: Enhancement

#5851 network: fixes to public address support
  network/requestTracker.go
  network/requestTracker_test.go
  network/wsNetwork.go
  network/wsNetwork_test.go
  network/wsPeer.go
Labels: Enhancement

#5842 Simulate: Properly handle failing clear state programs
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/data/routes.go
  daemon/algod/api/server/v2/generated/experimental/routes.go
  daemon/algod/api/server/v2/generated/model/types.go
  daemon/algod/api/server/v2/generated/nonparticipating/private/routes.go
  daemon/algod/api/server/v2/generated/nonparticipating/public/routes.go
  daemon/algod/api/server/v2/generated/participating/private/routes.go
  daemon/algod/api/server/v2/generated/participating/public/routes.go
  daemon/algod/api/server/v2/utils.go
  data/transactions/logic/debugger.go
  data/transactions/logic/eval.go
  data/transactions/logic/mocktracer/scenarios.go
  data/transactions/logic/mocktracer/tracer.go
  data/transactions/logic/tracer.go
  data/transactions/logic/tracer_test.go
  data/transactions/verify/txn_test.go
  ledger/eval/eval_test.go
  ledger/simulation/simulation_eval_test.go
  ledger/simulation/simulator_test.go
  ledger/simulation/trace.go
  ledger/simulation/tracer.go
Labels: Bug-Fix

#5861 Chore: Update testing to use current python SDK.
  test/scripts/e2e.sh
  test/scripts/e2e_client_runner.py
  test/scripts/e2e_subs/example.py
  test/scripts/e2e_subs/goal/goal.py
  test/scripts/e2e_subs/min_balance.py
  test/scripts/e2e_subs/shared-resources.py
Labels: Enhancement

#5864 AVM: Require every global field to get tested
  data/transactions/logic/eval_test.go
Labels: Enhancement

#5866 Docs: Eliminate a unicode character that causes trouble in doc generation
  cmd/opdoc/opdoc.go
  data/transactions/logic/TEAL_opcodes_v1.md
  data/transactions/logic/TEAL_opcodes_v10.md
  data/transactions/logic/TEAL_opcodes_v2.md
  data/transactions/logic/TEAL_opcodes_v3.md
  data/transactions/logic/TEAL_opcodes_v4.md
  data/transactions/logic/TEAL_opcodes_v5.md
  data/transactions/logic/TEAL_opcodes_v6.md
  data/transactions/logic/TEAL_opcodes_v7.md
  data/transactions/logic/TEAL_opcodes_v8.md
  data/transactions/logic/TEAL_opcodes_v9.md
Labels: Enhancement

#5869 tests: custom recipe tweaks
  test/testdata/deployednettemplates/generate-recipe/generate_network.py
  test/testdata/deployednettemplates/recipes/custom/configs/node.json
Labels: Skip-Release-Notes

#5868 Consensus: Upgrade to consensus version v39.
  agreement/player_permutation_test.go
  agreement/player_test.go
  agreement/service_test.go
  catchup/service_test.go
  config/consensus.go
  data/bookkeeping/block_test.go
  data/transactions/logic/assembler_test.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/langspec_v1.json
  data/transactions/logic/langspec_v10.json
  data/transactions/logic/langspec_v2.json
  data/transactions/logic/langspec_v3.json
  data/transactions/logic/langspec_v4.json
  data/transactions/logic/langspec_v5.json
  data/transactions/logic/langspec_v6.json
  data/transactions/logic/langspec_v7.json
  data/transactions/logic/langspec_v8.json
  data/transactions/logic/langspec_v9.json
  data/transactions/logic/opcodes.go
  ledger/testing/consensusRange.go
  ledger/testing/consensusRange_test.go
  protocol/consensus.go
Labels: Enhancement

#5872 txHandler: fix ARL triggering without ERL
  data/txHandler.go
Labels: Bug-Fix

#5874 network: fix TestSlowPeerDisconnection regression after #5634
  network/wsNetwork_test.go
Labels: Skip-Release-Notes

#5870 CICD: fix aptly repo management
  .aptly.conf
  docker/build/aptly.Dockerfile
  docker/build/docker.ubuntu.Dockerfile
  package-deploy.yaml
  scripts/release/mule/deploy/deb/deploy.sh
Labels: Bug-Fix

#5881 tests: log all relay logs on e2e failure
  netdeploy/network.go
  test/framework/fixtures/libgoalFixture.go
Labels: Skip-Release-Notes

#5882 agreement: dump demux queues on fuzzer test failure
  agreement/demux.go
  agreement/fuzzer/fuzzer_test.go
  agreement/fuzzer/networkFacade_test.go
  agreement/fuzzer/validator_test.go
  agreement/service.go
Labels: Skip-Release-Notes

#5884 AVM: Don't treat `any` as constant int in `loads`, `stores`
  data/transactions/logic/assembler.go
  data/transactions/logic/assembler_test.go
  data/transactions/logic/eval.go
Labels: Bug-Fix

#5873 txHandler: kick in ARL at 1/2 of a base backlog capacity
  data/txHandler.go
  data/txHandler_test.go
Labels: Enhancement

#5867 p2p: start p2p networking and DHT ops when starting services, not when instantiating them
  agreement/fuzzer/networkFacade_test.go
  agreement/gossip/network_test.go
  components/mocks/mockNetwork.go
  daemon/algod/server.go
  network/gossipNode.go
  network/hybridNetwork.go
  network/p2p/capabilities.go
  network/p2p/capabilities_test.go
  network/p2p/dht/dht.go
  network/p2p/dht/dht_test.go
  network/p2p/p2p.go
  network/p2pNetwork.go
  network/p2pNetwork_test.go
  network/wsNetwork.go
  network/wsNetwork_test.go
  node/follower_node.go
  node/node.go
  tools/debug/algodump/main.go
  tools/debug/transplanter/main.go
Labels: Skip-Release-Notes

#5876 tests: rewrite triggerTrackerFlush test helper
  ledger/catchpointtracker.go
  ledger/ledger_test.go
Labels: Skip-Release-Notes
