Repository algorand/go-algorand, pull requests merged in 2023-01, with the labels that each got.

#4944 tests: split TestResolver to enable more tests on CircleCI
  tools/network/resolver_test.go
Labels: Enhancement

#4935 Telemetry: Remove unused TelemetryOperation
  logging/log.go
  logging/telemetry.go
  logging/telemetryCommon.go
  logging/telemetryOperation.go
  logging/telemetry_test.go
  logging/telemetryspec/operation.go
Labels: Enhancement

#4800 goal: Added consensus upgrade fields to node status api & goal output
  cmd/goal/messages.go
  cmd/goal/node.go
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/data/routes.go
  daemon/algod/api/server/v2/generated/experimental/routes.go
  daemon/algod/api/server/v2/generated/model/types.go
  daemon/algod/api/server/v2/generated/nonparticipating/private/routes.go
  daemon/algod/api/server/v2/generated/nonparticipating/public/routes.go
  daemon/algod/api/server/v2/generated/participating/private/routes.go
  daemon/algod/api/server/v2/generated/participating/public/routes.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_resources_test.go
  daemon/algod/api/server/v2/test/handlers_test.go
  daemon/algod/api/server/v2/test/helpers.go
  node/node.go
Labels: Enhancement

#4962 Ledger: bulletin leaking waiters fix
  ledger/bulletin.go
  ledger/ledger_test.go
Labels: Team Sphinx, Bug-Fix

#4967 tools: nodecfg without dns
  cmd/nodecfg/apply.go
  netdeploy/remote/nodecfg/nodeConfigurator.go
  netdeploy/remote/nodecfg/nodeDir.go
Labels: Enhancement, Team Carbon-11

#4934 node: Add logging thread to node monitoring wg
  node/node.go
Labels: Bug-Fix

#4965 Tests: Re-enable TestResolverWithCloudflareDNSResolution in CircleCI
  tools/network/resolver_test.go
Labels: Enhancement

#4929 util/s3: enable more credential providers
  util/s3/s3Helper.go
  util/s3/s3Helper_test.go
Labels: Enhancement

#4927 CICD: add container build
  .github/workflows/container.yml
  Dockerfile
  docker/README.md
  docker/files/build/install.sh
  docker/files/run/run.sh
  scripts/compute_branch.sh
Labels: Enhancement

#4368 AVM: Catch any panic in edcsa verifying
  data/transactions/logic/eval.go
Labels: Bug-Fix

#4980 Test fix: flaky TestStreamVerifierCtxCancelPoolQueue
  data/transactions/verify/txn_test.go
Labels: Team Carbon-11, Bug-Fix

#4981 Tests: Fix `t.Parallel()` errors in `data` package
  .golangci.yml
  data/account/participationRegistry_test.go
  data/account/participation_test.go
  data/accountManager_test.go
  data/basics/address_test.go
  data/basics/fields_test.go
  data/basics/teal_test.go
  data/basics/units_test.go
  data/basics/userBalance_test.go
  data/bookkeeping/block_test.go
  data/bookkeeping/encoding_test.go
  data/bookkeeping/lightBlockHeader_test.go
  data/bookkeeping/txn_merkle_test.go
  data/committee/credential_test.go
  data/committee/encoding_test.go
  data/committee/sortition/sortition_test.go
  data/pools/transactionPool_test.go
  data/transactions/application_test.go
  data/transactions/json_test.go
  data/transactions/payment_test.go
  data/transactions/payset_test.go
  data/transactions/signedtxn_test.go
  data/transactions/teal_test.go
  data/transactions/transaction_test.go
  data/transactions/verify/txn_test.go
  data/transactions/verify/verifiedTxnCache_test.go
  data/txHandler_test.go
Labels: Enhancement

#4911 metrics: use uint64 for Counter and Gauge types
  data/txHandler.go
  ledger/metrics.go
  logging/usage.go
  network/wsNetwork.go
  node/node.go
  util/metrics/counter.go
  util/metrics/counterCommon.go
  util/metrics/counter_test.go
  util/metrics/gauge.go
  util/metrics/gauge_test.go
  util/metrics/registry_test.go
Labels: Enhancement

#4985 AVM: Revert 'AVM: Catch any panic in edcsa verifying (#4368)'
  data/transactions/logic/eval.go
Labels: Skip-Release-Notes

#4986 tests: fix unstable TestREDCongestionManagerShouldntDrop
  data/txHandler.go
  network/wsPeer.go
  util/rateLimit.go
  util/rateLimit_test.go
Labels: test, Team Carbon-11, Skip-Release-Notes

#4987 scripts(compute_branch): fix incorrect conditional
  scripts/compute_branch.sh
Labels: Bug-Fix

#4832 config: add HeartbeatUpdateInterval
  cmd/algod/main.go
  config/localTemplate.go
  config/local_defaults.go
  installer/config.json.example
  test/testdata/configs/config-v27.json
Labels: Enhancement

#4994 Updater: fix update.sh parsing of latest version
  cmd/updater/update.sh
Labels: High Priority, Team Hyper Flow, Bug-Fix

#4996 Tests: Fixes saved from 4981 revert
  data/account/participationRegistry_test.go
  data/account/participation_test.go
  data/bookkeeping/block_test.go
  data/transactions/json_test.go
  data/transactions/verify/txn_test.go
  data/txHandler_test.go
Labels: Enhancement

#5002 CI: Split paralleltest lint excludes to minimize merge conflicts
  .golangci.yml
Labels: Enhancement

#5010 AVM: Clearer cost benchmarks, and a nice optimization of b== and b<
  data/transactions/logic/eval.go
  data/transactions/logic/evalCrypto_test.go
  data/transactions/logic/eval_test.go
Labels: Enhancement

#4951 Enhancement: `goal` Error UX Improvement
  cmd/goal/clerk.go
  cmd/goal/multisig.go
  cmd/pingpong/runCmd.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_test.go
  data/transactions/logic/assembler.go
  data/transactions/logic/assembler_test.go
  test/scripts/e2e_subs/e2e-app-simple.sh
Labels: duplicate, Enhancement

#5026 tools: box key utility
  tools/boxkey/convertBoxKey.go
Labels: Team Carbon-11, Skip-Release-Notes

#4979 avm-abi: Update functions migrated to avm-abi library
  cmd/catchpointdump/file.go
  cmd/goal/application.go
  cmd/goal/interact.go
  daemon/algod/api/server/v2/handlers.go
  data/transactions/logic/box.go
  data/transactions/logic/box_test.go
  data/transactions/logic/parsing.go
  data/transactions/logic/parsing_test.go
  go.mod
  go.sum
  ledger/acctdeltas_test.go
  ledger/acctupdates_test.go
  ledger/catchpointwriter_test.go
  ledger/encoded/recordsV6_test.go
  ledger/internal/applications.go
  libgoal/libgoal.go
Labels: Enhancement

#5032 build: fix build after #4979
  tools/boxkey/convertBoxKey.go
Labels: Team Carbon-11, Bug-Fix

#5028 tech debt: Remove unused NetworkFetcher.
  catchup/networkFetcher.go
  catchup/networkFetcher_test.go
Labels: Enhancement, Team Lamprey

#4964 ledger: rearrange blockqueue start/stop
  ledger/archival_test.go
  ledger/blockqueue.go
  ledger/double_test.go
  ledger/ledger.go
  ledger/ledger_test.go
Labels: Team Carbon-11, Bug-Fix

#5008 debug: unmarshal and print transaction distribution
  logging/telemetryspec/metric.go
  logging/telemetryspec/metric_test.go
Labels: Enhancement

#5033 bugfix: Remove accidental devtesting output.
  cmd/goal/messages.go
Labels: Team Lamprey, Bug-Fix

#5027 tech debt: Remove topAccountListener.
  logging/telemetryspec/event.go
  node/node.go
  node/topAccountListener.go
  node/topAccountListener_test.go
Labels: Enhancement

#4757 tools: pingpong total latency
  cmd/pingpong/runCmd.go
  shared/pingpong/config.go
  shared/pingpong/pingpong.go
  test/heapwatch/block_history.py
  test/heapwatch/block_history_plot.py
  test/scripts/e2e_tx_latency.py
  test/scripts/latency_plot.py
Labels: Team Carbon-11, New Feature

#4740 config: add CadaverDirectory and prevent algod from starting if cadaver.init() fails
  agreement/agreementtest/simulate.go
  agreement/cadaver.go
  agreement/fuzzer/fuzzer_test.go
  agreement/service.go
  agreement/service_test.go
  agreement/trace.go
  config/localTemplate.go
  config/local_defaults.go
  installer/config.json.example
  node/node.go
  test/testdata/configs/config-v27.json
Labels: Enhancement

#5036 Mergeback: relstable3.13.3
  ledger/applications_test.go
  ledger/store/sql.go
Labels: Team Hyper Flow, Skip-Release-Notes

#5018 network: increase max incoming connections limit
  config/localTemplate.go
  config/local_defaults.go
  installer/config.json.example
  test/testdata/configs/config-v27.json
Labels: Enhancement, Team Carbon-11

#5005 network: new default gossip fanout setting for relays
  config/config.go
  config/localTemplate.go
  config/local_defaults.go
  installer/config.json.example
  test/testdata/configs/config-v27.json
Labels: Enhancement

#5025 algocfg: Clarify config file loading error.
  cmd/algocfg/getCommand.go
  cmd/algocfg/resetCommand.go
  cmd/algocfg/setCommand.go
Labels: Enhancement, Team Lamprey

#5041 agreement: fix receivedAt proposal performance timing
  agreement/events.go
  agreement/msgp_gen.go
  agreement/player_test.go
  agreement/proposal.go
  agreement/proposalStore.go
Labels: Bug-Fix

#4438 Algod: Replace `logic.DebuggerHook` with `logic.EvalTracer` interface
  cmd/tealdbg/README.md
  cmd/tealdbg/debugger.go
  cmd/tealdbg/debugger_test.go
  cmd/tealdbg/local.go
  cmd/tealdbg/remote.go
  daemon/algod/api/server/v2/dryrun.go
  data/transactions/logic/assembler.go
  data/transactions/logic/debugger.go
  data/transactions/logic/debugger_test.go
  data/transactions/logic/eval.go
  data/transactions/logic/evalStateful_test.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/fields.go
  data/transactions/logic/mocktracer/tracer.go
  data/transactions/logic/opcodes.go
  data/transactions/logic/tracer.go
  data/transactions/logic/tracer_test.go
  data/transactions/verify/txn.go
  data/transactions/verify/txn_test.go
  data/txntest/defi.go
  data/txntest/txn.go
  ledger/internal/eval.go
  ledger/internal/eval_test.go
  ledger/simple_test.go
  ledger/simulation/simulator.go
Labels: Enhancement

#5022 Txhandler: Improve dedupe hit rate
  data/txDupCache.go
Labels: Team Carbon-11, Skip-Release-Notes

#5047 lint: fix warnings
  .github/workflows/reviewdog.yml
  .golangci-warnings.yml
  agreement/events_test.go
  agreement/persistence_test.go
  cmd/goal/formatting_test.go
  cmd/tealdbg/dryrunRequest.go
  config/config_test.go
  daemon/algod/api/server/v2/errors.go
  logging/telemetryspec/metric_test.go
  shared/pingpong/pingpong.go
  util/rateLimit.go
  util/tcpinfo_linux.go
Labels: Enhancement, unplanned

#5051 AVM: Fix opBytesLt for len(rhs) < len(lhs)
  data/transactions/logic/eval.go
  data/transactions/logic/eval_test.go
Labels: Bug-Fix

#5053 tests: disable TestInitialSync on CI
  node/node_test.go
Labels: Team Carbon-11, Skip-Release-Notes

#5044 CICD: Adding github release notes template
  .github/release.yml
Labels: Enhancement, unplanned, Team Hyper Flow

#5050 build: update C++ flags for recent Mac compiler warnings
  data/committee/sortition/sortition.go
Labels: Enhancement

#5048 development: tool to convert validated blocks.
  daemon/algod/api/server/v2/delta.go
  daemon/algod/api/server/v2/delta_test.go
  daemon/algod/api/server/v2/handlers.go
  tools/debug/vbconvert/README.md
  tools/debug/vbconvert/main.go
Labels: Enhancement, Team Lamprey

#5062 e2e tests: log pending transactions in case of failure
  test/framework/fixtures/restClientFixture.go
Labels: tech debt, Team Carbon-11, Skip-Release-Notes

#5067 goal: allow for relative dataDir via -d cmd option
  cmd/goal/commands.go
  cmd/goal/commands_test.go
Labels: user-facing, external contribution, Bug-Fix

#5074 docs: fix typo in avm/teal spec
  data/transactions/logic/README.md
  data/transactions/logic/README_in.md
Labels: Skip-Release-Notes

#4902 Goal: --start option for network create command
  cmd/goal/network.go
Labels: Enhancement

#5021 refactor: abstract store and remove all `db.Atomic` usage
  ledger/acctdeltas_test.go
  ledger/acctonline.go
  ledger/acctonline_test.go
  ledger/acctupdates.go
  ledger/acctupdates_test.go
  ledger/archival_test.go
  ledger/catchpointtracker.go
  ledger/catchpointtracker_test.go
  ledger/catchpointwriter_test.go
  ledger/catchupaccessor.go
  ledger/ledger.go
  ledger/ledger_test.go
  ledger/store/interface.go
  ledger/store/store.go
  ledger/store/testing.go
  ledger/tracker.go
  ledger/trackerdb.go
  ledger/txtail.go
  ledger/txtail_test.go
Labels: Team Carbon-11, Skip-Release-Notes

#5031 refactor: remove `sql.Tx` from the transaction callback
  ledger/catchpointtracker.go
  ledger/catchpointwriter_test.go
  ledger/catchupaccessor.go
  ledger/store/interface.go
  ledger/store/merkle_commiter.go
  ledger/store/store.go
  ledger/txtail_test.go
Labels: Team Carbon-11, Skip-Release-Notes

#5077 network: Add GetUnderlyingConnTcpInfo method to wsPeer
  network/wsNetwork.go
  network/wsPeer.go
Labels: Team Carbon-11, Skip-Release-Notes

#5078 tests: add more logging to expect test
  netdeploy/networkTemplate.go
  test/e2e-go/cli/goal/expect/goalExpectCommon.exp
Labels: Team Carbon-11, Skip-Release-Notes
