Repository algorand/go-algorand, pull requests merged in 2023-08, with the labels that each got.

#5575 p2p: multiaddr dns bootstrapping utils
  cmd/algons/commands.go
  cmd/algons/dnsaddrCmd.go
  go.mod
  go.sum
  network/p2p/dnsaddr/resolve.go
  network/p2p/dnsaddr/resolveController.go
  network/p2p/dnsaddr/resolveController_test.go
  network/p2p/dnsaddr/resolve_test.go
  tools/block-generator/go.mod
  tools/block-generator/go.sum
  tools/network/resolveController.go
Labels: Enhancement

#5540 ledger: Remove redundant block header cache
  cmd/tealdbg/localLedger.go
  daemon/algod/api/server/v2/dryrun.go
  data/ledger_test.go
  data/transactions/logic/eval.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/ledger_test.go
  data/transactions/verify/txn_test.go
  ledger/acctupdates.go
  ledger/acctupdates_test.go
  ledger/blockHeaderCache.go
  ledger/blockHeaderCache_test.go
  ledger/eval/applications.go
  ledger/eval/cow.go
  ledger/eval/eval.go
  ledger/eval/eval_test.go
  ledger/eval/prefetcher/prefetcher_alignment_test.go
  ledger/evalindexer.go
  ledger/evalindexer_test.go
  ledger/ledger.go
  ledger/ledger_test.go
  ledger/roundlru.go
  ledger/roundlru_test.go
  ledger/tracker.go
  ledger/txtail.go
  stateproof/abstractions.go
Labels: Enhancement, Team Carbon-11

#5621 tools: test on CI regardless of modded file
  .github/workflows/tools.yml
  tools/block-generator/go.mod
  tools/x-repo-types/Makefile
  tools/x-repo-types/go.mod
Labels: Bug-Fix

#5627 tools: additional generator lifecycle logging.
  tools/block-generator/runner/run.go
  tools/block-generator/runner/template/conduit.yml.tmpl
Labels: Enhancement

#5630 tools: write block generator ledger output to a file
  ledger/lrukv.go
  ledger/lrukv_test.go
  ledger/lruresources.go
  ledger/lruresources_test.go
  tools/block-generator/generator/generate.go
  tools/block-generator/generator/generate_test.go
  tools/block-generator/generator/generator_ledger.go
  tools/block-generator/generator/generator_types.go
  tools/block-generator/generator/server.go
  tools/block-generator/runner/run.go
Labels: Enhancement

#5587 api: Describe WaitForBlock timeout behavior.
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/nonparticipating/public/routes.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_test.go
Labels: Team Lamprey, Bug-Fix

#5588 metrics: add counters to broadcastSignedTxGroup
  node/node.go
  util/metrics/metrics.go
Labels: Enhancement

#5622 libgoal: set FirstValid to LastRound to prevent early tnxs
  libgoal/libgoal.go
  libgoal/libgoal_test.go
  test/e2e-go/features/transactions/asset_test.go
  test/e2e-go/features/transactions/lease_test.go
  test/scripts/e2e_subs/e2e-teal.sh
  test/scripts/e2e_subs/limit-swap-test.sh
Labels: Team Carbon-11, Bug-Fix

#5632 tests: fix e2e TestAssetValidRounds after libgoal adjustment
  test/e2e-go/features/transactions/asset_test.go
Labels: Team Carbon-11, Skip-Release-Notes

#5634 network: make GossipNode more independent from wsNetwork implementation
  agreement/fuzzer/networkFacade_test.go
  agreement/gossip/network_test.go
  network/msgCompressor.go
  network/multiplexer.go
  network/multiplexer_test.go
  network/netidentity.go
  network/netidentity_test.go
  network/wsNetwork.go
  network/wsNetwork_test.go
  network/wsPeer.go
Labels: Enhancement, p2p

#5635 metrics: add counters for ledger locks trackerMu and accountsMu
  ledger/acctupdates.go
  ledger/ledger.go
Labels: Enhancement

#5636 tools: use CommandContext to cancel conduit process.
  tools/block-generator/runner/run.go
Labels: Enhancement, Team Lamprey

#5615 phonebook: Persist initial phonebook peers; remove unused ExtendPeerList
  network/phonebook.go
  network/phonebook_test.go
  network/wsNetwork.go
  network/wsNetwork_test.go
Labels: Enhancement, p2p

#5644 ledger: move accountUpdatesLedgerEvaluator to tracker.go
  ledger/acctupdates.go
  ledger/acctupdates_test.go
  ledger/tracker.go
  ledger/tracker_test.go
Labels: Team Carbon-11, Skip-Release-Notes

#5646 build: slightly more readable "make" output
  Makefile
Labels: Skip-Release-Notes

#5611 algod: Add API Endpoint to fetch TxIDs from block
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/data/routes.go
  daemon/algod/api/server/v2/generated/experimental/routes.go
  daemon/algod/api/server/v2/generated/model/types.go
  daemon/algod/api/server/v2/generated/nonparticipating/private/routes.go
  daemon/algod/api/server/v2/generated/nonparticipating/public/routes.go
  daemon/algod/api/server/v2/generated/participating/private/routes.go
  daemon/algod/api/server/v2/generated/participating/public/routes.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_test.go
  test/scripts/e2e_subs/e2e-logs.sh
Labels: Enhancement

#5642 tools: precompile block-generator teal code
  tools/block-generator/generator/daemon.go
  tools/block-generator/generator/generate.go
  tools/block-generator/generator/make_transactions.go
  tools/block-generator/generator/server.go
Labels: Enhancement

#5606 ledger: add pebbledb support
  daemon/algod/server.go
  go.mod
  go.sum
  ledger/ledger.go
  ledger/store/trackerdb/pebbledbdriver/pebbledriver.go
  ledger/store/trackerdb/pebbledbdriver/testing.go
  ledger/store/trackerdb/testsuite/accounts_ext_kv_test.go
  ledger/store/trackerdb/testsuite/pebbledb_test.go
  tools/block-generator/go.mod
  tools/block-generator/go.sum
Labels: Team Carbon-11, Skip-Release-Notes

#5619 tests: fix close - commit data race in tracker tests
  ledger/acctonline_test.go
  ledger/acctupdates_test.go
  ledger/catchpointfilewriter_test.go
  ledger/voters_test.go
Labels: Team Carbon-11, Bug-Fix

#5648 CICD: go-algorand relstable3.17.0-remerge mergeback
  config/version.go
Labels: Skip-Release-Notes

#5577 build: upgrade to go1.20.6
  .circleci/config.yml
  .github/workflows/reviewdog.yml
  Dockerfile
  Makefile
  scripts/get_golang_version.sh
Labels: Enhancement, Team Carbon-11, experimental

#5660 Build: Remove n-algorand from wsnetwork partial overlap test.
  network/wsNetwork_test.go
Labels: test, Bug-Fix

#5668 Ledger: Close the ledger at node shutdown
  node/node.go
Labels: Team Carbon-11, Bug-Fix

#5661 tools: metrics files visualizer
  test/heapwatch/.gitignore
  test/heapwatch/metrics_delta.py
  test/heapwatch/metrics_viz.py
  test/heapwatch/requirements.txt
Labels: Enhancement, Team Carbon-11

#5631 p2p: Add delete/create to algons dnsaddr command
  cmd/algons/dnsCmd.go
  cmd/algons/dnsaddrCmd.go
  network/p2p/dnsaddr/resolve.go
  network/p2p/dnsaddr/resolve_test.go
Labels: Enhancement, p2p

#5662 catchup: cleanup pipelinedFetch
  catchup/fetcher_test.go
  catchup/service.go
  catchup/service_test.go
  ledger/bulletin.go
  ledger/ledger.go
Labels: Skip-Release-Notes

#5645 build: update go-sqlite3 dependency
  go.mod
  go.sum
  tools/block-generator/go.mod
  tools/block-generator/go.sum
Labels: Skip-Release-Notes

#5675 chore: Remove faulty assertion
  network/wsNetwork_test.go
Labels: Enhancement

#5673 catchup: make unsupported block handling more deterministic
  catchup/service.go
  catchup/service_test.go
Labels: Bug-Fix

#5652 ledger: dual db testing test harness
  go.mod
  go.sum
  ledger/acctdeltas_test.go
  ledger/store/trackerdb/dualdriver/accounts_reader.go
  ledger/store/trackerdb/dualdriver/accounts_reader_ext.go
  ledger/store/trackerdb/dualdriver/accounts_writer.go
  ledger/store/trackerdb/dualdriver/accounts_writer_ext.go
  ledger/store/trackerdb/dualdriver/dualdriver.go
  ledger/store/trackerdb/dualdriver/online_accounts_reader.go
  ledger/store/trackerdb/dualdriver/online_accounts_writer.go
  ledger/store/trackerdb/dualdriver/stateproof_reader.go
  ledger/store/trackerdb/dualdriver/stateproof_writer.go
  ledger/store/trackerdb/dualdriver/transaction_for_testing.go
  ledger/store/trackerdb/generickv/accounts_reader.go
  ledger/store/trackerdb/generickv/accounts_writer.go
  ledger/store/trackerdb/generickv/onlineaccounts_reader.go
  ledger/store/trackerdb/interface.go
  ledger/store/trackerdb/sqlitedriver/sql.go
  ledger/store/trackerdb/testdb/testdb.go
  ledger/store/trackerdb/testsuite/dual_test.go
  tools/block-generator/go.sum
Labels: Team Carbon-11, Skip-Release-Notes

#5678 ledger: fix error condition leaked from KV-related refactoring
  ledger/acctdeltas.go
Labels: Bug-Fix

#5658 Simulate: Hash of Program Bytecodes in Simulation
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/data/routes.go
  daemon/algod/api/server/v2/generated/experimental/routes.go
  daemon/algod/api/server/v2/generated/model/types.go
  daemon/algod/api/server/v2/generated/nonparticipating/private/routes.go
  daemon/algod/api/server/v2/generated/nonparticipating/public/routes.go
  daemon/algod/api/server/v2/generated/participating/private/routes.go
  daemon/algod/api/server/v2/generated/participating/public/routes.go
  daemon/algod/api/server/v2/utils.go
  ledger/simulation/simulation_eval_test.go
  ledger/simulation/trace.go
  ledger/simulation/tracer.go
  test/e2e-go/restAPI/restClient_test.go
Labels: Team Scytale, New Feature

#5659 Simulate: Add State Change to Exec Trace
  cmd/goal/clerk.go
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/account.go
  daemon/algod/api/server/v2/generated/data/routes.go
  daemon/algod/api/server/v2/generated/experimental/routes.go
  daemon/algod/api/server/v2/generated/model/types.go
  daemon/algod/api/server/v2/generated/nonparticipating/private/routes.go
  daemon/algod/api/server/v2/generated/nonparticipating/public/routes.go
  daemon/algod/api/server/v2/generated/participating/private/routes.go
  daemon/algod/api/server/v2/generated/participating/public/routes.go
  daemon/algod/api/server/v2/utils.go
  data/transactions/logic/opcodeExplain.go
  data/transactions/logic/opcodes.go
  ledger/simulation/simulation_eval_test.go
  ledger/simulation/trace.go
  ledger/simulation/tracer.go
  test/e2e-go/restAPI/restClient_test.go
Labels: Team Scytale, New Feature

#5674 ledger: fix rare race in TestCommitRoundIOError
  ledger/tracker_test.go
  logging/log_test.go
Labels: Skip-Release-Notes

#5649 clocks: tagged deadlines
  agreement/agreementtest/simulate.go
  agreement/demux.go
  agreement/demux_test.go
  agreement/fuzzer/fuzzer_test.go
  agreement/fuzzer/networkFacade_test.go
  agreement/msgp_gen.go
  agreement/msgp_gen_test.go
  agreement/persistence.go
  agreement/persistence_test.go
  agreement/player.go
  agreement/player_test.go
  agreement/service.go
  agreement/service_test.go
  agreement/types.go
  node/node.go
  util/timers/frozen.go
  util/timers/interface.go
  util/timers/monotonic.go
  util/timers/monotonic_test.go
Labels: Enhancement

#5681 tests: log algod-err and algod-out on e2e failure
  test/framework/fixtures/libgoalFixture.go
Labels: Team Carbon-11, Skip-Release-Notes

#5682 build: disable pebbledb on arm32
  ledger/store/trackerdb/pebbledbdriver/pebbledriver.go
  ledger/store/trackerdb/pebbledbdriver/pebbledriver_arm.go
Labels: Team Carbon-11, Skip-Release-Notes

#5680 AVM: Expose `global` fields to TEAL that return MBR for asset create/optin
  data/transactions/logic/README.md
  data/transactions/logic/TEAL_opcodes.md
  data/transactions/logic/assembler_test.go
  data/transactions/logic/eval.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/fields.go
  data/transactions/logic/fields_string.go
  data/transactions/logic/langspec.json
  data/transactions/logic/teal.tmLanguage.json
Labels: Enhancement

#5683 txHandler: Enable ERL by default in configuration.
  config/localTemplate.go
  config/local_defaults.go
  data/txHandler_test.go
  installer/config.json.example
  test/testdata/configs/config-v30.json
Labels: New Feature

#5689 tools: add block-generator initial round to report.
  tools/block-generator/generator/generate.go
  tools/block-generator/generator/generator_types.go
  tools/block-generator/runner/reporting_test.go
  tools/block-generator/runner/run.go
Labels: Enhancement, Team Lamprey

#5692 tests: fix restAPI test fixture
  test/e2e-go/restAPI/helpers.go
  test/e2e-go/restAPI/other/appsRestAPI_test.go
  test/e2e-go/restAPI/other/misc_test.go
  test/e2e-go/restAPI/restClient_test.go
  test/e2e-go/restAPI/simulate/simulateRestAPI_test.go
  test/e2e-go/restAPI/stateproof/stateproofRestAPI_test.go
  test/framework/fixtures/libgoalFixture.go
Labels: Team Carbon-11, Skip-Release-Notes

#5694 tools: block-generator option to delay before running scenario.
  tools/block-generator/runner/run.go
  tools/block-generator/runner/runner.go
Labels: Enhancement, Team Lamprey

#5696 build: resume/fix ci expect tests
  test/scripts/e2e_go_tests.sh
Labels: Team Carbon-11, Skip-Release-Notes

#4924 AVM: EC math
  cmd/opdoc/opdoc.go
  data/transactions/logic/README.md
  data/transactions/logic/TEAL_opcodes.md
  data/transactions/logic/assembler.go
  data/transactions/logic/assembler_test.go
  data/transactions/logic/doc.go
  data/transactions/logic/evalCrypto_test.go
  data/transactions/logic/evalStateful_test.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/fields.go
  data/transactions/logic/fields_string.go
  data/transactions/logic/langspec.json
  data/transactions/logic/opcodes.go
  data/transactions/logic/pairing.go
  data/transactions/logic/pairing_test.go
  data/transactions/logic/teal.tmLanguage.json
  go.mod
  go.sum
  tools/block-generator/go.mod
  tools/block-generator/go.sum
  tools/x-repo-types/go.sum
Labels: Enhancement

#5677 ledger: kv keys allocation optimizations
  ledger/store/trackerdb/generickv/accounts_ext_reader.go
  ledger/store/trackerdb/generickv/accounts_ext_writer.go
  ledger/store/trackerdb/generickv/accounts_reader.go
  ledger/store/trackerdb/generickv/accounts_writer.go
  ledger/store/trackerdb/generickv/migrations.go
  ledger/store/trackerdb/generickv/onlineaccounts_reader.go
  ledger/store/trackerdb/generickv/onlineaccounts_writer.go
  ledger/store/trackerdb/generickv/schema.go
  ledger/store/trackerdb/generickv/stateproof_reader.go
  ledger/store/trackerdb/generickv/stateproof_writer.go
  ledger/store/trackerdb/testsuite/onlineaccounts_kv_test.go
Labels: Team Carbon-11, Skip-Release-Notes

#5705 Revert "Ledger: Close the ledger at node shutdown"
  node/node.go
Labels: Bug-Fix

#5708 Chore: Put the three doc strings about each op together
  data/transactions/logic/assembler.go
  data/transactions/logic/assembler_test.go
  data/transactions/logic/doc.go
  data/transactions/logic/doc_test.go
Labels: Enhancement

#5629 AVM: Generate langspec for each version
  .gitignore
  cmd/opdoc/opdoc.go
  cmd/opdoc/tmLanguage.go
  data/transactions/logic/TEAL_opcodes_v1.md
  data/transactions/logic/TEAL_opcodes_v10.md
  data/transactions/logic/TEAL_opcodes_v2.md
  data/transactions/logic/TEAL_opcodes_v3.md
  data/transactions/logic/TEAL_opcodes_v4.md
  data/transactions/logic/TEAL_opcodes_v5.md
  data/transactions/logic/TEAL_opcodes_v6.md
  data/transactions/logic/TEAL_opcodes_v7.md
  data/transactions/logic/TEAL_opcodes_v8.md
  data/transactions/logic/TEAL_opcodes_v9.md
  data/transactions/logic/doc.go
  data/transactions/logic/doc_test.go
  data/transactions/logic/langspec_v1.json
  data/transactions/logic/langspec_v10.json
  data/transactions/logic/langspec_v2.json
  data/transactions/logic/langspec_v3.json
  data/transactions/logic/langspec_v4.json
  data/transactions/logic/langspec_v5.json
  data/transactions/logic/langspec_v6.json
  data/transactions/logic/langspec_v7.json
  data/transactions/logic/langspec_v8.json
  data/transactions/logic/langspec_v9.json
  data/transactions/logic/opcodes.go
Labels: Enhancement, Team Scytale

#5614 algod: Hot/Cold Data Directories and Resource Paths
  agreement/service.go
  catchup/pref_test.go
  cmd/algod/main.go
  config/config_test.go
  config/localTemplate.go
  config/local_defaults.go
  daemon/algod/server.go
  data/ledger.go
  installer/config.json.example
  ledger/catchpointtracker.go
  ledger/catchpointtracker_test.go
  ledger/ledger.go
  ledger/ledger_test.go
  ledger/spverificationtracker_test.go
  ledger/tracker_test.go
  netdeploy/remote/deployedNetwork.go
  node/follower_node.go
  node/follower_node_test.go
  node/node.go
  node/node_test.go
  rpcs/blockService_test.go
  test/testdata/configs/config-v31.json
  tools/debug/transplanter/main.go
Labels: Team Carbon-11, New Feature

#5655 encoding: eliminate unnecessary allocations
  crypto/merklesignature/persistentMerkleSignatureScheme.go
  data/transactions/signedtxn.go
  data/transactions/teal.go
  data/transactions/transaction.go
  protocol/codec.go
Labels: Enhancement, Team Carbon-11

#5685 Simulate: Enable on follower node & allow specifying starting round
  cmd/goal/clerk.go
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/data/routes.go
  daemon/algod/api/server/v2/generated/experimental/routes.go
  daemon/algod/api/server/v2/generated/model/types.go
  daemon/algod/api/server/v2/generated/nonparticipating/private/routes.go
  daemon/algod/api/server/v2/generated/nonparticipating/public/routes.go
  daemon/algod/api/server/v2/generated/participating/private/routes.go
  daemon/algod/api/server/v2/generated/participating/public/routes.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/utils.go
  ledger/acctupdates.go
  ledger/ledger.go
  ledger/simulation/simulation_eval_test.go
  ledger/simulation/simulator.go
  ledger/simulation/simulator_test.go
  ledger/simulation/testing/utils.go
  node/follower_node.go
  node/follower_node_test.go
  test/e2e-go/restAPI/simulate/simulateRestAPI_test.go
Labels: Enhancement, Team Scytale

#5654 performance: dynamic lambda
  agreement/actions.go
  agreement/credentialArrivalHistory.go
  agreement/credentialArrivalHistory_test.go
  agreement/demux.go
  agreement/dynamicFilterTimeoutParams.go
  agreement/dynamicFilterTimeoutParams_test.go
  agreement/events.go
  agreement/eventtype_string.go
  agreement/msgp_gen.go
  agreement/persistence.go
  agreement/persistence_test.go
  agreement/player.go
  agreement/player_test.go
  agreement/proposalStore.go
  agreement/proposalTracker.go
  agreement/proposalTrackerContract.go
  agreement/service.go
  agreement/service_test.go
  agreement/state_machine_test.go
  agreement/vote.go
  config/consensus.go
  logging/telemetryspec/event.go
  tools/x-repo-types/xrt_test.go
Labels: Enhancement
