Repository algorand/go-algorand, pull requests merged in 2023-07, with the labels that each got.

#5524 fix: remove unnecessary bash scripts
  scripts/generate_beta_config.sh
  scripts/generate_devnet_config.sh
  scripts/generate_testnet_config.sh
Labels: Skip-Release-Notes

#5523 tests: make TestSendMessageCallbacks deterministic
  network/wsNetwork_test.go
Labels: test, Team Carbon-11, Skip-Release-Notes

#5496 tests: reenable TestVotersReloadFromDiskPassRecoveryPeriod
  ledger/acctonline.go
  ledger/acctonline_test.go
  ledger/ledger_test.go
  ledger/store/trackerdb/interface.go
  ledger/store/trackerdb/sqlitedriver/sql.go
Labels: SkippedTests, Team Carbon-11, Bug-Fix

#5521 tracer: Default to ledger tracer when starting new evaluator
  daemon/algod/api/client/restClient.go
  ledger/ledger.go
  test/e2e-go/features/devmode/devmode_test.go
  test/e2e-go/restAPI/restClient_test.go
  test/testdata/nettemplates/DevModeTxnTracerNetwork.json
Labels: Bug-Fix

#5525 docker: Additional private network options and container tweaks.
  Dockerfile
  docker/README.md
  docker/files/run/run.sh
Labels: Enhancement, Team Lamprey

#5526 Chore: Small cleanups for clarity
  crypto/multisig.go
  data/transactions/logic/backwardCompat_test.go
  data/transactions/logic/debugger.go
  data/transactions/logic/eval.go
  data/transactions/logic/evalStateful_test.go
  data/transactions/verify/txn.go
  data/transactions/verify/txnBatch.go
Labels: Enhancement

#5532 block-generator: conduit performance benchmark scenarios.
  tools/block-generator/README.md
  tools/block-generator/scenarios/benchmarks/organic.25000.yml
  tools/block-generator/scenarios/benchmarks/organic.50000.yml
  tools/block-generator/scenarios/benchmarks/payment.25000.yml
  tools/block-generator/scenarios/benchmarks/payment.50000.yml
  tools/block-generator/scenarios/benchmarks/stress.25000.yml
  tools/block-generator/scenarios/benchmarks/stress.50000.yml
Labels: Enhancement, Team Lamprey

#5530 Chore: remove a redundant argument to maintain single source of truth
  cmd/goal/clerk.go
  data/transactions/verify/txn.go
  data/transactions/verify/txn_test.go
Labels: Enhancement

#5534 fix: catchpoint pending hashes locking
  ledger/catchupaccessor.go
  ledger/store/trackerdb/sqlitedriver/sqlitedriver.go
  ledger/store/trackerdb/store.go
Labels: Team Carbon-11, Bug-Fix

#5531 Runtime: Add delete-if-exists check for the no longer used indexer.sqlite file…
  cmd/algod/main.go
Labels: Enhancement

#5533 test: Replace timer with counter loop in TestNodeTxHandlerRestart
  test/e2e-go/features/catchup/catchpointCatchup_test.go
  test/e2e-go/features/catchup/stateproofsCatchup_test.go
Labels: Enhancement, Team Carbon-11

#5529 CICD: Update docker containers to newer versions
  Dockerfile
  README.md
  docker/Dockerfile
  docker/build/Dockerfile
  docker/build/Dockerfile-deploy
  docker/build/aptly.Dockerfile
  docker/build/cicd.alpine.Dockerfile
  docker/build/cicd.centos.Dockerfile
  docker/build/cicd.centos8.Dockerfile
  docker/build/cicd.ubuntu.Dockerfile
  docker/build/docker.ubuntu.Dockerfile
  docker/build/releases-page.Dockerfile
  scripts/release/README.md
  scripts/release/common/docker/setup.Dockerfile
  scripts/release/common/setup.sh
  scripts/release/test/util/test_package.sh
  test/muleCI/mule.yaml
  test/packages/test_release.sh
  test/platform/test_linux_amd64_compatibility.sh
Labels: Enhancement

#5536 tests: fix coder tester for TxType bound
  protocol/codec_tester.go
Labels: Team Carbon-11, Skip-Release-Notes

#5552 CICD: Fix debian package error
  installer/debian/algorand-devtools/conffiles
Labels: Team Hyper Flow, Bug-Fix

#5551 catchup: Catchup variable reuse
  catchup/catchpointService.go
Labels: Enhancement

#5564 CICD: Update ubuntu circleci image and orbs
  .circleci/config.yml
Labels: Enhancement, Team Hyper Flow

#5565 perf tests: use metrics for memory usage charts
  shared/pingpong/pingpong.go
  test/heapwatch/client_ram_report.py
  test/heapwatch/plot_crr_csv.py
Labels: Enhancement, Team Carbon-11

#5555 CICD: downgrade ubuntu to 20.04 and ensure ARM64 binaries are built static
  .circleci/config.yml
  .github/workflows/pr-type-category.yml
  Dockerfile
  Makefile
  README.md
  docker/build/Dockerfile
  docker/build/Dockerfile-deploy
  docker/build/aptly.Dockerfile
  docker/build/cicd.ubuntu.Dockerfile
  docker/build/docker.ubuntu.Dockerfile
  docker/build/releases-page.Dockerfile
  scripts/release/README.md
  scripts/release/common/docker/setup.Dockerfile
Labels: Team Hyper Flow, Bug-Fix

#5585 docs: Fix broken markdown in follower documentation.
  docs/follower_node.md
Labels: Team Lamprey, Bug-Fix

#5563 Algod: Simulate endpoint scratch-change exposure
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/data/routes.go
  daemon/algod/api/server/v2/generated/experimental/routes.go
  daemon/algod/api/server/v2/generated/model/types.go
  daemon/algod/api/server/v2/generated/nonparticipating/private/routes.go
  daemon/algod/api/server/v2/generated/nonparticipating/public/routes.go
  daemon/algod/api/server/v2/generated/participating/private/routes.go
  daemon/algod/api/server/v2/generated/participating/public/routes.go
  daemon/algod/api/server/v2/utils.go
  data/transactions/logic/debugger.go
  data/transactions/logic/eval.go
  data/transactions/logic/opcodes.go
  ledger/simulation/simulation_eval_test.go
  ledger/simulation/trace.go
  ledger/simulation/tracer.go
  test/e2e-go/restAPI/restClient_test.go
Labels: Team Scytale, New Feature

#5584 tools: let catchpointdump to calculate and print data hashes
  catchup/catchpointService_test.go
  cmd/catchpointdump/file.go
  components/mocks/mockCatchpointCatchupAccessor.go
  ledger/catchupaccessor.go
  rpcs/ledgerService.go
Labels: Enhancement, Team Carbon-11

#5579 ledger: use single SP verification hash/data query for catchpoint tracking & generation
  ledger/catchpointtracker.go
  ledger/catchpointtracker_test.go
  ledger/catchpointwriter.go
  ledger/catchpointwriter_test.go
Labels: Bug-Fix

#5589 goal: support simulate scratch in exec trace
  cmd/goal/clerk.go
  test/scripts/e2e_client_runner.py
  test/scripts/e2e_subs/e2e-app-simulate.sh
  test/scripts/e2e_subs/tealprogs/stack-scratch.teal
Labels: Enhancement

#5590 CircleCI: Update macos xcode versions
  .circleci/config.yml
Labels: Enhancement

#5571 cli: clarify program source flag description
  cmd/goal/clerk.go
Labels: Enhancement, Team Lamprey

#5572 chore: use string builder instead of string concatenation in catchup service
  catchup/service.go
Labels: Enhancement, Team Lamprey

#5562 build: remove sqlite from release configurations
  docker/Dockerfile
  docker/build/Dockerfile
  docker/build/Dockerfile-deploy
  docker/build/cicd.alpine.Dockerfile
  docker/build/cicd.centos.Dockerfile
  docker/build/cicd.centos8.Dockerfile
  docker/build/cicd.ubuntu.Dockerfile
  scripts/check_deps.sh
  scripts/release/common/docker/centos.Dockerfile
  scripts/release/common/docker/centos8.Dockerfile
  scripts/release/common/setup.sh
Labels: Enhancement

#5582 tools: Reorganize block generator scripts.
  tools/block-generator/Makefile
  tools/block-generator/README.md
  tools/block-generator/generator/config_test.go
  tools/block-generator/generator/test_scenario.yml
  tools/block-generator/run_tests.sh
  tools/block-generator/scripts/print_tps.py
  tools/block-generator/scripts/run_postgres.sh
  tools/block-generator/scripts/run_runner.py
  tools/block-generator/scripts/run_runner.sh
Labels: Enhancement, Team Lamprey

#5592 catchpoint: use read connection for data retrieval for spver hash calculation
  ledger/catchpointtracker.go
Labels: Enhancement, Team Carbon-11

#5583 ledger: move MakeCatchpointReader back to the Reader interface
  ledger/catchpointtracker.go
  ledger/catchpointwriter.go
  ledger/store/trackerdb/sqlitedriver/catchpoint.go
  ledger/store/trackerdb/sqlitedriver/sqlitedriver.go
  ledger/store/trackerdb/store.go
Labels: Team Carbon-11, Bug-Fix

#5600 DevOps: rel/beta re-merge
  .github/workflows/pr-type-category.yml
  Dockerfile
  Makefile
  README.md
  docker/build/Dockerfile
  docker/build/Dockerfile-deploy
  docker/build/aptly.Dockerfile
  docker/build/cicd.ubuntu.Dockerfile
  docker/build/docker.ubuntu.Dockerfile
  docker/build/releases-page.Dockerfile
  installer/debian/algorand-devtools/conffiles
  scripts/release/README.md
  scripts/release/common/docker/setup.Dockerfile
Labels: Team Hyper Flow, Skip-Release-Notes

#5488 ledger: generic kv trackers backend implementation
  Makefile
  ledger/store/trackerdb/generickv/accounts_ext_reader.go
  ledger/store/trackerdb/generickv/accounts_ext_writer.go
  ledger/store/trackerdb/generickv/accounts_reader.go
  ledger/store/trackerdb/generickv/accounts_writer.go
  ledger/store/trackerdb/generickv/catchpoint.go
  ledger/store/trackerdb/generickv/init_accounts.go
  ledger/store/trackerdb/generickv/migrations.go
  ledger/store/trackerdb/generickv/msgp_gen.go
  ledger/store/trackerdb/generickv/msgp_gen_test.go
  ledger/store/trackerdb/generickv/onlineaccounts_reader.go
  ledger/store/trackerdb/generickv/onlineaccounts_writer.go
  ledger/store/trackerdb/generickv/reader.go
  ledger/store/trackerdb/generickv/schema.go
  ledger/store/trackerdb/generickv/stateproof_reader.go
  ledger/store/trackerdb/generickv/stateproof_writer.go
  ledger/store/trackerdb/generickv/writer.go
  ledger/store/trackerdb/testsuite/README.md
  ledger/store/trackerdb/testsuite/accounts_ext_kv_test.go
  ledger/store/trackerdb/testsuite/accounts_kv_test.go
  ledger/store/trackerdb/testsuite/dbsemantics_test.go
  ledger/store/trackerdb/testsuite/migration_test.go
  ledger/store/trackerdb/testsuite/mockdb_test.go
  ledger/store/trackerdb/testsuite/onlineaccounts_kv_test.go
  ledger/store/trackerdb/testsuite/sqlitedb_test.go
  ledger/store/trackerdb/testsuite/stateproofs_kv_test.go
  ledger/store/trackerdb/testsuite/utils_test.go
Labels: Team Carbon-11, New Feature

#5594 ledger: rename catchpointWriter to catchpointFileWriter for clarity
  ledger/catchpointfilewriter.go
  ledger/catchpointfilewriter_test.go
  ledger/catchpointtracker.go
Labels: tech debt, Team Carbon-11, Skip-Release-Notes

#5607 ledger: fixes to store interface after kv merge
  ledger/store/trackerdb/generickv/catchpoint.go
  ledger/store/trackerdb/generickv/msgp_gen.go
  ledger/store/trackerdb/generickv/onlineaccounts_reader.go
  ledger/store/trackerdb/generickv/reader.go
  ledger/store/trackerdb/testsuite/accounts_kv_test.go
  ledger/store/trackerdb/testsuite/onlineaccounts_kv_test.go
  ledger/store/trackerdb/testsuite/utils_test.go
Labels: Team Carbon-11, Skip-Release-Notes

#5609 goal: `--all-trace-options` keeps track of everything in exec trace
  cmd/goal/clerk.go
  test/scripts/e2e_subs/e2e-app-simulate.sh
Labels: Enhancement

#5617 tools: option to run test multiple times.
  tools/block-generator/generator/generate.go
  tools/block-generator/runner/run.go
  tools/block-generator/runner/runner.go
Labels: Enhancement, Team Lamprey

#5612 netdeploy: allow simple local net topologies
  netdeploy/network.go
  netdeploy/networkTemplate.go
  netdeploy/networkTemplates_test.go
  netdeploy/network_test.go
  netdeploy/remote/nodeConfig.go
  test/testdata/nettemplates/FiveNodesTwoRelays.json
Labels: Enhancement, Team Carbon-11

#5618 CICD: Macos dependencies
  scripts/configure_dev.sh
Labels: Team Hyper Flow, Bug-Fix

#5576 p2p: adding peerstore
  go.mod
  go.sum
  network/p2p/peerstore/peerstore.go
  network/p2p/peerstore/peerstore_test.go
  network/p2p/peerstore/utils.go
  network/p2p/peerstore/utils_test.go
  tools/block-generator/go.mod
  tools/block-generator/go.sum
  tools/x-repo-types/go.mod
  tools/x-repo-types/go.sum
Labels: Enhancement

#5613 node: use correct allocbound on netprioResponse Nonce field
  node/msgp_gen.go
  node/netprio.go
  node/netprio_test.go
  protocol/tags.go
Labels: Team Carbon-11, Skip-Release-Notes

#5527 ledger: increase locks granularity in lookupWithoutRewards
  ledger/acctupdates.go
Labels: Enhancement, Team Carbon-11

#5593 agreement: add omitempty to MessageHandle in agreement message
  agreement/message.go
  agreement/message_test.go
  agreement/msgp_gen.go
Labels: tech debt, Team Carbon-11, Skip-Release-Notes

#5528 AVM: Enable pooling of logicsig execution across a group
  cmd/goal/clerk.go
  cmd/tealdbg/debugger_test.go
  cmd/tealdbg/local.go
  cmd/tealdbg/localLedger_test.go
  config/consensus.go
  daemon/algod/api/server/v2/dryrun.go
  daemon/algod/api/server/v2/dryrun_test.go
  data/transactions/logic/README.md
  data/transactions/logic/README_in.md
  data/transactions/logic/assembler.go
  data/transactions/logic/backwardCompat_test.go
  data/transactions/logic/blackbox_test.go
  data/transactions/logic/debugger_eval_test.go
  data/transactions/logic/eval.go
  data/transactions/logic/evalAppTxn_test.go
  data/transactions/logic/evalBench_test.go
  data/transactions/logic/evalCrypto_test.go
  data/transactions/logic/evalStateful_test.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/export_test.go
  data/transactions/logic/fields_test.go
  data/transactions/logic/opcodes.go
  data/transactions/logic/resources_test.go
  data/transactions/logic/tracer_test.go
  data/transactions/verify/artifact_test.go
  data/transactions/verify/txn.go
  data/transactions/verify/txn_test.go
  data/transactions/verify/verifiedTxnCache.go
  data/transactions/verify/verifiedTxnCache_test.go
  ledger/apply/application_test.go
  ledger/eval/eval.go
  ledger/simulation/simulation_eval_test.go
  test/scripts/e2e_subs/app-group.py
  test/scripts/e2e_subs/app-inner-calls-csp.py
  test/scripts/e2e_subs/app-inner-calls.py
  test/scripts/e2e_subs/app-rekey.py
  test/scripts/e2e_subs/example.py
  test/scripts/e2e_subs/goal/goal.py
  test/scripts/e2e_subs/hdr-access.py
  test/scripts/e2e_subs/lsig-budget.py
  test/scripts/e2e_subs/shared-resources.py
Labels: Enhancement
