Repository algorand/go-algorand, pull requests merged in 2023-05, with the labels that each got.

#5351 tools: add block-generator into published build
  scripts/build_package.sh
Labels: Enhancement, Team Lamprey

#5339 tools: block generator data reporting
  tools/block-generator/requirements.txt
  tools/block-generator/runner/run.go
  tools/block-generator/upload_metrics.py
Labels: Enhancement, Team Lamprey

#5353 DevOps: Add CODEOWNERS to restrict workflow edits
  .github/workflows/pr-type-category.yml
  CODEOWNERS
Labels: Enhancement, Security, Team Hyper Flow

#5356 goal: Make goal state schema optional
  cmd/goal/README.md
  cmd/goal/application.go
  config/consensus.go
  data/transactions/transaction.go
  data/transactions/transaction_test.go
  test/scripts/e2e_subs/access-previous-scratch.sh
  test/scripts/e2e_subs/box-search.sh
  test/scripts/e2e_subs/e2e-app-abi-arg.sh
  test/scripts/e2e_subs/e2e-app-abi-method.sh
  test/scripts/e2e_subs/e2e-app-bootloader.sh
  test/scripts/e2e_subs/e2e-app-delete-clear.sh
  test/scripts/e2e_subs/e2e-app-extra-pages.sh
  test/scripts/e2e_subs/goal-app-create-state-defaults.sh
  test/scripts/e2e_subs/teal-creatable-id.sh
Labels: Enhancement

#5349 follow mode: set sync round after fast catchup.
  catchup/service.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_test.go
  node/error.go
  node/follower_node.go
  node/follower_node_test.go
Labels: Enhancement

#5359 logging: fix logging to line.
  daemon/algod/server.go
Labels: Bug-Fix

#5328 AVM: No low resources
  cmd/opdoc/opdoc.go
  config/consensus.go
  daemon/algod/api/server/v2/dryrun_test.go
  data/bookkeeping/genesis.go
  data/transactions/logic/README.md
  data/transactions/logic/README_in.md
  data/transactions/logic/assembler.go
  data/transactions/logic/assembler_test.go
  data/transactions/logic/box_test.go
  data/transactions/logic/doc_test.go
  data/transactions/logic/eval.go
  data/transactions/logic/evalAppTxn_test.go
  data/transactions/logic/evalStateful_test.go
  data/transactions/logic/fields_test.go
  data/transactions/logic/langspec.json
  data/transactions/logic/opcodes.go
  data/transactions/logic/resources.go
  data/transactions/logic/resources_test.go
  data/transactions/transaction.go
  data/txntest/txn.go
  ledger/apply/application.go
  ledger/apply/application_test.go
  ledger/apptxn_test.go
  ledger/boxtxn_test.go
  ledger/double_test.go
  ledger/eval/eval_test.go
  ledger/eval/txntracer_test.go
  ledger/eval_simple_test.go
  test/e2e-go/cli/goal/expect/goalAccountTest.exp
  test/scripts/e2e_subs/assets-app-b.sh
  test/scripts/e2e_subs/assets-app.sh
  test/scripts/e2e_subs/e2e-app-stateful-global.sh
  test/scripts/e2e_subs/e2e-app-stateful-local.sh
  test/scripts/e2e_subs/e2e-app-x-app-reads.sh
  test/scripts/e2e_subs/sectok-app.sh
Labels: Enhancement

#5354 Algod: Simulation run with extra budget per transaction group
  cmd/goal/clerk.go
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/data/routes.go
  daemon/algod/api/server/v2/generated/experimental/routes.go
  daemon/algod/api/server/v2/generated/model/types.go
  daemon/algod/api/server/v2/generated/nonparticipating/private/routes.go
  daemon/algod/api/server/v2/generated/nonparticipating/public/routes.go
  daemon/algod/api/server/v2/generated/participating/private/routes.go
  daemon/algod/api/server/v2/generated/participating/public/routes.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/utils.go
  ledger/simulation/simulation_eval_test.go
  ledger/simulation/simulator.go
  ledger/simulation/trace.go
  ledger/simulation/tracer.go
  test/e2e-go/restAPI/restClient_test.go
  test/scripts/e2e_subs/e2e-app-simulate.sh
Labels: Team Scytale, New Feature

#5350 algod: Txn Group Delta Apis
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/errors.go
  daemon/algod/api/server/v2/generated/data/routes.go
  daemon/algod/api/server/v2/generated/experimental/routes.go
  daemon/algod/api/server/v2/generated/model/types.go
  daemon/algod/api/server/v2/generated/nonparticipating/private/routes.go
  daemon/algod/api/server/v2/generated/nonparticipating/public/routes.go
  daemon/algod/api/server/v2/generated/participating/private/routes.go
  daemon/algod/api/server/v2/generated/participating/public/routes.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_resources_test.go
  daemon/algod/api/server/v2/test/handlers_test.go
  daemon/algod/api/server/v2/utils.go
  ledger/eval/txntracer.go
  ledger/ledger.go
Labels: New Feature

#5362 Algod: Use future consensus version to test with no low resources
  daemon/algod/api/server/v2/test/handlers_test.go
  daemon/algod/api/server/v2/test/helpers.go
  ledger/applications_test.go
  ledger/simulation/simulation_eval_test.go
  ledger/simulation/testing/utils.go
  ledger/testing/initState.go
Labels: Enhancement

#5326 tools: Run the Cross Repo Type Checker in C.I.
  .gitignore
  tools/x-repo-types/Makefile
  tools/x-repo-types/README.md
  tools/x-repo-types/go.mod
  tools/x-repo-types/go.sum
  tools/x-repo-types/typeAnalyzer/main.go
  tools/x-repo-types/typeAnalyzer/typeAnalyzer.go
  tools/x-repo-types/xrt.go
  tools/x-repo-types/xrt_test.go
Labels: Enhancement

#5363 Tests: Fix error messages in ledger tests
  ledger/acctonline_test.go
  ledger/acctupdates_test.go
  ledger/catchpointtracker_test.go
  ledger/voters_test.go
Labels: Enhancement

#5130 AVM: Modify StackType to provide additional information
  cmd/opdoc/opdoc.go
  data/transactions/logic/README.md
  data/transactions/logic/README_in.md
  data/transactions/logic/TEAL_opcodes.md
  data/transactions/logic/assembler.go
  data/transactions/logic/assembler_test.go
  data/transactions/logic/box_test.go
  data/transactions/logic/doc.go
  data/transactions/logic/doc_test.go
  data/transactions/logic/eval.go
  data/transactions/logic/evalAppTxn_test.go
  data/transactions/logic/evalStateful_test.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/fields.go
  data/transactions/logic/fields_test.go
  data/transactions/logic/langspec.json
  data/transactions/logic/opcodes.go
Labels: Enhancement

#5372 Documentation: Add container image tagging information
  docker/README.md
Labels: Team Hyper Flow, Skip-Release-Notes

#5361 lint: enable nilerr linter and fix errors
  .golangci.yml
  cmd/loadgenerator/main.go
  crypto/merklesignature/keysBuilder.go
  data/account/participation_test.go
  data/transactions/logic/eval.go
  ledger/acctdeltas_test.go
  ledger/acctonline.go
  ledger/catchpointtracker.go
  libgoal/libgoal.go
  node/follower_node_test.go
Labels: Enhancement

#5375 txngroup-deltas: Fix pointer bug copying deltas for txngroups
  daemon/algod/api/server/v2/test/handlers_test.go
  ledger/eval/eval_test.go
  ledger/eval/txntracer.go
  ledger/eval/txntracer_test.go
Labels: Bug-Fix

#5380 tools: allow dumpblocks work with wal-enabled dbs
  tools/debug/dumpblocks/main.go
Labels: Enhancement

#5368 Algod: Add EvalTracer tests for StateDeltas
  data/transactions/logic/mocktracer/scenarios.go
  data/transactions/logic/mocktracer/tracer.go
  ledger/eval/cow_test.go
  ledger/eval/eval_test.go
  ledger/ledgercore/statedelta.go
  ledger/ledgercore/statedelta_test.go
  ledger/simulation/simulation_eval_test.go
  ledger/simulation/simulator_test.go
  ledger/simulation/testing/utils.go
  ledger/simulation/trace.go
  ledger/simulation/tracer_test.go
Labels: Enhancement

#5367 flakes: reduce flakiness in TestSyncRoundWithRemake
  node/follower_node_test.go
Labels: Bug-Fix

#5389 DevOps: Update CODEOWNERS to only refer to the devops group
  CODEOWNERS
Labels: Enhancement, unplanned, Team Hyper Flow

#5395 Dependency: Update codec version to 1.1.9
  go.mod
  go.sum
Labels: Team Hyper Flow, Bug-Fix

#5396 algod: Move delta API tags
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/data/routes.go
  daemon/algod/api/server/v2/generated/nonparticipating/public/routes.go
Labels: Enhancement

#5392 netdeploy: Copy ledger directory for kv tracker database
  netdeploy/remote/nodecfg/nodeConfigurator.go
Labels: Enhancement, Team Carbon-11

#5400 assembler: Error if extra args are present in pragmas
  data/transactions/logic/assembler.go
  data/transactions/logic/assembler_test.go
  data/txntest/txn.go
  ledger/simulation/simulation_eval_test.go
  netdeploy/remote/deployedNetwork.go
  test/e2e-go/restAPI/restClient_test.go
Labels: Bug-Fix

#5403 ledger: Exclude stake at R-320 that is expired by R
  agreement/abstractions.go
  agreement/agreementtest/simulate_test.go
  agreement/common_test.go
  agreement/demux_test.go
  agreement/fuzzer/ledger_test.go
  agreement/selector.go
  catchup/service_test.go
  config/consensus.go
  data/datatest/impls.go
  data/ledger.go
  data/ledger_test.go
  ledger/acctonline.go
  ledger/acctonline_expired_test.go
  ledger/acctonline_test.go
  ledger/acctupdates.go
  ledger/acctupdates_test.go
  ledger/catchpointtracker_test.go
  ledger/double_test.go
  ledger/ledger.go
  ledger/ledger_test.go
  ledger/simple_test.go
  ledger/store/trackerdb/interface.go
  ledger/store/trackerdb/sqlitedriver/accountsV2.go
  ledger/store/trackerdb/sqlitedriver/schema.go
  ledger/store/trackerdb/sqlitedriver/trackerdbV2.go
  ledger/testing/testGenesis.go
Labels: Enhancement, Team Carbon-11

#5404 algod: Don't return a top level array from algod
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/data/routes.go
  daemon/algod/api/server/v2/generated/experimental/routes.go
  daemon/algod/api/server/v2/generated/model/types.go
  daemon/algod/api/server/v2/generated/nonparticipating/private/routes.go
  daemon/algod/api/server/v2/generated/nonparticipating/public/routes.go
  daemon/algod/api/server/v2/generated/participating/private/routes.go
  daemon/algod/api/server/v2/generated/participating/public/routes.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_test.go
Labels: Enhancement

#5405 typo: fix typo in event.go
  logging/telemetryspec/event.go
Labels: Skip-Release-Notes

#5384 tools: run block generator using a preloaded db
  tools/block-generator/generator/generate.go
  tools/block-generator/generator/generate_test.go
  tools/block-generator/generator/server.go
  tools/block-generator/run_runner.sh
  tools/block-generator/runner/run.go
  tools/block-generator/runner/runner.go
Labels: Enhancement, Team Lamprey

#5410 bug fix: block generator test
  tools/block-generator/generator/generate_test.go
Labels: Team Lamprey, Bug-Fix

#5357 docker: Fix ADMIN_TOKEN and add missing variables to echo statements.
  docker/files/run/run.sh
Labels: Team Lamprey, Bug-Fix

#5413 ledger: report catchpoint writing only when it actually started
  ledger/acctonline.go
  ledger/acctupdates.go
  ledger/bulletin.go
  ledger/catchpointtracker.go
  ledger/catchpointtracker_test.go
  ledger/ledger.go
  ledger/metrics.go
  ledger/notifier.go
  ledger/spverificationtracker.go
  ledger/tracker.go
  ledger/tracker_test.go
  ledger/txtail.go
Labels: Team Carbon-11, Bug-Fix

#5407 Goal: rename `--allow-extra-opcode-budget` to `--allow-more-opcode-budget`
  cmd/goal/clerk.go
  test/scripts/e2e_subs/e2e-app-simulate.sh
Labels: Enhancement

#5416 lint: Fix lint errors in `config/`
  config/consensus.go
  config/migrate.go
Labels: Enhancement

#5408 community: Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: Enhancement

#5398 Enhancement: 1. `go mod tidy` + 2. `diffutils` when mac OS
  Makefile
  scripts/configure_dev.sh
  scripts/get_golang_version.sh
  scripts/travis/codegen_verification.sh
Labels: Enhancement

#5421 AVM: Simplify conversion and fix a spurious complaint from static analysis
  data/transactions/logic/debugger.go
  data/transactions/logic/debugger_test.go
  data/transactions/logic/eval.go
Labels: Enhancement

#5402 TEAL: Add columns to assembly error messages.
  .golangci.yml
  cmd/opdoc/opdoc.go
  data/transactions/logic/assembler.go
  data/transactions/logic/assembler_test.go
  data/transactions/logic/backwardCompat_test.go
  data/transactions/logic/box_test.go
  data/transactions/logic/evalAppTxn_test.go
  data/transactions/logic/evalStateful_test.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/export_test.go
  data/transactions/logic/fields_test.go
  data/transactions/logic/frames_test.go
  data/transactions/logic/resources_test.go
Labels: Enhancement

#5409 tools: enable consecutive test runs in the block generator
  Makefile
  go.mod
  tools/block-generator/README.md
  tools/block-generator/generator/generate.go
  tools/block-generator/go.mod
  tools/block-generator/go.sum
  tools/block-generator/run_postgres.sh
  tools/block-generator/run_runner.sh
  tools/block-generator/run_tests.sh
  tools/block-generator/runner/run.go
  tools/block-generator/runner/runner.go
  tools/block-generator/scenarios/config.mixed.jumbo.yml
  tools/block-generator/scenarios/config.payment.full.yml
  tools/block-generator/scenarios/config.payment.jumbo.yml
  tools/block-generator/scenarios/config.payment.small.yml
  tools/block-generator/util/util.go
Labels: Enhancement, Team Lamprey

#5425 AVM: Make apps and app accounts available while creation is "pending"
  data/transactions/logic/eval.go
  data/transactions/logic/resources.go
  ledger/apptxn_test.go
  ledger/double_test.go
Labels: Enhancement

#5433 CICD: fix ci-build target for buildsrc-special support
  scripts/release/mule/Makefile.mule
Labels: Team Hyper Flow, Bug-Fix

#5436 test: skip flaky test `TestVotersReloadFromDiskPassRecoveryPeriod`
  ledger/ledger_test.go
Labels: Skip-Release-Notes

#5422 AVM: Increase coverage by deleting a dead function and adding limit tests
  data/transactions/logic/eval.go
  data/transactions/logic/evalAppTxn_test.go
  data/transactions/logic/evalStateful_test.go
Labels: Enhancement
