Repository algorand/go-algorand, pull requests merged in 2023-06, with the labels that each got.

#5437 Testing: Get rapid into the codebase
  data/transactions/logic/eval_test.go
  go.mod
  go.sum
Labels: Enhancement

#5261 lint: enable govet shadow linter and resolve linter warnings
  .golangci.yml
  agreement/demux.go
  agreement/pseudonode.go
  cmd/algocfg/profileCommand.go
  cmd/catchpointdump/net.go
  cmd/goal/account.go
  cmd/goal/application.go
  cmd/goal/asset.go
  cmd/goal/interact.go
  cmd/goal/network.go
  cmd/goal/tealsign.go
  cmd/loadgenerator/main.go
  cmd/netgoal/network.go
  cmd/pingpong/runCmd.go
  crypto/stateproof/prover.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/server.go
  data/account/participationRegistry.go
  data/account/registeryDbOps.go
  data/transactions/logic/assembler.go
  data/transactions/logic/eval.go
  data/transactions/logic/frames.go
  ledger/acctonline.go
  ledger/acctupdates.go
  ledger/apply/application.go
  ledger/apply/asset.go
  ledger/catchpointtracker.go
  ledger/catchupaccessor.go
  ledger/eval/eval.go
  ledger/eval/prefetcher/prefetcher.go
  ledger/store/trackerdb/sqlitedriver/accountsV2.go
  ledger/store/trackerdb/sqlitedriver/orderedAccountsIter.go
  ledger/store/trackerdb/sqlitedriver/schema.go
  ledger/store/trackerdb/sqlitedriver/sql.go
  ledger/store/trackerdb/sqlitedriver/trackerdbV2.go
  netdeploy/networkTemplate.go
  network/wsNetwork.go
  shared/pingpong/accounts.go
  stateproof/builder.go
  tools/block-generator/runner/run.go
  tools/debug/dumpblocks/main.go
  util/execpool/stream.go
Labels: Enhancement, Team Carbon-11

#5420 tools: txn replayer
  tools/debug/transplanter/main.go
Labels: Enhancement, Team Carbon-11

#5386 Algod: Add README file to state proof package
  stateproof/README.md
Labels: Enhancement

#5383 Bookkeeping: improve block documentation since no-low-resources
  data/bookkeeping/block.go
Labels: Skip-Release-Notes

#5419 config: make Tx dedupe cache maxSize configurable
  config/localTemplate.go
  config/local_defaults.go
  data/txHandler.go
  installer/config.json.example
  test/testdata/configs/config-v28.json
Labels: Enhancement, Team Carbon-11

#5216 cleanup: remove redundant method LookupAccountDataByAddress
  ledger/acctdeltas.go
  ledger/acctdeltas_test.go
  ledger/acctupdates_test.go
  ledger/store/trackerdb/data_test.go
  ledger/store/trackerdb/interface.go
  ledger/store/trackerdb/sqlitedriver/accountsV2.go
  ledger/store/trackerdb/sqlitedriver/sql.go
  ledger/store/trackerdb/store.go
  ledger/store/trackerdb/testinterface.go
Labels: Team Carbon-11, Skip-Release-Notes

#5429 build: use external sortition package
  data/committee/credential.go
  data/committee/sortition/sortition.cpp
  data/committee/sortition/sortition.go
  data/committee/sortition/sortition.h
  data/committee/sortition/sortition_test.go
  go.mod
  go.sum
  tools/block-generator/go.mod
  tools/block-generator/go.sum
Labels: Enhancement, Team Carbon-11, Team Hyper Flow

#5441 AVM: Some error cleanup, and added coverage
  data/transactions/logic/assembler.go
  data/transactions/logic/assembler_test.go
  data/transactions/logic/eval.go
  data/transactions/logic/evalAppTxn_test.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/opcodes.go
  data/transactions/logic/resources_test.go
  ledger/apptxn_test.go
Labels: Enhancement

#5446 config: let go-generate to produce config-vXX.json files
  config/config_test.go
  config/defaultsGenerator/defaultsGenerator.go
  config/migrate.go
  test/testdata/configs/config-v27.json
Labels: Team Carbon-11, Skip-Release-Notes

#5448 typo: Fix typo in blockService_test.go
  rpcs/blockService_test.go
Labels: Skip-Release-Notes

#5381 tools: EvalDelta and ConsensusParams x-repo type checks
  .github/workflows/tools.yml
  Makefile
  tools/block-generator/go.sum
  tools/x-repo-types/typeAnalyzer/typeAnalyzer.go
  tools/x-repo-types/xrt_test.go
Labels: Enhancement

#5453 CI: don't use deprecated set-output in github actions
  .github/workflows/build.yml
  .github/workflows/reviewdog.yml
  .github/workflows/tools.yml
Labels: Bug-Fix

#5449 tools: bugfix block-generator to handle conduit's Init block requests
  tools/block-generator/generator/generate.go
  tools/block-generator/generator/generate_test.go
  tools/block-generator/runner/run.go
Labels: Bug-Fix

#5457 algod: adjust numeric version encoding
  config/version.go
  config/version_test.go
  util/s3/s3Helper_test.go
Labels: Team Carbon-11, Bug-Fix

#5087 Algod: Leverage 2 SRV record providers for resolving relay addresses w/ de-duplication.
  cmd/algod/main.go
  cmd/algoh/main.go
  cmd/catchupsrv/download.go
  config/config_test.go
  config/dnsbootstrap.go
  config/dnsbootstrap_test.go
  config/localTemplate.go
  config/local_defaults.go
  installer/config.json.example
  internal/rapidgen/rapidgenerators.go
  internal/rapidgen/tld.go
  netdeploy/remote/nodecfg/nodeDir.go
  network/wsNetwork.go
  network/wsNetwork_test.go
  test/testdata/configs/config-v28.json
  tools/network/telemetryURIUpdateService.go
Labels: New Feature

#5445 Fix: Large Database Generation
  cmd/netgoal/generate.go
  netdeploy/remote/bootstrappedNetwork.go
  netdeploy/remote/deployedNetwork.go
  test/testdata/deployednettemplates/recipes/bootstrappedScenario/Makefile
  test/testdata/deployednettemplates/recipes/bootstrappedScenario/boostrappedFile.json
Labels: Team Carbon-11, Bug-Fix

#5458 go-algorand 3.16.1-beta Release PR
  buildnumber.dat
  config/version.go
  config/version_test.go
  daemon/algod/api/server/v2/handlers.go
  ledger/eval/eval.go
  util/s3/s3Helper_test.go
Labels: Team Hyper Flow

#5459 build: remove boost dependency and internal sortition package
  .github/workflows/reviewdog.yml
  .github/workflows/tools.yml
  data/committee/sortition/sortition.cpp
  data/committee/sortition/sortition.go
  data/committee/sortition/sortition.h
  data/committee/sortition/sortition_test.go
  docker/Dockerfile
  docker/build/Dockerfile
  docker/build/Dockerfile-deploy
  docker/build/cicd.alpine.Dockerfile
  docker/build/cicd.centos.Dockerfile
  docker/build/cicd.centos8.Dockerfile
  docker/build/cicd.ubuntu.Dockerfile
  docker/build/docker.ubuntu.Dockerfile
  scripts/configure_dev.sh
  scripts/install_linux_deps.sh
  scripts/release/common/docker/centos.Dockerfile
  scripts/release/common/docker/centos8.Dockerfile
  scripts/travis/configure_dev.sh
Labels: Enhancement

#5385 network: peer selector expansion and PeersPhonebookArchivalNodes
  catchup/peerSelector.go
  catchup/peerSelector_test.go
  catchup/service.go
  catchup/service_test.go
  network/wsNetwork.go
  network/wsNetwork_test.go
  tools/network/bootstrap.go
  tools/network/bootstrap_test.go
Labels: Enhancement, Team Carbon-11

#5443 tools: prepare block-generator for configuring apps
  tools/block-generator/README.md
  tools/block-generator/generator/config.go
  tools/block-generator/generator/config_test.go
  tools/block-generator/generator/generate.go
  tools/block-generator/generator/generate_test.go
  tools/block-generator/generator/generator_types.go
  tools/block-generator/generator/server.go
  tools/block-generator/generator/server_test.go
Labels: Enhancement

#5463 genesis: add GenesisAccountData type for use in GenesisAllocation
  cmd/incorporate/incorporate.go
  data/bookkeeping/genesis.go
  data/bookkeeping/genesis_test.go
  data/bookkeeping/msgp_gen.go
  data/bookkeeping/msgp_gen_test.go
  gen/generate.go
  netdeploy/remote/deployedNetwork.go
  node/follower_node_test.go
  tools/block-generator/generator/generate.go
Labels: Enhancement

#5467 AVM: proper cross product check for app put and del
  data/transactions/logic/eval.go
  data/transactions/logic/evalStateful_test.go
  data/transactions/logic/resources_test.go
Labels: Bug-Fix

#5468 go-algorand v3.16.2-beta
  buildnumber.dat
  data/transactions/logic/eval.go
  data/transactions/logic/evalStateful_test.go
  data/transactions/logic/resources_test.go
Labels: Team Hyper Flow

#5469 go-algorand 3.16.2-stable Release PR
  buildnumber.dat
  data/transactions/logic/eval.go
  data/transactions/logic/evalStateful_test.go
  data/transactions/logic/resources_test.go
Labels: Team Hyper Flow

#5450 tools: block-generator applications. Part 1: create
  .gitignore
  tools/block-generator/Makefile
  tools/block-generator/generator/generate.go
  tools/block-generator/generator/generate_test.go
  tools/block-generator/generator/generator_types.go
  tools/block-generator/generator/make_transactions.go
  tools/block-generator/generator/teal/poap_boxes.teal
  tools/block-generator/generator/teal/poap_clear.teal
  tools/block-generator/generator/teal/swap_amm.teal
  tools/block-generator/generator/teal/swap_clear.teal
  tools/block-generator/run_runner.py
  tools/block-generator/runner/runner.go
  tools/block-generator/scenarios/config.app.create.yml
  tools/block-generator/util/util.go
Labels: Enhancement

#5466 cmd/updater: add install directory to logging
  cmd/updater/update.sh
Labels: Skip-Release-Notes

#5471 encoding: Update go-codec version.
  go.mod
  go.sum
  tools/block-generator/go.mod
  tools/block-generator/go.sum
Labels: Enhancement

#5476 network: improve MsgOfInterest message handling
  network/msgOfInterest.go
  network/wsNetwork_test.go
  network/wsPeer.go
  network/wsPeer_test.go
  protocol/tags.go
  protocol/tags_test.go
Labels: Enhancement, Team Carbon-11

#5451 ledger: refactor store module interfaces before kv impl merge
  ledger/acctdeltas.go
  ledger/acctdeltas_test.go
  ledger/acctonline.go
  ledger/acctonline_test.go
  ledger/acctupdates.go
  ledger/acctupdates_test.go
  ledger/archival_test.go
  ledger/catchpointtracker.go
  ledger/catchpointtracker_test.go
  ledger/catchpointwriter.go
  ledger/catchpointwriter_test.go
  ledger/catchupaccessor.go
  ledger/ledger.go
  ledger/ledger_test.go
  ledger/spverificationtracker.go
  ledger/spverificationtracker_test.go
  ledger/store/merkle_committer.go
  ledger/store/testing/helpers.go
  ledger/store/trackerdb/interface.go
  ledger/store/trackerdb/sqlitedriver/accountsV2.go
  ledger/store/trackerdb/sqlitedriver/catchpointPendingHashesIter.go
  ledger/store/trackerdb/sqlitedriver/encodedAccountsIter.go
  ledger/store/trackerdb/sqlitedriver/kvsIter.go
  ledger/store/trackerdb/sqlitedriver/merkle_commiter.go
  ledger/store/trackerdb/sqlitedriver/orderedAccountsIter.go
  ledger/store/trackerdb/sqlitedriver/schema.go
  ledger/store/trackerdb/sqlitedriver/spVerificationAccessor.go
  ledger/store/trackerdb/sqlitedriver/sql.go
  ledger/store/trackerdb/sqlitedriver/sql_test.go
  ledger/store/trackerdb/sqlitedriver/sqlitedriver.go
  ledger/store/trackerdb/sqlitedriver/store_sqlite_impl.go
  ledger/store/trackerdb/sqlitedriver/testing.go
  ledger/store/trackerdb/sqlitedriver/trackerdbV2.go
  ledger/store/trackerdb/store.go
  ledger/store/trackerdb/testinterface.go
  ledger/tracker.go
  ledger/trackerdb.go
  ledger/txtail.go
  ledger/txtail_test.go
Labels: Team Carbon-11, Skip-Release-Notes

#5470 tools: replace upload_metrics
  tools/block-generator/print_tps.py
  tools/block-generator/upload_metrics.py
Labels: Enhancement, Team Lamprey

#5431 network: discard unrequested or stale block messages
  network/wsNetwork_test.go
  network/wsPeer.go
  util/metrics/counter.go
  util/metrics/counter_test.go
Labels: Enhancement, Team Carbon-11

#5477 Cleanup: Remove indexer v1 from codebase
  .golangci.yml
  cmd/goal/node.go
  config/localTemplate.go
  config/local_defaults.go
  daemon/algod/api/server/v2/test/helpers.go
  installer/config.json.example
  node/indexer/db.go
  node/indexer/indexer.go
  node/indexer/indexer_test.go
  node/node.go
  test/testdata/configs/config-v28.json
Labels: Enhancement

#5482 CICD: go-algorand relstable3.16.2-remerge mergeback
  config/version.go
  config/version_test.go
  ledger/eval/eval.go
  util/s3/s3Helper_test.go
Labels: Team Hyper Flow, Skip-Release-Notes

#5485 Build: Split nightly job into its own workflow. Remove ARM64 platform builds from our triggered/on commit builds.
  .circleci/config.yml
Labels: Enhancement

#5486 api: Disable body limit middleware for admin endpoints.
  daemon/algod/api/server/router.go
  daemon/algod/api/server/router_test.go
  daemon/algod/api/server/v2/test/handlers_test.go
  daemon/algod/api/server/v2/test/helpers.go
Labels: Bug-Fix

#5489 go-algorand v3.16.3-beta
  buildnumber.dat
  daemon/algod/api/server/router.go
  daemon/algod/api/server/router_test.go
  daemon/algod/api/server/v2/test/handlers_test.go
  daemon/algod/api/server/v2/test/helpers.go
Labels: Team Hyper Flow

#5473 netdeploy: Add AdminAPIToken to network templates
  netdeploy/remote/buildConfig.go
  netdeploy/remote/deployedNetwork.go
  netdeploy/remote/nodeConfig.go
  netdeploy/remote/nodecfg/nodeDir.go
  test/testdata/deployednettemplates/configs/reference.json
  test/testdata/deployednettemplates/recipes/baseline/reference.json
  test/testdata/deployednettemplates/recipes/custom/configs/node.json
  test/testdata/deployednettemplates/recipes/custom/configs/relay.json
  test/testdata/deployednettemplates/recipes/scenario1s/net.json
  test/testdata/deployednettemplates/recipes/scenario1s/relay.json
  test/testdata/deployednettemplates/recipes/scenario3s/genesis.json
  test/testdata/deployednettemplates/recipes/scenario3s/net.json
  test/testdata/deployednettemplates/recipes/scenario3s/relay.json
Labels: Skip-Release-Notes

#5487 tests: flaky tests fixes
  Makefile
  data/ledger_test.go
  tools/network/dnssec/sort_test.go
Labels: Team Carbon-11, Skip-Release-Notes

#5491 CI: Don't run tests during benchmark
  .github/workflows/benchmarks.yml
Labels: Enhancement

#5479 Chore: Use exp/slices and exp/maps to simplify some code
  agreement/agreementtest/simulate_test.go
  agreement/autopsy.go
  agreement/common_test.go
  cmd/algokey/keyreg.go
  cmd/goal/account.go
  cmd/opdoc/opdoc.go
  cmd/tealdbg/local.go
  crypto/merklearray/merkle.go
  crypto/merkletrie/cache.go
  crypto/merkletrie/committer.go
  crypto/merkletrie/committer_test.go
  crypto/merkletrie/node.go
  daemon/algod/api/server/v2/account.go
  daemon/algod/api/server/v2/test/handlers_test.go
  daemon/algod/api/server/v2/utils.go
  data/basics/teal.go
  data/basics/userBalance.go
  data/transactions/application.go
  data/transactions/common_test.go
  data/transactions/logic/eval.go
  data/transactions/logic/evalCrypto_test.go
  data/transactions/logic/opcodes.go
  data/transactions/logic/opcodes_test.go
  data/transactions/teal.go
  data/transactions/transaction.go
  go.mod
  go.sum
  ledger/acctupdates.go
  ledger/acctupdates_test.go
  ledger/apply/application_test.go
  ledger/apply/asset_test.go
  ledger/apply/mockBalances_test.go
  ledger/eval/cow.go
  ledger/eval/txntracer.go
  ledger/ledger.go
  ledger/ledger_test.go
  ledger/ledgercore/statedelta.go
  network/phonebook.go
  stateproof/builder.go
  test/e2e-go/upgrades/stateproof_participation_test.go
  test/reflectionhelpers/helpers.go
  tools/block-generator/go.mod
  tools/block-generator/go.sum
  util/metrics/tagcounter.go
Labels: Enhancement

#5490 go-algorand 3.16.3-stable Release PR
  buildnumber.dat
  daemon/algod/api/server/router.go
  daemon/algod/api/server/router_test.go
  daemon/algod/api/server/v2/test/handlers_test.go
  daemon/algod/api/server/v2/test/helpers.go
Labels: Team Hyper Flow

#5494 tests: fix flaky ledger stateproof and rpcs tests
  ledger/ledger_test.go
  rpcs/blockService_test.go
Labels: Skip-Release-Notes

#5495 Chore: more deadcode
  ledger/store/trackerdb/interface.go
  ledger/store/trackerdb/sqlitedriver/sql.go
  ledger/store/trackerdb/sqlitedriver/sql_test.go
Labels: Skip-Release-Notes

#5481 algocfg: Add EnableTxnEvalTracer to algocfg development profile.
  cmd/algocfg/profileCommand.go
Labels: Enhancement

#5393 catchup: Add HEAD request to catchpoint service start
  catchup/catchpointService.go
  catchup/ledgerFetcher.go
  catchup/ledgerFetcher_test.go
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/nonparticipating/private/routes.go
  daemon/algod/api/server/v2/handlers.go
  node/error.go
  node/follower_node.go
  node/node.go
  rpcs/ledgerService.go
  rpcs/ledgerService_test.go
  test/e2e-go/features/catchup/catchpointCatchup_test.go
  tools/block-generator/go.sum
Labels: Enhancement

#5497 Chore: Use generics to simplify some code in v2
  daemon/algod/api/server/v2/account.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/utils.go
Labels: Skip-Release-Notes

#5499 Fix: goal clerk rawsend print pending round rather than ptr to round
  cmd/goal/clerk.go
  test/scripts/e2e_subs/rawsend.sh
Labels: Bug-Fix

#5501 Chore: apply `golang.org/x/exp/constraints` to `overflow.go`
  data/basics/overflow.go
  data/basics/units_test.go
  ledger/apply/application.go
Labels: Skip-Release-Notes

#5502 algocfg: Remove block validation override from participation profile.
  cmd/algocfg/profileCommand.go
Labels: Enhancement, Team Lamprey

#5478 tools: block generator apps. Part 2: boxes
  tools/block-generator/Makefile
  tools/block-generator/README.md
  tools/block-generator/generator/config.go
  tools/block-generator/generator/generate.go
  tools/block-generator/generator/generate_test.go
  tools/block-generator/generator/generator_types.go
  tools/block-generator/generator/make_transactions.go
  tools/block-generator/generator/server.go
  tools/block-generator/generator/teal/poap_boxes.teal
  tools/block-generator/go.mod
  tools/block-generator/run_runner.py
  tools/block-generator/run_runner.sh
  tools/block-generator/run_tests.sh
  tools/block-generator/runner/run.go
  tools/block-generator/runner/runner.go
  tools/block-generator/scenarios/config.allmixed.jumbo.yml
  tools/block-generator/scenarios/config.allmixed.small.yml
  tools/block-generator/scenarios/config.appboxes.small.yml
  tools/block-generator/scenarios/config.appcreate.small.yml
Labels: Enhancement

#5507 tests: Fix catchpoint catchup tests to use relay for catchup
  test/e2e-go/features/catchup/catchpointCatchup_test.go
Labels: Enhancement

#5513 enhancement: fix slow docker container start up
  Dockerfile
Labels: Team Lamprey, Bug-Fix

#5515 API: Allow DELETE calls
  daemon/algod/api/server/lib/middlewares/cors.go
Labels: Enhancement

#5516 Fix: Use Buffered syncNow channel to correctly trigger sync in private networks
  catchup/service.go
Labels: Bug-Fix

#5472 network:ws block byte limiter
  catchup/fetcher_test.go
  catchup/peerSelector_test.go
  config/localTemplate.go
  config/local_defaults.go
  installer/config.json.example
  network/wsNetwork.go
  network/wsNetwork_test.go
  network/wsPeer.go
  rpcs/blockService.go
  rpcs/blockService_test.go
  test/testdata/configs/config-v28.json
Labels: Enhancement, Team Carbon-11

#5506 tools: block generator inner transactions
  tools/block-generator/Makefile
  tools/block-generator/generator/config.go
  tools/block-generator/generator/generate.go
  tools/block-generator/generator/generate_apps.go
  tools/block-generator/generator/generate_test.go
  tools/block-generator/generator/generator_ledger.go
  tools/block-generator/generator/generator_types.go
  tools/block-generator/generator/make_transactions.go
  tools/block-generator/generator/teal/poap_boxes.teal
  tools/block-generator/runner/run.go
  tools/block-generator/scenarios/config.appboxes.small.yml
Labels: Bug-Fix

#5519 Bugfix: rawsend.sh nightly test failure fix
  test/scripts/e2e_subs/rawsend.sh
Labels: Bug-Fix

#5514 docker: Start kmd in the background.
  Dockerfile
  docker/files/run/run.sh
Labels: Team Lamprey, Bug-Fix

#5518 bugfix: ensure blockservice callbacks are not nil
  network/wsPeer.go
Labels: Team Carbon-11, Bug-Fix

#5520 tests: fix TestLedgerReloadStateProofVerificationTracker
  ledger/acctonline.go
  ledger/ledger_test.go
  ledger/spverificationtracker.go
Labels: Team Carbon-11, Skip-Release-Notes
