Repository algorand/go-algorand, pull requests merged in 2023-03, with the labels that each got.

#5165 goal: catchup without args prompts to continue
  cmd/goal/messages.go
  cmd/goal/node.go
Labels: Enhancement, Team Carbon-11

#5170 Do not stop stateproof service in fast catchup mode
  node/node.go
  stateproof/worker.go
  test/e2e-go/features/catchup/stateproofsCatchup_test.go
Labels: Team Carbon-11, Bug-Fix

#5171 api: lower default for MaxHeaderBytes.
  daemon/algod/server.go
Labels: Bug-Fix

#4917 AVM: Go19 curve check
  config/consensus.go
  data/transactions/logic/eval.go
Labels: Enhancement

#5159 Algod: Make simulation endpoint non-experimental
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/data/routes.go
  daemon/algod/api/server/v2/generated/experimental/routes.go
  daemon/algod/api/server/v2/generated/nonparticipating/private/routes.go
  daemon/algod/api/server/v2/generated/nonparticipating/public/routes.go
  daemon/algod/api/server/v2/generated/participating/private/routes.go
  daemon/algod/api/server/v2/generated/participating/public/routes.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_test.go
Labels: Enhancement

#5155 deploy templates: Recipe Changes
  test/testdata/deployednettemplates/generate-recipe/generate_network_tpl.py
  test/testdata/deployednettemplates/recipes/custom/README.md
  test/testdata/deployednettemplates/recipes/custom/configs/node.json
  test/testdata/deployednettemplates/recipes/custom/example/npr/five-relays.txt
  test/testdata/deployednettemplates/recipes/custom/network_templates/five-relays.json
  test/testdata/deployednettemplates/recipes/legacy-mainnet-model/Makefile
  test/testdata/deployednettemplates/recipes/legacy-mainnet-model/README.md
  test/testdata/deployednettemplates/recipes/legacy-mainnet-model/configs/node.json
  test/testdata/deployednettemplates/recipes/legacy-mainnet-model/configs/nonPartNode.json
  test/testdata/deployednettemplates/recipes/legacy-mainnet-model/configs/relay.json
  test/testdata/deployednettemplates/recipes/legacy-mainnet-model/data/bandwidth.json
  test/testdata/deployednettemplates/recipes/legacy-mainnet-model/data/countries.json
  test/testdata/deployednettemplates/recipes/legacy-mainnet-model/data/latency.json
  test/testdata/deployednettemplates/recipes/legacy-mainnet-model/generate_network_rules.js
  test/testdata/deployednettemplates/recipes/legacy-mainnet-model/generated/genesis.json
  test/testdata/deployednettemplates/recipes/legacy-mainnet-model/generated/net.json
  test/testdata/deployednettemplates/recipes/legacy-mainnet-model/generated/topology.json
  test/testdata/deployednettemplates/recipes/legacy-mainnet-model/network-tpl.json
  test/testdata/deployednettemplates/recipes/legacy-mainnet-model/network_performance_rules
  test/testdata/deployednettemplates/recipes/legacy-mainnet-model/recipe.json
Labels: Enhancement

#5178 deploy templates: increase default npn number for mmnet-model
  test/testdata/deployednettemplates/generate-recipe/generate_network_tpl.py
Labels: Team Carbon-11, Skip-Release-Notes

#5175 Refactor: Push test-only functionality of storage interfaces into test-interface.
  ledger/acctdeltas_test.go
  ledger/acctonline_test.go
  ledger/acctupdates_test.go
  ledger/ledger_test.go
  ledger/store/trackerdb/interface.go
  ledger/store/trackerdb/sqlitedriver/accountsV2.go
  ledger/store/trackerdb/sqlitedriver/store_sqlite_impl.go
  ledger/store/trackerdb/sqlitedriver/testing.go
  ledger/store/trackerdb/store.go
  ledger/store/trackerdb/testinterface.go
  ledger/txtail_test.go
Labels: Enhancement, tech debt

#5177 ledger: remove "rowid" from the public interface
  ledger/acctdeltas.go
  ledger/acctdeltas_test.go
  ledger/acctonline.go
  ledger/acctonline_test.go
  ledger/acctupdates.go
  ledger/acctupdates_test.go
  ledger/applications_test.go
  ledger/catchpointtracker.go
  ledger/lruaccts_test.go
  ledger/lruonlineaccts_test.go
  ledger/lruresources_test.go
  ledger/store/trackerdb/data.go
  ledger/store/trackerdb/interface.go
  ledger/store/trackerdb/sqlitedriver/accountsV2.go
  ledger/store/trackerdb/sqlitedriver/orderedAccountsIter.go
  ledger/store/trackerdb/sqlitedriver/sql.go
Labels: Team Carbon-11, Skip-Release-Notes

#4993 Tests: Fix t.Parallel() errors in netdeploy package
  .golangci.yml
  netdeploy/networkTemplates_test.go
  netdeploy/network_test.go
  netdeploy/remote/bootstrappedNetwork_test.go
  netdeploy/remote/deployedNetwork_test.go
Labels: Enhancement

#4991 Tests: Fix t.Parallel() errors in cmd package
  .golangci.yml
  cmd/algocfg/getCommand_test.go
  cmd/algofix/deadlock_test.go
  cmd/algofix/main_test.go
  cmd/algoh/blockWatcher_test.go
  cmd/algoh/blockstats_test.go
  cmd/catchupsrv/download_test.go
  cmd/goal/application_test.go
  cmd/goal/commands_test.go
  cmd/goal/formatting_test.go
  cmd/goal/inspect_test.go
  cmd/goal/node_test.go
  cmd/tealdbg/cdtSession_test.go
  cmd/tealdbg/cdtdbg_test.go
  cmd/tealdbg/debugger_test.go
  cmd/tealdbg/localLedger_test.go
  cmd/tealdbg/local_test.go
  cmd/tealdbg/remote_test.go
  cmd/tealdbg/server_test.go
  cmd/tealdbg/webdbg_test.go
  cmd/updater/version_test.go
Labels: Enhancement

#5184 Enhancement: Disable LRU `flushPendingWrite` warning if disabled
  ledger/acctonline.go
  ledger/acctupdates.go
Labels: Enhancement

#5160 docs: Message pack information.
  docs/messagepack.md
Labels: Enhancement, Team Lamprey

#5142 agreement: update AttachReceivedAt to handle compound (PP) messages
  agreement/demux.go
  agreement/events.go
  agreement/msgp_gen.go
  agreement/player_test.go
  agreement/proposal.go
Labels: Enhancement, Team Carbon-11

#5164 feat(algocfg): add development profile and profile descriptions.
  cmd/algocfg/profileCommand.go
Labels: Enhancement, Team Lamprey

#5181 Docs: add follower node documentation.
  docs/follower_node.md
Labels: Enhancement

#5182 devmode: Fix devmode networking
  node/node.go
Labels: Enhancement, Team Lamprey

#5188 ledger: fix error shadowing in onlineAccountsNewRoundImpl
  data/transactions/logic/eval.go
  data/transactions/logic/evalAppTxn_test.go
  data/transactions/logic/evalStateful_test.go
  data/transactions/logic/eval_test.go
  ledger/acctdeltas.go
  ledger/acctdeltas_test.go
  ledger/acctonline.go
  ledger/internal/appcow.go
Labels: Team Carbon-11, Bug-Fix

#5193 algocfg: Bug fix - Add colon to indicate port specification
  cmd/algocfg/profileCommand.go
Labels: Team Hyper Flow, Bug-Fix

#5196 CI: set reviewdog golangci-lint go version
  .github/workflows/reviewdog.yml
  ledger/internal/appcow.go
  logging/telemetryspec/metric.go
Labels: Enhancement

#4922 goal: user defined scheme to connect to remote host
  nodecontrol/algodControl.go
Labels: Enhancement, external contribution

#5192 ERL: Support zero-size reservations
  util/rateLimit.go
  util/rateLimit_test.go
Labels: Bug-Fix

#5168 refactor: Move streamVerifier to util/execpool/stream (phase 2)
  data/transactions/verify/txnBatch.go
  data/transactions/verify/txnBatch_test.go
  data/txHandler.go
  util/execpool/stream.go
  util/execpool/stream_test.go
Labels: Team Carbon-11, Skip-Release-Notes

#5195 Catchpoints: Small tweaks, mostly to comments
  crypto/merkletrie/cache.go
  crypto/merkletrie/cache_test.go
  crypto/merkletrie/committer.go
  crypto/merkletrie/committer_test.go
  crypto/merkletrie/node.go
  crypto/merkletrie/node_test.go
  crypto/merkletrie/trie.go
  ledger/store/merkle_committer.go
Labels: Enhancement

#5200 txHandler: make dedup working set independent from ERL
  config/config.go
  data/txHandler.go
  data/txHandler_test.go
  ledger/catchpointtracker_test.go
Labels: Team Carbon-11, Bug-Fix

#5211 Algod: Remove unused 404 resp in simulate endpoint
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/nonparticipating/public/routes.go
Labels: Enhancement

#5210 catchpointdump: fix panic when processing gzip files
  cmd/catchpointdump/file.go
Labels: Team Carbon-11, Skip-Release-Notes

#5207 Fix: Tech Debt (wsNetwork "auto" and OnlineAccountsDelete comment)
  ledger/store/trackerdb/sqlitedriver/accountsV2.go
  network/wsNetwork.go
  network/wsNetwork_test.go
Labels: Enhancement, Team Carbon-11

#5213 Goal: Introduce new command for simulate
  cmd/goal/application.go
  cmd/goal/clerk.go
  daemon/algod/api/client/restClient.go
  libgoal/libgoal.go
  test/scripts/e2e_subs/e2e-app-simulate.sh
Labels: Enhancement

#5223 CICD: go-algorand relstable3.15.0-remerge mergeback
  config/version.go
Labels: Team Hyper Flow, Skip-Release-Notes

#5224 util/s3: improve patch number capacity in version comparison
  cmd/updater/version_test.go
  util/s3/s3Helper.go
  util/s3/s3Helper_test.go
Labels: Team Carbon-11, Skip-Release-Notes

#5000 Dev Tools: Integrate Logfile Navigator (lnav)
  daemon/algod/server.go
  scripts/algorand_node_log.json
  scripts/configure_dev.sh
Labels: Enhancement

#5231 test: enable runtime metrics in custom templates
  test/testdata/deployednettemplates/recipes/custom/configs/nonPartNode.json
  test/testdata/deployednettemplates/recipes/custom/configs/relay.json
Labels: Team Carbon-11, Skip-Release-Notes

#5221 Simulate: Add opcode costs and budgets into response
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/data/routes.go
  daemon/algod/api/server/v2/generated/experimental/routes.go
  daemon/algod/api/server/v2/generated/model/types.go
  daemon/algod/api/server/v2/generated/nonparticipating/private/routes.go
  daemon/algod/api/server/v2/generated/nonparticipating/public/routes.go
  daemon/algod/api/server/v2/generated/participating/private/routes.go
  daemon/algod/api/server/v2/generated/participating/public/routes.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_test.go
  daemon/algod/api/server/v2/utils.go
  data/transactions/logic/mocktracer/scenarios.go
  ledger/simulation/simulation_eval_test.go
  ledger/simulation/simulator.go
  ledger/simulation/trace.go
  ledger/simulation/tracer.go
Labels: Enhancement

#5209 docker container: dockerfile update
  docker/README.md
  docker/files/run/followermode_template.json
  docker/files/run/run.sh
Labels: Enhancement, Team Lamprey

#5235 algod: search phonebook in data directory as well
  cmd/algod/main.go
Labels: Enhancement, Team Carbon-11

#5236 ledger: rename "internal" to "eval"
  ledger/acctupdates_test.go
  ledger/archival_test.go
  ledger/double_test.go
  ledger/eval/appcow.go
  ledger/eval/appcow_test.go
  ledger/eval/applications.go
  ledger/eval/assetcow.go
  ledger/eval/cow.go
  ledger/eval/cow_creatables.go
  ledger/eval/cow_test.go
  ledger/eval/eval.go
  ledger/eval/eval_test.go
  ledger/eval/evalindexer.go
  ledger/eval/prefetcher/error.go
  ledger/eval/prefetcher/prefetcher.go
  ledger/eval/prefetcher/prefetcher_alignment_test.go
  ledger/eval/prefetcher/prefetcher_test.go
  ledger/eval/prefetcher/prefetcher_whitebox_test.go
  ledger/evalbench_test.go
  ledger/evalindexer.go
  ledger/fullblock_perf_test.go
  ledger/ledger.go
  ledger/ledger_perf_test.go
  ledger/simple_test.go
  ledger/simulation/simulator_test.go
  ledger/tracker.go
Labels: Enhancement

#5239 tools: Don't use strings.Title in chopper
  tools/debug/chopper/main.go
Labels: Enhancement

#5225 ledger: convert FC unmarshalled nil value to empty byte slice on DB write KVs
  ledger/acctdeltas_test.go
  ledger/catchupaccessor.go
  ledger/store/trackerdb/sqlitedriver/schema.go
  ledger/store/trackerdb/sqlitedriver/testing.go
  ledger/store/trackerdb/sqlitedriver/trackerdbV2.go
Labels: Enhancement

#5244 tests: fix expect test regex and logger
  test/e2e-go/cli/goal/expect/goalExpectCommon.exp
Labels: Team Carbon-11, Skip-Release-Notes

#5245 tools: block generator
  .gitignore
  tools/block-generator/README.md
  tools/block-generator/core/commands.go
  tools/block-generator/generator/daemon.go
  tools/block-generator/generator/generate.go
  tools/block-generator/generator/generate_test.go
  tools/block-generator/generator/make_transactions.go
  tools/block-generator/generator/server.go
  tools/block-generator/generator/server_test.go
  tools/block-generator/generator/utils.go
  tools/block-generator/generator/utils_test.go
  tools/block-generator/main.go
  tools/block-generator/metrics/metrics.go
  tools/block-generator/run_generator.sh
  tools/block-generator/run_postgres.sh
  tools/block-generator/run_runner.sh
  tools/block-generator/run_tests.sh
  tools/block-generator/runner/metrics_collector.go
  tools/block-generator/runner/run.go
  tools/block-generator/runner/runner.go
  tools/block-generator/scenarios/config.asset.close.yml
  tools/block-generator/scenarios/config.asset.destroy.yml
  tools/block-generator/scenarios/config.asset.xfer.yml
  tools/block-generator/scenarios/config.mixed.jumbo.yml
  tools/block-generator/scenarios/config.mixed.yml
  tools/block-generator/scenarios/config.payment.full.yml
  tools/block-generator/scenarios/config.payment.jumbo.yml
  tools/block-generator/scenarios/config.payment.small.yml
  tools/block-generator/test_config.yml
  tools/block-generator/util/util.go
Labels: Enhancement, Team Lamprey

#4844 Algod: New health endpoint (k8s `/ready` endpoint)
  catchup/service.go
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/client/restClient.go
  daemon/algod/api/server/common/handlers.go
  daemon/algod/api/server/common/routes.go
  daemon/algod/api/server/common/test/handlers_test.go
  daemon/algod/api/server/common/test/helpers.go
  daemon/algod/api/server/lib/common.go
  daemon/algod/api/server/v2/generated/data/routes.go
  daemon/algod/api/server/v2/generated/experimental/routes.go
  daemon/algod/api/server/v2/generated/nonparticipating/private/routes.go
  daemon/algod/api/server/v2/generated/nonparticipating/public/routes.go
  daemon/algod/api/server/v2/generated/participating/private/routes.go
  daemon/algod/api/server/v2/generated/participating/public/routes.go
  daemon/algod/api/server/v2/test/helpers.go
  node/follower_node.go
  test/e2e-go/features/catchup/basicCatchup_test.go
  test/e2e-go/features/catchup/catchpointCatchup_test.go
  test/e2e-go/features/followerNode/syncDeltas_test.go
Labels: Enhancement, Team Scytale
