Repository algorand/go-algorand, pull requests merged in 2023-11, with the labels that each got.

#5815 tests: add refreshAvailablePeers catchup unit test
  catchup/peerSelector.go
  catchup/peerSelector_test.go
Labels: Skip-Release-Notes

#5814 ledger: support WaitWithCancel for unsuccessful WaitForBlock API calls
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_resources_test.go
  ledger/bulletin.go
  ledger/bulletin_test.go
  ledger/ledger.go
Labels: Enhancement

#5598 ledger: make catchpoint generation backward compatible
  ledger/catchpointtracker.go
  ledger/catchpointtracker_test.go
  ledger/tracker.go
Labels: Team Carbon-11, Bug-Fix

#5819 catchup: Provide more information to client when requested block not available
  catchup/universalFetcher.go
  catchup/universalFetcher_test.go
  rpcs/blockService.go
Labels: Enhancement

#5809 catchup: fetchAndWrite/fetchRound quit early on errNoBlockForRound
  catchup/peerSelector.go
  catchup/service.go
  catchup/service_test.go
  test/e2e-go/features/catchup/basicCatchup_test.go
Labels: Enhancement

#5821 build: regenerate api routes and resolve merge error in catchup
  catchup/service.go
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/data/routes.go
  daemon/algod/api/server/v2/generated/experimental/routes.go
  daemon/algod/api/server/v2/generated/nonparticipating/private/routes.go
  daemon/algod/api/server/v2/generated/nonparticipating/public/routes.go
  daemon/algod/api/server/v2/generated/participating/private/routes.go
  daemon/algod/api/server/v2/generated/participating/public/routes.go
  data/transactions/logic/Makefile
Labels: Skip-Release-Notes

#5802 catchup: Dynamic parallel catchup
  catchup/service.go
Labels: Enhancement

#5824 algocfg: Add print option to algocfg.
  cmd/algocfg/profileCommand.go
  cmd/algocfg/resetCommand.go
  cmd/algocfg/setCommand.go
  config/localTemplate.go
  util/codecs/json.go
  util/codecs/json_test.go
Labels: Enhancement

#5827 p2p dht: more tests and minor fixes
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/data/routes.go
  daemon/algod/api/server/v2/generated/experimental/routes.go
  daemon/algod/api/server/v2/generated/nonparticipating/private/routes.go
  daemon/algod/api/server/v2/generated/nonparticipating/public/routes.go
  daemon/algod/api/server/v2/generated/participating/private/routes.go
  daemon/algod/api/server/v2/generated/participating/public/routes.go
  network/p2p/capabilities_test.go
  network/p2p/dht/dht.go
Labels: Skip-Release-Notes

#5833 p2p: fix dht-hybrid merge
  network/p2p/p2p.go
Labels: Skip-Release-Notes

#5834 typo: fix typos in md files
  README.md
  data/transactions/logic/README.md
  data/transactions/logic/README_in.md
  data/transactions/logic/jsonspec.md
  docs/follower_node.md
  scripts/windows/instructions.md
Labels: external contribution, Skip-Release-Notes

#5830 ledger: rollback vetting historical stateproof blocks
  ledger/eval/eval.go
  ledger/eval/eval_test.go
Labels: Bug-Fix

#5817 config: move crash and stateproof DB defaults to hot dir
  config/config_test.go
  config/localTemplate.go
  node/follower_node.go
  node/node.go
  node/node_test.go
Labels: Enhancement

#5836 catchup: use specialized backoff behavior for follower mode
  catchup/service.go
Labels: Enhancement

#5759 statetrie: nibbles
  crypto/statetrie/nibbles/nibbles.go
  crypto/statetrie/nibbles/nibbles_test.go
Labels: New Feature

#5838 catchup: increase followLatestBackoff to 100ms
  catchup/service.go
Labels: Enhancement

#5700 cgo: Properly manage memory passing from cgo to go on Batch Verifiers
  crypto/batchverifier.c
  crypto/batchverifier.go
  crypto/curve25519.go
  crypto/onetimesig.go
  crypto/util.go
  crypto/util_test.go
Labels: Enhancement, Team Carbon-11

#5839 tests: fix state proof e2e test failures
  config/consensus.go
  test/e2e-go/features/stateproofs/stateproofs_test.go
Labels: Skip-Release-Notes

#5840 chore: Cut out some useless allocations when computing payset commitments
  crypto/hashes.go
  crypto/merklearray/layer.go
  crypto/merklearray/merkle_test.go
  crypto/merklearray/partial.go
Labels: Enhancement

#5846 catchup: Fix empty cert if ledger already has a block
  catchup/catchpointService.go
  catchup/catchpointService_test.go
  ledger/catchupaccessor.go
Labels: Bug-Fix
