Repository algorand/go-algorand, pull requests merged in 2024-08, with the labels that each got.

#6091 netgoal: allow unknown template tokens
  cmd/netgoal/network.go
  netdeploy/remote/deployedNetwork.go
Labels: Enhancement

#6078 cmd: Add goal node subcommand to generate peer private key
  cmd/goal/node.go
  cmd/goal/p2pid.go
Labels: Enhancement, p2p

#6093 tests: fixes to e2e test logs parsers
  test/heapwatch/agreement-log.py
  test/heapwatch/topology-extract-ws-e2e.py
  test/heapwatch/topology-extract-ws.py
Labels: Skip-Release-Notes

#6095 tests: fix e2e subs goal-partkey-commands
  test/scripts/e2e.sh
  test/scripts/e2e_subs/goal-partkey-commands.sh
Labels: Bug-Fix

#6092 p2p: do not advertise private and non-routable addresses
  network/hybridNetwork_test.go
  network/p2p/p2p.go
  network/p2p/p2p_test.go
Labels: Enhancement, p2p

#6070 p2p: handle txns in pubsub validator
  components/mocks/mockNetwork.go
  data/transactions/verify/txnBatch.go
  data/transactions/verify/txnBatch_test.go
  data/txHandler.go
  data/txHandler_test.go
  network/gossipNode.go
  network/hybridNetwork.go
  network/multiplexer.go
  network/p2p/pubsub.go
  network/p2p/pubsubTracer.go
  network/p2pNetwork.go
  network/p2pNetwork_test.go
  network/wsNetwork.go
  test/e2e-go/features/p2p/p2p_basic_test.go
  util/metrics/metrics.go
Labels: Enhancement, p2p

#6081 network: remove ws net proto 2.1
  network/msgCompressor.go
  network/msgCompressor_test.go
  network/wsNetwork.go
  network/wsNetwork_test.go
  network/wsPeer.go
Labels: Enhancement

#6098 tests: flaky tests fixes
  ledger/ledger_test.go
  network/p2p/p2p_test.go
  test/scripts/e2e_subs/goal-partkey-commands.sh
Labels: Skip-Release-Notes

#6096 docs: p2p package overview
  catchup/ledgerFetcher.go
  catchup/universalFetcher.go
  network/README-P2P.md
  network/limitcaller/rateLimitingTransport.go
  network/p2p/README.md
  network/p2p/capabilities.go
  network/p2p/capabilities_test.go
  network/p2p/p2p.go
  network/p2pNetwork.go
  network/p2pNetwork_test.go
  network/p2pPeer.go
  node/node.go
Labels: Enhancement

#6101 p2p: get rid of interface{} from PeerStore methods
  network/p2p/capabilities_test.go
  network/p2p/p2p.go
  network/p2p/peerstore/peerstore.go
  network/p2p/peerstore/peerstore_test.go
  network/p2pNetwork.go
  network/p2pNetwork_test.go
  network/phonebook/phonebook.go
Labels: Enhancement, p2p

#6102 Installer: add support for algoh to systemd installs
  cmd/updater/systemd-setup-user.sh
  cmd/updater/systemd-setup.sh
Labels: Enhancement

#6110 network: fix publicKeyIdentTracker data race in hybrid mode
  network/netidentity.go
Labels: Bug-Fix, p2p

#6103 config: use P2PHybridIncomingConnectionsLimit only for hybrid mode
  cmd/algocfg/profileCommand.go
  cmd/algocfg/profileCommand_test.go
  config/config.go
  config/config_test.go
  config/localTemplate.go
  config/local_defaults.go
  daemon/algod/server.go
  installer/config.json.example
  netdeploy/remote/deployedNetwork.go
  netdeploy/remote/nodeConfig.go
  netdeploy/remote/nodecfg/nodeDir.go
  network/README-P2P.md
  network/hybridNetwork.go
  network/hybridNetwork_test.go
  network/p2p/README.md
  network/p2p/p2p.go
  node/node_test.go
  test/testdata/configs/config-v34.json
  test/testdata/deployednettemplates/recipes/scenario1s-p2p/copy-node-configs.py
Labels: Enhancement, p2p

#6113 FNet: named current future protocol as "fnet1"
  config/consensus.go
  protocol/consensus.go
Labels: New Feature

#6108 metrics: collect total netdev sent/received bytes
  config/localTemplate.go
  config/local_defaults.go
  daemon/algod/server.go
  go.mod
  go.sum
  installer/config.json.example
  test/testdata/configs/config-v34.json
  test/testdata/deployednettemplates/recipes/scenario1s/genesis.json
  test/testdata/deployednettemplates/recipes/scenario1s/net.json
  test/testdata/deployednettemplates/recipes/scenario1s/node.json
  test/testdata/deployednettemplates/recipes/scenario1s/nonPartNode.json
  test/testdata/deployednettemplates/recipes/scenario1s/relay.json
  tools/block-generator/go.mod
  tools/block-generator/go.sum
  util/metrics/netdev_common.go
  util/metrics/netdev_darwin.go
  util/metrics/netdev_linux.go
  util/metrics/netdev_noop.go
  util/metrics/registry.go
Labels: Enhancement

#6106 REST API: Fix `LedgerStateDelta` JSON encoding
  daemon/algod/api/client/restClient.go
  daemon/algod/api/server/v2/handlers.go
  data/transactions/transaction.go
  libgoal/libgoal.go
  test/e2e-go/features/devmode/devmode_test.go
  test/e2e-go/features/followernode/syncDeltas_test.go
Labels: Bug-Fix

#6105 p2p: Add algod_network_p2p_* traffic metrics
  cmd/algod/main.go
  network/metrics.go
  network/metrics_test.go
  network/p2p/p2p.go
  network/p2p/pubsub.go
  network/p2p/pubsubTracer.go
  network/p2pNetwork.go
  network/wsNetwork.go
  network/wsPeer.go
  test/heapwatch/block_history_plot.py
  test/heapwatch/metrics_aggs.py
  test/heapwatch/metrics_delta.py
  test/heapwatch/metrics_lib.py
  test/heapwatch/requirements.txt
  util/metrics/metrics.go
Labels: Enhancement, p2p

#6116 tests: fix a race in TestP2PwsStreamHandlerDedup
  network/p2p/capabilities_test.go
  network/p2pNetwork_test.go
Labels: Bug-Fix, p2p

#6115 tests: use temp file for capturing e2e goal-partkey-commands output
  .github/workflows/reviewdog.yml
  test/scripts/e2e_subs/goal-partkey-commands.sh
Labels: Skip-Release-Notes
