Repository algorand/go-algorand, pull requests merged in 2024-06, with the labels that each got.

#6012 CICD: update OS support in test release script
  test/packages/test_release.sh
Labels: Bug-Fix

#6016 Tests: Fix e2e kmd timeout
  test/scripts/e2e_client_runner.py
Labels: Bug-Fix

#6013 metrics: Add TagCounterFiltered metrics for handler calls
  network/wsNetwork.go
  network/wsPeer.go
Labels: Enhancement

#6017 Tests: Fix flakey htlc test
  test/scripts/e2e_subs/htlc-teal-test.sh
Labels: Bug-Fix

#6014 ledger: introduce expired stake cache
  ledger/acctonline.go
  ledger/acctonline_expired_test.go
  ledger/acctonline_test.go
  ledger/acctonlineexp.go
  ledger/acctonlineexp_test.go
Labels: Enhancement

#6019 txHandler: fixes to ERL resources management
  data/txHandler.go
  data/txHandler_test.go
Labels: Bug-Fix

#6007 agreement: log current player state for VoteBroadcast and ProposalBroadcast events
  agreement/pseudonode.go
Labels: Enhancement

#6021 tests: set communication timeout in kmd.init_wallet_handle
  test/scripts/e2e_subs/goal/goal.py
Labels: Bug-Fix

#6020 Tools: Fix Cloudflare SRV update utility after API change
  tools/network/cloudflare/createRecord.go
  tools/network/cloudflare/updateRecord.go
Labels: Bug-Fix

#6018 rest api: /debug/settings/pprof admin endpoint for debugging
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/common/handlers.go
  daemon/algod/api/server/v2/generated/data/routes.go
  daemon/algod/api/server/v2/generated/experimental/routes.go
  daemon/algod/api/server/v2/generated/model/types.go
  daemon/algod/api/server/v2/generated/nonparticipating/private/routes.go
  daemon/algod/api/server/v2/generated/nonparticipating/public/routes.go
  daemon/algod/api/server/v2/generated/participating/private/routes.go
  daemon/algod/api/server/v2/generated/participating/public/routes.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_test.go
Labels: New Feature

#6024 tests: fix TestVotersReloadFromDiskAfterOneStateProofCommitted
  ledger/ledger_test.go
  ledger/tracker.go
  ledger/tracker_test.go
Labels: Bug-Fix

#6009 network: Allow short-lived connections to query /status endpoint when at full capacity
  config/localTemplate.go
  daemon/algod/server.go
  network/requestTracker.go
  network/wsNetwork.go
  rpcs/healthService.go
  rpcs/healthService_test.go
Labels: Enhancement

#6026 tests: debug output on LibGoalFixture failure
  test/framework/fixtures/libgoalFixture.go
Labels: Skip-Release-Notes

#6025 AVM: Expose relevant incentive constants
  data/transactions/logic/assembler_test.go
  data/transactions/logic/eval.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/fields.go
  data/transactions/logic/fields_string.go
Labels: Enhancement

#6027 libgoal: output debug info on failure to stderr
  test/framework/fixtures/libgoalFixture.go
Labels: Skip-Release-Notes

#6028 Legacy Docker: pin ubuntu version
  docker/releases/build_releases.sh
Labels: Bug-Fix

#6006 config: Add warning if EndpointAddress and NetAddress ports are equal
  daemon/algod/server.go
Labels: Enhancement, external contribution

#6030 tests: preserve logs on LibGoalFixture failure
  agreement/service.go
  catchup/catchpointService.go
  catchup/service.go
  data/txHandler.go
  netdeploy/network.go
  network/wsNetwork.go
  node/impls.go
  node/node.go
  nodecontrol/algodControl.go
  rpcs/blockService.go
  rpcs/ledgerService.go
  rpcs/txSyncer.go
  stateproof/worker.go
  test/e2e-go/features/catchup/basicCatchup_test.go
  test/framework/fixtures/libgoalFixture.go
Labels: Enhancement

#5942 simulate: fix signers
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/data/routes.go
  daemon/algod/api/server/v2/generated/experimental/routes.go
  daemon/algod/api/server/v2/generated/model/types.go
  daemon/algod/api/server/v2/generated/nonparticipating/private/routes.go
  daemon/algod/api/server/v2/generated/nonparticipating/public/routes.go
  daemon/algod/api/server/v2/generated/participating/private/routes.go
  daemon/algod/api/server/v2/generated/participating/public/routes.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/utils.go
  ledger/simulation/simulation_eval_test.go
  ledger/simulation/simulator.go
  ledger/simulation/simulator_test.go
  ledger/simulation/trace.go
  ledger/simulation/tracer.go
  test/e2e-go/restAPI/simulate/simulateRestAPI_test.go
Labels: external contribution, Bug-Fix

#6033 CICD: go-algorand relstable3.25.0-remerge mergeback
  config/version.go
Labels: Team Hyper Flow, Skip-Release-Notes

#6037 catchup: do not loop forever if there is no peers
  catchup/service.go
  test/e2e-go/features/catchup/basicCatchup_test.go
Labels: Bug-Fix

#6036 CICD: remove mac AMD64 support from circleci
  .circleci/config.yml
Labels: Enhancement

#6038 p2p feature PR: CR fixes
  agreement/fuzzer/networkFacade_test.go
  agreement/gossip/network_test.go
  components/mocks/mockNetwork.go
  config/localTemplate.go
  config/local_defaults.go
  daemon/algod/server.go
  data/txHandler.go
  installer/config.json.example
  logging/log.go
  netdeploy/remote/nodecfg/nodeDir.go
  network/connPerfMon_test.go
  network/gossipNode.go
  network/hybridNetwork.go
  network/limitcaller/rateLimitingTransport.go
  network/p2p/dnsaddr/resolve.go
  network/p2p/http.go
  network/p2p/logger.go
  network/p2p/peerstore/peerstore.go
  network/p2p/peerstore/peerstore_test.go
  network/p2p/pubsub.go
  network/p2pNetwork.go
  network/p2pNetwork_test.go
  network/phonebook/phonebook.go
  network/wsNetwork.go
  node/node.go
  node/node_test.go
  test/testdata/configs/config-v34.json
  util/metrics/opencensus_test.go
Labels: Skip-Release-Notes, p2p

#6039 node: close ledger and part keys on node shutdown
  data/pools/transactionPool.go
  ledger/notifier.go
  node/node.go
Labels: Bug-Fix

#6040 p2p: more CR fixes: ERL and DHT err logging
  data/txHandler.go
  network/p2p/capabilities.go
  network/p2p/capabilities_test.go
  network/p2pNetwork.go
Labels: Skip-Release-Notes, p2p

#6003 Metrics: Add algod version to metrics
  daemon/algod/server.go
Labels: Enhancement, external contribution

#6041 ledger: restore block listeners on reloadLedger
  catchup/fetcher_test.go
  catchup/pref_test.go
  daemon/algod/api/server/v2/test/helpers.go
  data/common_test.go
  data/datatest/fabricateLedger.go
  data/ledger.go
  data/txHandler_test.go
  ledger/ledger.go
  ledger/ledger_test.go
  node/assemble_test.go
  node/follower_node.go
  node/node.go
  node/node_test.go
  rpcs/blockService_test.go
Labels: Bug-Fix

#4350 testing: set pprof labels for goroutines that use the same code for different cases
  agreement/demux.go
  network/p2pNetwork.go
  network/wsNetwork.go
  node/node.go
  util/execpool/backlog.go
  util/execpool/pool.go
  util/process.go
Labels: Enhancement
