Repository algorand/go-algorand, pull requests merged in 2024-03, with the labels that each got.

#5946 CICD: go-algorand relstable3.22.1-remerge mergeback
  data/transactions/logic/eval.go
  data/transactions/logic/evalAppTxn_test.go
Labels: Skip-Release-Notes

#5944 Network: Support simple liveness check via http on gossip server port.
  node/follower_node.go
  node/node.go
  rpcs/healthService.go
  rpcs/healthService_test.go
Labels: Enhancement

#5949 build: upgrade to go 1.20.14
  Dockerfile
  scripts/get_golang_version.sh
Labels: Skip-Release-Notes

#5955 Docker: Bump debian version in algod container
  Dockerfile
Labels: Enhancement

#5959 Network: Penalize peer/class rankings when peer does not have catchpoint
  catchup/catchpointService.go
  catchup/peerSelector.go
Labels: Enhancement

#5964 CICD: go-algorand relstable3.23.1-remerge mergeback
  config/version.go
Labels: Team Hyper Flow, Skip-Release-Notes

#5963 catchpoint: fix data files deletion in hot/cold dirs scenario
  ledger/catchpointtracker.go
  ledger/catchpointtracker_test.go
Labels: Bug-Fix

#5938 Tests: Thread testing.T through so we panic less
  agreement/service_test.go
Labels: Enhancement

#5952 tests: dump logs at the end of exit callback
  test/framework/fixtures/libgoalFixture.go
Labels: Skip-Release-Notes

#5956 metrics: support labeled gauges
  util/metrics/couge.go
  util/metrics/counter.go
  util/metrics/counterCommon.go
  util/metrics/counter_test.go
  util/metrics/gauge.go
  util/metrics/gauge_test.go
Labels: Enhancement

#5968 build: support SWAGGER_CONVERTER_API override
  .github/workflows/codegen_verification.yml
  daemon/algod/api/Makefile
  daemon/algod/api/README.md
Labels: Enhancement
