Repository algorand/go-algorand, pull requests merged in 2024-07, with the labels that each got.

#6044 network: use http.ResponseController instead of GetHTTPRequestConnection
  agreement/gossip/network_test.go
  components/mocks/mockNetwork.go
  network/gossipNode.go
  network/hybridNetwork.go
  network/p2p/p2p.go
  network/p2p/p2p_test.go
  network/p2p/streams.go
  network/p2pNetwork.go
  network/p2pNetwork_test.go
  network/requestTracker.go
  network/requestTracker_test.go
  network/wsNetwork.go
  rpcs/ledgerService.go
Labels: Enhancement

#6048 tests: extend TestP2PRelay logging
  network/p2pNetwork_test.go
Labels: Skip-Release-Notes

#6050 CI: increase artifact upload timeout
  .circleci/config.yml
Labels: Bug-Fix

#6049 Config: Expose merged configuration for easier debugging
  cmd/algod/main.go
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/data/routes.go
  daemon/algod/api/server/v2/generated/experimental/routes.go
  daemon/algod/api/server/v2/generated/nonparticipating/private/routes.go
  daemon/algod/api/server/v2/generated/nonparticipating/public/routes.go
  daemon/algod/api/server/v2/generated/participating/private/routes.go
  daemon/algod/api/server/v2/generated/participating/public/routes.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_test.go
Labels: Enhancement

#6056 tests: increase ListPeersForTopic wait time in TestP2PRelay
  network/p2pNetwork_test.go
Labels: Skip-Release-Notes

#6058 ci: pin reviewdog version to v0.18.1
  .github/workflows/reviewdog.yml
Labels: Skip-Release-Notes

#6061 algod: fix telemetry lookup if phonebook is used
  cmd/algod/main.go
Labels: Bug-Fix

#6060 tests: fix concurrent accout commits in TestLedgerVerifiesOldStateProofs
  ledger/ledger_test.go
Labels: Bug-Fix

#6059 tests: disable TestP2PRelay on CI
  ledger/ledger_test.go
  network/p2pNetwork_test.go
Labels: Skip-Release-Notes

#6047 logging: change transaction pool re-evaluation message from warn to info
  data/pools/transactionPool.go
  logging/telemetryspec/metric.go
Labels: Enhancement

#6064 P2P: Disable circuit relaying via libp2p.NoListenAddrs
  network/p2p/p2p.go
Labels: Enhancement

#6067 rest api: Fix to Disable API authentication
  daemon/algod/api/server/router.go
  test/e2e-go/restAPI/other/misc_test.go
  test/framework/fixtures/libgoalFixture.go
Labels: Bug-Fix

#6069 rest api: make RawTransactionAsync developer api
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/experimental/routes.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_test.go
Labels: Enhancement

#6062 P2P: Introduce profiles for hybridRelay, hybridArchival, and hybridClient.
  cmd/algocfg/profileCommand.go
  cmd/algocfg/profileCommand_test.go
  config/config.go
  network/p2p/p2p.go
  network/p2pNetwork.go
  network/p2pNetwork_test.go
Labels: Enhancement

#6035 p2p: hybrid node net identity for connection deduplication
  config/config.go
  config/config_test.go
  config/localTemplate.go
  config/local_defaults.go
  daemon/algod/server.go
  installer/config.json.example
  netdeploy/remote/deployedNetwork.go
  netdeploy/remote/nodeConfig.go
  netdeploy/remote/nodecfg/nodeConfigurator.go
  netdeploy/remote/nodecfg/nodeDir.go
  network/hybridNetwork.go
  network/hybridNetwork_test.go
  network/netidentity.go
  network/netidentity_test.go
  network/p2p/logger.go
  network/p2p/p2p.go
  network/p2p/peerID_test.go
  network/p2pNetwork.go
  network/p2pNetwork_test.go
  network/requestLogger_test.go
  network/requestTracker_test.go
  network/wsNetwork.go
  network/wsNetwork_test.go
  node/follower_node.go
  node/node.go
  node/node_test.go
  test/testdata/configs/config-v34.json
  test/testdata/deployednettemplates/recipes/scenario1s-p2p/Makefile
  test/testdata/deployednettemplates/recipes/scenario1s-p2p/README.md
  test/testdata/deployednettemplates/recipes/scenario1s-p2p/copy-node-configs.py
Labels: Enhancement, p2p

#6072 build: quiet duplicate libraries and ATOMIC_VAR_INT messages
  Makefile
  go.mod
  go.sum
Labels: Skip-Release-Notes

#6053 catchup: skip logging err for catchup cancellation
  catchup/service.go
Labels: Bug-Fix

#6071 CI: update nightly builds to use universal mac update
  .circleci/config.yml
  Makefile
  cmd/updater/update.sh
  package-upload.yaml
  scripts/release/mule/Makefile.mule
  scripts/release/mule/README.md
  scripts/travis/deploy_packages.sh
  test/muleCI/mule.yaml
  util/s3/s3Helper.go
Labels: Enhancement

#6080 CI: update to CentOS Stream 9 and start integrating universal target
  docker/build/cicd.centos.Dockerfile
  docker/build/cicd.centos9.Dockerfile
  package-deploy.yaml
  package-test.yaml
  package.yaml
  scripts/release/README.md
  scripts/release/build/stage/build/task.sh
  scripts/release/common/docker/centos.Dockerfile
  scripts/release/common/docker/centos9.Dockerfile
  scripts/release/common/setup.sh
  scripts/release/mule/common/ensure_centos9_image.sh
  scripts/release/mule/package/rpm/package.sh
  scripts/release/prod/rpm/run_centos.sh
  scripts/release/test/rpm/run_centos.sh
  scripts/release/test/util/test_package.sh
  test/muleCI/mule.yaml
  test/platform/test_linux_amd64_compatibility.sh
Labels: Bug-Fix

#6082 p2p: fix connection deduplication in hybrid mode
  network/p2pNetwork.go
  network/p2pNetwork_test.go
Labels: Bug-Fix, p2p

#6075 txHandler: fix TestTxHandlerAppRateLimiter
  data/appRateLimiter.go
  data/appRateLimiter_test.go
  data/txHandler_test.go
Labels: Bug-Fix

#6079 tests: fix TestNodeHybridTopology
  node/node_test.go
Labels: Skip-Release-Notes, p2p

#6084 CI: fix mac universal rebuild for nightlies
  scripts/travis/build.sh
  scripts/travis/deploy_packages.sh
Labels: Bug-Fix

#5718 rpcs: simplify API for BlockService to handle multiple HTTP paths
  catchup/fetcher_test.go
  catchup/pref_test.go
  catchup/service_test.go
  catchup/universalFetcher_test.go
  components/mocks/mockNetwork.go
  network/gossipNode.go
  network/hybridNetwork.go
  network/p2p/http.go
  network/p2pNetwork.go
  network/wsNetwork.go
  rpcs/blockService.go
  rpcs/blockService_test.go
  rpcs/registrar.go
  rpcs/txService_test.go
Labels: Skip-Release-Notes

#6086 p2p: do not register closing peer
  catchup/universalFetcher_test.go
  network/p2pNetwork.go
Labels: Bug-Fix, p2p

#6087 CICD: fix broken ci-build target
  scripts/release/mule/Makefile.mule
Labels: Bug-Fix

#6073 p2p: support EnableGossipService in p2p streams
  network/p2p/p2p.go
  network/p2p/streams.go
  network/p2pNetwork_test.go
Labels: Enhancement, p2p

#6088 tests: debug logging for TestVotersReloadFromDiskAfterOneStateProofCommitted
  ledger/acctupdates_test.go
  ledger/blockqueue_test.go
  ledger/ledger.go
  ledger/ledger_test.go
  ledger/tracker.go
Labels: Skip-Release-Notes

#6090 tests: fix flushing in TestVotersReloadFromDiskAfterOneStateProofCommitted
  ledger/ledger_test.go
Labels: Bug-Fix
