Repository algorand/go-algorand, pull requests merged in 2024-04, with the labels that each got.

#5974 Tools: Revert "feat: add support to display mnemonic discreetly for `algokey generate`"
  cmd/algokey/common.go
  cmd/algokey/common_test.go
  cmd/algokey/generate.go
  go.mod
  go.sum
Labels: Enhancement

#5977 Utils: Renaming files across devices
  config/localTemplate.go
  logging/cyclicWriter.go
  logging/cyclicWriter_test.go
  util/io.go
  util/io_test.go
Labels: Bug-Fix

#5982 p2p: fix wantTXGossip modifications
  network/p2pNetwork.go
  network/p2pNetwork_test.go
  network/wsNetwork_test.go
Labels: Bug-Fix, p2p

#5985 Tests: Fix `AccountsUpdateSchemaTest` ignoring error bug
  ledger/ledger_test.go
Labels: Bug-Fix

#5986 Tests: Fix flakey incentive e2e tests
  test/e2e-go/features/incentives/payouts_test.go
  test/e2e-go/features/incentives/suspension_test.go
Labels: Enhancement

#5965 refactor: remove ledgercore.OnlineAccountData
  ledger/acctdeltas_test.go
  ledger/acctonline.go
  ledger/acctonline_test.go
  ledger/acctupdates_test.go
  ledger/ledger.go
  ledger/ledgercore/accountdata.go
  ledger/store/trackerdb/data.go
  ledger/store/trackerdb/dualdriver/accounts_reader_ext.go
  ledger/store/trackerdb/generickv/accounts_ext_reader.go
  ledger/store/trackerdb/interface.go
  ledger/store/trackerdb/sqlitedriver/accountsV2.go
Labels: Skip-Release-Notes
