Repository algorand/go-algorand, pull requests merged in 2024-01, with the labels that each got.

#5888 Chore: Update check_license script to update copyright year
  scripts/check_license.sh
Labels: Skip-Release-Notes

#5889 Dryrun: Improve assembler error reporting
  daemon/algod/api/server/v2/dryrun.go
  daemon/algod/api/server/v2/dryrun_test.go
Labels: Bug-Fix

#5599 AVM: Adding sumhash and falcon_verify
  data/transactions/logic/assembler_test.go
  data/transactions/logic/crypto.go
  data/transactions/logic/crypto_test.go
  data/transactions/logic/doc.go
  data/transactions/logic/evalStateful_test.go
  data/transactions/logic/opcodes.go
  data/transactions/logic/teal.tmLanguage.json
Labels: New Feature

#5893 Algocfg: Introduce new archival node algocfg profile.
  cmd/algocfg/profileCommand.go
  cmd/algocfg/profileCommand_test.go
Labels: Enhancement

#5895 CICD: go-algorand relstable3.21.0-remerge mergeback
  config/version.go
Labels: Skip-Release-Notes

#5896 Releases Page: remove indexer and point to github
  scripts/release/mule/deploy/releases_page/generate_releases_page.py
  scripts/release/mule/deploy/releases_page/html.tpl
Labels: Skip-Release-Notes

#5906 API: Make maps the right size from the start
  data/pools/statusCache.go
Labels: Enhancement

#5907 Docs: Updates to SECURITY.md
  SECURITY.md
Labels: documentation, Enhancement

#5891 api: optimize /transactions/pending/{txid} endpoint
  ledger/ledger.go
  ledger/txtail.go
  ledger/txtail_test.go
  node/node.go
Labels: Enhancement

#5875 AVM: report structure txn failure info
  daemon/algod/api/client/restClient.go
  daemon/algod/api/server/v2/utils.go
  data/basics/serr.go
  data/basics/serr_test.go
  data/transactions/logic/eval.go
  data/transactions/logic/evalAppTxn_test.go
  data/transactions/logic/evalStateful_test.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/export_test.go
  data/transactions/logic/ledger_test.go
  data/transactions/logic/resources_test.go
  ledger/simulation/simulation_eval_test.go
  test/e2e-go/cli/goal/expect/goalAppAccountAddressTest.exp
  test/e2e-go/cli/goal/expect/statefulTealCreateAppTest.exp
  test/e2e-go/cli/goal/expect/tealConsensusTest.exp
  test/e2e-go/restAPI/other/appsRestAPI_test.go
  test/scripts/e2e_subs/avm-failure-info.py
  test/scripts/e2e_subs/goal/goal.py
Labels: Enhancement

#5902 AVM: Add a lot of type annotations to opcodes
  data/transactions/logic/README.md
  data/transactions/logic/TEAL_opcodes_v1.md
  data/transactions/logic/TEAL_opcodes_v10.md
  data/transactions/logic/TEAL_opcodes_v2.md
  data/transactions/logic/TEAL_opcodes_v3.md
  data/transactions/logic/TEAL_opcodes_v4.md
  data/transactions/logic/TEAL_opcodes_v5.md
  data/transactions/logic/TEAL_opcodes_v6.md
  data/transactions/logic/TEAL_opcodes_v7.md
  data/transactions/logic/TEAL_opcodes_v8.md
  data/transactions/logic/TEAL_opcodes_v9.md
  data/transactions/logic/crypto_test.go
  data/transactions/logic/eval.go
  data/transactions/logic/evalStateful_test.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/langspec_v1.json
  data/transactions/logic/langspec_v10.json
  data/transactions/logic/langspec_v2.json
  data/transactions/logic/langspec_v3.json
  data/transactions/logic/langspec_v4.json
  data/transactions/logic/langspec_v5.json
  data/transactions/logic/langspec_v6.json
  data/transactions/logic/langspec_v7.json
  data/transactions/logic/langspec_v8.json
  data/transactions/logic/langspec_v9.json
  data/transactions/logic/opcodes.go
Labels: Enhancement

#5904 Config: Archival mode is no longer automatically enabled when netAddress is s…
  cmd/algocfg/profileCommand.go
  config/config.go
  config/config_test.go
  test/e2e-go/cli/goal/expect/catchpointCatchupTest.exp
Labels: Enhancement

#5913 Network: Like #5906, but for messageFilter, optimize cache mem and speed
  network/messageFilter.go
Labels: Enhancement

#5917 Tests: Adjust catchup e2e tests for non-archival relays
  netdeploy/networkTemplate.go
  test/e2e-go/features/catchup/catchpointCatchup_test.go
Labels: Skip-Release-Notes

#5918 Config: Set relay profile's MaxBalanceHistoryLookback to 22000
  cmd/algocfg/profileCommand.go
Labels: Skip-Release-Notes

#5910 blockdb: bound max deleted blocks per blockdb sync
  ledger/blockqueue.go
  ledger/blockqueue_test.go
  ledger/ledger.go
  ledger/ledger_test.go
Labels: Enhancement

#5920 Archival Support: Remove configurable support for catching up from "archivers"
  catchup/catchpointService.go
  catchup/peerSelector_test.go
  catchup/service.go
  catchup/service_test.go
  config/localTemplate.go
  config/local_defaults.go
  installer/config.json.example
  network/wsNetwork.go
  network/wsNetwork_test.go
  rpcs/blockService.go
  rpcs/blockService_test.go
  test/testdata/configs/config-v33.json
Labels: Enhancement, sys-arch

#5912 netgoal: Use --last-part-key-round when generating a goalnet template
  cmd/netgoal/generate.go
Labels: Enhancement

#5898 p2p: HTTP catchup over p2p network
  catchup/universalFetcher.go
  data/transactions/logic/opcodes.go
  go.mod
  go.sum
  network/addr.go
  network/addr_test.go
  network/p2p/capabilities_test.go
  network/p2p/dnsaddr/resolve.go
  network/p2p/dnsaddr/resolveController.go
  network/p2p/http.go
  network/p2p/p2p.go
  network/p2p/peerID.go
  network/p2p/streams.go
  network/p2pNetwork.go
  network/p2pNetwork_test.go
  network/wsPeer.go
  node/node_test.go
  tools/block-generator/go.mod
  tools/block-generator/go.sum
Labels: SkippedTests, p2p

#5922 p2p: enable p2p http txsync
  components/mocks/mockNetwork.go
  network/addr_test.go
  network/gossipNode.go
  network/hybridNetwork.go
  network/p2p/capabilities_test.go
  network/p2p/http.go
  network/p2p/p2p.go
  network/p2p/streams.go
  network/p2p/testing/httpNode.go
  network/p2pNetwork.go
  network/p2pNetwork_test.go
  network/wsNetwork.go
  network/wsPeer.go
  rpcs/httpTxSync.go
  rpcs/txService_test.go
  rpcs/txSyncer_test.go
Labels: Enhancement, p2p
