Repository algorand/go-algorand, pull requests merged in 2024-02, with the labels that each got.

#5926 p2p: fix infinite loop in dnsaddr resolution
  network/p2p/dnsaddr/resolve.go
  network/p2p/dnsaddr/resolve_test.go
Labels: Bug-Fix, p2p

#5930 CICD: go-algorand relstable3.22.0-remerge mergeback
  config/version.go
Labels: Team Hyper Flow, Skip-Release-Notes

#5929 p2p: support block request redirects for p2p addresses
  rpcs/blockService.go
  rpcs/blockService_test.go
Labels: Enhancement, p2p

#5927 Blocks: Bump min to save based on catchpoint support
  ledger/ledger.go
  ledger/ledger_test.go
Labels: Enhancement

#5886 feat: add support to display mnemonic discreetly for `algokey generate`
  cmd/algokey/common.go
  cmd/algokey/common_test.go
  cmd/algokey/generate.go
  go.mod
  go.sum
Labels: Enhancement

#5931 p2p: rate limit outgoing p2p http connections
  catchup/ledgerFetcher.go
  catchup/universalFetcher.go
  cmd/algod/main.go
  cmd/goal/node.go
  network/addr.go
  network/addr/addr.go
  network/addr/addr_test.go
  network/limitcaller/dialer.go
  network/limitcaller/rateLimitingTransport.go
  network/p2p/http.go
  network/p2p/peerstore/peerstore.go
  network/p2p/peerstore/peerstore_test.go
  network/p2p/peerstore/utils.go
  network/p2pNetwork.go
  network/p2pNetwork_test.go
  network/phonebook/phonebook.go
  network/phonebook/phonebook_test.go
  network/requestLogger_test.go
  network/requestTracker.go
  network/requestTracker_test.go
  network/websocketProxy_test.go
  network/wsNetwork.go
  network/wsNetwork_test.go
  node/node_test.go
  rpcs/blockService.go
  rpcs/blockService_test.go
  rpcs/httpTxSync.go
Labels: Enhancement, p2p

#5933 network: unify wsPeerCore use for HTTP and p2p HTTP transport
  catchup/fetcher_test.go
  catchup/ledgerFetcher.go
  catchup/ledgerFetcher_test.go
  catchup/universalFetcher.go
  components/mocks/mockNetwork.go
  network/addr/addr_test.go
  network/gossipNode.go
  network/hybridNetwork.go
  network/netprio.go
  network/p2pNetwork.go
  network/p2pNetwork_test.go
  network/wsNetwork.go
  network/wsNetwork_test.go
  network/wsPeer.go
  rpcs/httpTxSync.go
  rpcs/txService_test.go
  rpcs/txSyncer_test.go
Labels: Enhancement

#5934 CICD: fix package signing issues
  package-deploy.yaml
  scripts/release/mule/common/ensure_centos8_image.sh
  scripts/release/mule/deploy/deb/deploy.sh
  scripts/release/mule/deploy/docker/docker.sh
  scripts/release/mule/deploy/releases_page/generate_releases_page.sh
  scripts/release/mule/deploy/rpm/deploy.sh
  scripts/release/mule/sign/sign.sh
  test/muleCI/mule.yaml
Labels: Bug-Fix

#5936 network: use network context for DNS operations in readFromSRV
  cmd/catchpointdump/net.go
  network/wsNetwork.go
  network/wsNetwork_test.go
  tools/network/bootstrap.go
  tools/network/bootstrap_test.go
  tools/network/telemetryURIUpdateService.go
Labels: Bug-Fix

#5937 Network: Class-based Peer Selector
  catchup/catchpointService.go
  catchup/classBasedPeerSelector.go
  catchup/classBasedPeerSelector_test.go
  catchup/peerSelector.go
  catchup/peerSelector_test.go
  catchup/service.go
  catchup/service_test.go
Labels: New Feature

#5935 p2p: introduce Gossip peer capability
  network/p2p/capabilities.go
  network/p2p/capabilities_test.go
  network/p2p/dnsaddr/resolve_test.go
  network/p2p/p2p.go
  network/p2p/p2p_test.go
  network/p2p/peerstore/peerstore.go
  network/p2p/peerstore/peerstore_test.go
  network/p2p/pubsub.go
  network/p2pNetwork.go
  network/p2pNetwork_test.go
  node/node.go
  node/node_test.go
Labels: Enhancement, p2p

#5940 Network: Archival node DNS Resolution
  catchup/peerSelector.go
  config/localTemplate.go
  network/gossipNode.go
  network/phonebook.go
  network/phonebook_test.go
  network/wsNetwork.go
  network/wsNetwork_test.go
Labels: Enhancement
