Repository algorand/go-algorand, pull requests merged in 2024-05, with the labels that each got.

#5948 API: Experimental full assets for account endpoint.
  cmd/goal/account.go
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/client/restClient.go
  daemon/algod/api/server/v2/generated/data/routes.go
  daemon/algod/api/server/v2/generated/experimental/routes.go
  daemon/algod/api/server/v2/generated/model/types.go
  daemon/algod/api/server/v2/generated/nonparticipating/private/routes.go
  daemon/algod/api/server/v2/generated/nonparticipating/public/routes.go
  daemon/algod/api/server/v2/generated/participating/private/routes.go
  daemon/algod/api/server/v2/generated/participating/public/routes.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_resources_test.go
  ledger/acctupdates.go
  ledger/catchpointfilewriter_test.go
  ledger/ledger.go
  ledger/ledger_test.go
  ledger/ledgercore/accountresource.go
  ledger/store/trackerdb/data.go
  ledger/store/trackerdb/dualdriver/accounts_reader.go
  ledger/store/trackerdb/generickv/accounts_reader.go
  ledger/store/trackerdb/generickv/migrations.go
  ledger/store/trackerdb/interface.go
  ledger/store/trackerdb/sqlitedriver/schema.go
  ledger/store/trackerdb/sqlitedriver/sql.go
  ledger/store/trackerdb/sqlitedriver/testing.go
  ledger/store/trackerdb/sqlitedriver/trackerdbV2.go
  ledger/store/trackerdb/testsuite/accounts_kv_test.go
  ledger/store/trackerdb/testsuite/sqlitedb_test.go
  ledger/store/trackerdb/version.go
  libgoal/libgoal.go
  test/scripts/e2e_subs/goal-account-asset.sh
Labels: Enhancement, experimental

#5992 Tests: Stabilize nightly tests.
  test/e2e-go/features/incentives/payouts_test.go
  test/e2e-go/features/incentives/suspension_test.go
Labels: Enhancement

#5966 tests: move TestCheckSpender to transactions package
  data/transactions/payment.go
  data/transactions/payment_test.go
  data/transactions/transaction.go
  ledger/apply/payment_test.go
Labels: Skip-Release-Notes

#5988 crypto: convert BatchVerifier to interface
  crypto/batchverifier.go
  crypto/batchverifier_test.go
  crypto/multisig.go
  crypto/onetimesig.go
  data/transactions/verify/txn.go
  data/transactions/verify/txnBatch.go
Labels: Enhancement

#5994 Build: Go 1.21 Support
  .github/workflows/reviewdog.yml
  .golangci.yml
  Dockerfile
  cmd/goal/account.go
  cmd/partitiontest_linter/go.mod
  cmd/partitiontest_linter/go.sum
  crypto/secp256k1/secp256_test.go
  data/pools/transactionPool.go
  data/pools/transactionPool_test.go
  data/transactions/logic/opcodes.go
  go.mod
  go.sum
  ledger/acctdeltas_test.go
  ledger/eval/txntracer.go
  ledger/store/trackerdb/dualdriver/dualdriver.go
  network/p2p/peerstore/peerstore_test.go
  scripts/buildtools/versions
  scripts/get_golang_version.sh
  tools/block-generator/go.mod
  tools/block-generator/go.sum
  tools/x-repo-types/go.mod
Labels: New Feature

#5971 Scripts: update buildnumber to use timezone-aware datetime
  scripts/buildnumber.py
Labels: Enhancement

#5993 tests: fix TestExactAccountChunk
  ledger/catchpointfilewriter_test.go
Labels: Skip-Release-Notes

#5995 tests: make e2e TestBasicSuspension less flaky
  test/e2e-go/features/incentives/suspension_test.go
Labels: Skip-Release-Notes

#5996 tests: make TestBasicPayouts less flaky
  test/e2e-go/features/incentives/payouts_test.go
Labels: Skip-Release-Notes

#5976 p2p: refactor gossipsub to validation and handling
  components/mocks/mockNetwork.go
  data/txHandler.go
  network/gossipNode.go
  network/hybridNetwork.go
  network/multiplexer.go
  network/p2pNetwork.go
  network/p2pNetwork_test.go
  network/wsNetwork.go
Labels: Enhancement, p2p

#5999 logger: fix data race in tests
  logging/log.go
Labels: Bug-Fix

#6001 Typos: Correct some spelling mistakes
  cmd/netgoal/network.go
  netdeploy/remote/deployedNetwork.go
  test/testdata/deployednettemplates/recipes/bootstrappedScenario/Makefile
  test/testdata/deployednettemplates/recipes/bootstrappedScenario/recipe.json
  test/testdata/deployednettemplates/recipes/scenario1s/Makefile
Labels: Enhancement

#5984 AVM: incentive opcodes
  agreement/proposal.go
  agreement/pseudonode.go
  agreement/pseudonode_test.go
  agreement/selector.go
  cmd/tealdbg/localLedger.go
  daemon/algod/api/server/v2/dryrun.go
  data/transactions/logic/assembler_test.go
  data/transactions/logic/doc.go
  data/transactions/logic/eval.go
  data/transactions/logic/evalStateful_test.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/fields.go
  data/transactions/logic/fields_string.go
  data/transactions/logic/fields_test.go
  data/transactions/logic/ledger_test.go
  data/transactions/logic/opcodes.go
  data/transactions/logic/teal.tmLanguage.json
  ledger/apptxn_test.go
  ledger/double_test.go
  ledger/eval/appcow_test.go
  ledger/eval/applications.go
  ledger/eval/cow.go
  ledger/eval/cow_test.go
  ledger/eval/eval.go
  ledger/eval/eval_test.go
  ledger/eval/prefetcher/prefetcher_alignment_test.go
  ledger/eval_simple_test.go
  ledger/evalindexer.go
  ledger/evalindexer_test.go
  ledger/tracker.go
Labels: Enhancement

#5987 chore: fix non-exported function names in comments
  agreement/proposalManager.go
  catchup/catchpointService.go
  catchup/universalFetcher.go
  cmd/goal/application.go
Labels: external contribution, Skip-Release-Notes

#6002 CICD: go-algorand relstable3.24.0-remerge mergeback
  config/version.go
Labels: Team Hyper Flow, Skip-Release-Notes

#6005 Tests: Fix flakey ECDSA testing
  data/transactions/logic/crypto_test.go
Labels: Bug-Fix

#6004 CICD: Update to switch e2e_expect to large
  .circleci/config.yml
  CODEOWNERS
Labels: Enhancement
