Repository algorand/go-algorand, pull requests merged in 2024-10, with the labels that each got.

#6146 CICD: go-algorand relstable3.26.0-remerge mergeback
  config/version.go
  installer/rpm/algorand-devtools/algorand-devtools.spec
  installer/rpm/algorand/algorand.spec
  scripts/build_packages.sh
  scripts/release/mule/sign/sign.sh
Labels: Team Hyper Flow, Skip-Release-Notes

#6148 Consensus: For Devnet and Betanet, support custom network upgrade delay
  cmd/algod/main.go
  config/consensus.go
  config/consensus_test.go
Labels: Enhancement

#6153 Tools: add support for developing in OpenSUSE Tumbleweed
  scripts/install_linux_deps.sh
Labels: Enhancement

#6154 AVM: Only update the bytec disassembleState for bytecblock opcodes
  data/transactions/logic/assembler.go
  data/transactions/logic/assembler_test.go
Labels: Bug-Fix

#6147 tools: heapWatch metrics imported into Prometheus/Grafana
  network/metrics.go
  network/metrics_test.go
  test/heapwatch/metrics_aggs.py
  test/heapwatch/metrics_gra.py
  test/heapwatch/metrics_lib.py
Labels: Enhancement

#6099 Docs: Update README.md to be more concise
  README.md
Labels: Enhancement

#6068 API: MaxTealSourceBytes to 512 kb
  daemon/algod/api/server/v2/handlers.go
Labels: Enhancement, external contribution
