Repository algorand/go-algorand, pull requests merged in 2024-09, with the labels that each got.

#6119 p2p: store private keys as PKCS#8 ASN.1 DER PEM
  network/p2p/peerID.go
Labels: Enhancement

#6118 network: fix outgoing HTTP rate limiting
  network/limitcaller/rateLimitingTransport.go
  network/limitcaller/rateLimitingTransport_test.go
  network/p2p/http.go
  network/p2pNetwork.go
  network/p2pNetwork_test.go
  network/wsNetwork.go
  network/wsNetwork_test.go
Labels: Bug-Fix

#6107 AVM: Provide access to some more block header values
  data/transactions/logic/TEAL_opcodes_v10.md
  data/transactions/logic/TEAL_opcodes_v7.md
  data/transactions/logic/TEAL_opcodes_v8.md
  data/transactions/logic/TEAL_opcodes_v9.md
  data/transactions/logic/assembler_test.go
  data/transactions/logic/eval.go
  data/transactions/logic/fields.go
  data/transactions/logic/fields_string.go
  data/transactions/logic/langspec_v10.json
  data/transactions/logic/langspec_v7.json
  data/transactions/logic/langspec_v8.json
  data/transactions/logic/langspec_v9.json
  test/scripts/e2e_subs/hdr-access.py
Labels: Enhancement

#6121 algons: expose error for dnsaddr command
  cmd/algons/dnsaddrCmd.go
Labels: Enhancement

#6122 tests: fix expect tests and add EOF linter
  Makefile
  scripts/travis/codegen_verification.sh
  test/e2e-go/cli/goal/expect/basicExpectTest.exp
  test/e2e-go/cli/goal/expect/corsTest.exp
  test/e2e-go/cli/goal/expect/expect_linter.py
  test/e2e-go/cli/goal/expect/goalCmdFlagsTest.exp
  test/e2e-go/cli/goal/expect/goalDryrunRestTest.exp
  test/e2e-go/cli/goal/expect/goalExpectCommon.exp
  test/e2e-go/cli/goal/expect/goalTxValidityTest.exp
  test/e2e-go/cli/goal/expect/limitOrderTest.exp
  test/e2e-go/cli/goal/expect/tealAndStatefulTealTest.exp
  test/e2e-go/cli/goal/expect/tealConsensusTest.exp
  test/e2e-go/cli/goal/expect/testInfraTest.exp
Labels: Bug-Fix

#6114 AVM: Derive looser, but more principled, checks of txn max size
  node/node_test.go
  protocol/tags.go
  protocol/tags_test.go
Labels: Enhancement

#6123 p2p: make sure p2p http server runs on all interfaces
  network/p2p/http.go
  network/p2p/p2p.go
  network/p2pNetwork.go
  network/p2pNetwork_test.go
Labels: Bug-Fix

#6130 config: ensure both ws and p2p net running the same mode in hybrid
  config/config_test.go
  config/localTemplate.go
  network/hybridNetwork.go
  network/hybridNetwork_test.go
Labels: Bug-Fix

#6127 node: clear new p2p net handlers on fast catchup
  data/txHandler.go
  network/gossipNode.go
  network/hybridNetwork.go
  network/p2p/http.go
  network/p2pNetwork.go
  network/p2pNetwork_test.go
  network/wsNetwork.go
  node/node.go
  node/node_test.go
Labels: Bug-Fix

#6129 p2p: reuse existing libp2p.Host for http clients
  network/p2p/http.go
  network/p2p/p2p.go
  network/p2p/testing/httpNode.go
  network/p2pNetwork.go
  network/p2pNetwork_test.go
Labels: Bug-Fix

#6134 CI: fix rpmbuild call for cross-platform execution
  installer/rpm/algorand-devtools/algorand-devtools.spec
  installer/rpm/algorand/algorand.spec
Labels: Bug-Fix

#6135 CI: remove homebrew autoupdate deactivation from CircleCI
  .circleci/config.yml
  scripts/configure_dev.sh
Labels: Bug-Fix

#6120 CI: promote unused linter
  .golangci-warnings.yml
  .golangci.yml
  daemon/algod/api/client/restClient.go
  data/transactions/verify/txn.go
  ledger/store/trackerdb/generickv/schema.go
  ledger/store/trackerdb/sqlitedriver/spVerificationAccessor.go
  network/msgOfInterest.go
  network/msgOfInterest_test.go
  network/p2p/capabilities.go
  network/wsNetwork.go
  network/wsNetwork_test.go
  network/wsPeer.go
  network/wsPeer_test.go
  node/node_test.go
  protocol/tags.go
  protocol/tags_test.go
  shared/pingpong/accounts.go
  util/metrics/service.go
Labels: Skip-Release-Notes

#6089 api: Add support for Private Network Access header preflight requests
  config/localTemplate.go
  config/local_defaults.go
  daemon/algod/api/server/lib/middlewares/cors.go
  daemon/algod/api/server/lib/middlewares/cors_test.go
  daemon/algod/api/server/router.go
  daemon/kmd/api/api.go
  daemon/kmd/api/cors.go
  daemon/kmd/config/config.go
  daemon/kmd/kmd.go
  daemon/kmd/server/server.go
  installer/config.json.example
  test/e2e-go/cli/goal/expect/corsTest.exp
  test/e2e-go/cli/goal/expect/goalExpectCommon.exp
  test/testdata/configs/config-v34.json
  test/testdata/nettemplates/TwoNodes50EachPNA.json
Labels: Enhancement

#6138 build: Add automake to linux dependencies
  scripts/install_linux_deps.sh
Labels: Enhancement

#6143 tests: make goal-partkey-commands e2e-subs test serial
  test/scripts/e2e_subs/serial/goal-partkey-commands.sh
Labels: Skip-Release-Notes

#6141 CI: updates to fix publishing universal darwin binaries
  scripts/build_packages.sh
  scripts/release/mule/sign/sign.sh
Labels: Enhancement

#6137 tests: go test RUN/PASS output parser
  test/scripts/go-hanging-test.py
Labels: Skip-Release-Notes

#6142 p2p: upgrade libp2p
  go.mod
  go.sum
  network/p2p/p2p.go
  network/p2p/p2p_test.go
  network/p2pNetwork_test.go
  tools/block-generator/go.mod
  tools/block-generator/go.sum
  tools/x-repo-types/go.mod
  tools/x-repo-types/go.sum
Labels: Enhancement
