Repository algorand/go-algorand, pull requests merged in 2024-11, with the labels that each got.

#6164 Incentives: Use agreement round when estimating a node's proposal interval
  agreement/selector.go
  ledger/apply/keyreg.go
  ledger/eval/eval.go
  ledger/eval/eval_test.go
  ledger/eval_simple_test.go
  test/e2e-go/features/incentives/whalejoin_test.go
Labels: Bug-Fix

#6057 AVM: Implement lsig size pooling
  cmd/goal/clerk.go
  config/consensus.go
  data/transactions/logic/eval.go
  data/transactions/logic/eval_test.go
  data/transactions/logicsig.go
  data/transactions/msgp_gen.go
  data/transactions/verify/txn.go
  data/transactions/verify/txn_test.go
  data/txntest/program.go
  node/node_test.go
  test/e2e-go/cli/goal/expect/tealConsensusTest.exp
  test/e2e-go/features/transactions/logicsig_test.go
  test/testdata/nettemplates/TwoNodes50EachV18.json
Labels: Enhancement, external contribution

#6169 Build: Upgrade to Golang 1.23
  .github/workflows/benchmarks.yml
  .github/workflows/build.yml
  .github/workflows/reviewdog.yml
  .github/workflows/tools.yml
  .golangci.yml
  Dockerfile
  catchup/ledgerFetcher_test.go
  cmd/algocfg/getCommand_test.go
  cmd/goal/application.go
  cmd/goal/application_test.go
  cmd/goal/asset.go
  cmd/goal/clerk.go
  cmd/goal/clerk_test.go
  cmd/goal/commands.go
  cmd/goal/formatting_test.go
  cmd/goal/node_test.go
  cmd/loadgenerator/main.go
  cmd/partitiontest_linter/go.mod
  cmd/partitiontest_linter/go.sum
  cmd/tealdbg/local_test.go
  config/config_test.go
  config/dnsbootstrap.go
  config/localTemplate.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_test.go
  data/transactions/logic/assembler_test.go
  data/transactions/logic/backwardCompat_test.go
  data/transactions/logic/blackbox_test.go
  data/transactions/logic/box_test.go
  data/transactions/logic/crypto_test.go
  data/transactions/logic/debugger_eval_test.go
  data/transactions/logic/evalAppTxn_test.go
  data/transactions/logic/evalStateful_test.go
  data/transactions/logic/eval_test.go
  data/transactions/logic/mocktracer/scenarios.go
  data/transactions/logic/tracer_test.go
  data/transactions/verify/txn_test.go
  go.mod
  go.sum
  ledger/eval/eval.go
  ledger/eval/eval_test.go
  ledger/eval/txntracer_test.go
  ledger/simulation/simulation_eval_test.go
  ledger/simulation/tracer_test.go
  ledger/tracker.go
  libgoal/participation/participation_test.go
  network/gossipNode.go
  network/p2p/peerstore/utils_test.go
  network/wsNetwork.go
  node/follower_node.go
  node/node.go
  scripts/buildtools/versions
  scripts/get_golang_version.sh
  tools/block-generator/go.mod
  tools/block-generator/go.sum
  tools/x-repo-types/go.mod
  util/codecs/json_test.go
  util/db/initialize_test.go
Labels: Enhancement

#6163 API: New algod endpoint `/v2/block/{round}/header` omits transactions and cert from response
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/data/routes.go
  daemon/algod/api/server/v2/generated/experimental/routes.go
  daemon/algod/api/server/v2/generated/model/types.go
  daemon/algod/api/server/v2/generated/nonparticipating/private/routes.go
  daemon/algod/api/server/v2/generated/nonparticipating/public/routes.go
  daemon/algod/api/server/v2/generated/participating/private/routes.go
  daemon/algod/api/server/v2/generated/participating/public/routes.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_test.go
Labels: Enhancement

#6173 tests: Fix MaxConnectionsPerIP setting in agreement/gossip tests
  agreement/gossip/networkFull_test.go
Labels: Bug-Fix

#6175 CI: update reviewdog warning linter job
  .github/workflows/reviewdog.yml
  .golangci-warnings.yml
  data/transactions/logic/assembler.go
Labels: Skip-Release-Notes

#6179 refactor: replace experimental `maps` and `slices` with stdlib
  agreement/agreementtest/simulate_test.go
  agreement/autopsy.go
  agreement/common_test.go
  cmd/algokey/keyreg.go
  cmd/goal/account.go
  cmd/tealdbg/local.go
  crypto/merklearray/merkle.go
  crypto/merkletrie/cache.go
  crypto/merkletrie/committer.go
  crypto/merkletrie/committer_test.go
  crypto/merkletrie/node.go
  daemon/algod/api/server/v2/account.go
  daemon/algod/api/server/v2/test/handlers_test.go
  daemon/algod/api/server/v2/utils.go
  data/basics/teal.go
  data/basics/userBalance.go
  data/transactions/application.go
  data/transactions/logic/crypto_test.go
  data/transactions/logic/eval.go
  data/transactions/logic/opcodes.go
  data/transactions/logic/opcodes_test.go
  data/transactions/teal.go
  data/transactions/transaction.go
  ledger/apply/application_test.go
  ledger/apply/mockBalances_test.go
  ledger/eval/cow.go
  ledger/eval/txntracer.go
  ledger/ledger_test.go
  ledger/ledgercore/statedelta.go
  ledger/simulation/simulation_eval_test.go
  netdeploy/network.go
  network/p2p/peerstore/peerstore.go
  network/phonebook/phonebook.go
  stateproof/builder.go
  test/reflectionhelpers/helpers.go
  util/metrics/opencensus.go
  util/metrics/tagcounter.go
Labels: Enhancement
