Repository algorand/go-algorand, pull requests merged in 2025-03, with the labels that each got.

#6261 network: fix peerstore Get/Put races
  network/p2p/peerstore/peerstore.go
Labels: Bug-Fix, p2p

#6266 catchpointdump: support p2p nodes
  catchup/catchpointService.go
  cmd/catchpointdump/net.go
Labels: New Feature, p2p

#6267 p2p: fix http RoundTripper
  network/p2p/http.go
Labels: Bug-Fix, p2p

#6268 build: stop duplicate library LDFLAGS warning
  Makefile
  crypto/batchverifier.go
  crypto/vrf.go
Labels: Enhancement

#6198 Performance: Node benchmarking utility
  cmd/catchpointdump/bench.go
  cmd/catchpointdump/bench_report.go
  cmd/catchpointdump/commands.go
  go.mod
  util/util.go
  util/util_windows.go
Labels: Enhancement, external contribution

#6269 test: add OverrideKmdConfig to libgoalFixture
  daemon/kmd/config/config.go
  netdeploy/network.go
  netdeploy/networkTemplate.go
  netdeploy/networkTemplates_test.go
  test/framework/fixtures/libgoalFixture.go
Labels: Skip-Release-Notes

#6272 util: implement GetTotalMemory for mac and windows
  util/util.go
  util/util_darwin.go
  util/util_linux.go
  util/util_test.go
  util/util_windows.go
Labels: Bug-Fix

#6277 catchup: improve classBasedPeerSelector on small peer sets
  catchup/classBasedPeerSelector.go
  catchup/classBasedPeerSelector_test.go
  catchup/peerSelector.go
  catchup/service.go
  network/gossipNode.go
Labels: Bug-Fix

#6278 test: fix flaky TestExactAccountChunk again
  ledger/catchpointfilewriter_test.go
Labels: Skip-Release-Notes

#6282 kmd: upgrade karalabe/usb to karalabe/hid
  daemon/kmd/wallet/driver/ledger_hid.go
  go.mod
  go.sum
Labels: Enhancement

#6279 API: box paging
  Makefile
  cmd/goal/account.go
  cmd/goal/box.go
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/client/restClient.go
  daemon/algod/api/server/v2/generated/data/routes.go
  daemon/algod/api/server/v2/generated/experimental/routes.go
  daemon/algod/api/server/v2/generated/model/types.go
  daemon/algod/api/server/v2/generated/nonparticipating/private/routes.go
  daemon/algod/api/server/v2/generated/nonparticipating/public/routes.go
  daemon/algod/api/server/v2/generated/participating/private/routes.go
  daemon/algod/api/server/v2/generated/participating/public/routes.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/handlers_test.go
  daemon/algod/api/server/v2/test/handlers_resources_test.go
  data/transactions/logic/assembler_test.go
  ledger/acctdeltas_test.go
  ledger/acctupdates.go
  ledger/acctupdates_test.go
  ledger/catchpointfilewriter_test.go
  ledger/ledger.go
  ledger/ledgercore/statedelta.go
  ledger/store/trackerdb/dualdriver/accounts_reader.go
  ledger/store/trackerdb/generickv/accounts_reader.go
  ledger/store/trackerdb/interface.go
  ledger/store/trackerdb/sqlitedriver/sql.go
  libgoal/libgoal.go
  test/e2e-go/restAPI/other/appsRestAPI_test.go
  test/scripts/e2e_subs/box-search.sh
  util/set.go
Labels: Enhancement

#6287 Txn: Refactor some stateless checks on transactions
  daemon/algod/api/server/v2/dryrun.go
  daemon/algod/api/server/v2/dryrun_test.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_resources_test.go
  daemon/algod/api/server/v2/utils.go
  data/bookkeeping/block.go
  data/bookkeeping/block_test.go
  data/ledger.go
  data/pools/transactionPool.go
  data/transactions/application.go
  data/transactions/application_test.go
  data/transactions/common_test.go
  data/transactions/error.go
  data/transactions/heartbeat.go
  data/transactions/heartbeat_test.go
  data/transactions/keyreg.go
  data/transactions/keyreg_test.go
  data/transactions/payment.go
  data/transactions/payment_test.go
  data/transactions/payset_test.go
  data/transactions/stateproof.go
  data/transactions/stateproof_test.go
  data/transactions/transaction.go
  data/transactions/transaction_test.go
  data/txHandler.go
  ledger/apply/asset_test.go
  ledger/apply/keyreg.go
  ledger/apply/keyreg_test.go
  ledger/apply/payment_test.go
  ledger/eval/eval.go
  ledger/testing/randomAccounts.go
Labels: Enhancement
