Repository algorand/go-algorand, pull requests merged in 2025-05, with the labels that each got.

#6311 API: Use integer and uint64 to better express the genesis schema
  daemon/algod/api/Makefile
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/data/routes.go
  daemon/algod/api/server/v2/generated/experimental/routes.go
  daemon/algod/api/server/v2/generated/model/types.go
  daemon/algod/api/server/v2/generated/nonparticipating/private/routes.go
  daemon/algod/api/server/v2/generated/nonparticipating/public/routes.go
  daemon/algod/api/server/v2/generated/participating/private/routes.go
  daemon/algod/api/server/v2/generated/participating/public/routes.go
  daemon/algod/api/server/v2/test/genesis_types_test.go
  tools/x-repo-types/Makefile
  tools/x-repo-types/xrt.go
  tools/x-repo-types/xrt_test.go
Labels: Bug-Fix

#6316 tests: fix TestP2PRelay data race
  network/p2pNetwork_test.go
Labels: Skip-Release-Notes

#6308 network: close p2p conn in CloseWithoutFlush
  network/p2pPeer.go
Labels: Bug-Fix, p2p

#6320 tests: fix TestP2PEnableGossipService_BothDisable
  network/p2p/p2p.go
  network/p2pNetwork_test.go
Labels: Skip-Release-Notes

#6321 CI: use partitiontest for Fuzz tests
  network/vpack/rapid_test.go
  network/vpack/vpack_test.go
  test/partitiontest/filtering.go
Labels: Skip-Release-Notes

#6323 Testing: Remove sd.Valid()
  data/basics/teal.go
  data/basics/teal_test.go
Labels: Enhancement

#6312 p2p: peer metainfo support
  network/addr.go
  network/msgp_gen.go
  network/msgp_gen_test.go
  network/p2p/p2p.go
  network/p2p/p2p_test.go
  network/p2p/streams.go
  network/p2pMetainfo.go
  network/p2pMetainfo_test.go
  network/p2pNetwork.go
  network/p2pNetwork_test.go
  network/requestLogger_test.go
  network/requestTracker_test.go
  network/wsNetwork.go
  network/wsNetwork_test.go
  node/node_test.go
Labels: Enhancement

#6324 Chore: Move allocbounds
  agreement/bundle.go
  agreement/msgp_gen.go
  config/bounds/bounds.go
  config/config.go
  config/config_test.go
  config/consensus.go
  crypto/stateproof/structs.go
  crypto/stateproof/weights_test.go
  daemon/algod/api/server/v2/handlers.go
  data/appRateLimiter.go
  data/appRateLimiter_test.go
  data/basics/msgp_gen.go
  data/basics/teal.go
  data/basics/userBalance.go
  data/basics/userBalance_test.go
  data/bookkeeping/block.go
  data/bookkeeping/msgp_gen.go
  data/transactions/application.go
  data/transactions/logic/eval.go
  data/transactions/logic/eval_test.go
  data/transactions/logicsig.go
  data/transactions/msgp_gen.go
  data/transactions/teal.go
  data/transactions/teal_test.go
  data/transactions/transaction.go
  data/txDupCache.go
  data/txHandler.go
  data/txHandler_test.go
  ledger/acctdeltas_test.go
  ledger/simulation/trace.go
  ledger/store/trackerdb/data.go
  ledger/store/trackerdb/msgp_gen.go
  ledger/testing/randomAccounts.go
  node/node_test.go
  protocol/codec_test.go
  protocol/consensus.go
  protocol/msgp_gen.go
  scripts/export_sdk_types.py
  tools/debug/transplanter/main.go
  tools/x-repo-types/xrt_test.go
Labels: Enhancement

#6330 network: count received traffic before decompression
  network/wsPeer.go
Labels: Bug-Fix

#6331 network: enable vote compression for P2PNetwork
  network/p2pNetwork.go
  network/p2pNetwork_test.go
  network/wsNetwork_test.go
Labels: Enhancement

#6333 API: Update 'value' in API Box type to be optional (reflecting updated get…
  cmd/goal/box.go
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/data/routes.go
  daemon/algod/api/server/v2/generated/experimental/routes.go
  daemon/algod/api/server/v2/generated/model/types.go
  daemon/algod/api/server/v2/generated/nonparticipating/private/routes.go
  daemon/algod/api/server/v2/generated/nonparticipating/public/routes.go
  daemon/algod/api/server/v2/generated/participating/private/routes.go
  daemon/algod/api/server/v2/generated/participating/public/routes.go
  daemon/algod/api/server/v2/handlers.go
  test/e2e-go/restAPI/other/appsRestAPI_test.go
Labels: Bug-Fix

#6336 tests: fix a race in TestP2PMetainfoExchange
  network/p2pNetwork_test.go
Labels: Skip-Release-Notes

#6334 network: add "uncompressed bytes by tag" metric
  network/metrics.go
  network/wsPeer.go
Labels: Enhancement

#6338 refactor: use the built-in max/min to simplify the code
  crypto/statetrie/nibbles/nibbles.go
  network/limitlistener/rejectingLimitListener_test.go
  tools/debug/carpenter/main.go
  util/bloom/bloom.go
  util/watchdogStreamReader.go
Labels: Enhancement, external contribution

#6342 tests: fix TestStateProofRecovery
  test/e2e-go/features/stateproofs/stateproofs_test.go
Labels: Skip-Release-Notes

#6343 API: Revert boxes pagination
  cmd/goal/account.go
  cmd/goal/box.go
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/client/restClient.go
  daemon/algod/api/server/v2/generated/data/routes.go
  daemon/algod/api/server/v2/generated/experimental/routes.go
  daemon/algod/api/server/v2/generated/model/types.go
  daemon/algod/api/server/v2/generated/nonparticipating/private/routes.go
  daemon/algod/api/server/v2/generated/nonparticipating/public/routes.go
  daemon/algod/api/server/v2/generated/participating/private/routes.go
  daemon/algod/api/server/v2/generated/participating/public/routes.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/handlers_test.go
  daemon/algod/api/server/v2/test/handlers_resources_test.go
  data/transactions/logic/assembler_test.go
  ledger/acctdeltas_test.go
  ledger/acctupdates.go
  ledger/acctupdates_test.go
  ledger/catchpointfilewriter_test.go
  ledger/ledger.go
  ledger/ledgercore/statedelta.go
  ledger/store/trackerdb/dualdriver/accounts_reader.go
  ledger/store/trackerdb/generickv/accounts_reader.go
  ledger/store/trackerdb/interface.go
  ledger/store/trackerdb/sqlitedriver/sql.go
  libgoal/libgoal.go
  test/e2e-go/restAPI/other/appsRestAPI_test.go
  test/scripts/e2e_subs/box-search.sh
  util/set.go
Labels: Bug-Fix

#6346 CICD: GitHub Actions workflows for nightly and PR tests
  .github/workflows/ci-nightly.yml
  .github/workflows/ci-pr.yml
Labels: New Feature

#6307 build: upgrade Go and package versions
  Dockerfile
  cmd/partitiontest_linter/go.mod
  go.mod
  go.sum
  scripts/get_golang_version.sh
  tools/block-generator/go.mod
  tools/block-generator/go.sum
  tools/x-repo-types/go.mod
  tools/x-repo-types/go.sum
Labels: Skip-Release-Notes
