Repository algorand/go-algorand, pull requests merged in 2025-02, with the labels that each got.

#6242 config: remove unused EnableOnlineAccountCatchpoints consensus flag, rename EnableAccountDataResourceSeparation
  config/consensus.go
  ledger/acctupdates.go
  ledger/applications_test.go
Labels: Skip-Release-Notes

#6132 p2p: exclude self from GetPeers results
  network/p2pNetwork.go
  network/p2pNetwork_test.go
Labels: Enhancement

#6247 API: Explicitly set the x-algorand-format for BlockHeaderResponse to 'Bloc…
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/data/routes.go
  daemon/algod/api/server/v2/generated/experimental/routes.go
  daemon/algod/api/server/v2/generated/nonparticipating/private/routes.go
  daemon/algod/api/server/v2/generated/nonparticipating/public/routes.go
  daemon/algod/api/server/v2/generated/participating/private/routes.go
  daemon/algod/api/server/v2/generated/participating/public/routes.go
Labels: Bug-Fix

#6250 CI: upgrade to actions/cache@v4
  .github/workflows/build.yml
  .github/workflows/reviewdog.yml
Labels: Skip-Release-Notes

#6248 API: Block Header API Revamp
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/data/routes.go
  daemon/algod/api/server/v2/generated/experimental/routes.go
  daemon/algod/api/server/v2/generated/model/types.go
  daemon/algod/api/server/v2/generated/nonparticipating/private/routes.go
  daemon/algod/api/server/v2/generated/nonparticipating/public/routes.go
  daemon/algod/api/server/v2/generated/participating/private/routes.go
  daemon/algod/api/server/v2/generated/participating/public/routes.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/test/handlers_test.go
Labels: Bug-Fix

#6241 Comments: Correct deadline comment issue#6201
  data/pools/transactionPool.go
Labels: Enhancement

#6251 tests: fix flaky TestApplicationsUpgradeOverGossip
  ledger/catchpointfilewriter_test.go
  ledger/simple_test.go
  test/e2e-go/upgrades/application_support_test.go
Labels: Skip-Release-Notes

#6256 tests: fix flaky TestApplicationsUpgradeOverREST
  test/e2e-go/upgrades/application_support_test.go
Labels: Skip-Release-Notes

#6237 Config: Add TELEMETRY_URL support for telemetry configuration
  docker/README.md
  docker/files/run/run.sh
Labels: Enhancement

#6246 Net: Tiny speedup, less allocation
  config/consensus.go
  data/transactions/verify/verifiedTxnCache.go
  data/txDupCache.go
  data/txDupCache_test.go
  data/txHandler.go
  data/txHandler_test.go
  node/node.go
Labels: Enhancement

#6257 txHandler: do not drop accepted mgs
  data/txHandler.go
Labels: Bug-Fix

#6259 tests: fix flaky TestLedgerErrorValidate
  data/ledger_test.go
Labels: Skip-Release-Notes

#6260 Build: Bump Ubuntu version in codegen_verification job.
  .github/workflows/codegen_verification.yml
Labels: Skip-Release-Notes, dependencies

#6126 p2p: fan in incoming txns into backlog worker
  data/txHandler.go
  data/txHandler_test.go
  network/p2pNetwork.go
Labels: Enhancement

#6161 goal: added "wallet rename"
  cmd/goal/messages.go
  cmd/goal/wallet.go
  daemon/kmd/client/wrappers.go
  libgoal/wallets.go
  test/e2e-go/cli/goal/expect/createWalletTest.exp
  test/e2e-go/cli/goal/expect/goalExpectCommon.exp
Labels: Enhancement, external contribution

#6176 txHandler: Use IP address instead of IP:port pair
  data/txHandler.go
  data/txHandler_test.go
Labels: Enhancement

#6183 algod: Add static EnableTelemetry retry
  cmd/algod/main.go
  cmd/algoh/main.go
  data/pools/transactionPool_test.go
  logging/log.go
  logging/telemetry.go
  logging/telemetryCommon.go
  logging/telemetry_test.go
  logging/telemetryhook.go
Labels: Enhancement, external contribution

#6160 goal: non-interactive wallet creation with "wallet new --unencrypted --no-display-seed"
  cmd/goal/messages.go
  cmd/goal/wallet.go
Labels: Enhancement, external contribution

#6180 goal: Improve logicsig with signer support for clerk send
  cmd/goal/clerk.go
  test/e2e-go/cli/goal/expect/goalLogicSigTest.exp
  test/scripts/e2e_subs/tealprogs/int1.teal
Labels: Enhancement, external contribution

#6131 network: allow multi-role phonebook entries
  network/p2p/p2p.go
  network/p2p/peerstore/peerstore.go
  network/p2p/peerstore/peerstore_test.go
  network/p2pNetwork.go
  network/p2pNetwork_test.go
  network/phonebook/phonebook.go
  network/phonebook/phonebook_test.go
  network/requestLogger_test.go
  network/requestTracker_test.go
  network/wsNetwork.go
  network/wsNetwork_test.go
Labels: Enhancement
