Repository algorand/go-algorand, pull requests merged in 2025-04, with the labels that each got.

#6288 DevOps: fix golang version handling in bash scripts
  Makefile
  scripts/check_golang_version.sh
  scripts/get_golang_version.sh
Labels: Bug-Fix

#6284 API: Enable gzip middleware and test for it
  daemon/algod/api/server/router.go
  test/scripts/e2e_subs/api-compression.sh
Labels: Enhancement

#6294 Test: Wait for the box list to be for the commit round
  test/scripts/e2e_subs/box-search.sh
Labels: Enhancement

#6290 catchpoint: handle loadFromDisk/recoverFromCrash during first stage correctly
  ledger/catchpointtracker.go
Labels: Bug-Fix

#6292 tools: Add catchpointdump msgpack decode feature
  cmd/catchpointdump/file.go
  cmd/catchpointdump/net.go
Labels: Skip-Release-Notes

#6299 p2p: fix DHT FindPeer internal buffer size
  network/p2p/dht/dht.go
Labels: Bug-Fix, p2p

#6157 REST API: genesis endpoint schema definition
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/data/routes.go
  daemon/algod/api/server/v2/generated/experimental/routes.go
  daemon/algod/api/server/v2/generated/model/types.go
  daemon/algod/api/server/v2/generated/nonparticipating/private/routes.go
  daemon/algod/api/server/v2/generated/nonparticipating/public/routes.go
  daemon/algod/api/server/v2/generated/participating/private/routes.go
  daemon/algod/api/server/v2/generated/participating/public/routes.go
  daemon/algod/api/server/v2/test/genesis_types_test.go
Labels: Enhancement, external contribution
