Repository algorand/go-algorand, pull requests merged in 2025-01, with the labels that each got.

#6217 Testing: Correct an off by one, and retry instead of fail with bad accounts
  test/e2e-go/features/incentives/challenge_test.go
  util/set.go
Labels: Bug-Fix

#6218 Testing: Move WaitForConfirmedTxn down into clients
  daemon/algod/api/client/restClient.go
  libgoal/transactions.go
  test/e2e-go/features/incentives/challenge_test.go
  test/e2e-go/features/incentives/payouts_test.go
  test/e2e-go/features/incentives/suspension_test.go
  test/e2e-go/features/incentives/whalejoin_test.go
  test/framework/fixtures/restClientFixture.go
Labels: Enhancement

#6214 catchpoints: more support for EnableOnlineAccountCatchpoints
  cmd/catchpointdump/database.go
  cmd/catchpointdump/file.go
  cmd/catchpointdump/net.go
  ledger/acctdeltas_test.go
  ledger/acctonline_test.go
  ledger/catchpointfilewriter.go
  ledger/catchpointfilewriter_test.go
  ledger/catchpointtracker.go
  ledger/catchpointtracker_test.go
  ledger/catchupaccessor.go
  ledger/store/trackerdb/dualdriver/dualdriver.go
  ledger/store/trackerdb/generickv/reader.go
  ledger/store/trackerdb/sqlitedriver/accountsV2.go
  ledger/store/trackerdb/sqlitedriver/kvsIter.go
  ledger/store/trackerdb/sqlitedriver/sqlitedriver.go
  ledger/store/trackerdb/store.go
Labels: Bug-Fix

#6221 CI: Remove lnav mac dev dependency
  scripts/configure_dev.sh
Labels: Bug-Fix

#6225 Dev Tools: remove lnav dependency from beta branch
  scripts/configure_dev.sh
Labels: Bug-Fix

#6228 Testing: Moar unflaky
  test/e2e-go/features/incentives/challenge_test.go
Labels: Bug-Fix

#6223 build: upgrade minimum MacOS version to 13
  .circleci/config.yml
  Makefile
Labels: Enhancement

#6222 CI: install lnav outside of CI environments
  scripts/algorand_node_log.json
  scripts/configure_dev.sh
Labels: Skip-Release-Notes

#6229 Testing: Don't fail for heartbeat in same block as proposal
  test/e2e-go/features/incentives/challenge_test.go
Labels: Bug-Fix

#6230 CICD: go-algorand relstable4.0.1-remerge mergeback
  config/version.go
Labels: Skip-Release-Notes

#6231 DB: Remove AtomicContextWithRetryClearFn, rename to AtomicContext
  ledger/store/trackerdb/sqlitedriver/sqlitedriver.go
  util/db/dbutil.go
Labels: Enhancement

#6235 tools: add -d and -o args for catchpointdump net, like file, new info command
  cmd/catchpointdump/commands.go
  cmd/catchpointdump/info.go
  cmd/catchpointdump/net.go
Labels: Skip-Release-Notes

#6239 Devmode: Zero out ProposerPayout when Proposer is not set (which i…
  node/node.go
Labels: Bug-Fix
