Repository algorand/go-algorand, pull requests merged in 2025-06, with the labels that each got.

#6339 crypto: add SHA-512 hashes
  agreement/msgp_gen.go
  catchup/catchpointService_test.go
  config/consensus.go
  crypto/hashes.go
  crypto/msgp_gen.go
  crypto/msgp_gen_test.go
  data/bookkeeping/block.go
  data/bookkeeping/block_test.go
  data/bookkeeping/genesis.go
  data/bookkeeping/msgp_gen.go
  data/bookkeeping/txn_merkle.go
  data/ledger_test.go
  ledger/ledger_test.go
  protocol/tags.go
Labels: Enhancement

#6359 test: waitFor was badly broken
  heartbeat/service_test.go
Labels: Bug-Fix

#6365 Testing: test vFuture, so we are exercising branch512
  ledger/ledger_test.go
  scripts/export_sdk_types.py
Labels: Enhancement

#6367 CICD: fix uploading testdata in nightlies
  .github/workflows/ci-nightly.yml
  .github/workflows/ci-pr.yml
  test/scripts/e2e.sh
Labels: Bug-Fix

#6370 CICD: fix short test flag and up parallelism
  .github/workflows/ci-pr.yml
Labels: Bug-Fix

#6310 p2p: ignore initial no peers error in capabilities advertisement
  go.mod
  network/p2p/capabilities.go
  network/p2p/capabilities_test.go
Labels: Bug-Fix, p2p
