Repository algorand/go-algorand, pull requests merged in 2025-08, with the labels that each got.

#6408 CI: build Go cache on master merges
  .github/workflows/ci-nightly.yml
Labels: Enhancement

#6409 Build: .gitignore .claude
  .gitignore
Labels: Enhancement

#6309 AVM: Allow access to boxes for apps made in the same group without explicit boxrefs
  Makefile
  config/consensus.go
  daemon/algod/api/server/v2/handlers.go
  daemon/algod/api/server/v2/utils.go
  data/basics/overflow.go
  data/basics/units_test.go
  data/transactions/logic/box.go
  data/transactions/logic/eval.go
  data/transactions/logic/evalStateful_test.go
  data/transactions/logic/resources.go
  ledger/boxtxn_test.go
  ledger/simulation/resources.go
  ledger/simulation/simulation_eval_test.go
  ledger/simulation/testing/utils.go
Labels: Enhancement

#6418 Docs: v12 docs
  cmd/opdoc/opdoc.go
  data/transactions/logic/README.md
  data/transactions/logic/README_in.md
  data/transactions/logic/TEAL_opcodes_v12.md
  data/transactions/logic/doc.go
  data/transactions/logic/langspec_v12.json
  data/transactions/logic/teal.tmLanguage.json
Labels: Enhancement

#6420 tests: increase wait timeout in TestTotalWeightChanges
  test/e2e-go/features/stateproofs/stateproofs_test.go
Labels: Skip-Release-Notes

#6422 Consensus: Consensus version v41 upgrade.
  config/consensus.go
  data/transactions/logic/langspec_v1.json
  data/transactions/logic/langspec_v10.json
  data/transactions/logic/langspec_v11.json
  data/transactions/logic/langspec_v12.json
  data/transactions/logic/langspec_v2.json
  data/transactions/logic/langspec_v3.json
  data/transactions/logic/langspec_v4.json
  data/transactions/logic/langspec_v5.json
  data/transactions/logic/langspec_v6.json
  data/transactions/logic/langspec_v7.json
  data/transactions/logic/langspec_v8.json
  data/transactions/logic/langspec_v9.json
  data/transactions/verify/txn_test.go
  ledger/testing/consensusRange.go
  protocol/consensus.go
Labels: Enhancement

#6425 pingpong: fix regression when making app calls
  shared/pingpong/pingpong.go
Labels: Bug-Fix

#6426 Build: Nightly test file naming fix
  .github/workflows/ci-nightly.yml
Labels: Skip-Release-Notes
