Repository algorand/go-algorand, pull requests merged in 2025-07, with the labels that each got.

#6375 API: Avoid downstream generated type changes for pre-existing TransactionP…
  daemon/algod/api/algod.oas2.json
  daemon/algod/api/algod.oas3.yml
  daemon/algod/api/server/v2/generated/data/routes.go
  daemon/algod/api/server/v2/generated/experimental/routes.go
  daemon/algod/api/server/v2/generated/nonparticipating/private/routes.go
  daemon/algod/api/server/v2/generated/nonparticipating/public/routes.go
  daemon/algod/api/server/v2/generated/participating/private/routes.go
  daemon/algod/api/server/v2/generated/participating/public/routes.go
Labels: Enhancement

#6376 node: fallback to ws or p2p on hybrid misconfiguration
  config/config.go
  config/config_test.go
  config/localTemplate.go
  go.mod
  node/node.go
  node/node_test.go
Labels: Enhancement

#6377 tests: remove "Fail" part from test test names
  agreement/cryptoVerifier_test.go
  agreement/persistence_test.go
  agreement/pseudonode_test.go
  catchup/peerSelector_test.go
  config/config_test.go
  daemon/algod/api/server/v2/test/handlers_test.go
  data/bookkeeping/block_test.go
  data/transactions/logic/evalAppTxn_test.go
  data/transactions/logic/eval_test.go
  data/transactions/verify/txn_test.go
  ledger/apply/challenge_test.go
  ledger/apptxn_test.go
  ledger/eval/eval_test.go
  ledger/simulation/simulation_eval_test.go
  network/p2p/dnsaddr/resolve_test.go
  network/p2pNetwork_test.go
  test/e2e-go/cli/goal/account_test.go
  test/e2e-go/features/catchup/catchpointCatchup_test.go
  test/e2e-go/kmd/e2e_kmd_server_client_test.go
  test/e2e-go/kmd/e2e_kmd_sqlite_test.go
  test/e2e-go/restAPI/other/misc_test.go
  test/e2e-go/restAPI/restClient_test.go
  tools/network/dnssec/trustedchain_test.go
Labels: Skip-Release-Notes

#6378 Ops: Bump ubuntu and centos versions for building and testing
  .circleci/config.yml
  .github/workflows/codegen_verification.yml
  .github/workflows/container.yml
  Dockerfile
  Makefile
  README.md
  cmd/updater/update.sh
  docker/Dockerfile
  docker/build/Dockerfile
  docker/build/Dockerfile-deploy
  docker/build/aptly.Dockerfile
  docker/build/cicd.centos10.Dockerfile
  docker/build/cicd.ubuntu.Dockerfile
  docker/build/docker.ubuntu.Dockerfile
  docker/build/releases-page.Dockerfile
  docker/releases/build_releases.sh
  package-deploy.yaml
  package-test.yaml
  package.yaml
  scripts/build_package.sh
  scripts/configure_dev.sh
  scripts/release/README.md
  scripts/release/build/stage/build/task.sh
  scripts/release/common/docker/centos10.Dockerfile
  scripts/release/common/docker/setup.Dockerfile
  scripts/release/common/setup.sh
  scripts/release/mule/common/ensure_centos10_image.sh
  scripts/release/prod/rpm/run_centos.sh
  scripts/release/test/rpm/run_centos.sh
  scripts/release/test/util/test_package.sh
  scripts/travis/configure_dev.sh
  test/muleCI/mule.yaml
  test/packages/test_release.sh
  test/platform/test_linux_amd64_compatibility.sh
Labels: Enhancement

#6381 network: do not use telemetry id for p2p nets
  network/p2pNetwork.go
Labels: Enhancement

#6383 Dev: fix darwin universal targets
  Makefile
Labels: Bug-Fix

#6373 refactor: use maps.Copy for cleaner map handling
  cmd/algofix/typecheck.go
Labels: Enhancement

#6374 network: refactor networking mesh maintaining code
  network/addr.go
  network/hybridNetwork.go
  network/hybridNetwork_test.go
  network/mesh.go
  network/p2pNetwork.go
  network/p2pNetwork_test.go
  network/requestLogger_test.go
  network/requestTracker_test.go
  network/wsNetwork.go
  network/wsNetwork_test.go
  node/follower_node.go
  node/node.go
Labels: Enhancement

#6384 logging: log configuration migration messages
  cmd/algod/main.go
  config/config.go
  config/config_test.go
  config/migrate.go
  daemon/algod/server.go
Labels: Enhancement

#6390 CI: run PR tests on release PRs
  .github/workflows/ci-pr.yml
Labels: Bug-Fix
